### ISSUE TITLE
Geolocation Support

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#10]
Moved from: https://github.com/adamdriscoll/poshprotools/issues/228

**Comment by adamdriscoll** [comment]
![dwcg3bhu8aaskht](https://user-images.githubusercontent.com/1256531/36447056-d09339ec-1648-11e8-824d-99f363c51c05.jpg)

**Comment by adamdriscoll** [comment]
You'll be able to specify the -GeoLocation switch parameter on New-UDDashboard and when users visit the site they will prompted to allow location detection. In all endpoints for users that allowed detection, the $Location variable will be defined as follows:

```
@{
coords = @{
Altitude,
Longitude,
Latitude,
Heading,
Speed
}
Timestamp
}
```

**Comment by adam-acosta** [comment]
Is this supported as of today? If not, coming soon?

**Comment by adamdriscoll** [comment]
Yep. This works today. You can use the `-GeoLocation` parameter of `New-UDDashboard` to turn it on. Then if a user accepts location tracking in the browser, you will have a `$Location` variable available in your endpoints. 

https://docs.universaldashboard.io/endpoints/variables-defined-in-endpoints#variables-defined-in-endpoints

**Comment by adam-acosta** [comment]
Thanks! My apologies for not seeing it before.
