### ISSUE TITLE
option to force scheduled endpoint to disallow concurrent run.

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/universal-dashboard#1000]
we should be able to specifie that a scheduled endpoint is disallow concurrent run, it seems that DisallowConcurrentExecution could fix that.

not sure how to implement that.

link: https://stackoverflow.com/questions/5984220/in-quartz-net-is-there-a-way-to-set-a-property-that-will-only-allow-one-instance

**Comment by adamdriscoll** [comment]
This issue now has a bounty: https://www.bountysource.com/issues/78621599-option-to-force-scheduled-endpoint-to-not-allow-run-multiply-times

The scheduled endpoint job is here: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Execution/ScheduledEndpointJob.cs#L9

This will also require tests.

**Comment by oitptobbe** [comment]
The DisallowConcurrentExecution will only disallow a Task to run multiple jobs at the same time. What we would need to implement is a change to line 67 (or an option) to use .WithRepeatCount instead of .RepeatForever

**Comment by McAndersDK** [comment]
@oitptobbe I changed the title and text to reflect my initial issue :)
I can see that it were not correct, as it could be misunderstanded, just like you did :)

I am not sure what a use case would be for a scheduled task that are not allowed to repeat itself? :)

**Comment by oitptobbe** [comment]
@McAndersDK Ah yes then I see what you want to accomplish. However maybe you could clarify a bit more for me.

Well for me it might be a case of I want to run a ping 3 times, then wait 5 minutes and run another ping 3 times for a total of 10 repeats... And I've already implemented that... :P

I can see the point of disallowing it sure, for instance when processing files/ad/db etc and it takes longer than the time until the next execution.

However there are also points for allowing it to run multiple at the same time tho this could swamp the cpu/memory of the server (tho it looks like its capped at 100 threads).

@adamdriscoll how would you like to see this implemented? A change from the current way of doing things or ability to "select" that certain endpoints are allowed to run concurrently and certain are not?

It might be possible to add a variable for each job that states if its able to run multiple at once...

**Comment by McAndersDK** [comment]
I see this use case:
This is the example on https://docs.universaldashboard.io/endpoints/scheduled-endpoints
```
$Schedule = New-UDEndpointSchedule -Every 1 -Hour

$EveryHour = New-UDEndpoint -Schedule $Schedule -Endpoint {
    $Cache:ModuleCount = (Get-Module -ListAvailable).Count
}
```
I wanted to have a switch like this:
```
$Schedule = New-UDEndpointSchedule -Every 1 -Hour -Consecutive

$EveryHour = New-UDEndpoint -Schedule $Schedule -Endpoint {
    #This stuff are only allowed to run consecutive.
    # So it can not run multiply time at any time. 
    $Cache:ModuleCount = (Get-Module -ListAvailable).Count
}
```
As I see the code change the following is needed:
- Copy the public class ScheduledEndpointJob : IJob
  - public class ScheduledEndpointjobConsecutive : IJob
  - the new class have the attribute [DisallowConcurrentExecution]
- Add the switch "Consecutive" to the powershell cmdlet "New-UDEndpointSchedule"
- Add logic to handle the switch between the 2 classes.

**Comment by oitptobbe** [comment]
What happens if a job is already running at the time the scheduled endpoint want to run?
Will it wait for the job to be finished, and then execute?
Or will it just be discarded, and the first run at the next scheduled time?

You have the option to choose this with setting 
                    trigger = TriggerBuilder.Create()
                        .StartNow()
                        .WithSimpleSchedule(x => x
                            .WithIntervalInSeconds((int)endpoint.Schedule.Every.TotalSeconds)
                            .WithRepeatCount(endpoint.Schedule.Repeat - 1)
                            **.WithMisfireHandlingInstructionIgnoreMisfires())**
                        .Build();
And this can be set to WithMisfireHandlingInstructionFireNow, IgnoreMisfires, NextWithExistingCount, NextWithRemainingCount, NowWithExistingCount, NowWithRemainingCount.

This will also require modification of ScheduledEndpointManager.cs as far as I can see it...

**Comment by McAndersDK** [comment]
Ah, I guess that need to be implemented as well, for a full configurable behavior implementation :)

`$Schedule = New-UDEndpointSchedule -Every 1 -Hour -Consecutive -Misfire 'option'`

**Comment by oitptobbe** [comment]
So I have a solution I think that would suit you. I haven't implemented the misfire option (at least not yet) but so the code would be something like this.

$Schedule1 = New-UdEndpointSchedule -Repeat 60 -Every 10 -Second
This schedule repeats 60 times. After that it doesn't run anymore.

$Schedule2 = New-UdEndpointSchedule -Every 30 -Second -consecutive
This schedule runs every 30 seconds but doesn't allow concurrent "instances"

$Schedule3 = New-UdEndpointSchedule -Every 10 -Second -consecutive
This schedule runs every 10 seconds but doesn't allow concurrent "instances"

```
Import-Module UniversalDashboard.Community

$Schedule1 = New-UdEndpointSchedule -Repeat 60 -Every 10 -Second
$Schedule2 = New-UdEndpointSchedule -Every 30 -Second -consecutive
$Schedule3 = New-UdEndpointSchedule -Every 10 -Second -consecutive
$Cache:First = ""
$Cache:Second = ""
$Cache:Third = ""
$Endp1 = new-udendpoint -schedule $schedule1 -endpoint {
    $Cache:First = Get-Date
}
$Endp2 = new-udendpoint -schedule $schedule2 -endpoint {
    $Cache:Second = Get-Date
    Start-Sleep -seconds 140
}
$Endp3 = new-udendpoint -schedule $schedule3 -endpoint {
    $Cache:Third = Get-Date
    Start-Sleep -seconds 30
}
$WelcomePage = New-UDPage -Name 'Welcome' -Endpoint {
    New-UDCard -Title "Welcome, $User" -Text "This is your custom dashboard for user $User."
}
$dashboard = New-UDDashboard -Title 'Test consecutive' -Pages $WelcomePage
Get-UDDashboard|Stop-UDDashboard
Start-UDDashboard -Dashboard $dashboard -AutoReload -Port '8000' -Endpoint @($Endp1, $Endp2, $Endp3)
start-sleep -Seconds 3
while($true) {
    write-host "Current time: $(Get-Date)"
    write-host "First schedule: $($Cache:First)"
    write-host "Second schedule: $($Cache:Second)"
    write-host "Third schedule: $($Cache:Third)"
    start-sleep -Seconds 10
}

```

And the output would be similar to this.

So all scheduled task currently have 12:20:50
> Current time: 08/15/2019 12:20:58
> First schedule: 08/15/2019 12:20:50
> Second schedule: 08/15/2019 12:20:50
> Third schedule: 08/15/2019 12:20:50

T+10 - The first schedule has fired again.

** > Current time: 08/15/2019 12:21:01
** > First schedule: 08/15/2019 12:20:58
> Second schedule: 08/15/2019 12:20:50
> Third schedule: 08/15/2019 12:20:50

T+20 - The first schedule has fired again.

> Current time: 08/15/2019 12:21:11
> First schedule: 08/15/2019 12:21:08
> Second schedule: 08/15/2019 12:20:50
> Third schedule: 08/15/2019 12:20:50

T+30 - The first schedule and third schedule have fired again.

> Current time: 08/15/2019 12:21:21
> First schedule: 08/15/2019 12:21:18
> Second schedule: 08/15/2019 12:20:50
> Third schedule: 08/15/2019 12:21:20

T+50 - The first schedule has fired twice.

> Current time: 08/15/2019 12:21:41
> First schedule: 08/15/2019 12:21:38
> Second schedule: 08/15/2019 12:20:50
> Third schedule: 08/15/2019 12:21:20

T+140 -The second schedule have also fired now

> Current time: 08/15/2019 12:23:11
> First schedule: 08/15/2019 12:23:08
> Second schedule: 08/15/2019 12:23:10
> Third schedule: 08/15/2019 12:22:50

**Comment by adamdriscoll** [comment]
@oitptobbe That's awesome!

**Comment by McAndersDK** [comment]
I look forward to test this ! :)
