### ISSUE TITLE
Query string parameters

### ISSUE THREAD

**Issue by jan-sp** [ironmansoftware/universal-dashboard#1003]
Hi,

I'm trying to create some API's using UD  and it works fine.  However I was wondering if there 's a way of using query string parameters like api/Users?Name=Jan&Role=Administrator without having to define all parameters and possible combinations.  In other words:  it would be great if this could work by default and everything past "?" is handled by default as parameters.

Is there a way of getting this work?

Code below works, however only for the parameter "role"  i've defined.

        # Sample data
            $Users = @(
            [PSCustomObject]@{Name = "Jan"; Id = 1; Role = "Administrator"}
            [PSCustomObject]@{Name = "Eef"; Id = 2; Role = "Director"}
            [PSCustomObject]@{Name = "Jef"; Id = 3; Role = "Inspector"}
            )

        $Endpoints +=New-UDEndpoint -Url 'user' -Endpoint {
        param($Role)
        If ($Role) {
        $Users | Where-Object Role -EQ $Role | ConvertTo-Json
        }
        $Users | ConvertTo-Json
        }

tx in advance

Jan

**Comment by adamdriscoll** [comment]
This is because UD is passing the in the query string parameters as parameters rather than variables. It could be changed. I'll have to do some validation to ensure that doesn't break anything.

**Comment by jan-sp** [comment]
That would be a great enhancement!

Kind regards
Jan

**Comment by adamdriscoll** [comment]
This is how PowerShell Universal APIs will work in 1.2. You will not have to define the parameters to have access to the query values.
