### ISSUE TITLE
Update Default Theme to Look Nicer

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1031]
**Suggestions for the Base Theme(s) to be more appealing**
These should comprise simple changes that will allow for a more "modern-looking" UD design out of the box. A few small changes will greatly enhance the look.

**Changes**
- Padding left\right around the main content (50px). 
- Padding top of main content (25px). 
- Make background color set to #eeeeee
- Change default button color to #01579B
- Change default pager colors 

To be continued....

**Simple Mockup** - Seriously it just POPS:
![image](https://user-images.githubusercontent.com/274883/63306642-18a55880-c2b1-11e9-82a1-3c7637f31fdc.png)

**Comment by AlonGvili** [comment]
Way way better...

**Comment by psDevUK** [comment]
Just a thought for next release or something...But how about adding a -border parameter to all main UI controls/objects so you would have something like
New-UDCard -border Round
New-UDCard -border Square
 Like or no like?

**Comment by adamdriscoll** [comment]
@psDevUK I think we should try to avoid that if possible because then we would have to do the same thing for all controls that use cards.

We might want to consider having themes that have Round\Square borders for cards that adjust that for all cards. This way it's consistent across the dashboard and you don't have to set it on every component. 

That said, were you looking to have some cards rounded and some cards square in the same dashboard?

**Comment by psDevUK** [comment]
Hey @adamdriscoll yeah I was thinking default to a square boarder if parameter not specified, but yeah idea was would allow user to have some "rounded boarded" elements on a page and some "square boarded" elements...

**Comment by adamdriscoll** [comment]
Ok. Gotcha. Let me think about that. One thing that we've been talking about is is moving controls out of cards. For example UDChart and UDInput would just be outside of a card and if you want to put it in a card, you could use UDCard. Then adding the -Border parametr would be that bit of a deal.

**Comment by leeberg** [comment]
I have the basics working in a default - I'll ping you @adamdriscoll but the PR should be pretty much ready. Great Conversation about adding more stuff but we can create more enhancements for additional fancy.
