### ISSUE TITLE
Include column Headers on Export to CSV for UD-Grid

### ISSUE THREAD

**Issue by YouTheITGuy** [ironmansoftware/universal-dashboard#1035]
Currently when you export a UDGrid the column headings are not included. 

Can you please configure the export to CSV on New-UDGrid to include column headers?

Thanks

**Comment by dtnyc9005** [comment]
Would be awesome to have this for UDGrid

**Comment by psDevUK** [comment]
So been trying to research this and it looks like the "this.state.headers" contains the headers...so now need to implement that into the current onExportData function inside ud-grid.jsx

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/new-udgrid-out-udgriddata/2900/2
