### ISSUE TITLE
error New-uddashboard

### ISSUE THREAD

**Issue by rddoove** [ironmansoftware/universal-dashboard#105]
New-UDDashboard : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621))

**Comment by adamdriscoll** [comment]
What version are you using?

**Comment by adamdriscoll** [comment]
I can reproduce this in the latest version.

**Comment by adamdriscoll** [comment]
This has been fixed in 1.6.0-beta3.

**Comment by ryaker** [comment]
I'm getting this with UniversalDashboard.Community 2.2.1

**Comment by adamdriscoll** [comment]
@ryaker Could you please run the following in your PowerShell session? 

```
$PSVersionTable
Get-Module 
[NewtonSoft.Json.JsonConvert].Assembly.FullName
```

**Comment by ryaker** [comment]
PS C:\Users\richardya-a> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\richardya-a> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageP...
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapabil...
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSRead...
Script     2.2.1      UniversalDashboard.Community        {Add-UDElement, Clear-UDElement, ConvertTo-JsonEx, Disable-UDL...


PS C:\Users\richardya-a> [NewtonSoft.Json.JsonConvert].Assembly.FullName
Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

**Comment by adamdriscoll** [comment]
I think I need to update the system requirements. I just checked the the first version of PS Core with NewtonSoft.Json 11 was 6.0.3. I think you'll need to update to at least that version.

**Comment by adamdriscoll** [comment]
Oh, I guess I already updated the docs to require 6.1 -> https://docs.universaldashboard.io/system-requirements

So if possible, try updating to that. It might work with 6.0.3 or later though.
