### ISSUE TITLE
Tabs colors don't match the rest of the new default theme

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1060]
#### Describe the Issue

They are still pink\orange while everything else is blue.

#### To Reproduce
```
    New-UDTabContainer -Tabs {
        New-UDTab -Text "Tab1" -Content {

        }

        New-UDTab -Text "Tab2" -Content {
        }

        New-UDTab -Text "Tab3" -Content {
        }
    }
```
#### Expected behavior

They should match the rest of the theme. 

#### Screenshots

![image](https://user-images.githubusercontent.com/1256531/63897692-555d0800-c9b3-11e9-9d58-6d06e302eef7.png)

#### Script Sample
Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information
- **Operating System**: Any
- **PowerShell Version**: Any
- **Universal Dashboard Version**: 2.5.4 (or 2.6)
- **UD Hosting Method**: Any

**Comment by leeberg** [comment]
See: https://github.com/ironmansoftware/universal-dashboard/pull/1062
