### ISSUE TITLE
Floating UDButton Float Color Is Incorrect

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1061]
#### Describe the Issue

When you use -Floating with New-UDButton and hover over it, the color is teal. This is different than if you don't use -Floating. 

#### To Reproduce

```
  New-UDButton -Floating -Icon calendar
```

#### Expected behavior

It should match the hover color of the regular button.

#### Screenshots

![image](https://user-images.githubusercontent.com/1256531/63897823-bbe22600-c9b3-11e9-8a30-cb924fce64d4.png)

#### Version Information
- **Operating System**: Any
- **PowerShell Version**: Any
- **Universal Dashboard Version**: 2.5.4
- **UD Hosting Method**: Any

**Comment by leeberg** [comment]
See: https://github.com/ironmansoftware/universal-dashboard/pull/1062
