### ISSUE TITLE
Enhancement for toast notifications or an alternative

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#1064]
#### Is your Enhancement request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] and would receive great value from [...]
Seen a few request for the toast messages and the position, plus I think the user may not always see the toast if the timeout is to short

#### Describe the solution you'd like
Well after surfing the internet this evening I stumbled across https://sweetalert2.github.io/#download looks like its compatible with react. So was thinking if this could be implemented...?

#### Describe how this would improve your Universal Dashboard Quality of Life
Please help us understand how this would improve your usage of universal dashboard and/or what new capabilities this enhancement would provide you with.
Would give the user designing the dashboard a better way to notify end users with countless modifications that can be maded to this "sweet alert 2" 

#### Describe alternatives you've considered
A clear and concise description of any alternative solutions or Enhancements you've considered.
Literally only found this, and thought it would be a really nice way to enhance the UI of UD

#### Additional context
Add any other context or screenshots about the Enhancement request here.

**Comment by adamdriscoll** [comment]
I just want to point out that `Show-UDToast` has a TON of options. You can certainly change the position and duration of the toast message. `New-UDInputAction -Toast` isn't as customizable...

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Cmdlets/ShowToastCommand.cs

But I took a look at that control and it seems neat and would make a great custom control.

**Comment by psDevUK** [comment]
Ok noted about the options in show-udtoast. I’ve only used toast in buttons.
  As you have approved and recommend this as a custom component I will look to make that happen
