### ISSUE TITLE
Progress Bar Color

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1071]
#### Describe the Issue

The `-ProgressColor` doesn't do anything and the progress bar color is still teal in the default theme. It looks out of place. 

![image](https://user-images.githubusercontent.com/1256531/64032265-4f783b80-cb07-11e9-8176-76710479a96f.png)

#### To Reproduce

```
New-UDPreloader -BackgroundColor 'white' -ProgressColor '#3f51b5' -PercentComplete $PercentComplete
```

#### Expected behavior

The default color should be nice. The `-ProgressColor` should change the progress bar color. 

#### Version Information
- **Universal Dashboard Version**: 2.6\2.5.3

**Comment by leeberg** [comment]
Damn, more green! Will get on it.

**Comment by leeberg** [comment]
See PR: 1072
