### ISSUE TITLE
New-UDEndpoint -AuthorizationPolicy Parameter

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-dashboard#1075]
#### Describe the Issue
When I run this command:

```PowerShell
New-UDEndpoint -AuthorizationPolicy "PolicyName" -Schedule $Schedule -Endpoint $Scriptblock
```

I receive a parameter binding error. I can exclude the `-AuthorizationPolicy` parameter and it works, or I can exclude `-Schedule` in which case I'm prompted for a URL. Are `-Schedule` and `-AuthorizationPolicy` actually mutually exclusive? I can't tell because the help document doesn't include `-AuthorizationPolicy` even though it does autocomplete in the console.

I may be misinterpreting the use of scheduled endpoints, and maybe they don't actually need an authorization policy. It's not explicitly stated in [the docs](https://docs.universaldashboard.io/endpoints/scheduled-endpoints) however.

#### Version Information
- **Operating System**: Windows Server 2016 Standard
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.5.3
- **UD Hosting Method**: IIS

**Comment by mattmcnabb** [comment]
Ok, I can see now that `-Schedule` and `-AuthorizationPolicy` are in fact in two mutually exclusive parameter sets:

![image](https://user-images.githubusercontent.com/6998507/64199109-98a5f380-ce57-11e9-833e-c5bfb7937a25.png)

So if Scheduled Endpoints cannot have authorization policies, I'm assuming that they cannot be queried with a GET request like an API endpoint could?

**Comment by adamdriscoll** [comment]
Correct. Scheduled endpoints are run as background jobs and not exposed as rest apis.

**Comment by mattmcnabb** [comment]
Thanks @adamdriscoll!
