### ISSUE TITLE
Nested dashboard under IIS have incorrect page URL

### ISSUE THREAD

**Issue by mponton** [ironmansoftware/universal-dashboard#1078]
#### Describe the Issue
Based on https://github.com/adamdriscoll/universal-dashboard-documentation/blob/master/running-dashboards/iis.md#creating-nested-iis-sites we only need to change `base href` if we want to host a dashboard under IIS as a nested site.

Given a website with only an `index.html` and an application with alias `ui` that host UD (with a modified `base href` set to `/ui/`), browsing to `https://my.domain.tld/ui` result in a `Page Not Found` error inside the React app. The header/footer/navbar are loaded correctly, but the pages aren't. You can manually browse to the page using `https://my.domain.tld/ui/page_name` but all links in the app seem to be broken.

#### To Reproduce
1. Setup a website in IIS, in the site's root, simply put an `index.html` to confirm the site is working and keep things simple.
2. Under that website in IIS add an application with a virtual path of `/ui` and a physical path that points to your UD folder.
3. In the UD folder, ensure the `<base href="/ui/"/>` is present in the `<head>` of `client/index.html`
4. In the UD folder, create a dashboard.ps1 file with this content:
```powershell
$Pages = @(
    (New-UDPage -Name "Home" -Icon "home" -Content {
        New-UDRow -Columns {
            New-UDColumn -Size 12 -Endpoint  {
                New-UDHeading -Text "This is the home page"
            }
        }
    } -DefaultHomePage),
    (New-UDPage -Name "ui/Test" -Icon "book" -Content {
        New-UDRow -Columns {
            New-UDColumn -Size 12 -Endpoint  {
                New-UDHeading -Text "This is the second page"
            }
        }
    })
)

$Dashboard = New-UDDashboard -Title "Nested Dashboard" -Page $Pages

Start-UDDashboard -Dashboard $Dashboard -Wait
```
5. Browse to `your.domain.tld/ui`

#### Expected behavior
Fully working dashboard with all links working correctly.

#### Actual behavior

**Browsing to `your.domain.tld/ui` shows a `Page not found` error**
![chrome_2019-09-03_10-12-20](https://user-images.githubusercontent.com/822167/64181090-e1e44c00-ce33-11e9-9e6a-bd439e2f98d6.png)

**Browsing to `your.domain.tld/ui/Home` correctly shows the Home page**
![chrome_2019-09-03_10-12-29](https://user-images.githubusercontent.com/822167/64181099-e6a90000-ce33-11e9-8c55-7db16a0b7d51.png)

**Clicking on the NavBar's `Home` link brings you to `your.domain.tld/Home`**
*Broken of course, since invalid path*

**Browsing to `your.domain.tld/ui/Test` shows a `Page not found` error**
![chrome_2019-09-03_10-12-39](https://user-images.githubusercontent.com/822167/64181165-ffb1b100-ce33-11e9-809f-4e57f769aeba.png)

**Browsing to `your.domain.tld/ui/ui/Test` correctly shows the Test page**
![chrome_2019-09-03_10-12-48](https://user-images.githubusercontent.com/822167/64181178-06402880-ce34-11e9-8acd-960f3d95eaea.png)

**Clicking on the NavBar's `Test` link brings you to `your.domain.tld/ui/Test`**
*Showing `Page not found` as above*

#### Version Information
- **Operating System**: Windows 2016 Server
- **PowerShell Version**: 5.1.14393.2636
- **Universal Dashboard Version**: 2.5.3 (Licensed version)
- **UD Hosting Method**: IIS

#### Additional context
* Related to #555
* I was unable to get UD working in a nested setup *without* using an `application` under IIS. This always resulted in IIS failing to start UD with error `...failed to start process with commandline ' ', ErrorCode = '0x80070057 : 0.` in the event log. I suspect a step is missing in the documentation for this to work. In any case, because of other considerations, I would definitely need this to work as a separate application running under another AppPool user with some different settings.

**Comment by adamdriscoll** [comment]
I can reproduce this. Looking into it.

**Comment by mponton** [comment]
Thanks for the fix! Is this available in the enterprise nightly build? And if so, is the nightly build solid enough for development until the next official release?

**Comment by adamdriscoll** [comment]
Tonight's nightly will be much more stable. I had to make some changes to the way that session and connections were being tracked so there were likely issues but my latest PR should fix those.
