### ISSUE TITLE
Allow user to specify REST API base URL and allow nested hosting under IIS

### ISSUE THREAD

**Issue by mponton** [ironmansoftware/universal-dashboard#1079]
#### Is your Enhancement request related to a problem? Please describe
I would like to be able to specify my own "base URL" for the REST API feature.

#### Describe the solution you'd like
For example, instead of always having `/api` as the base URL, I would like to be able to specify things like `/` or `/api/v1`. If I could have multiple base URLs in the same UDRestApi server, it would be even better, but being able to change it would be enough.

#### Describe how this would improve your Universal Dashboard Quality of Life
Right now, with `/api` being hardcoded, it makes some things, like hosting multiple versions of an API, more complicated. Yes, I can "mount" different versions under a `v1` and `v2` path under the base URL, but then I need to duplicate code and keep different versions side by side in a repo instead of say using tags/branches and different applications under IIS.

Also, right now, I found no way of hosting a UDRestApi server in a nested path under IIS.

Being able to  split the dashboard (UI) code from the REST API code under IIS as different applications also allows me to enforce Windows authentication on the dashboard will using JWT on the API (for easier access from Linux servers for example).

#### Describe alternatives you've considered
Right now my setup host the REST API code in the root of the IIS website with a modified `web.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <security>
      </security>
      <handlers>
        <add name="aspNetCore api/login" path="api/login" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
        <add name="aspNetCore api/v1" path="api/v1*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\net472\universaldashboard.server.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile="L:\UD\api-stdout.log" forwardWindowsAuthToken="false" />
      <httpProtocol>
        <customHeaders>
          <remove name="X-Powered-By" />
        </customHeaders>
      </httpProtocol>
    </system.webServer>
  </location>
</configuration>
```
Effectively, this routes requests to `/api/login` and `/api/v1*` to the UDRestAPI server and allows me to (for example) host a swagger UI in `/api/` and a UI under another UD application with virtual path `/ui` (which currently is not working due to #1078).

IIS authentication is set to allow "Anonymous Auth" and "Windows Auth" on the website BUT *only* "Windows Auth" on the `/ui` application.

Ideally, it would make my life easier if I could host each UD instance (UI and REST APIs) under their own application. For example, have a website that contains the following apps:

* `/ui` (UD Dashboard)
* `/api/v1` (UD REST API)
* `/api/v2` (UD REST API)
...

#### Version Information
**Operating System:** Windows 2016 Server
**PowerShell Version:** 5.1.14393.2636
**Universal Dashboard Version:** 2.5.3 (Licensed version)
**UD Hosting Method:** IIS

**Comment by adamdriscoll** [comment]
This will be possible in PowerShell Universal 1.2.
