### ISSUE TITLE
Azure Runspaces

### ISSUE THREAD

**Issue by kpoineal** [ironmansoftware/universal-dashboard#108]
Hey Adam, I know we talked about this but I figured I would leave it here.

Here's the output from the reddit thread:

Essentially if my colleague logs in and starts looking at another Azure subscription, when I refresh my page, my page and data sets will correspond to that subscription as well. Even though I didn't log in to that subscription at all.

I'm guessing this is a limitation of the Powershell Universal Dashboard, but I don't know how to make a webapp and this seemed like a good shot.

Thanks in advance for any help! This type of thing is all new to me!

EDIT: Since a couple people have requested code snippets here they are:

This is how I'm logging in and authenticating:

#LoginForm
$FormLogin = New-UDAuthenticationMethod -Endpoint {
param([PSCredential]$Credentials)
$username = $Credentials.UserName
$password = $Credentials.Password
$creds = New-ObjectSystem.Management.Automation.PSCredential($username,$password)
if (Connect-AzureRmAccount -Credential $creds) {
New-UDAuthenticationResult -Success -UserName $username
}
}
Here's a data page that lists all the VMs in a subscription as a table:

$AzureVMTable_Page = New-UDPage -name "Azure VMs" -Icon table -Content{
ShowContextTopPage
New-UdGrid -Title "Azure VMs" -Headers 
@("ResourceGroupName","Name","Location","VMSize") -Properties 
@("ResourceGroupName","Name","Location","VmSize") -AutoRefresh -RefreshInterval 60 - 
Endpoint {
Get-AzureRmVm | select ResourceGroupName,Name,Location -ExpandProperty 
HardwareProfile | Out-UDGridData
}
}
This is how I'm trying to have the user select a subscription within the app. It works on my local machine, but when I run it from IIS it doesn't even load. Tells me to run Connect-AzureRmAccount cmdlet.

$SelectContext_page = New-UDPage -Name "Select Subscription" -Icon cloud -Content{

$Subs = Get-AzureRmSubscription
New-UDInput -Title "Set Azure Context" -Id "Form" -Content {
New-UDInputField -Type 'select' -Name 'SelectAzureContext' -DefaultValue (Get- 
AzureRmContext).Subscription.Name -Placeholder 'Select Azure Subscription' -Values 
$Subs.Name     
} -Endpoint {
param($SelectAzureContext)
New-UDInputAction -Toast "You Selected $SelectAzureContext"
New-UDInputAction -RedirectUrl "http://localhost:1000/Select-Subscription"
$Context = Set-AzureRmContext $SelectAzureContext   
}
}

**Comment by kpoineal** [comment]
Hey Adam,

Was there ever any update on this? Having one runspace per user would be amazing.

Thanks!

**Comment by adamdriscoll** [comment]
Folding into #950
