### ISSUE TITLE
UDInput errors and gets stuck with Spinning Circle.

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1082]
#### Describe the Issue
This has been a bug I have dealt with since early versions. When using New-UDInput, when the endpoint finishes running, it causes an error and the input gets stuck with a spinning circle. It often times seems random when some will work and others won't. Sometimes just slightly altering the code has cleared it up or made it less likely to happen. Sometimes it can also be intermittent.

I am having issues finding the right combination of things to make this reproducible. Once I remove all of the internal commands, it has altered the udinput enough to make the issue not happen. Often times when this is happening, there really isn't anything that stands out as a pattern. I can have almost identical forms, and it will happen every time on one, and work perfect on the other.

```powershell
New-UDInput -Title "Title" -SubmitText "Submit" -Id "id" -Content {
    New-UDInputField -Name "Name" -Placeholder "Name" -Type "textbox"
} -Endpoint {
    param
    (
        $Name
    )

    Invoke-SomeAction -Name $Name
}
```

```powershell
New-UDInput -Title "Title" -SubmitText "Submit" -Id "id" -Content {
    New-UDInputField -Name "Name" -Placeholder "Name" -Type "textbox"
} -Endpoint {
    param
    (
        $Name
    )

    Invoke-SomeAction -Name $Name

    New-UDInputAction -ClearInput -Toast "Finished"
}
```

```powershell
New-UDInput -Title "Title" -SubmitText "Submit" -Id "id" -Content {
    New-UDInputField -Name "Name" -Placeholder "Name" -Type "textbox"
    New-UDInputField -Name "Item" -Placeholder "Item" -Type "textbox"
} -Endpoint {
    param
    (
        $Name,
        $Item
    )

    Invoke-SomeAction -Name $Name -Item $Item
}
```

I have also had it happen where removing a try\catch made it start working.

Worked
```powershell
New-UDInput -Title "Title" -SubmitText "Submit" -Id "id" -Content {
    New-UDInputField -Name "Name" -Placeholder "Name" -Type "textbox"
} -Endpoint {
    param
    (
        $Name
    )

    Invoke-SomeAction -Name $Name
}
```

Broken
```powershell
New-UDInput -Title "Title" -SubmitText "Submit" -Id "id" -Content {
    New-UDInputField -Name "Name" -Placeholder "Name" -Type "textbox"
} -Endpoint {
    param
    (
        $Name
    )
    Try
    {
        Invoke-SomeAction -Name $Name
    }
    Catch
    {
        Throw
    }
}
```

#### To Reproduce
Steps to reproduce the behavior: (Example)

#### Expected behavior
The udinputs should not get stuck when the endpoint completes.

#### Version Information
- **Operating System**: Server 2019, Windows 10 1803, 1809, 1903
- **PowerShell Version**: 5.1.18362.145, 5.1.14393.2969
- **Universal Dashboard Version**: 2.5.2 
- **UD Hosting Method**: Powershell and IIS

#### Additional context
Setups where issue is Present:
- Prod Server 2019\2016 using https and IIS Auth 
- Dev Windows 10 using http and azure AD Auth
- Dev Windows 10 using http and no Auth
- Versions 2.0.1 to 2.5.2 have all had the issue

When it happens, you get the following error in the logs.

```
9:31:26 [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HLPH8HR5BL7L", Request id "0HLPH8HR5BL7L:00000004": An unhandled exception was thrown by the application.
```

And here is some more context

```
09:31:26 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action method UniversalDashboard.Controllers.ComponentController.Input (UniversalDashboard), returned result Microsoft.AspNetCore.Mvc.JsonResult in 13763.8475ms.
09:31:26 [Info] Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor Executing JsonResult, writing value of type 'System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.Management.Automation.PSObject, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=]]'.
09:31:26 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action UniversalDashboard.Controllers.ComponentController.Input (UniversalDashboard) in 13882.1427ms
09:31:26 [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HLPH8HR5BL7L", Request id "0HLPH8HR5BL7L:00000004": An unhandled exception was thrown by the application.
09:31:26 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 13916.6051ms 200 application/json; charset=utf-8

```

**Comment by adamdriscoll** [comment]
I didn't realize you were throwing out of the Catch handler. The problem here is that any terminating error is causing the UDInput to fail to return correctly. If you do something like this, is it still flaky? 

```
New-UDInput -Title "Title" -SubmitText "Submit" -Id "id" -Content {
    New-UDInputField -Name "Name" -Placeholder "Name" -Type "textbox"
} -Endpoint {
    param
    (
        $Name
    )
    Try
    {
        Invoke-SomeAction -Name $Name
    }
    Catch
    {
         New-UDInputAction -Content { New-UDHeading -Text $_.Exception.Message } 
    }
}
```

**Comment by adamdriscoll** [comment]
That said, we should make the UDInput endpoint handler more resilient so this doesn't happen. Terminating errors should result in some sort of notification to the user.

**Comment by gerane** [comment]
@adamdriscoll I finally figured out the issue. I noticed one of my forms would sometimes work and other times hang. I then figured out a pattern to when it would hang, and after debugging the code, I realized that a Set- command would pass back an object if it made a change, and pass back $null if it didn't make a change. I wasn't setting this to a variable, so when it actually sets something, it would pass back output and break the udinput.

**Comment by gerane** [comment]
@adamdriscoll also, the issue with try catch was when it didn't error. When it errored, it would should a red toast in bottom right and the input field would typically return.

**Comment by adamdriscoll** [comment]
Ah, I see. So you are saying that if an object is dropped on the pipeline it breaks the UDInput and never returns.

**Comment by gerane** [comment]
@adamdriscoll yeah, now that I am aware, I know how to work around it.

**Comment by gerane** [comment]
@adamdriscoll this has returned in 2.6.2. Especially on endpoints that take more than a minute or so.

**Comment by adamdriscoll** [comment]
Please provide relevant logs. I'll take a look.  

Please look over the test that was put in place to validate this and compare it with what you are doing: https://github.com/ironmansoftware/universal-dashboard/pull/1107/files
