### ISSUE TITLE
Can't hit sub-buttons in UDFAB

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1088]
#### Describe the Issue
I added a Simple UDFab with a "sub" button, intended to add stuff to a list.
I'm having a hard time hitting the sub button, as it folds down almost immediately.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard with an UDFAB (Floating Action button)
2. point on the button
3. Try to hit the "sub" button

#### Expected behavior
Being able to hit the second button more often than 1/10 attempts would be nice.

#### Screenshots

https://twitter.com/PorreKaj/status/1170986105598070785

#### Script Sample
```
New-UDFab -ButtonColor 'orange' -Icon beer -Size Large -onClick {
    
    } -Content {
    
        New-UDFabButton -ButtonColor 'blue' -Icon plus -onClick {
            Show-UDToast -Message "Add"
        }
    }
```

#### Version Information
- **Operating System**: W10 1903
- **PowerShell Version**:  5.1.14393.3053   
- **Universal Dashboard Version**: 2.5.3
- **UD Hosting Method**: IIS

#### Additional context
Happens in both Chrome and Edge

**Comment by adamdriscoll** [comment]
@PorreKaj Did this get resolved in 2.6 or is this still a problem?

**Comment by PorreKaj** [comment]
Not solved in 2.6.0 :-)

________________________________

**Comment by adamdriscoll** [comment]
I figured it out. The validateSet was looking for "Large" and "Small". The tests were using "large" and "small". If you actually used the upper version, it was causing the CSS to fail. It also made the icon shift over in the fab.

**Comment by PorreKaj** [comment]
Two birds with one stone :-)

________________________________
