### ISSUE TITLE
UDGrid Export is wonky

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-dashboard#1089]
When I attempt to export the data from a UDGrid, I just get this:

![image](https://user-images.githubusercontent.com/6998507/64566779-b3c7a600-d324-11e9-94b0-9a037609723a.png)

Windows 10
UD Version 2.5.3

**Comment by adamdriscoll** [comment]
This is a problem because the CSV is being generated on the client side after formatting has been done. Your grid probably has custom formatting on all the rows. 

This is going to be an issue until we separate the data from the cell format. I hope to achieve this with #697
