### ISSUE TITLE
New-UDTextbox, New-UDSwitch, New-UDCheckbox  broken in 1.6.0-beta 3

### ISSUE THREAD

**Issue by fmichaleczek** [ironmansoftware/universal-dashboard#111]
Steps to reproduce
------------------

Create a page with 4 elements : UDElement Tag H3 + UDTextBox +UD Switch + UDCheckbox

```
New-UDPage -Name 'Home' -Icon home -Content {
    New-UDElement -Tag 'h3' -Id 'Title' -Content { 'Title' }
    New-UDTextbox -Label "Textbox" -Placeholder "Enter your name"
    New-UDSwitch -OnText "Yes" -OffText "No"
    New-UDCheckbox -Label Unchecked
}
```

Expected behavior
-----------------

A page with a UDElement Tag H3 + UDTextBox +UD Switch + UDCheckbox

Actual behavior  [Updated] 
---------------

Error in page : 
 Cannot read property 'type' of undefined
 Cannot read property 'type' of undefined
 Cannot read property 'type' of undefined

UDElement Tag H3 is OK.

## [EDIT 1]

In Chrome Debug javascript
```
react-dom.production.min.js:163 TypeError: Cannot read property 'type' of undefined
    at UDElementContent.value (ud-element.jsx:109)
    at commitLifeCycles (react-dom.production.min.js:148)
    at t (react-dom.production.min.js:157)
    at y (react-dom.production.min.js:168)
    at v (react-dom.production.min.js:167)
    at m (react-dom.production.min.js:165)
    at f (react-dom.production.min.js:164)
    at Object.enqueueSetState (react-dom.production.min.js:107)
    at t.o.setState (react.production.min.js:11)
    at t.<anonymous> (ud-page.jsx:44)
```

A UDElement with a Tag Input has the same behaviour

```
New-UDElement` -Tag 'input' -Id 'inputTest' -Attributes @{ Value = "inputTest" }
```

## [EDIT 2]

If I start browsing at "http://localhost", it redirects to "/Home" and display UDTextbox.

If I refresh the webpage, UDTextbox failed.

Environment data
----------------

- Universal Dashboard 1.6.0-beta3
- Windows 10 1709 
- PowerShell 5.1
- Chrome 65.0.3325.181 (Official Build) (64-bit)

**Comment by adamdriscoll** [comment]
I pushed a 1.6.0-beta4 that should resolve this.
