### ISSUE TITLE
2.6.0 - changes to Themes breaking the navigation menu on DarkDefault

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1110]
#### Describe the Issue
Child nav items have a White background with Grey Text

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

#### Screenshots
![image](https://user-images.githubusercontent.com/20628942/64866055-0235b700-d63b-11e9-8ec5-7a6ddf164279.png)

#### Script Sample
$theme = Get-UDTheme DarkDefault

$Navigation = New-UDSideNav -Endpoint {
    New-UDSideNavItem -Text "Consultants Dashboard" -PageName "Consultants Dashboard" -Icon hourglass_half
    New-UDSideNavItem -Text "Departments" -PageName "Departments" -Icon sitemap
    New-UDSideNavItem -Text "Employees" -PageName "Employees" -Icon User
    New-UDSideNavItem -Divider
    New-UDSideNavItem -Text " Manage ->" -Icon tools -Children {
        New-UDSideNavItem -Subheader -Text "Subheader"
        New-UDSideNavItem -Text "Manage Departments" -PageName "Admin - Departments" -Icon sitemap
        New-UDSideNavItem -Text "Manage Blue Collars" -PageName "Admin - Blue Collars" -Icon users
    }
}

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by adamdriscoll** [comment]
@leeberg Time to give the dark theme some love ;)

**Comment by leeberg** [comment]
PR in : https://github.com/ironmansoftware/universal-dashboard/pull/1117

**Comment by leeberg** [comment]
https://github.com/ironmansoftware/universal-dashboard/pull/1118
