### ISSUE TITLE
2.6.0 - Clicking Hamburger opens Nav menu, Clicking Hamburger doesn't close Nav menu

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1111]
#### Describe the Issue
Clicking the Hamburger icon with an open nav menu should close it.

#### To Reproduce
Create dashboard with custom nav menu

#### Script Sample
Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by adamdriscoll** [comment]
v3 changes this behavior and it won't be a problem any more.
