### ISSUE TITLE
2.6.0 - UDFAB looks wonky

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1112]
#### Describe the Issue
See screenshot - happens with or without the -content parameter.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

#### Screenshots
![image](https://user-images.githubusercontent.com/20628942/64866383-a28bdb80-d63b-11e9-8a5e-f66dfc626811.png)

#### Script Sample
New-UDFab -ButtonColor 'orange' -Icon plus -Id "FABNew" -Size Large -onClick {
        Show-UDModal -Height "100%" -Width "50%" -Header {
            #New-UDHeading -Size 4 -Text "New Department"
        } -Content { 
             New-UDInput -Title "New Department" -Id "NewDepartmentForm" -Content {
                New-UDInputField -Type 'textbox' -Name 'DepartmentNumber' -Placeholder 'Department Number ("2600922")'
                New-UDInputField -Type 'textbox' -Name 'ShortDepartmentNumber' -Placeholder 'Short Department Number ("922")'
                New-UDInputField -Type 'textbox' -Name 'DepartmentName' -Placeholder 'Department Name ("2600922 - IT")'
                New-UDInputField -Type 'textbox' -Name 'DepartmentNameFriendly' -Placeholder 'Friendly Department Name ("Information Technology")'
                New-UDInputField -Type 'textbox' -Name 'ParentDepartment' -Placeholder 'If applicable, the department number of the parent department ("2600890")'
                New-UDInputField -Type 'textbox' -Name 'Manager' -Placeholder 'Username of the department Manager'
                New-UDInputField -Type 'textarea' -Name 'Notes' -Placeholder 'Optional text that will be included in the notification to IT-Support'
            } -Endpoint {
                param($DepartmentNumber, $ShortDepartmentNumber, $DepartmentName, $DepartmentNameFriendly, $ParentDepartment, $Manager, $notes)

                Show-something

            } -SubmitText "Create"
        }
    }

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by leeberg** [comment]
Hey @PorreKaj, I am having a hard time reproducing this.

I have used your code sample on: Chrome, Firefox, and IE and the FAB seems to be working as expected.

![image](https://user-images.githubusercontent.com/274883/64903398-7abd6780-d67d-11e9-90da-ee4b466b616a.png)

Any chance you could provide a larger sample script?

**Comment by PorreKaj** [comment]
Any particular parts that could be relevant?

________________________________

**Comment by PorreKaj** [comment]
I notice that the button also doesn't change size when I change the -Size Parameter. 

This is the entire page.
Changing theme or browser doesn't affect the issue.

```
New-UDPage -Name "Admin - Blue Collars" -AuthorizationPolicy @("BlueCollarsAdmin") -Icon users -Content {
    
    function Show-something {
    
         Show-UDToast -Message "works" -Duration 6000 -Position topRight -BackgroundColor LightGreen
    
    }

    New-UDRow {
        New-UDColumn -LargeSize 12 -Content {
            New-UDGrid -Id "DepartmentsGrid" -Title "Departments" -Headers @("DepartmentNumber", "DepartmentName", "DepartmentNameFriendly", "ManagerFriendly","Employees","More", "Edit") -Properties @("DepartmentNumber", "DepartmentName", "DepartmentNameFriendly", "ManagerFriendly","Employees","More", "Edit") -DefaultSortColumn "DepartmentNumber" -DefaultSortDescending -PageSize 50 -Endpoint{
                $Cache:AllDepartments | Out-UDGridData
            }
        }
    }
    New-UDFab -ButtonColor 'orange' -Icon address_book -Id "FABNew" -Size Small -onClick {
        Show-UDModal -Height "100%" -Width "50%" -Header {
            #New-UDHeading -Size 4 -Text "New Department"
        } -Content { 
             New-UDInput -Title "New Department" -Id "NewDepartmentForm" -Content {
                New-UDInputField -Type 'textbox' -Name 'DepartmentNumber' -Placeholder 'Department Number ("2600922")'
                New-UDInputField -Type 'textbox' -Name 'ShortDepartmentNumber' -Placeholder 'Short Department Number ("922")'
                New-UDInputField -Type 'textbox' -Name 'DepartmentName' -Placeholder 'Department Name ("2600922 - IT")'
                New-UDInputField -Type 'textbox' -Name 'DepartmentNameFriendly' -Placeholder 'Friendly Department Name ("Information Technology")'
                New-UDInputField -Type 'textbox' -Name 'ParentDepartment' -Placeholder 'If applicable, the department number of the parent department ("2600890")'
                New-UDInputField -Type 'textbox' -Name 'Manager' -Placeholder 'Username of the department Manager'
                New-UDInputField -Type 'textarea' -Name 'Notes' -Placeholder 'Optional text that will be included in the notification to IT-Support'
            } -Endpoint {
                param($DepartmentNumber, $ShortDepartmentNumber, $DepartmentName, $DepartmentNameFriendly, $ParentDepartment, $Manager, $notes)


                Show-something




            } -SubmitText "Create"
        }
    }

} 
```

**Comment by PorreKaj** [comment]
Not page specific as well, happens on all pages.

**Comment by PorreKaj** [comment]
At some point, I played with the Padding/Margin of buttons. I wonder if that is related - The changes persisted until I changed to another theme and back.

It was all good, until 2.6.0.

https://forums.universaldashboard.io/t/change-magin-padding-on-buttons/728

Also: issue persists across clients, not specific to the PC i'm usually testing from.

Also Also "sub-buttons" looks fine
![image](https://user-images.githubusercontent.com/20628942/64944027-925b4280-d86d-11e9-9f7a-c896865d645b.png)

**Comment by PorreKaj** [comment]
The buttons are unaffected by the size parameter. They are always always small.

**Comment by PorreKaj** [comment]
Recycled and stopped the appPool, stopped IIS, deleted all UD from the root folder, copied module over again. No effect :-(

Spun up a new dashboard from powershell on the same server: nothing:
![image](https://user-images.githubusercontent.com/20628942/65039311-3d452c80-d952-11e9-8e67-d75f7c113ec3.png)

**Comment by PorreKaj** [comment]
Copied the Module over from another machine - same.
I'll restart the server, its due anyways.

**Comment by PorreKaj** [comment]
Issue persist across hosts. Infuriating!

**Comment by PorreKaj** [comment]
This is gibberish to me, but maybe not to someone else:
![image](https://user-images.githubusercontent.com/20628942/65042160-91530f80-d958-11e9-8c7f-5347f8b24b41.png)

**Comment by leeberg** [comment]
Repro'd - started using non-release version and happened right away - taking a look.

**Comment by adamdriscoll** [comment]
@leeberg Can you post your script? This was due to the class names being uppercase. I thought I fixed it....

**Comment by leeberg** [comment]
```powershell
    New-UDFab -Icon plus -Id "FAB1" -Size small -onClick {} -
    New-UDFab -Icon plus -Id "FAB2" -Size Small -onClick {}
    New-UDFab -Icon plus -Id "FAB3" -Size large -onClick {}
    New-UDFab -Icon plus -Id "FAB4" -Size Large -onClick {}
```

![image](https://user-images.githubusercontent.com/274883/65648311-635c7380-dfc7-11e9-833e-649c23db1e07.png)

**Comment by adamdriscoll** [comment]
dang....

**Comment by leeberg** [comment]
@adamdriscoll  - looking at the fab documentation... I think I got this...

**Comment by leeberg** [comment]
Easy JSX and PS module Tweak 

![image](https://user-images.githubusercontent.com/274883/65649498-69a11e80-dfcc-11e9-8387-89d9fdee8c97.png)
