### ISSUE TITLE
Use Xterm.js for the design terminal

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1120]
#### Is your Enhancement request related to a problem? Please describe

The existing terminal is hard to use and hard to read with the latest theme update. We should take this opportunity to just update the terminal to XTerm.js

#### Describe the solution you'd like

Use Xterm.js because it's awesome

#### Describe how this would improve your Universal Dashboard Quality of Life

Let's make the terminal actually nice. 

#### Describe alternatives you've considered

We could try to improve the existing terminal...but meh. 

#### Additional context
Add any other context or screenshots about the Enhancement request here.

**Comment by mylabonline** [comment]
Hey Adam - Anyway we can implement XTerm.js to use as a bash terminal?

would be great to have a linux/powershell console window to run additional commands from within the UD Dashboard.. like connecting to Azure/Office 365.

**Comment by adamdriscoll** [comment]
Not going to take this one on at this time.
