### ISSUE TITLE
UDCodeEditor -Code Parameter ignores line

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1122]
#### Describe the Issue
Passing a multiline PS1 through Get-Content to the -Code parameter will result in a single, very long line of code displayed in the code editor.

#### Expected behavior
Lines mshould survive

#### Script Sample
#Note: $Scriptcontent contains a Get-Content on a 60 line PS1 file
```
$ScriptContent = Get-Content $($ArgumentList[0])

   Show-UDModal -Height "1000px" -Width "1000px" -Header {
      New-UDHeading -Size 6 -Text "$($ArgumentList[0])"
   } -Content { 
      New-UDCodeEditor -Id 'editor' -Language powershell -Height "72ch" -Width "118ch" -Code "$ScriptContent" -Theme vs-dark -ReadOnly
   }
```

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by PorreKaj** [comment]
```
Add-UDElement -ParentId 'editor' -Content {
   $ScriptContent
}
```
has the same effect.

**Comment by adamdriscoll** [comment]
Try changing your `Get-Content` call to include the `-Raw` parameter. 

```
$ScriptContent = Get-Content $($ArgumentList[0]) -Raw
```

If you don't do this, it will be an array strings. It seems like UDCodeEditor should support that but it doesn't right now.

**Comment by PorreKaj** [comment]
Yup, that did it.

________________________________
