### ISSUE TITLE
New-UDTabContainer -TabsOrientation Vertical / Default tab

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#1124]
#### Is your Enhancement request related to a problem? Please describe
I do need a convenient way to see a lot of content without scrolling. 
TabsContainer is a good way to achieve that. 

I am running in a situation where I have a lot of tab and would love the ability to use "vertical tabs" 

#### Describe the solution you'd like
As mentionned above, in some situation, having Vertical tabs options would reveal useful.

Current behavior requires horizontal tabs
![image](https://user-images.githubusercontent.com/1980296/64932547-d6b6f600-d80d-11e9-85e1-9be5c446ed65.png)

Vertical tabs, in this particular case,  look neater due to the sheer quantity of tabs 
![image](https://user-images.githubusercontent.com/1980296/64932572-0403a400-d80e-11e9-9bf2-95b84f3f0507.png)

#### Describe how this would improve your Universal Dashboard Quality of Life
This is a layout preference which improves the control by offering more control over the disposition. In the same line of thoughts, having a DefaultIndex parameter could come in handyé

#### Describe alternatives you've considered
I have considered the following
- Use of horizontal tabs anyway
- Reorganize content otherwise to make a lesser use of tabs
- Possibly using a Grid layout using 2 columns / buttons with Set-Element to show only one element and simulate a vertical tab control
- Make the modification myself and create a pull request

**Comment by camusicjunkie** [comment]
Would the side navigation not solve your problem? https://docs.universaldashboard.io/components/navigation

**Comment by itfranck** [comment]
> Would the side navigation not solve your problem? https://docs.universaldashboard.io/components/navigation

@camusicjunkie 

No.
For the same reason side navigation wouldn't be an appropriate replacement for the regular tab container. 

The goal of the tab container is to re-use the same space without the need to scroll back and forth (or change page) between each elements associated to a same context. 

Vertical orientation, when having a bigger number of tabs (9) with somewhat long names, make for a better shaped tab container (less elongated) and the surface area to cover to navigate in-between tabs is optimized.

For a more reasonable number of tabs, horizontal orientation is perfect and the most used. 

It is not a blocker, as I can work around it, which I would have done anyway if the control did simply not exist. That being said, I figured if I had a use case that would benefit from it, others might too.

**Comment by camusicjunkie** [comment]
When using the `-Fixed` parameter with `New-UDSideNav` you can get the dashboard to look very similar to your vertical tab screenshot. I think there are some changes that need to be made to `New-UDSideNav` before this solution would be completely viable but it might do for you needs now.

![image](https://user-images.githubusercontent.com/33888807/65581396-3c069780-df30-11e9-9f50-c005bd990ff9.png)

```powershell
$Page1 = New-UDPage -Name "Page Name" -Content { New-UDCard -Id 'page-1' }
$Page2 = New-UDPage -Name "Page Name 2" -Content { 
    New-UDRow -Columns {
        New-UDColumn -Content {} -SmallSize 1
        New-UDColumn -Content {
            New-UDCard -Id 'page-2'
        } -size 11
    }
}
    
$Navigation = New-UDSideNav -Content {
    New-UDSideNavItem -Text "My First Page" -PageName "Page Name" -Icon group
    New-UDSideNavItem -Subheader -Text "Subheader"
    New-UDSideNavItem -Text "My Second Page" -PageName "Page Name 2" -Icon User
    New-UDSideNavItem -Divider
    New-UDSideNavItem -Text "Google" -Url 'https://www.google.com' -Icon Users
} -Fixed
    
$dashboard = New-UDDashboard -Title "Navigation" -Pages @($Page1, $Page2) -Navigation $Navigation
Start-UDDashboard -Dashboard $dashboard -Port 1000 -Force
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/help-plan-the-future-of-universal-dashboard/2176/2
