### ISSUE TITLE
New-UDInput Fails Validation With Content and Endpoint

### ISSUE THREAD

**Issue by awickham10** [ironmansoftware/universal-dashboard#1130]
#### Describe the Issue
It appears that when using -Validate, -Content, and -Endpoint on New-UDInput the validation fails. The frontend ends up calling a URL with a null reference to the endpoint.

```http://localhost/api/internal/component/input/validate/null/MyFieldName```

#### To Reproduce
Put this in a dashboard and do not fill out the field. The URL above will be called and get a 404.
```powershell
        New-UDInput -Title 'Request' -Validate -Content {
            New-UDInputField -Type 'textbox' -Name 'MyField'
        } -Endpoint {
            param (
                [Parameter(Mandatory)]
                $MyField
            )
        }
```

#### Expected behavior
Validation to work properly with -Content and -Endpoint.

#### Script Sample
This works properly.
```
powershell
        New-UDInput -Title 'Request' -Validate -Endpoint {
            param (
                [Parameter(Mandatory)]
                $MyField
            )
        }
```

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1.17134.858
- **Universal Dashboard Version**: 2.6
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment]
#1136 - Kinda related. Moral of the story: make validation work better when using New-UDInputField.
