### ISSUE TITLE
Google+ API auth has been deprecated

### ISSUE THREAD

**Issue by Claustn** [ironmansoftware/universal-dashboard#1137]
#### Describe the Issue
You can no longer use Google+ based Auth
https://github.com/aspnet/AspNetCore/issues/6486
This causes authentication against google to fail, this has been fixed in later versions of Microsoft.AspNetCore.Authentication.Google.dll, I have tested with version 2.1.8, which seems to work fine.
Current behavior when you have signed into google, and you are returned to the URL you have specified in the google auth setup, but  you get a 500 unavailable.

#### To Reproduce
Create a simple login page that uses google as provider, and it will fail.
I used this example to test https://poshtools.com/2017/11/12/login-pages-powershell-universal-dashboard (Using the google provider instead)

#### Expected behavior
Authentication should be successful

#### Version Information
- **Windows 10 - 1903**:
- **PowerShell Core 6.2.2**:
- **Universal Dashboard Version 2.6.0**:
- **UD Hosting Method**: (Powershell )

#### Additional context
Currently, you can just replace PowerShell\Modules\UniversalDashboard\2.6.0\netstandard2.0\Microsoft.AspNetCore.Authentication.Google.dll  with a newer version from here:
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Google/2.1.8
That seems to work fine.

Since I do not have VS 2017 on this machine, I have not been able to try an actually build the entire project, just thought I would submit an issue, if other people come across this issue as well, so they do not have to spend as much time on it as me.

**Comment by adamdriscoll** [comment]
Thanks! Got the change in the next version.
