### ISSUE TITLE
Collapsible has a white background color

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1149]
There is some weird white space (probably just coloring) when you use New-UDCollapsible. 

Probably need to set the background to transport. 

```
 New-UDCollapsible -Popout -Items {
        # Get value (show websocket)

        New-UDCollapsibleItem -Title "Get-UDElement" -Content {
            New-UDTextbox -Label "Enter some text" -Id 'MyTextbox'
            New-UDButton -Text 'Get the text' -OnClick {
                Show-UDToast -Message (Get-UDElement -Id 'MyTextbox').Attributes['value']
            }
        }
}
```

![image](https://user-images.githubusercontent.com/1256531/65304188-ae2c5480-db9d-11e9-845c-cedc73d0f46a.png)

**Comment by leeberg** [comment]
UDCollapsible defaulting some backgrounds - will probably update this component

![image](https://user-images.githubusercontent.com/274883/65400655-10957880-dd89-11e9-9c03-2fe1bb822174.png)

**Comment by leeberg** [comment]
PR'ed https://github.com/ironmansoftware/universal-dashboard/pull/1184

**Comment by psDevUK** [comment]
Added a pull request last night which resolves this issue.
