### ISSUE TITLE
Footer has a slightly different color bar at the top

### ISSUE THREAD

**Issue by camusicjunkie** [ironmansoftware/universal-dashboard#1153]
#### Describe the Issue
The footer is split in to two similar colors. There is a different color bar that sits at the top of the footer. This behavior occurs regardless of the theme or background color assigned to New-UDFooter.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard

#### Expected behavior
The footer should be one solid color from top to bottom.

#### Screenshots
![image](https://user-images.githubusercontent.com/33888807/65370769-5af3e980-dc11-11e9-9ed4-07ea9ba7689d.png)

#### Version Information
- **Operating System**: 10.0.18362
- **PowerShell Version**: 5.1.18362.145
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: Powershell

**Comment by leeberg** [comment]
Fixed in upcoming PR.

![image](https://user-images.githubusercontent.com/274883/65398285-e7bab680-dd7b-11e9-87dc-6058e09fcc12.png)

**Comment by leeberg** [comment]
This causes problems on the footer when specifying copyright on new-udfooter 😱

**Comment by leeberg** [comment]
Latest PR should Resolve! https://github.com/ironmansoftware/universal-dashboard/pull/1175
