### ISSUE TITLE
Footer color can not be changed with New-UDFooter

### ISSUE THREAD

**Issue by camusicjunkie** [ironmansoftware/universal-dashboard#1154]
#### Describe the Issue
Footer color cannot be changed with ```New-UDFooter -BackgroundColor Gray```. The only way to change the footer color is to change the nav bar background color.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start dashboard with a different color footer.

#### Expected behavior
The background color of the footer should be able to be modified independent of the nav bar background color

#### Script Sample
```powershell
$dashboard = New-UDDashboard -Title "Test Dashboard" -Content {
    New-UDHeading -Text "Test" -NavBarColor 'gray' -Footer (New-UDFooter -Copyright Copyright' -BackgroundColor 'Blue')
}
Start-UDDashboard -Dashboard $dashboard -Port 1000 -Verbose
```

**Comment by leeberg** [comment]
Found issues with how the New-Footer - in since initial release - nice find :)

PR https://github.com/ironmansoftware/universal-dashboard/pull/1185

**Comment by psDevUK** [comment]
Hey @camusicjunkie just went on to poshud and was able to change the footer tweaking:-
.ud-footer {
	background-color: #3f5;
	color: #000;
}
 So if a must need then this could be converted to a custom theme...?
