### ISSUE TITLE
Margin/padding differences in Sidenavitems

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1164]
#### Describe the Issue
Related to closed issue 808 (https://github.com/ironmansoftware/universal-dashboard/issues/808).

The Icons of sidenavitems with children are placed juuust a bit more to the left, than other items - and the text quite a bit more

#### Expected behavior
Margins and padding for all sidenavitems should be the same

#### Screenshots
![image](https://user-images.githubusercontent.com/20628942/65406246-49f8d300-dddf-11e9-8e62-373677633b80.png)

#### Script Sample
```
$Navigation = New-UDSideNav -Endpoint {
    $Policies = Get-UDAuthorizationPolicy
    New-UDSideNavItem -Text "Home" -PageName "Home" -Icon home
    New-UDSideNavItem -Text "Consultants Dashboard" -PageName "Consultants Dashboard" -Icon hourglass_half
    New-UDSideNavItem -Text "Departments" -PageName "Departments" -Icon sitemap
    New-UDSideNavItem -Text "Employees Dashboard" -PageName "Employees Dashboard" -Icon User
    New-UDSideNavItem -Text "Blue Collars" -PageName "BlueCollars" -Icon User
    if ($Policies -contains 'Manager'){
        New-UDSideNavItem -Divider
        New-UDSideNavItem -Text "Manager ->" -Icon sitemap -Children {
            New-UDSideNavItem -Text "Your Department" -PageName "Manager" -Icon User
        }
    }
    if ($Policies -contains 'AdminCollection'){
        New-UDSideNavItem -Divider
        New-UDSideNavItem -Text "Administration ->" -Icon tools -Children {
            if ($Policies -contains 'DepartmentsAdmin'){
                New-UDSideNavItem -Text "Administer Departments" -PageName "Admin - Departments" -Icon sitemap
            }
            if ($Policies -contains 'BlueCollarsAdmin'){
                New-UDSideNavItem -Text "Administer Blue Collars" -PageName "Admin - Blue Collars" -Icon users
            }
            if ($Policies -contains 'EmployeesAdmin'){
                New-UDSideNavItem -Text "Administer Employees" -PageName "Admin - Employees" -Icon users
            }
        }
    }
}
```

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by psDevUK** [comment]
fixed this issue in the pull request I submitted

**Comment by adamdriscoll** [comment]
@PorreKaj  @psDevUK  - Just going through the UD backlog. Is this still any issue?

**Comment by psDevUK** [comment]
Hello Mr @adamdriscoll, going via the post I put in the pull request for this after I fixed it. I'm happy it is fixed if the pull request was accepted.
