### ISSUE TITLE
Faster Get-UDAuthorizationPolicy?

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1165]
#### Is your Enhancement request related to a problem? Please describe
The time it takes to Get-UDAuthorizationPolicy, can in some cases cause UX issues.

For example, I dynamically add/remove sidenavitems based on Get-UDAuthorizationPolicy - Fast visitors could end up with a blank menu for a few seconds.

#### Describe the solution you'd like
Not sure. Any kind of improvement to the speed would be helpful

#### Additional context
Add any other context or screenshots about the Enhancement request here.
![image](https://user-images.githubusercontent.com/20628942/65406533-23876780-dde0-11e9-8c45-169dbd4c437b.png)

**Comment by mylabonline** [comment]
I experience the same issue - I use the Get-UDAuthorizationPolicy to load the Navigation as well as some elements on the page itself, like buttons (enabled/disabled) and depending on the load of the Dashboard some elements take 15-20 seconds to load.

**Comment by PorreKaj** [comment]
Itfranck suggested storing the authorization in a session variable, that way you only need to run it once. Still, any improvement would be welcome.

https://forums.universaldashboard.io/t/sidenav-configuration-and-authorizationpolicies/1288/5?u=porrekaj

**Comment by adamdriscoll** [comment]
2.7 will evaluate all authorization policies on login and then store that information in the session automatically. This will improve the performance of both Get-UDAuthorizationPolicy as well as loading pages that have authorization policies defined.
