### ISSUE TITLE
TabControl is also struck by the midnight blues in DarkRounded

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1167]
#### Describe the Issue
Another control that has an distinct blue tone on the DarkRounded theme

#### Screenshots
![image](https://user-images.githubusercontent.com/20628942/65439652-d29b6180-de27-11e9-8844-3e6805574eb2.png)

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by adamdriscoll** [comment]
@psDevUK FYI

**Comment by psDevUK** [comment]
I thought I sorted that? on it now....

**Comment by psDevUK** [comment]
Yep I did sort it 6 days ago...I just double checked forked again then loaded the code and its fixed so no changes needed :-)
![fixedAlready](https://user-images.githubusercontent.com/44211223/65629616-8f79f380-dfcb-11e9-8a0a-799349440b7a.PNG)

**Comment by psDevUK** [comment]
You see I also even fixed the gap between nav and tabs as well :-)

**Comment by adamdriscoll** [comment]
@psDevUK Sweet! Thanks!

**Comment by psDevUK** [comment]
Sorry @adamdriscoll do you want the spacing fixed between the top NAV on the default theme? I know this is @leeberg baby so I don't want to tred on any toes...but here is same dashboard using default theme:-
![spacing](https://user-images.githubusercontent.com/44211223/65630171-c8669800-dfcc-11e9-87df-0c7187265186.PNG)

**Comment by psDevUK** [comment]
I did a crappy yellow highlight to show the empty space...I work on tiny laptop screen so space matters to me 👍

**Comment by adamdriscoll** [comment]
We added that space intentionally. Maybe we create another theme called "Tight" that reduces all the spacing.

**Comment by PorreKaj** [comment]
Could it be done in a way so you could just put a -Tight switch on get-UDTheme? That way you don’t have to maintain nX2 themes.

**Comment by adamdriscoll** [comment]
Now that is an interesting concept. I think it would be neat to provide options for themes. We could extend the Get-UDTheme cmdlet to use dynamic parameters and then pass those values into the theme. Then you could have simple logic in the theme to make those adjustments.

**Comment by PorreKaj** [comment]
Glad I could inspire :D Sound like a neat feature.

________________________________

**Comment by psDevUK** [comment]
I been thinking this in my head, but if you had a page with all possible standard UD components on it, then a styler react component that let you adjust it all real-time, then you press the GENERATE button which then gives you the code you need to apply as a custom theme, then anyone can sort there own styling issues out before they get started on a project
