### ISSUE TITLE
Folders in SideNav are not displaying right in new default theme

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1192]
#### Describe the Issue
Folders in SideNav are not displaying right in new default theme

#### Expected behavior
The folders should look the same

#### Screenshots
![2019-09-28_16-00-05](https://user-images.githubusercontent.com/6662208/65822428-60e95c00-e209-11e9-9663-3ec16be10f20.png)

#### Version Information
- **Operating System**: Windows 10 (Haven't tested under prod server 2016\2019)
- **PowerShell Version**: 5.1.18362.145
- **Universal Dashboard Version**: 2.6.2
- **UD Hosting Method**: PowerShell (have not tested under IIS yet)

**Comment by gerane** [comment]
I had a couple minutes to play with the default theme, but wasn't able to get it perfect. Are the folders supposed to be bigger than the others? I was also seeing some of behavior with the li elements and the highlighted colors. The small strip on the left highlights slightly shower than the rest and lags behind. Is that meant to stay solid?

**Comment by gerane** [comment]
I also found a weird issue that seems to be caused by the window losing focus. If I alt tab and come back with the sidebar open, the collapsible header goes white.

![losefocus](https://user-images.githubusercontent.com/6662208/65834405-15ce5800-e2a0-11e9-9edb-fdbcb5fbeb19.gif)

**Comment by gerane** [comment]
And here is the behavior I was seeing with the collapsible li hover color lagging.

![hoverlag](https://user-images.githubusercontent.com/6662208/65834439-7e1d3980-e2a0-11e9-9ad1-5335eec6261c.gif)

**Comment by gerane** [comment]
Here are the snippet I was playing with. I am not very good at the web design stuff, so would love to understand how this should work. Just uncomment the one block to turn the hover color on\off.

```powershell
$Theme = New-UDTheme -Name "Test" -Parent 'Default' -Definition @{

        '.sidenav .collapsible-header' = @{
            'color'= "#FFFFFF"
            # 'font-size' = 'large'
            'background-color' = "#3F51B5"
        }

        '.sidenav .subheader' = @{
            'color' = "#FFFFFF"
            # 'font-size' = 'large'
        }

        '.sidenav .collapsible-header:hover, .sidenav.fixed .collapsible-header:hover' = @{
            'color'= "#FFFFFF"
            'background-color' = "#2C387E"
        }

        # '.sidenav .collapsible li:hover, .sidenav.fixed .collapsible li:hover' = @{
        #     'color'= "#FFFFFF"
        #     'background-color' = "#2C387E"
        # }

        '.sidenav .collapsible li, .sidenav.fixed .collapsible li' = @{
            'padding' = '0'
            'background-color' = '#3F51B5'
        }

        '.sidenav .collapsible li active, .sidenav.fixed .collapsible li active' = @{
            'background-color' = "#3F51B5"
        }

        '.sidenav .collapsible-header active' = @{
            'background-color' = "#3F51B5"
        }
    }
```

**Comment by gerane** [comment]
Hmm, is the issue that the side nav main background should be the blue color?

**Comment by adamdriscoll** [comment]
I think we were going for the blue color on the side nav. It looks like you are close. @leeberg might have some ideas on how to dial this in.

**Comment by gerane** [comment]
@adamdriscoll that seems to have fixed the issue with the white coming through. Still can't get the header sizing to look quite right, but haven't had much time to look at it.

**Comment by gerane** [comment]
@adamdriscoll I take that back, setting '.sidenav' background color isn't enough. The issue with the white header still happens

**Comment by adamdriscoll** [comment]
Blarg. Ok. I'll futz with it.

**Comment by psDevUK** [comment]
Hey @adamdriscoll  and @gerane this should be resolved in the pull request i did last night.
