### ISSUE TITLE
Modals can stop working on pages and cause dashboard to lag

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1195]
#### Describe the Issue
I use a lot of modals to display results or selection boxes to end users. When running in my dev environment, I cannot reproduce this. I still need to test if this issue would occur if not running under IIS. I am testing 2.6.2 to try to upgrade prod to see if it clears up the issue, but still working out a few issues with 2.6.2. I am also testing ADFS auth with the plan to migrate from IIS auth to ADFS auth to see if that might clear the issue.

When a user clicks a selection button, it is supposed to open up a selection modal, sometimes they are left with a spinning circle and the page never opens the modal. Usually refreshing the page makes it work again. However, in some cases it hangs the dashboard up and it becomes unresponsive. Pages stop loading, and I usually start getting messages from users and I will have to restart IIS. 

The more modals I use, the bigger chance this happens. The flow that would kill the page 90% of the time:

* user types in values
* hits submit button
* log modal pops up (udgrid with log entries sorted by date)
* log modal is hidden and selection modal pops up (UDTable with rows that have a select button)
* user clicks select button to make choice with onclick 
* selection modal is hidden and log modal pops up.
* Log modal stays until results modal pops up.
* User closes modal.

This flow was almost unusable in prod on Server 2016 under IIS. I cannot reproduce it on my windows 10 dev box running it under powershell. Removing the log modals and only using select and results modals has helped, but it still happens often.

I couldn't find anything that stood out in the logs. There didn't really look like anything was different than when it was running normal. I have been trying to disable logging to see if it helped, so I don't have any logs at the current moment, but I can reenable the logging and try to gather some when it is having the issue.

#### To Reproduce
I am unsure if this is specifically related with udselect endpoints opening modals or if it is just modals in general. I am hoping to upgrade to 2.6.2 and swap from IIS to ADFS tomorrow to see if that clears anything up.

#### Expected behavior
Modals should not break the page.

#### Screenshots
I have provided Adam with a few images and gifs of the modal flow, but I don't want to post those here.

#### Version Information
- **Operating System**: Dev: Windows 10. Prod: sever 2016
- **PowerShell Version**: Dev: 5.1.18362.14, Prod: 5.1.14393.2969
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: Dev: Powershell, Prod: IIS

**Comment by adamdriscoll** [comment]
@gerane Can you try tonight's nightly build? I think I found the issue... It will be available tomorrow.
