### ISSUE TITLE
Modals can pop up in different tabs\browser windows if focus is changed.

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1196]
#### Describe the Issue
When opening a modal, if a user change to a different tab or browser window with a dashboard, the modal will open up on whatever page is active.

I'm currently away from my PC, but I can get a gif of this happening if needed.

#### To Reproduce
1. Trigger modal (sometimes there might be some backend code that makes the modal delay opening by a second or 2)
2. Alt tab to a different browser window on a different page of the dashboard.
3. Modal will open on the alt tabbed browser.

#### Expected behavior
The modals should be tied to the page that opens them.

#### Version Information
- **Operating System**: windows 10\server 2016
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.6.0 (but I think it's there in 2.6.2, but need to verify)
- **UD Hosting Method**: Powershell, IIS

**Comment by adamdriscoll** [comment]
This has been resolved by some changes I made to session state that will be coming in the next version.
