### ISSUE TITLE
New default themes padding makes small screens like phones much harder to user.

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1203]
#### Describe the Issue
The older default themes had a much better experience on smaller screen devices. They would expand to the edges, but with the new themes you lose a ton of real estate.

@adamdriscoll Can the original theme be included in the Get-UDTheme? I am taking the old default and using that, but would be nice if the old default was still included.

#### Expected behavior
Should have a better smaller screen experience

#### Screenshots
Old Theme
![2019-09-30_16-43-45](https://user-images.githubusercontent.com/6662208/65919346-a771be80-e3a1-11e9-866b-ecab777b45bf.png)

New Theme
![2019-09-30_16-44-25](https://user-images.githubusercontent.com/6662208/65919356-af316300-e3a1-11e9-92a0-fd8c2dd694d0.png)

#### Version Information
- **Operating System**: Windows 10, server 2016
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.6.0 and 2.6.2
- **UD Hosting Method**: (Powershell, IIS)

#### Additional context

**Comment by psDevUK** [comment]
Did post a new default theme last night with less padding, however this is not a bug in my opinion as everyone has their own preference for how a dashboard should look.  So I personally would tweek the theme by doing this:-

$Theme = New-UDTheme -Name "Basic" -Definition @{
  'main' = @{
            'padding-left' = "0px"
            'padding-right' = "0px"
            'padding-top' = "0px"
            'padding-bottom' = "0px"
        }
  } -Parent "Default"

  Then you have no padding and elements should make full use of the page area. Then simply add this $Theme as the theme for your dashboard.  If you are happy with this reponse then please close the request. Thanks
