### ISSUE TITLE
Footer contains additional > displaying in the footer

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#1209]
#### Describe the Issue
A clear and concise description of what the issue is.
https://forums.universaldashboard.io/t/ud-footer-jsx-has-an-extra-arrow-and-needs-to-be-removed/1342

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

$Footer = New-UDFooter -Copyright 'Designed by Adam'
#### Expected behavior
Not for an addition > to be displayed in the footer

#### Screenshots
Screenshot located here:-
https://forums.universaldashboard.io/t/greater-than-sign-in-bottom-left-of-footer/1367

#### Script Sample
Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)
Windows 10, UD 2.6.2

**Comment by mylabonline** [comment]
Same.

![image](https://user-images.githubusercontent.com/22712034/66041013-cded4200-e4e6-11e9-84a0-cd903ddef12c.png)
