### ISSUE TITLE
Performance issues when running numerous sessions

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#122]
When a page has a several controls with auto refresh with low refresh intervals, the entire dashboard can become unresponsive for users. CPU usage may be relatively low but it seems like HTTP connections may be saturated as it takes multiple seconds for ASP.NET to return from requests.

**Comment by fmichaleczek** [comment]
Too many endpoint ?

We maybe need a throttled data layer.

It's very experimental but maybe the solution to create a high performance data pool without runspacepool.
https://github.com/SeeminglyScience/PSLambda
