### ISSUE TITLE
Tabs in Modal Display issue

### ISSUE THREAD

**Issue by GoGorillaUK** [ironmansoftware/universal-dashboard#1221]
#### Describe the Issue
When Tabs are used inside a modal, a scrollbar is displayed on load.
Once any tab is clicked it behaves as expected. 

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

#### Expected behavior
No scrollbar displayed on load

#### Screenshots
![image](https://user-images.githubusercontent.com/41877129/66160863-f2e6cf80-e622-11e9-8ef1-9c68f4e0ec83.png)

#### Script Sample
    New-UDButton -Text 'More Tabs' -Icon baseball_ball -onclick{
        Show-UDModal -Content{
            
                New-UDTabContainer  -Tabs {
                    New-UDTab -Text 'Tab1.1' -Content{
                        New-UDParagraph -Text 'This is Tab1.1'
                    }
            
                    New-UDTab -Text 'Tab2.1' -Content{
                        New-UDParagraph -Text 'This is Tab2.1'
                    }
            
                    New-UDTab -Text 'Tab3.1' -Content{
                        New-UDParagraph -Text 'This is Tab3.1'
                    }
            
            } 
        } 
    }

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5
- **Universal Dashboard Version**: 2.6.0
- **UD Hosting Method**: Powershell

**Comment by dtnyc9005** [comment]
beat me to it ;) confirmed, this is also happening in one of my modals.

**Comment by adamdriscoll** [comment]
Workaround posted to forums: https://forums.universaldashboard.io/t/tabs-in-modal-strange-display-issue/1388/10
