### ISSUE TITLE
Add the ability to Limit -Design access

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1222]
#### Is your Enhancement request related to a problem? Please describe
As my dashboard get used by more and more users, restarting the whole dashboard to enable the -Design switch becomes a disruption.
I don't want users to poke around in the design terminal, or move elements around so leaving the design switch on always is a no go.

#### Describe the solution you'd like
Implement, if possible, the ability to limit the Design features to specified users/auth policy.

**Comment by adamdriscoll** [comment]
I like this idea! Like admins have design while others do not. Neat.

**Comment by mattmcnabb** [comment]
+1!

I could definitely use that!

**Comment by adamdriscoll** [comment]
There is now an AdminAuthorizationPolicy parameter on New-UDDashboard. This limits access to design mode as well as the new diagnostics page. 

https://forums.universaldashboard.io/t/ud-enterprise-diagnostics/1477
