### ISSUE TITLE
Allow use of Grant-UDJsonWebToken*AND* New-UDAuthenticationResult under REST API

### ISSUE THREAD

**Issue by mponton** [ironmansoftware/universal-dashboard#1226]
Unless I missed a memo, there is currently not way under the REST API server (Start-UDRestApi) to enable both:

- API-based authentication via the /api/login endpoint
- Grant your own JWT with your own signing key and parameters

**NOTE:** This [thread](https://forums.universaldashboard.io/t/authentication-authorization-in-the-rest-api/149/4) seems to indicate there might be some way to do this BUT I could never make this work and I'm looking for a simpler way to do things.

I understand that a lot of users may be using UD's dashboard features more than it's REST API system, but in my case the latter is more important and I feel that authentication/authorization is lacking on this side (I will open other FR and to be more specific).

What I see is something I described [here](https://github.com/ironmansoftware/universal-dashboard/issues/945#issuecomment-536592505) and may be (somewhat) related to that ticket. The TL;DR is that I need and easy way to change the JWT signing key while allowing users to login via a `POST /api/login` like this (or similar):

```
$Token = Grant-UDJsonWebToken -Issuer "MyIssuer" -SigningKey "MyTopSecretSigningKey" -Username "SomeUser" -Subject "MySubject" -Expiry (Get-Date).AddMinutes(60)
New-UDAuthenticationResult -Success -UserName $userName -Role $role -ErrorMessage '' -Token $Token
```

The `/api/login` endpoints should then succeed but return **MY** token, not one signed with the default key.

**NOTE:** Yes, this may read more like a feature request than a bug, but I prefer to classify it as a bug since security should come foremost for any API, particularly in an enterprise.

**Comment by mponton** [comment]
@adamdriscoll By the way, re-reading myself tonigh, I sound particularly condescending. That was not my intention. My apologies.

**Comment by adamdriscoll** [comment]
@mponton No worries!

**Comment by mponton** [comment]
@adamdriscoll May I inquire if you think this might be a feature present in the next UD version? Technically, with the other fixes/features you are planning, this is the only thing I won't have a full solution to on the authentication side. Right now I even tested hex-editing the default signing key in the DLL (old school but it works :smile:) in case I have to release the API before I have some official way of changing the JWT signing key. This is my last resort and it does not give me full control on the JWT, but it ensure the signing key is not the default one while allowing API authentication.

If I'm missing an obvious workaround to this, please let me know.

Thanks!

**Comment by adamdriscoll** [comment]
I can get this in.

**Comment by mponton** [comment]
This is very much appreciated! Thanks a lot!

**Comment by adamdriscoll** [comment]
This will be in tonight's nightly.
