### ISSUE TITLE
Allow developer to add custom payload to the JWT

### ISSUE THREAD

**Issue by mponton** [ironmansoftware/universal-dashboard#1227]
The JWT specification allows custom payload entries and I would like to be able to give Grant-UDJsonWebToken a hash of entries to add to the token. Some examples:

* User full name
* Session ID (instead of a cookie because when the API is used by things like curl, cookies are not stored by default)

I'm not looking to make a database out of the JWT but being able to add custom key=value entries would definitely help some use cases.

**Comment by adamdriscoll** [comment]
I've added a -Payload parameter to Grant-UDJsonWebToken to pass in a hashtable.

**Comment by mponton** [comment]
That is great news, thanks!
