### ISSUE TITLE
Unexpected layout from InputField type 'date'

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#1230]
```powershell
New-UDInput -Id "DateForm" -Content {
    New-UDInputField -Type 'date' -Name 'DateFrom' -Placeholder 'From:' -DefaultValue "01-01-2019"
    New-UDInputField -Type 'date' -Name 'DateTo' -Placeholder 'To:'-DefaultValue "01-02-2019"
} -Endpoint {
    param(
        $DateFrom,
        $DateTo
    )

}
```

I would expect this to produce something a little bit more elegant than this:
![image](https://user-images.githubusercontent.com/9411143/66280795-33d22480-e86d-11e9-89c0-3d201ec835a5.png)

- Default values aren't showing up.
- Expected the 'From:/To:' labels to be above the input field.
- Expected each input field to be horizontal, like every other input field, not side by side.

**Comment by mkellerman** [comment]
And while we're at it.. why is creating an UDInput automatically making a UDCard? If we want a UDCard, we should create it, and put the UDInput in the content, instead of forcing the style. or add a switch -AsCard ?

**Comment by adamdriscoll** [comment]
I think I'm just going to move everything out of cards. UDInput, UDCharts, UDTables etc. Doesn't make sense to put everything in a card.

**Comment by mkellerman** [comment]
It allows us to do a little bit more advanced layout.

**Comment by adamdriscoll** [comment]
What control are you putting this input in? If i have the input directly in a page it looks ok. 

![image](https://user-images.githubusercontent.com/1256531/66671077-85393580-ec18-11e9-8baf-689085122c36.png)

**Comment by mkellerman** [comment]
inside of a custom table

New-UDElement -Tag 'table' -Content {
New-UDElement -Tag 'tr' -Content {
New-UDElement -Tag 'td' -Content {
<! -- here -->
}
}
}

I might be breaking things with my 'Tight' theme.. :/ I'll test without any custom theme and get back to you.

**Comment by mkellerman** [comment]
Yup.. looks like I works without my custom theme.. <f>

I'll create a new issue regarding all other elements from not using card class.

**Comment by adamdriscoll** [comment]
Cool. Sounds good

**Comment by adamdriscoll** [comment]
I'm also looking at the default value for this. That is broken
