### ISSUE TITLE
New-UDDashboard -NavBarLogo not working

### ISSUE THREAD

**Issue by Zuldan** [ironmansoftware/universal-dashboard#1253]
It looks like -NavBarLogo is broken again in New-UDDashboard. I downloaded and tried build 20191011.6 but still no luck.

    $Logo = New-UDImage -Path 'C:\Scripts\Dashboard\My Logo.png'

    $Theme = New-UDTheme -Name "Basic" -Definition @{
        UDNavBar = @{
            BackgroundColor = "grey"
            FontColor       = "white"
        }
        UDFooter = @{
             BackgroundColor = "grey"
            FontColor       = "white"
        }
    }

    $Dashboard = New-UDDashboard -Title 'My Dashboard' -NavBarLogo $Logo -Theme $Theme -Content {}

**Comment by adamdriscoll** [comment]
I just wrote an integration test to validate this is working. I don't have an issue adding a navbar logo. Please check out this test to see if this matches what you are seeing.

**Comment by adamdriscoll** [comment]
https://github.com/ironmansoftware/universal-dashboard/pull/1260/files
