### ISSUE TITLE
Modals appearing on other peoples screens in IE using 2.6.2

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#1258]
#### Describe the Issue
A clear and concise description of what the issue is.
Modals are appearing on other peoples screens when they have not selected a modal more details here:-
https://forums.universaldashboard.io/t/modals-appearing-on-other-peoples-screens/1465/3

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

#### Expected behavior
That other peoples modal windows would not appear on other peoples screens

#### Script Sample
Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)
Universal Dashboard 2.6.2 running in IIS using IE to view dashboard pages

**Comment by wsl2001** [comment]
same issue here as well using google chrome.
