### ISSUE TITLE
Add UDDatePicker

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#126]
Have a cmdlet for UDDatePicker:
https://material.io/guidelines/components/pickers.html#pickers-time-pickers

Would be useful for dashboards to be able to pick a date/time for some reports. Having a built in cmdlet would help greatly.

**Comment by adamdriscoll** [comment]
This was implemented in New-UDInput in version 1.7.

**Comment by adamdriscoll** [comment]
https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.UITest/Integration/Input.Tests.ps1#L36
