### ISSUE TITLE
Token Expiration not valid

### ISSUE THREAD

**Issue by LxLeChat** [ironmansoftware/universal-dashboard#1265]
#### Describe the Issue
When creating a token with ``Grant-UDJsonWebToken`` with a custom lifetime, to ``New-UDAuthenticationResult``, the token lifetime is always 25 minutes.

#### To Reproduce
in a ``New-UDAuthenticationMethod`` endpoint passing the following code should return a token with a lifetime of 10 minutes
```powershell
$date = (get-date).AddMinutes(10)
$token = Grant-UDJsonWebToken -Identity $Credential.UserName -Role $Role -Expiry $date
New-UDAuthenticationResult -Success -UserName $Credential.UserName -Role $role -Token $token
```
Pass the generated token to jwt.io and check the ``expiration time``  property of the toke

#### Expected Behavior
If i generate a token with a 10 minutes lifetime, the expiration date should be 10 minutes from ..now !
And maybe if i generate a token with ``Grant-UDJsonWebToken`` ,  ``New-UDAuthenticationResult`` should not accept ``username`` and ``role`` property ? since it's already  in the ``$token`` variable.

#### Script Sample
```powershell
$AuthMethod = New-UDAuthenticationMethod -Endpoint {
    param([PSCredential]$Credential)
    $date = (Get-Date).AddMinutes(10)
    $role = "role1","role2"
    $Token = Grant-UDJsonWebToken -Role $Role -Expiry $date -Identity $Credential.UserName
    New-UDAuthenticationResult -Success -UserName $Credential.UserName -Role $role -Token $Token
}

Start-UDRestApi -Port 10001 -Endpoint @(
) -AuthenticationMethod $AuthMethod
```

#### Version Information
- **Operating System**: Windows 2012 R2
- **PowerShell Version**:  5.1
- **Universal Dashboard Version**: 2.6.2
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

#### Additional context
The token request is made with postman, or with a client side website.

**Comment by adamdriscoll** [comment]
The bug here is that the time needs to be in UTC for it to work. I'll get this fixed internally but you can work around this by using [DateTime]::UtcNow.AddMinutes(10)

```
PS C:\Users\adamr> [Microsoft.IdentityModel.Logging.IdentityModelEventSource]::ShowPII = $true
PS C:\Users\adamr> Grant-UDJsonWebToken -Identity "UserName" -Expiry (Get-Date).AddMinutes(10)
Grant-UDJsonWebToken : IDX12401: Expires: '10/19/2019 13:00:07' must be after NotBefore: '10/19/2019 18:50:07'.
At line:1 char:1
+ Grant-UDJsonWebToken -Identity "UserName" -Expiry (Get-Date).AddMinut ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Grant-UDJsonWebToken], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,UniversalDashboard.Cmdlets.GrantJsonWebTokenCommand
PS C:\Users\adamr> Grant-UDJsonWebToken -Identity "UserName" -Expiry ([DateTIme]::UtcNow).AddMinutes(10)
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXNlck5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9oYXNoIjoiZDU5NjFmODEtZmIxZC00NDA2LThhYWMtZTQ4NDA0NmJiMmM2Iiwic3ViIjoiVW5pdmVyc2FsRGFzaGJvYXJkIiwibmJmIjoxNTcxNTEwOTE1LCJleHAiOjE1NzE1MTE1MTUsImlzcyI6InBvc2h1ZC5jb20iLCJhdWQiOiJVbml2ZXJzYWxEYXNoYm9hcmQifQ.HY6KSF2lSIV8jTnjZLDsKCT8bJf2WRCoWq1K9rpjurk
```
