### ISSUE TITLE
Idle Timeout Message

### ISSUE THREAD

**Issue by awickham10** [ironmansoftware/universal-dashboard#1270]
#### Is your Enhancement request related to a problem? Please describe
When users leave a dashboard open in the browser beyond the idle timeout (default 25 minutes), everything seems to stop working for them (spinning progress bars, etc.). This can be frustrating for the user because they don't know whether to wait or refresh the page.

#### Describe the solution you'd like
It would be nice to be able to popup a "Your Session Timed Out" page when the session times out, potentially with some verbiage that they should refresh the page.

#### Describe how this would improve your Universal Dashboard Quality of Life
Users would know when their session times out.

**Comment by awickham10** [comment]
As an additional question... if I increased the session timeout to something like 8 hours, what impact would that have?

**Comment by adamdriscoll** [comment]
The session cookie should be valid for 8 hours. It seems like there is a separate issue with SignalR that might not be tied to the session that needs to be resolved. The web socket becomes disconnected and then things like Set-UDElement, Get-UDElement, and Show-UDModal won't work.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/reload-page-on-tab-change/2546/5
