### ISSUE TITLE
UDDashboard -Scripts -Stylesheets behavior and index.html

### ISSUE THREAD

**Issue by fmichaleczek** [ironmansoftware/universal-dashboard#128]
Each dashboard has a requirement to directory ./site where file 'index.html' is.

If I include a custom javascript file or a css file, there is a difference between : 
- adding javascript/css to index.html
- adding javascript/css to UDDashboard argument

Because loading javascript/css before or after React has consequence, there is 2 solutions : 
- adding javascript/css hook 'Before/After' into New-UDDashboard 
- adding custom directory .site support for each UDDashboard

Maybe adding more informations about how to add a custom react js is maybe a better way.

**Comment by jvedie** [comment]
I'm getting the following error message in the browser console when adding a custom JS script file to the New-UDDashboard cmdlet:

` ReferenceError: file is not defined - fetch-service.jsx:22`
    `at t.value (ud-dashboard.jsx:148)`
    `at Array.map (<anonymous>)`
    `at t.<anonymous> (ud-dashboard.jsx:165)`

The dashboard is not loading and I only have an empty white screen page.

On the other side, adding custom CSS file is working well.

Any idea if this is a bug or am I not using correctly the feature ?

**Comment by jvedie** [comment]
Thanks @itfranck , I've used that too in the meantime.
Adam just published v1.6.2 that looks to have solved the issue, I'm going to test it.
