### ISSUE TITLE
2.6.0 to 2.7.0, Authorization Policies Not loading

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#1290]
#### Describe the Issue
https://forums.universaldashboard.io/t/new-udauthorizationpolicy-change/1526

Dashboard is not processing Authorization Policies after update to 2.7.0

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Does not apply policies

#### Expected behavior
Load policies correctly

#### Screenshots
![image](https://user-images.githubusercontent.com/23514631/67772797-15f17d00-fa31-11e9-89b2-7ac630ec1939.png)

#### Script Sample
https://hastebin.com/zolateheje.php

#### Version Information
- **Operating System**: Windows 10 and Server 2016
- **PowerShell Version**:  5.1.18362.145 (Win 10) and 5.1.14393.3053 (Server 16)
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: IIS

#### Additional context
09:33:27 [Fatal] Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor An error occurred starting the application

is the only entry from Enable-UDLogging -Level warning

My account should be pulling the ITPolicy AuthPolicy.

**Comment by adamdriscoll** [comment]
This has been resolved and verified. It will be in tonight's nightly build.
