### ISSUE TITLE
2.7.0 - Dashboards error when starting

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1296]
#### Describe the Issue
After updating to 2.7.0 Dashboards can no longer start. Even if I just do Start-UDDashboard as basic as I can.

There isn't a lot of log that happens, as it errors when starting up 

```
14:53:08 [Info] Quartz.Impl.StdSchedulerFactory Using object serializer: Quartz.Simpl.BinaryObjectSerializer, Quartz
14:53:08 [Info] Quartz.Core.SchedulerSignalerImpl Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
14:53:08 [Info] Quartz.Core.QuartzScheduler Quartz Scheduler v.3.0.6.0 created.
14:53:08 [Info] Quartz.Simpl.RAMJobStore RAMJobStore initialized.
14:53:08 [Info] Quartz.Core.QuartzScheduler Scheduler meta-data: Quartz Scheduler (v3.0.6.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 100 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

14:53:08 [Info] Quartz.Impl.StdSchedulerFactory Quartz scheduler 'QuartzScheduler' initialized
14:53:08 [Info] Quartz.Impl.StdSchedulerFactory Quartz scheduler version: 3.0.6.0
14:53:08 [Info] Quartz.Core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED started.
14:53:08 [Fatal] Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor An error occurred starting the application
```

#### Version Information
- **Operating System**: Windows 10 10.0.18362
- **PowerShell Version**: 5.1.18362.145
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment]
Can you provide some more information about the dashboard you are trying to start? I can start dashboards in 5.1 and Win10 without issue. I've tried both a pretty blank dashboard.ps1 and using the built-in dashboard.

**Comment by gerane** [comment]
```powershell
Start-UdDashboard -Content {
    New-UdDashboard -Title "Test" -Content {
        'Content'
    }
}
```

It errors with any dashboard, even a pretty much blank one.

**Comment by adamdriscoll** [comment]
Can you run a Get-Module after starting the dashboard? What else is loaded into this powershell instance?

**Comment by gerane** [comment]
![2019-10-30_16-01-15](https://user-images.githubusercontent.com/6662208/67898586-91852400-fb2e-11e9-9d10-7abe7b382bd7.png)

**Comment by gerane** [comment]
and from a powershell.exe with -noprofile
![2019-10-30_16-04-39](https://user-images.githubusercontent.com/6662208/67898814-05bfc780-fb2f-11e9-9d06-6c73f9af0073.png)

**Comment by gerane** [comment]
I wish try reinstalling the module and see if that does anything

**Comment by adamdriscoll** [comment]
I just encountered the error. The dashboard works though. 

```
15:06:11 [Debug] Quartz.Core.QuartzSchedulerThread Batch acquisition of 1 triggers
15:06:11 [Fatal] Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor An error occurred starting the application
15:06:11 [Debug] Quartz.Simpl.SimpleJobFactory Producing instance of Job 'DEFAULT.2d3b8d6e-1f60-4d53-801e-6755a73b5975', class=UniversalDashboard.Services.LicenseCheckJob

15:06:11 [Debug] Quartz.Core.QuartzSchedulerThread Batch acquisition of 0 triggers
15:06:11 [Debug] Quartz.Core.JobRunShell Calling Execute on job DEFAULT.2d3b8d6e-1f60-4d53-801e-6755a73b5975
15:06:11 [Debug] Quartz.Core.JobRunShell Trigger instruction : NoInstruction
Name        Port Running DashboardService
----        ---- ------- ----------------
Dashboard1 10000    True UniversalDashboard.Services.DashboardService
```

**Comment by gerane** [comment]
I think a lot of this was cleared up after reinstalling the module. I still get that error, but the other errors that were keeping it from working went away. I had some issues getting adfs working again, but finally seem to have found a combo that works

**Comment by adamdriscoll** [comment]
Fixed this error in tonight's build.

**Comment by wesleykirkland** [comment]
I just wanted to comment and say we experience the "Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor An error occurred starting the application" on 2.7.0 with an existing dashboard. It works fine locally but refuses to run on Azure App Service.
