### ISSUE TITLE
ADFS Authentication appears to be broken in 2.7

### ISSUE THREAD

**Issue by jdmuetzel** [ironmansoftware/universal-dashboard#1299]
I currently have a dashboard (version 2.6.2) running on IIS that uses
$Auth = New-UDAuthenticationMethod -MetadataAddress 'https://myfederationmetadatahere.xml" -wtrealm “https://mydashboardurlhere” for ADFS authentication.

This works fine in 2.6.2 but when I try doing this in 2.7 the page comes up blank and does not redirect to my ADFS signin page. If I change the AuthenticationMethod to use -Windows, my page loads fine so it appears there is something broken with 2.7 and ADFS authentication.

I did roll back to 2.6.2 for now and my page is redirecting to ADFS properly again.

**Comment by jdmuetzel** [comment]
Here is what gets logged when I try to access the page.  Like I mentioned, all I get is a blank page whether I have already authenticated with ADFS or not.

09:31:26 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://hdtoolkit.mydomain.com/  
09:31:26 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 10.4708ms 200 text/html; charset=utf-8
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://hdtoolkit.mydomain.com/api/internal/dashboard/theme  
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Route matched with {action = "Theme", controller = "Dashboard"}. Executing action UniversalDashboard.Controllers.DashboardController.Theme (UniversalDashboard)
09:31:27 [Debug] PowerShellExecutionService ExecutionService constructor
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executing action method UniversalDashboard.Controllers.DashboardController.Theme (UniversalDashboard) - Validation state: Valid
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action method UniversalDashboard.Controllers.DashboardController.Theme (UniversalDashboard), returned result Microsoft.AspNetCore.Mvc.ContentResult in 0.3135ms.
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Infrastructure.ContentResultExecutor Executing ContentResult with HTTP Response ContentType of text/css
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action UniversalDashboard.Controllers.DashboardController.Theme (UniversalDashboard) in 2.6647ms
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 6.565ms 200 text/css
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://hdtoolkit.mydomain.com/api/internal/javascript/plugin  
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Route matched with {action = "Plugin", controller = "JavaScript"}. Executing action PowerShellProTools.UniversalDashboard.Controllers.JavaScriptController.Plugin (UniversalDashboard)
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executing action method PowerShellProTools.UniversalDashboard.Controllers.JavaScriptController.Plugin (UniversalDashboard) - Validation state: Valid
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action method PowerShellProTools.UniversalDashboard.Controllers.JavaScriptController.Plugin (UniversalDashboard), returned result Microsoft.AspNetCore.Mvc.ContentResult in 16.2607ms.
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Infrastructure.ContentResultExecutor Executing ContentResult with HTTP Response ContentType of text/javascript
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action PowerShellProTools.UniversalDashboard.Controllers.JavaScriptController.Plugin (UniversalDashboard) in 43.0249ms
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 44.4349ms 200 text/javascript
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://hdtoolkit.mydomain.com/api/internal/dashboard  
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Route matched with {action = "Index", controller = "Dashboard"}. Executing action UniversalDashboard.Controllers.DashboardController.Index (UniversalDashboard)
09:31:27 [Info] Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler WsFederation was not authenticated. Failure message: Not authenticated
09:31:27 [Debug] AuthorizationHandler Configuring authorization for session:06405456-6e90-400b-9605-ce6c14be8d17
09:31:27 [Debug] PowerShellExecutionService Parameters--------------
09:31:27 [Debug] PowerShellExecutionService User = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService Context variables--------------
09:31:27 [Debug] PowerShellExecutionService User = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService DashboardHub = Microsoft.AspNetCore.SignalR.Internal.HubContext`1[UniversalDashboard.DashboardHub]
09:31:27 [Debug] PowerShellExecutionService Cache = Microsoft.Extensions.Caching.Memory.MemoryCache
09:31:27 [Debug] PowerShellExecutionService StateRequestService = UniversalDashboard.Services.StateRequestService
09:31:27 [Debug] PowerShellExecutionService ConnectionId = 
09:31:27 [Debug] PowerShellExecutionService SessionId = 06405456-6e90-400b-9605-ce6c14be8d17
09:31:27 [Debug] PowerShellExecutionService ArgumentList = 
09:31:27 [Debug] PowerShellExecutionService UDPage = 
09:31:27 [Debug] PowerShellExecutionService ClaimsPrinciple = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://hdtoolkit.mydomain.com/favicon.ico  
09:31:27 [Info] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware Sending file. Request path: '/favicon.ico'. Physical path: 'D:\poshud\HDToolkit\client\favicon.ico'
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 7.2448ms 200 image/x-icon
09:31:27 [Debug] PowerShellExecutionService Context variables--------------
09:31:27 [Debug] PowerShellExecutionService User = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService DashboardHub = Microsoft.AspNetCore.SignalR.Internal.HubContext`1[UniversalDashboard.DashboardHub]
09:31:27 [Debug] PowerShellExecutionService Cache = Microsoft.Extensions.Caching.Memory.MemoryCache
09:31:27 [Debug] PowerShellExecutionService StateRequestService = UniversalDashboard.Services.StateRequestService
09:31:27 [Debug] PowerShellExecutionService ConnectionId = 
09:31:27 [Debug] PowerShellExecutionService SessionId = 06405456-6e90-400b-9605-ce6c14be8d17
09:31:27 [Debug] PowerShellExecutionService ArgumentList = 
09:31:27 [Debug] PowerShellExecutionService UDPage = 
09:31:27 [Debug] PowerShellExecutionService ClaimsPrinciple = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService Context variables--------------
09:31:27 [Debug] PowerShellExecutionService User = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService DashboardHub = Microsoft.AspNetCore.SignalR.Internal.HubContext`1[UniversalDashboard.DashboardHub]
09:31:27 [Debug] PowerShellExecutionService Cache = Microsoft.Extensions.Caching.Memory.MemoryCache
09:31:27 [Debug] PowerShellExecutionService StateRequestService = UniversalDashboard.Services.StateRequestService
09:31:27 [Debug] PowerShellExecutionService ConnectionId = 
09:31:27 [Debug] PowerShellExecutionService SessionId = 06405456-6e90-400b-9605-ce6c14be8d17
09:31:27 [Debug] PowerShellExecutionService ArgumentList = 
09:31:27 [Debug] PowerShellExecutionService UDPage = 
09:31:27 [Debug] PowerShellExecutionService ClaimsPrinciple = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] PowerShellExecutionService ClaimsPrincipal = System.Security.Claims.ClaimsPrincipal
09:31:27 [Debug] AuthorizationHandler Valid authorization policies for session: AllITUsers
09:31:27 [Debug] AuthorizationHandler No valid roles for session.
09:31:27 [Info] Microsoft.AspNetCore.Authorization.DefaultAuthorizationService Authorization failed.
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
09:31:27 [Info] Microsoft.AspNetCore.Mvc.ChallengeResult Executing ChallengeResult with authentication schemes (Cookies, WsFederation).
09:31:27 [Info] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler AuthenticationScheme: Cookies was challenged.
09:31:27 [Info] Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler AuthenticationScheme: WsFederation was challenged.
09:31:27 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action UniversalDashboard.Controllers.DashboardController.Index (UniversalDashboard) in 42.7481ms
09:31:27 [Info] Microsoft.AspNetCore.Session.DistributedSession Session started; Key:abda043f-18d5-7251-efb8-937028ea761b, Id:4daffa30-3316-d0af-0f13-2c3b3c35026d
09:31:27 [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HLR91QRPM564", Request id "0HLR91QRPM564:00000003": An unhandled exception was thrown by the application.
09:31:27 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 47.0363ms 200

**Comment by adamdriscoll** [comment]
Resolved in tonight's nightly (2.8.0)
