### ISSUE TITLE
Submit button gets erased by grid when clicking submit

### ISSUE THREAD

**Issue by Stephanevg** [ironmansoftware/universal-dashboard#130]
This follows this ticket --> https://github.com/ironmansoftware/universal-dashboard/issues/110

![image](https://user-images.githubusercontent.com/6302961/39463331-b6121254-4d17-11e8-8f47-2c008e2ce2a8.png)

Once I click the submit button, it actually ends up displaying the information, 'but' the submit button disapears.
It turns the original search text field, into the filter text field from the grid, and I am unable to query data from another server.

![image](https://user-images.githubusercontent.com/6302961/39463320-abe1c3ec-4d17-11e8-94a6-689eb6e26cbc.png)

Did I miss configured something?

**Comment by adamdriscoll** [comment]
@Stephanevg This is actually by design of New-UDInput. In 1.6.0, you'll be able to do this with UDElements but I'll mark this as an enhancement to New-UDInput. It would be nice to retain the form after clicking submit. The current design just replaces the form with the output content.

**Comment by Stephanevg** [comment]
Yes, I would really like to be able to have the possibility set, let's say below the form, the result of my query.

**Comment by adamdriscoll** [comment]
This can now be accomplished with Add-UDElement.

```
New-UDInput -Endpoint {
   Add-UDElement -ParentId 'target' -Content { 
<#
Controls
#>
}
}
New-UDElement -Tag 'div' -Id target
```
