### ISSUE TITLE
Value of New-UDSelect if no choice? 

### ISSUE THREAD

**Issue by b-sarrazin** [ironmansoftware/universal-dashboard#1302]
#### Describe the Issue
When no choice is made on a drop-down list where a value is preselected it is not possible to find the value with Get-UDElement.

#### Script Sample
```
$Cache:Companies = @("A", "B", "C", "D", "E", "F", "G")

New-UDPage -Url "test" -Title "Test" -Endpoint {
	
	$Company = "D"
	New-UDSelect -Id "select" -Label "Company" -Option {
		$Cache:Companies | ForEach-Object {
			if ($_ -eq $Company)
			{
				New-UDSelectOption -Name $_ -Value $_ -Selected
			}
			else
			{
				New-UDSelectOption -Name $_ -Value $_
			}
		}
	} -OnChange {
		Show-UDToast -Title "onchange" -Message $EventData
	}
	
	New-UDButton -Text "test" -OnClick {
		$Test = (Get-UDElement -Id "select").Attributes['value']
		Show-UDToast -Title "button" -Message $Test
		
	}
}
```

#### To Reproduce
Launch script and push button : no value is returned 

#### Expected behavior
Return a value even if New-UDSelect isn't modified by the user

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: Powershell

**Comment by augiaugi** [comment]
can also reproduce this issue in my project.

**Comment by adamdriscoll** [comment]
This has been resolved in tonight's v3 build.
