### ISSUE TITLE
You should add Sponsors button to this repo

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#1304]
#### Is your Enhancement request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] and would receive great value from [...]

#### Describe how this would improve your Universal Dashboard Quality of Life
Please help us understand how this would improve your usage of universal dashboard and/or what new capabilities this enhancement would provide you with.

#### Describe alternatives you've considered
A clear and concise description of any alternative solutions or Enhancements you've considered.

#### Additional context
Add any other context or screenshots about the Enhancement request here.

**Comment by adamdriscoll** [comment]
I added the yml necessary. GitHub will respond within two weeks as to whether I have been accepted.
