### ISSUE TITLE
More documentation on customising the footer

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#1306]
#### Is your Enhancement request related to a problem? 
Thread raised on forum on how to customise the footer, as no real documentation on this on
https://docs.universaldashboard.io/

#### Describe the solution you'd like
  Add a brief FOOTER section to the docs site, saying how to customise it, and how to hide it.

#### Describe how this would improve your Universal Dashboard Quality of Life
 Seems this would improve life for some users
https://forums.universaldashboard.io/t/license-not-removing-created-with-powershell-universal-dashboard/1582/5

#### Describe alternatives you've considered
None

#### Additional context
 Thank you

**Comment by adamdriscoll** [comment]
Done: https://docs.universaldashboard.io/components/footer
