### ISSUE TITLE
Windows Authentication broken in 2.7.0

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/universal-dashboard#1309]
Hi

Our Windows Authentication is broken since 2.7.0
We only get the non-authorized error:
```
You are not authorized to view any pages. Please contact your administrator.
```

Host Dashboard in IIS
Configure WindowsAuth / LoginPage etc.

Following lines are present in UD-Log:
```
[Warn] ServerStartup Port and HTTPS port are the same. HTTPS Redirection will not work. Select two different ports.
[Warn] ServerStartup Port and HTTPS port are the same. HTTPS Redirection will not work. Select two different ports.
[Fatal] Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor An error occurred starting the application
```

Altough the Dashboard starts otherwise normally (loads CSS / Custom Endpoints / Navbar and stuff)

Thanks for looking into it

**Comment by gitbute** [comment]
It probably has to do with this:
https://github.com/ironmansoftware/universal-dashboard/issues/1194

We will roll back to 2.6.2 for the meantime

**Comment by adamdriscoll** [comment]
Can you please try the latest nightly release? I'm seeing Windows Auth work there. If you could also provide some info on how you've setup your claims policies, that would be great.

**Comment by adamdriscoll** [comment]
This is my current setup for Windows auth. 

```
$AuthenticationMethod = New-UDAuthenticationMethod -Windows

$AuthenticationPolicy = New-UDAuthorizationPolicy -Name 'Policy' -Endpoint {
    param($ClaimsPrincipal)

    $ClaimsPrincipal.Identity.Name -eq 'DESKTOP-RB1QJB4\iis'
}

$LoginPage = New-UDLoginPage -AuthenticationMethod $AuthenticationMethod -AuthorizationPolicy $AuthenticationPolicy

$Cache:MyValue = "True"

$Page1 = New-UDPage -Name "CanSee" -Content {}
$Page2 = New-UDPage -Name "CantSee" -Content {} -AuthorizationPolicy "Policy"

$Dashboard = New-UDDashboard -Title 'Test' -Pages @($Page1, $Page2) -LoginPage $LoginPage 
Start-UDDashboard  -Port 10000 -Force  -Dashboard $Dashboard -AllowHttpForLogin -Wait -AdminMode
```

![image](https://user-images.githubusercontent.com/1256531/69282435-924a2c80-0ba7-11ea-8354-890862ae7a8a.png)

![image](https://user-images.githubusercontent.com/1256531/69282442-95ddb380-0ba7-11ea-8372-af1772ef7c36.png)

**Comment by gitbute** [comment]
Hi adam

Its is fixed for me in the current nightly! Thanks a lot!
