### ISSUE TITLE
Can I change your pipeline and run my stuff is azure?

### ISSUE THREAD

**Issue by L0wry** [ironmansoftware/universal-dashboard#1310]
Hey dude, 
So I've just been searching for an azure reporting tool. Came accross this repo.

I've noticed that you have pipeline as code for an open source repo.
Sounds good on paper, but I'm fairly sure there would not be much stopping me from forking, changing your pipline as code to spin me up some custom compute images to mine bitcoin or something similar, creating a PR and watching my bad boys run!

Could be wrong, but thought I'd let you have a think about it!

**Comment by adamdriscoll** [comment]
Having a pipeline as code is a very common practice in open source repos. 

The PowerShell team does the same thing on their repo: https://github.com/PowerShell/PowerShell/blob/master/.vsts-ci/windows.yml

You can certainly put in PRs to change stuff but you won't be able to output secrets. You'd have to enter your own Azure creds to spin up custom compute images. I have heard of people trying to put in PRs to mine bitcoin but you'd have to put in a TON of PRs to make that worth it. 

That said, Azure DevOps builds are capped at 1 hour so it wouldn't be all the great and I'm sure GitHub would rate limit you before you could make any money. ;)
