### ISSUE TITLE
Adjustable icon size for New-UDFab/New-UDFabButton

### ISSUE THREAD

**Issue by cpurules** [ironmansoftware/universal-dashboard#1324]
#### Is your Enhancement request related to a problem? Please describe
Currently there is no way to change the size of the icon within the New-UDFab / New-UDFabButton cmdlets.  If you use a large button, the icon remains the same small size and does not take up nearly as much of the button as it could, making it less pleasant graphically

#### Describe the solution you'd like
Either map the icon size to the button size so that it fills up the size of the button, or add an `-IconSize` parameter to the New-UDFab/New-UDFabButton cmdlets to allow you to choose how large the icon should be.

#### Describe how this would improve your Universal Dashboard Quality of Life
This is entirely graphical and does not affect any functionality but it would make it look nicer for myself and my team who will be using the dashboard I'm developing.

#### Describe alternatives you've considered
I've tried using other buttons but none of them quite look as nice as the FAB.

#### Additional context
Sample code:
```
New-UDFab -ButtonColor 'DarkGreen' -Icon plus_circle -Size large -Content {
        New-UDFabButton -Icon database -Size Large -ButtonColor Gray -IconColor White -OnClick {
            ...
        }
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/52503242/68872248-bb604e00-06cb-11ea-8a5b-fc2a030e3adc.png)

It would be nice to be able to get the icon size closer to this (approx. double the existing size):

![image](https://user-images.githubusercontent.com/52503242/68872455-109c5f80-06cc-11ea-891f-68a9b6fe7076.png)

**Comment by adamdriscoll** [comment]
FABs now support the ability to customize the icon size in v3. You'll be able to adjust both the button size as well as the icon size. https://universaldashboard-dev.azurewebsites.net/floating-action-button
