### ISSUE TITLE
Sync-UDElement not working on UDTable

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1332]
#### Describe the Issue
Sync-UDElement is not updating a UDTable.

#### To Reproduce
see script

#### Expected behavior
Sync-UDElement is normally updating UDTable as all other elemts (grids, ...).

#### Screenshots
![image](https://user-images.githubusercontent.com/23495782/69547040-2562d800-0f95-11ea-977d-ab427729d419.png)

after click update button (change data)

![image](https://user-images.githubusercontent.com/23495782/69547078-3c092f00-0f95-11ea-8404-16660986aa19.png)

#### Script Sample
```
 $Session:Data = [PSCustomObject]@{
        Name = "test"
        Value = 1
    }

    New-UDTable -Title 'Table' -id 'table' -Headers @("Name", "Value") -Endpoint {
        $Session:Data | Out-UDTableData -Property @("Name", "Value")
    } 

    New-UdGrid -Title 'Grid' -Id 'grid' -Headers @("Name", "Value") -Properties @("Name", "Value") -Endpoint {
        $Session:Data | Out-UdGridData
    }

    New-UDButton -Text "Update" -OnClick (New-UDEndpoint -Endpoint {
        $Session:Data = [PSCustomObject]@{
            Name = "test"
            Value = 2
        }

        Sync-UDElement -Id 'table'
        Sync-UDElement -Id 'grid'
    })
```

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1.17763.771
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: Powershell

**Comment by H4nYolo** [comment]
Hey, if you add **-AutoRefresh** to your New-UDTable, it works.

```
New-UDTable -Title 'Table' -id 'table' -Headers @("Name", "Value") -Endpoint {
        $Session:Data | Out-UDTableData -Property @("Name", "Value")
        
    } -AutoRefresh
```
I don't know, if it's intended to be like this, but that can only be answered by Adam. And, syncing the  table is a lot slower than syncing the grid. Probably because of the AutoRefresh interval.

Cheers

**Comment by augiaugi** [comment]
Thanks for mentioning this way ... I am awaiting adams answer to this issue as I think in some situations it is required to have an UDTable update only on request via Sync-UDElement.

**Comment by adamdriscoll** [comment]
This should work with Sync-UDElement. Let's keep this one open.

**Comment by augiaugi** [comment]
@adamdriscoll totally agree hope to see an bugfix for this

**Comment by augiaugi** [comment]
referencing to an existing forum thread: https://forums.universaldashboard.io/t/unable-to-sync-udtable/796/5

**Comment by BoSen29** [comment]
Seems like the UD Table endpoint is suffixed with "-tbody", hence the sync won't work with just the regular.

Using: 
Sync-UDElement -Id 'table-tbody'

Works like a charm.

Ref: 
https://github.com/ironmansoftware/universal-dashboard/blob/76681d0c96cf4ca016b723d11f49813a489b58e4/src/UniversalDashboard.Materialize/Scripts/table.ps1#L63

Either make the table not use New-UDElement, or move the relevant ID to the endpoint of the tbody? @adamdriscoll

**Comment by augiaugi** [comment]
test Script for the workaround using the ID suffix "-tbody" - confirm that its working

```
$Cache:UDTable = [PSCustomObject]@{
        Name = "Augustin Ziegler"
        Surname = "Ziegler"
        Firstname = "Augustin"
        Age = 21
    }

    New-UDCard -Content {
        New-UDTable -Title 'Test' -Id 'table' -Headers @("Name", "Value") -Endpoint {
            ($Cache:UDTable).PSObject.Properties | %{Out-UDTableData -Data $_ -Property @("Name", "Value")}
        }
    }  

    New-UDButton -Text "Change" -OnClick {
        $Cache:UDTable.Age = Get-Random -Minimum 10 -Maximum 100

        #workaround - Seems like the UD Table endpoint is suffixed with "-tbody", hence the sync won't work with just the regular.
        Sync-UDElement -Id 'table-tbody'
    }
```

**Comment by adamdriscoll** [comment]
@BoSen29 I think we should move away from using New-UDElement for built-in controls like this. It has a performance penalty that we can easily resolve by moving this code to JSX.

**Comment by BoSen29** [comment]
@adamdriscoll Fair point.
I can probably draft something up after work. The missus is working evening shifts, which means pizza and UD or CSGO for me :-)
If you don't see a PR later tonight, asume that i'm hiding in shame or anger.

**Comment by augiaugi** [comment]
@BoSen29 
seams that CSGO was your evening plan ;)
any update or PR on this one?

**Comment by BoSen29** [comment]
Hi @augiaugi 
Sadly, converting the UD-Table to non-UDElement dependant would cause a breaking change with "out-udtabledata". 
I'm awaiting feedback from @adamdriscoll for a plan of action. I've got a working build, but it would... limit the usability of Out-UDTableData and would require some rework of certain implementations of it.

**Comment by augiaugi** [comment]
Thanks for your effort on this :)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/help-plan-the-future-of-universal-dashboard/2176/2
