### ISSUE TITLE
Admin diagnostics site endpoint codeblock overflow css

### ISSUE THREAD

**Issue by BoSen29** [ironmansoftware/universal-dashboard#1334]
#### Is your Enhancement request related to a problem? Please describe
Add overflow:scroll to the CSS of the collapsible body when viewing endpoints scriptblocks.

#### Describe the solution you'd like
Add overflow:scroll would be best, also remove unnecessary whitespace. 

#### Describe how this would improve your Universal Dashboard Quality of Life
Easily read the relevant scriptblocks

#### Describe alternatives you've considered
Doing the CSS myself

#### Additional context
Image
![image](https://user-images.githubusercontent.com/54361737/69627734-7cc37f80-104b-11ea-8f9e-a1c28ae654bb.png)

**Comment by adamdriscoll** [comment]
Implemented in tonight's build .
