### ISSUE TITLE
New-UDGrid : provide ability to custom the text

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#134]
I'd like the ability to display in french:
   - Filter input box

**Comment by adamdriscoll** [comment]
This story has a bounty: https://www.bountysource.com/issues/57810286-new-udgrid-provide-ability-to-custom-the-text

**Comment by rishiloyola** [comment]
I saw your bounty on bountysource.com
I would like to work on this issue. Can you give me more details? 

Like which filter input box you are talking about?

**Comment by apetitjean** [comment]
To clarify I'd like the ability to customize the text in the filter box which is by default "Filter".

**Comment by adamdriscoll** [comment]
FilterText is already on the component in PowerShell. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Scripts/grid.ps1#L30



The JSX file needs to be updated here to  use the filter text. The filterText will come in via the `this.props.filterText` prop. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Components/ud-grid.jsx#L278

**Comment by oitptobbe** [comment]
@adamdriscoll I think what @apetitjean means is that he would like to replace the placeholder that says "Filter" with something in perhaps Japanese, or have it say "I can haz filter here?" but without filtering the result. Setting filterText will prefilter the result as far as I can tell...

As far as I can see in the griddle-react component there is no way to change this natively. Without building a custom component/plugin.

http://griddlegriddle.github.io/Griddle/docs/customization/

However this might be something that should be added? Might be nice to be able to support drop down menus and select filter from also.

**Comment by apetitjean** [comment]
> @apetitjean <https://github.com/apetitjean> means is that he would like
to replace the placeholder that says "Filter" with something in perhaps
Japanese, or have it say "I can haz filter here?"

Yes, this is exactly what I meant.

**Comment by oitptobbe** [comment]
I've found the issue now so I will submit a PR in a short while :)

**Comment by adamdriscoll** [comment]
@oitptobbe If you click "Claim Bounty" on the Bounty Source link, I can send some funds your way.
