### ISSUE TITLE
UDChart - candle stick chart type

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1340]
#### Describe the solution you'd like
As I am working on an project where UD meets financial data, I would love to see a new UDChart type for candle sticks - https://github.com/chartjs/chartjs-chart-financial

#### Describe how this would improve your Universal Dashboard Quality of Life
This feature can open a whole new project context to users.

**Comment by leeberg** [comment]
+1 - Love this chart style

**Comment by augiaugi** [comment]
New custom component: https://forums.universaldashboard.io/t/financial-chart-beta/1967

**Comment by augiaugi** [comment]
https://github.com/darrenjrobinson/UniversalDashboard.UDFinancialChart
