### ISSUE TITLE
nested Navigation format

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1341]
#### Describe the Issue
When using nested Navigation structures the format (size and indentation) is completely miss leading.

https://docs.universaldashboard.io/components/navigation#creating-nested-menu-structures

#### To Reproduce
see script

#### Expected behavior

* "Page 1" and "Page 2" should be have the same format than "Section"
* after expanding "Sub-Page 1" and "Sub-Page 2" should not have the same format as "Page 2" (this looks like the "Page 2" is in "Section")

#### Screenshots
![image](https://user-images.githubusercontent.com/23495782/69918999-906e4c00-1478-11ea-8d2c-81309ae9f41b.png)

![image](https://user-images.githubusercontent.com/23495782/69919002-9ebc6800-1478-11ea-994c-80f60cbb45bd.png)

#### Script Sample
The script was mainly written by the official doc (https://docs.universaldashboard.io/components/navigation#creating-nested-menu-structures)

```
$Page1 = New-UDPage -Name "Page 1" -Content {New-UDCard -Id 'page-1'}
$Page2 = New-UDPage -Name "Page 2" -Content {New-UDCard -Id 'page-2'}

$Navigation = New-UDSideNav -Content {
    New-UDSideNavItem -Text "Page 1" -PageName "Page 1" -Icon User

    New-UDSideNavItem -Text "Section" -Children { 
        New-UDSideNavItem -Text "Sub-Page 1" -PageName "Page 1" -Icon User
        New-UDSideNavItem -Text "Sub-Page 2" -PageName "Page 2" -Icon User
    }

    New-UDSideNavItem -Text "Page 2" -PageName "Page 2" -Icon User
}

$Dashboard = New-UDDashboard -Title "Navigation" -Pages @($Page1, $Page2) -Navigation $Navigation

Start-UDDashboard -Dashboard $Dashboard -Port 10005
```

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1.17763.771
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: Powershell

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/help-plan-the-future-of-universal-dashboard/2176/2

**Comment by adamdriscoll** [comment]
This has been resolved in the latest version of v3. You can configure this using the AppBar and Drawer. See the AppBar page on the docs for more info.

**Comment by augiaugi** [comment]
@adamdriscoll 

But as far as I can see this is not configured by default, whats the right way to configure this in V3?

![image](https://user-images.githubusercontent.com/23495782/77831226-36cc1480-712e-11ea-8168-43331134cbb6.png)

```
$Drawer = New-UDDrawer -Children {
        New-UDList -Children {
            New-UDListItem -Label "Home" -OnClick { Invoke-UDRedirect -Url "/home" }
            New-UDListItem -Label "Identity" -Children {
                New-UDListItem -Label "User" -OnClick { Invoke-UDRedirect -Url "/identity/user" }
                New-UDListItem -Label "Group" -OnClick { Invoke-UDRedirect -Url "/identity/group" }
            }
            New-UDListItem -Label "Test" -Children {
                New-UDListItem -Label "Temp" -OnClick { Invoke-UDRedirect -Url "/test/temp" }
            }
        }
    }
    
    New-UDAppbar -Children {
        New-UDElement -Tag 'div' -Content {$title}
    } -Drawer $Drawer
}
```
