### ISSUE TITLE
Grid Layout Not Working

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-dashboard#1353]
#### Describe the Issue
I'm not able to get the `-Layout` parameter of `New-UDGridLayout` working. The elements in the grid are instead arranged at the default position and overlapping.

#### To Reproduce
1. Create new grid layout and include line charts in the grid
2. Launch the dashboard in admin mode
3. Drag the elements into desired positions
4. Save the grid layout to the clipboard and add it to the script
5. Stop and restart the dashboard
6. Visit in new browser session

#### Expected behavior
The grid layout exported from admin mode should be respected, but appears to be ignored.

#### Script Sample
```powershell
New-UDGridLayout -Id MyCharts -Content {
    New-UDChart -Title Chart1 -Id Chart1 -Type Line -ArgumentList @($Dataset1SB) -Endpoint {
        &$ArgumentList[0] | Out-UDChartData -LabelProperty $LabelProperty -Dataset @(
            New-UDChartDataset @Splat_Data -DataProperty $DataProperty -Label $DataProperty
        )
    }

    New-UDChart -Title Chart2 -Id Chart2 -Type Line -ArgumentList @($Dataset2SB) -Endpoint {
        &$ArgumentList[0] | Out-UDChartData -LabelProperty $LabelProperty -Dataset @(
            New-UDChartDataset @Splat_Data -DataProperty $DataProperty -Label $DataProperty
        )
    }

    New-UDChart -Title Chart3 -Id Chart3 -Type Line -ArgumentList @($Dataset3SB) -Endpoint {
        &$ArgumentList[0] | Out-UDChartData -LabelProperty $LabelProperty -Dataset @(
            New-UDChartDataset @Splat_Data -DataProperty $DataProperty -Label $DataProperty
        )
    }
} -Layout '{"lg":[{"w":4,"h":9,"x":0,"y":0,"i":"grid-element-Chart1","moved":false,"static":true},{"w":4,"h":9,"x":4,"y":0,"i":"grid-element-Chart2","moved":false,"static":true},{"w":4,"h":10,"x":8,"y":0,"i":"grid-element-Chart3","moved":false,"static":true}]}'

```

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: Windows PowerShell 5.1
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: PowerShell

**Comment by paulharman** [comment]
Hi @mattmcnabb, it seemed to work fine for me - I took your code and ran it with adminmode - moved the charts around and copied the new layout code.  Updated your script with the new layout and removed adminmode.

`-Layout '{"lg":[{"w":3,"h":15,"x":6,"y":0,"i":"grid-element-Chart1","moved":false,"static":true},{"w":4,"h":21,"x":2,"y":0,"i":"grid-element-Chart2","moved":false,"static":true},{"w":3,"h":17,"x":2,"y":21,"i":"grid-element-Chart3","moved":false,"static":true}]}'`

![image](https://user-images.githubusercontent.com/3407038/70862419-2358bd00-1f34-11ea-9a03-15d8b9dfcbf7.png)

**Comment by paulharman** [comment]
Ok an update - it seems that keeping adminmode enabled makes it ignore the layout.  Could you try removing adminmode and see if that works for you?

**Comment by mattmcnabb** [comment]
I'll try that tonight and see if that's the case. I think that I did have admin mode enabled.

**Comment by adamdriscoll** [comment]
Please reopen if it's still an issue.
