### ISSUE TITLE
Could not load type ‘System.IdentityModel.Tokens.JwtSecurityToken’

### ISSUE THREAD

**Issue by Ashley-V** [ironmansoftware/universal-dashboard#1356]
#### Describe the Issue
When connecting to MSOnline using "Connect-MsolService" inside a endpoint (IIS Hosted Dashboard) an error is returned:

Could not load type ‘System.IdentityModel.Tokens.JwtSecurityToken’ from assembly ‘System.IdentityModel.Tokens.Jwt, Version=5.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35’

Suggestion from UD Forum that the 365 Module and UD both use the JWT assembly but different versions.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start IIS Hosted Dashboard
2. Use 'Connect-MsolService' with credentials, inside an endpoint
3. Toast is displayed with message

#### Expected behavior
Successful connection to MSOnline established.

#### Script Sample
```
New-UDInputField -Type textbox -Name "UPN" -Placeholder 'Email Address'
    } -Endpoint {

        param($UPN)
        
        $Creds = Import-Clixml -Path 'E:\365Dashboard\PSOffice365Dashboard.Cred'

        Connect-MsolService -Credential $Cred

        $UserDetails = Get-MsolUser -UserPrincipalName $UPN
        
}
```

#### Version Information
- **Operating System**: Windows Server 2016
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: IIS

#### Additional context
[UD Forum post](https://forums.universaldashboard.io/t/could-not-load-type-when-using-connect-msolservice-in-an-endpoint/1750/2)

**Comment by dkkazak** [comment]
I am having the same issue.  Running 1.1.183.57 of the MSOnline cmdlets.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/could-not-load-type-when-using-connect-msolservice-in-an-endpoint/1750/8

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/endpoint-working-locally-but-not-on-iis/2018/8

**Comment by adamdriscoll** [comment]
This issue has been resolved in PowerShell Universal. UD dashboards no longer run directly in the same process as the ASP.NET web server. They now run in an isolated PowerShell prompt that will no longer load this DLL.
