### ISSUE TITLE
CustomAssemblyLoadContext Native file path does not exist

### ISSUE THREAD

**Issue by paulharman** [ironmansoftware/universal-dashboard#1375]
#### Describe the Issue
Warning received in console

[Warn] CustomAssemblyLoadContext Native file path does not exist. Universal Dashboard may not work. C:\Users\harmanp\Documents\WindowsPowerShell\Modules\UniversalDashboard\2.8.0\net472\runtimes\win-x64\native

#### Version Information
- **Operating System**: Win 10
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8.0
- **UD Hosting Method**:  Powershell

#### Additional context
The runtimes folder is no longer needed as UD now used .NET Sockets instead of libuv. Libuv was a native library that required that a version was compiled for each operating system. .NET Sockets are completely .NET based so this isn’t required.

**Comment by adamdriscoll** [comment]
@paulharman - Just merged a fix for this 👍
