### ISSUE TITLE
UDStudio - You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by paulharman** [ironmansoftware/universal-dashboard#1376]
#### Describe the Issue
Vscode.UDStudio is giving an error “You cannot call a method on a null-valued expression.” and is not showing all of the endpoints or scheduled endpoints correctly even though I’d given all components with endpoints an ID

![image](https://user-images.githubusercontent.com/3407038/70808246-2bd7b900-1db7-11ea-9d48-7d3b891b6dad.png)

#### Expected behavior
No error and endpoints/scheduled endpoints to be displayed correctly

#### Screenshots

![image](https://user-images.githubusercontent.com/3407038/70808317-4f9aff00-1db7-11ea-837c-e3e055649635.png)

#### Script Sample
```
$Schedule5 = New-UDEndpointSchedule -Every 5 -Minute
$Schedule2 = New-UDEndpointSchedule -Every 2 -Minute
$endpoint1 = New-UDEndpoint -Schedule $Schedule5 -Id 'endpoint1' -Endpoint {
    $Cache:oldesttickets = get-oldesttickets
    $Cache:summarytable = get-summarytable
    $Cache:totaltickets = get-totaltickets
    $Cache:totalticketsbystatus = get-totalticketsbystatus
    $Cache:responsesla = get-responsesla
    $Cache:resolutionsla = get-resolutionsla
    $Cache:responsesoonfail = get-responsesoonfail
    $Cache:resolutionsoonfail = get-resolutionsoonfail
}
$endpoint2 = New-UDEndpoint -Schedule $Schedule2 -Id 'endpoint2' -Endpoint {
    Sync-UDElement -id 'responsesla' -Broadcast
    Sync-UDElement -id 'resolutionsla' -Broadcast
    Sync-UDElement -id 'Total' -Broadcast
    Sync-UDElement -id 'Totalheading' -Broadcast
}
$endpoint = $endpoint1, $endpoint2


Start-UDDashboard -Port $ConfigurationFile.dashboard.port -Dashboard $MyDashboard -Name $ConfigurationFile.dashboard.title -Force -Endpoint  $endpoint  -AutoReload
```

#### Version Information
- **Operating System**: Win 10 x64
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8/0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)  Powershell

**Comment by adamdriscoll** [comment]
Fixed in 0.1.6. Should be release in about 10 minutes.
