### ISSUE TITLE
New-UDSelect  -  Initial value

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#138]
When page is created, UDSelect shows one of the value (the first one in the list of UDSelectOptions), but there is no way to grab that value to initialize the rest of the page. The user has to change the selection to force an OnChange event, and update whatever $Session:State = $EventData code, to give access to the state.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/help-plan-the-future-of-universal-dashboard/2176/2

**Comment by adamdriscoll** [comment]
Resolved in tonight's v3 build.
