### ISSUE TITLE
UDStudio - Endpoints not picking up Id

### ISSUE THREAD

**Issue by paulharman** [ironmansoftware/universal-dashboard#1385]
#### Describe the Issue
I’ve noticed in UDStudio that I’ve got a couple of endpoints which are not picking up their ID. Also no endpoints are showing under sessions.

#### To Reproduce
Run dashboard in VSCode - Expand Endpoints in UDStudio - some endpoints with ID's are loaded correctly, others still have GUID e.g. :

    New-UDGrid  -NoFilter -Title " " -Id "oldestgrid" -AutoRefresh -RefreshInterval 230 -PageSize 10 -Endpoint {
        $Cache:oldesttickets |
        Out-UDGridData
    }

#### Expected behavior
endpoints should be shown correctly

#### Screenshots
![image](https://user-images.githubusercontent.com/3407038/70906066-6af74b80-1ffd-11ea-8376-f8c6f55dac21.png)

#### Version Information
- **Operating System**:  Win 10 x64
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) - Powershell via VS Code

**Comment by adamdriscoll** [comment]
Fixed in 0.1.7
