### ISSUE TITLE
Concurrency issue with AssetService.RegisterAsset

### ISSUE THREAD

**Issue by TonyBunce** [ironmansoftware/universal-dashboard#1387]
I have a persistent issue with my dashboard randomly hitting 100% CPU (I'm running the nightly build)

I have a memory dump of the UniveralDashboard.Server.exe process when the CPU is peg and when trying to find the issue  I see lots of exceptions in the dump that look like this:

Exception calling "RegisterAsset" with "1" argument(s): "Index was outside the bounds of the array."

It looks like AssetService.cs uses a List<String> for the variable "Assets" which is not thread safe and is likely causing this exception.  

I don't know if that is the root cause of the CPU issue but we have noticed that sometimes before we see the CPU spike that HTTP request to /api/internal/dashboard/theme will error out instead of returning valid CSS.  It looks like that code path also uses the Assets List<String>.

**Comment by adamdriscoll** [comment]
I've merged a PR to introduce thread-safe collections for that class. Can you try tonight's build? I haven't actually reproduced the CPU spike or the RegisterAsset issue so hopefully, this resolves it for you.

**Comment by TonyBunce** [comment]
It doesn't look like this is in the nightly enterprise release, I'll upgrade my dashboard with the latest enterprise nightly once it is released.

**Comment by adamdriscoll** [comment]
Ack. I messed up the release pipeline and didn't realize it until today. The build is published now: https://github.com/ironmansoftware/universal-dashboard-enterprise/releases/tag/nightly.20191219.2

**Comment by adamdriscoll** [comment]
Closing this for now as I haven't heard back and I'm not getting reports of issues. Please reopen if you still have issues.
