### ISSUE TITLE
New-UDRow and New-UDColomn broken after upgrade to 1.5.3

### ISSUE THREAD

**Issue by Stephanevg** [ironmansoftware/universal-dashboard#139]
Hi,

I had a dashboard that worked on  version: 1.2.2

I upgraded to the version 1.5.3 and ran the same dashboard, and received the following error:

![image](https://user-images.githubusercontent.com/6302961/39594777-f302bedc-4f0d-11e8-851e-bfc8ae89a76a.png)

I have tested independent chucks of code, and the issue seems to be located somehwere in New-UDColomn and new-UdRow cmdlets.

Creating just two empty scriptblocks and executing them using F8 results in this:

![image](https://user-images.githubusercontent.com/6302961/39595171-03cae306-4f0f-11e8-9db2-71d5c717c619.png)

**Comment by Stephanevg** [comment]
ok... I have done some additional tests:
I tests on the same machine, using module 1.2.2 -> No success (Importing the module 'hardcoding' the path to the psd1 file from 1.2.2).

I tried the same method, on another server (With PowerShell version 4(!) and there the dashboard worked !!

Is there maybe a prerequisites that is missing / corrupt that could cause this type of error?

**Comment by adamdriscoll** [comment]
Whoa. That's very weird. Can you see what version of .NET Framework you are running on the two machines? Sure seems like a dependency is missing.

**Comment by adamdriscoll** [comment]
This has been isolated to this issue: #175. .NET Framework 4.7 is now required and will be properly documented
