### ISSUE TITLE
UDTab - load data on request

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1392]
Is there any way to load tab specific data on click on the related tab?

Example: have a page to see AD user information with 2 tabs:

-overview (general properties displayed - SamAccountName, DisplayName, …)
-group memberships (UDGrid of all groups the user is member of)

But the “group memberships” data should only be queried if the tab gets clicked, not each time the page gets visited.

**Comment by augiaugi** [comment]
https://forums.universaldashboard.io/t/udtab-load-data-on-request/1856

**Comment by AlonGvili** [comment]
Add option for this in #1169
