### ISSUE TITLE
manage UDEndpointSchedule

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1394]
in order to fully manage UDEndpointSchedule I think it makes sense to have commands to

-set (change schedule, endpoint, ..)
-stop - remove schedule _(not that sure if it really is needed)_
-remove - remove it completely
-new - create new scheduled endpoint on the fly inside pages

**Comment by augiaugi** [comment]
see forum: https://forums.universaldashboard.io/t/manage-udendpointschedule/1857

**Comment by PowerMav** [comment]
Hi, I have a issue that when I do "Get-UDRestApi | Stop-UDRestApi" and then:
1. remove the part "New-UDEndpoint -Schedule (New-UDEndpointSchedule -Every 1 -Minute) -Endpoint {}" from my script
2. Start-UDRestApi (just Endpoints without schedules)

I notice that the Scheduled Endpoint still gets running and that can create a mess. Totaly confused until I noticed (had a txt file created everytime the schedule ran). Can find any trace that the endpoint is running... but it is ;)

So workaround is to wipe my runspace in vscode everytime I restart script.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/returning-status-before-end-of-endpoint/2057/11
