### ISSUE TITLE
New-UDModal - Naming button & behavior

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#140]
No parameter to set the name of the button created to open the modal.

Shouldn't new-UDModal invoke only the overlay, and this way, allow the user the implement it anywhere as  a prompt, without having to work with the button?

**Comment by adamdriscoll** [comment]
I agree. New-UDModal wasn't totally thought through. I'm not even going to release New-UDModal in 1.6.0 and will be releasing Show-UDModal in 1.7.0. This will allow you to show a modal via any endpoint. I'll make sure to make it fully customizable.

**Comment by Phyziik** [comment]
Sounds Great !

**Comment by adamdriscoll** [comment]
Implemented for 1.7.0. Available in nightly: 

https://udnightly.blob.core.windows.net/master/1.6.2.354/Build.zip
