### ISSUE TITLE
$ClaimsPrincipal can't be referenced when using ADFS login

### ISSUE THREAD

**Issue by dcherry88** [ironmansoftware/universal-dashboard#1407]
#### Describe the Issue
While logged into a UD site utilizing ADFS configuration for login, UD cannot utilize the claims of $claimsprincipal/principle to use Authorization policies for rights access to pages or components of pages.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Setup UD site with AD Federated Services for login.
2. Create page and setup authorization policy based off a $claimsprinciple of an account. You can freely look at $claimsprincipal/principle properties from the Admin Console on the UD page.
3. Test access to page. It should be unavailable.

#### Expected behavior
UD Page should properly read $claimsprinciple data so that it can properly determine Authorizationpolicy for UD site.

#### Version Information
- **Operating System**: Server 2019
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8
- **UD Hosting Method**: IIS

**Comment by adamdriscoll** [comment]
This is resolved in 2.8.2. Please try in a nightly build and let me know if you still have problems.
