### ISSUE TITLE
1.6.0: ConvertTo-JsonEx is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by skest3qc** [ironmansoftware/universal-dashboard#143]
Hi Adam,

I am getting this error with the new version on my dashboard: 

The term 'ConvertTo-JsonEx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again

**Comment by apetitjean** [comment]
Same error here when trying to display a GRID:
```
16:10:14 ExecutionService Error executing endpoint script. The term 'ConvertTo-JsonEx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
16:10:14 ComponentController {"Error":{"message":"The term 'ConvertTo-JsonEx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.","location":null,"type":"error","id":null,"refreshInterval":0,"autoRefresh":false,"hasCallback":false}}
16:10:14 Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor Executing JsonResult, writing value { Error = PowerShellProTools.UniversalDashboard.Models.Error }.
16:10:14 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action PowerShellProTools.UniversalDashboard.Controllers.ComponentController.DataTable (PowerShellProTools.UniversalDashboard) in 1039.9463ms
```

I had no issue with 1.6.0.beta4.

**Comment by NJK-Work** [comment]
Same issue for me.  Was working fine is beta-2.  Trying to use Out-UDGridData with a SQL server query as the endpoint.

**Comment by WPTechnician** [comment]
Same here!  Just upgraded and out-udgriddata stopped working with the above error.

**Comment by rnemeth90** [comment]
Same here! Just cloned the repo and ran the server-performance-dashboard sample. 

![2018-05-07_14h58_17](https://user-images.githubusercontent.com/16194992/39719416-22575d7c-5207-11e8-9618-8482b64a4112.png)

**Comment by kaband** [comment]
Yah, I got the error as well when using Out-UDGridData.  I edited the PSM file - line 234 - removed the Ex from 'ConvertTo-JsonEx' so it becomes ConvertTo-Json and I'm back in business.

**Comment by adamdriscoll** [comment]
I can reproduce this as well. 

Thanks for the workaround, @kaband.

**Comment by adamdriscoll** [comment]
Fixed in 1.6.1.

**Comment by ChrisMagnuson** [comment]
PS, if you need the fix before 1.6.1 is released the file is UniversalDashboardServer.psm1 and per @kaband its line 234 that needs to have the Ex removed from.

**Comment by NJK-Work** [comment]
I must be missing something...my line 234 already has the EX missing:

function Out-UDGridData {
	[CmdletBinding()]
    param(
		[Parameter(ValueFromPipeline = $true)]
		$Data,
		$TotalItems
	)
	
    Begin {
        New-Variable -Name Items -Value @()
    }

	Process {
		$Items += $Data
	}

	End {
		if ($TotalItems -eq 0 -and $Items.Length -ne 0) {
			$TotalItems = $Items.Length
		}

	    @{
			data = $Items
			recordsTotal = $TotalItems
			recordsFiltered = $Items.Length
			draw = $drawId
		} | ConvertTo-Json -Depth 2
	}
}

Is there another UniversalDaashboardServer.psm1 file that I am not seeing?  The one I am looking at is in the root of the 1.60 folder.

NK

**Comment by NJK-Work** [comment]
OK side note, from a newbee, how do I properly insert code?  I tried the <> button but it did fix my above post...
NK

**Comment by NJK-Work** [comment]
Ah problem solved.  I was looking at the downloaded 1.60 beta 2 version I had in another location.  Looking at the official 1.60 release I see the EX...my bad.
NK
