### ISSUE TITLE
Button clicked once but action lauched twice (regression between 2.8.1 and 2.8.2 last nightly build)

### ISSUE THREAD

**Issue by b-sarrazin** [ironmansoftware/universal-dashboard#1438]
#### Describe the Issue
if I click the button once, the action is launched twice

#### To Reproduce
Click once the button and the toast appears twice

#### Expected behavior
Click once the button and the toast appears once

#### Script Sample
`New-UDPage -Url "test" -Title "Test" -Endpoint {

    $Version = Get-Module -Name UniversalDashBoard | Select-Object -ExpandProperty Version
    
    New-UDButton -Text "test" -OnClick {
		  Show-UDToast -Title "button" -Message "Universal Dashboard version $Version" -Duration 60000
    }
}`

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8.2 (last nightly build)
- **UD Hosting Method**: Powershell

#### Additional context
this portion of code worked on version 2.8.1

**Comment by BoSen29** [comment]
This is probably due to the bug: #1440

**Comment by adamdriscoll** [comment]
It was the double websocket. Resolved in tonight's build.
