### ISSUE TITLE
Unlicenced dashboard throws "NoRemote is not defined" error instead of 1 hour grace

### ISSUE THREAD

**Issue by BoSen29** [ironmansoftware/universal-dashboard#1439]
#### Describe the Issue
![image](https://user-images.githubusercontent.com/54361737/72075967-0c1fac00-32f5-11ea-9ee0-05ec198fa0ec.png)

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Remove license.lic file
2. Restart app-pool (IIS)
3. Load dashboard 

#### Expected behavior
1 hour graceperiod warning, and actually loading of content.

#### Screenshots
See description

#### Script Sample
N/A

#### Version Information
- **Server 2019 Std**:
- **5.1**:
- **Latest nightly as of 08.01.2020**:
- **IIS**: (Powershell, IIS, App Service, Etc.)

#### Additional context
The relevant javascript error is not being thrown in the console anymore, compared to previous nightly builds.

**Comment by adamdriscoll** [comment]
Resolved in tonight's build.
