### ISSUE TITLE
Recent nightly builds has double websocket, throwing errors back and forth

### ISSUE THREAD

**Issue by BoSen29** [ironmansoftware/universal-dashboard#1440]
#### Describe the Issue
A clear and concise description of what the issue is.
![image](https://user-images.githubusercontent.com/54361737/72076592-05ddff80-32f6-11ea-9995-d3b8c42a2da8.png)

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Check console

#### Expected behavior
Single websocket per session

#### Screenshots
See description.

#### Script Sample
N/A

#### Version Information
- **Win 2019 Server Std**:
- **5.1**:
- **Latest nightly as of 08.01.2020**:
- **IIS**: (Powershell, IIS, App Service, Etc.)

#### Additional context
@adamdriscoll  is working on this at the moment. Just for logging purposes.

**Comment by adamdriscoll** [comment]
Resolved in tonight's build.
