### ISSUE TITLE
New-UDEndpoint missing AuthorizedRole and AuthorizationPolicy parameter

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/universal-dashboard#1441]
#### Is your Enhancement request related to a problem? 
Today we are unable to protect endpoints that are created outside of a page.
like scheduled endpoints

#### Describe the solution you'd like
I want to have the same parameter as new-udpage have, AuthorizedRole and AuthorizationPolicy.

#### Describe how this would improve your Universal Dashboard Quality of Life
This will prevent leaking of confidential informations to users that are not allowed to see it.

#### Describe alternatives you've considered
I guess it would be possible to code this into every endpoint myself by using "Get-UDAuthorizationPolicy", but it's a tidius and bloating approach ;)

#### Additional context
Adam Agree it's a miss on his page :D

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/authorization-and-policys/1961/7

**Comment by McAndersDK** [comment]
ok, it only miss AuthorizationPolicy, as AuthorizedRole are under deprecation.
