### ISSUE TITLE
Show-UdToast -replacetoast not working

### ISSUE THREAD

**Issue by mieel** [ironmansoftware/universal-dashboard#1449]
#### Describe the Issue
I noticed the ‘ReplaceToast’ parameter on the Show-UDToast cmdlet. Either I misunderstand the function of this parameter or I am not using it right.

`    Show-UDToast -Id tstSyncDraft -message "Syncing.." -Duration 5000 -ReplaceToast
`      
` Do-someting
`        
`        Show-UDToast -Id tstSyncDraft -message "Sync complete " -Duration 5000 -ReplaceToast
`My expectation is that the second toast will replace the first, but it just goes on top of it. What Am I doing wrong?

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Use above snippet
2. Start Dashboard

#### Expected behavior
The Toasts should replace each other instead of stacking up

#### Version Information
- **Operating System**: win server 2016
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.2.7
- **UD Hosting Method**: Powershell

**Comment by AlonGvili** [comment]
@adamdriscoll can you help in this one, i read the docs for the toast react component and like @mieel  saying  it will create new toast, s you think its a bug , i think its by design.

**Comment by adamdriscoll** [comment]
@AlonGvili It looks like we had a mismatch between the displayMode and replaceToast parameter s in the new version of IziToast. I did a quick PR for it.

**Comment by JustinGrote** [comment]
@adamdriscoll I'm seeing this in PU 1.3.0. As a workaround I do a `hide-udtoast` immediately before the `show-udtoast` for now
``` powershell
                        New-UDButton -Icon (New-UDIcon -Icon unlock) -Text 'Unlock' -OnClick { 
                            Show-UDToast -Id mytoast -Message "Unlocking $($RowItem.SamAccountName)" -Duration 5000
                            sleep 2
                            Show-UDToast -Id mytoast -Message "Unlocked!" -Duration 5000  -ReplaceToast
                        } 
```

![Capture](https://user-images.githubusercontent.com/15258962/89956894-ea6c0780-dbea-11ea-8304-c8f8adf9e795.gif)
