### ISSUE TITLE
1.6.0 : New-UDPage : Cannot process argument transformation on parameter 'Content'

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#145]
My Dashboard works fine with 1.6.0-beta4 but not anymore with 1.6.0 final. :-(
Is there some breaking changes?

```
New-UDPage : Cannot process argument transformation on parameter 'Content'. Cannot convert the "My Title" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
At C:\UniversalDashboard\MPA_UserDashboard11.ps1:67 char:16
+ $PageAccueil = New-UDPage -Name 'Accueil' -Icon home -Content {
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (PowerShellProTo...ard.Models.Page:Page) [New-UDPage], CmdletInvocationException
    + FullyQualifiedErrorId : PowerShellProTools.UniversalDashboard.Cmdlets.NewPageCommand
```

Code extract:
```PowerShell
$PageAccueil = New-UDPage -Name 'Accueil' -Icon home -Content {

        New-UDRow -Columns {
            New-UDColumn -Size 12 -Content {
                New-UDHeading -Size 5 -Content "My Title"
            }
        }
...
```

**Comment by apetitjean** [comment]
I found the issue. It's related to a change you made in New-UDHeading. I had a Heading in my page.

Now in 1.6.0 the -Content parameter does not work as it used to. I had now to use -Text instead of -Content to make my Dashboard work again.

**Comment by adamdriscoll** [comment]
@apetitjean Apologies. This was changed to be more consistent with the rest of the module. Content was always a script block and not a string so I changed this between RTM and beta. I should have called it out in the release notes.

**Comment by adamdriscoll** [comment]
Closing this as designed. Re-open if you think it's still an issue.

**Comment by apetitjean** [comment]
That makes sense. Fair enough.
