### ISSUE TITLE
Set-UDClipboard does not work when in a modal

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-dashboard#1461]
Set-UDClipboard functionality seems to be broken when it is used on a control in a modal. If NOT in a modal embedding this function in buttons in grids seems to work fine!

#### Working 
Works fine on pages OR in grids...

```powershell
Set-UDClipboard -Data "ZYX098"
```

#### Not Working
```powershell
Show-UDModal -Width "75%" -Height "75%" -Content {
    New-UDPageHeader -Text ("My Test")
    $CopyStringButton = New-UDButton -Icon copy -OnClick {
        Set-UDClipboard -Data "ABC123"
    }
}
```

```

**Comment by augiaugi** [comment]
Should be fixed in 2.8.2 

https://github.com/ironmansoftware/universal-dashboard/issues/1292

If you are using this version might be not fixed ....

**Comment by AlonGvili** [comment]
I fix this problem, in 2.8.2

**Comment by leeberg** [comment]
Nice! Sorry missed this one - Still on 2.8.1 - I will retest my dashboard today with 2.8.2 and close my issue :)

**Comment by AlonGvili** [comment]
> Nice! Sorry missed this one - Still on 2.8.1 - I will retest my dashboard today with 2.8.2 and close my issue - nice work

thos it working for you ?

**Comment by adamdriscoll** [comment]
Just wrote a test for this. It's working fine in v3
