### ISSUE TITLE
UDDashboard module could not be loaded

### ISSUE THREAD

**Issue by sonanath** [ironmansoftware/universal-dashboard#1462]
Hi

I am new to powershell and was trying use UDDashboards. But unfortunately unable to work with the same

Please find the errors below. Can anyone help find what is missing

I am using a Windows 10 PC with powershell version 5.1.

PS C:\WINDOWS\System32> Install-Module UniversalDashboard -Scope CurrentUser -Force

PS C:\WINDOWS\System32> Start-UDDashboard port 1000
Start-UDDashboard : The 'Start-UDDashboard' command was found in the module 'UniversalDashboard', but the module
could not be loaded. For more information, run 'Import-Module UniversalDashboard'.
At line:1 char:1

Start-UDDashboard port 1000
  + CategoryInfo          : ObjectNotFound: (Start-UDDashboard:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\WINDOWS\System32> $Dashboard = New-UDDashboard -Title "Hello World" -Content {}
New-UDDashboard : The 'New-UDDashboard' command was found in the module 'UniversalDashboard', but the module could
not be loaded. For more information, run 'Import-Module UniversalDashboard'.
At line:1 char:14

$Dashboard = New-UDDashboard -Title "Hello World" -Content {}
         ~~~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (New-UDDashboard:String) [], CommandNotFoundException
FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by adamdriscoll** [comment]
@sonanath You may need to install .NET 4.7.2. If you want more information about the error, try loading the module manually. 

```
Import-Module UniversalDashboard -Verbose
```

**Comment by adamdriscoll** [comment]
Please reopen this if your problem is not solved.
