### ISSUE TITLE
Diagnostic page doesn't use the new UDTab

### ISSUE THREAD

**Issue by BoSen29** [ironmansoftware/universal-dashboard#1472]
#### Describe the Issue
The diag page doesn't utilize the freshly revised UDTabs. 
Class names mismatch.
Makes the CSS inconsistent or requires duplicate.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Open diag page with DarkDefault Theme

#### Expected behavior
Honor the UDTabs in the theme.

#### Screenshots
Diag page:
![image](https://user-images.githubusercontent.com/54361737/72980463-ec9b7f80-3dda-11ea-99d2-d04a5454e31a.png)
![image](https://user-images.githubusercontent.com/54361737/72980559-1bb1f100-3ddb-11ea-86d7-beb87f1941b1.png)

Regular: 
![image](https://user-images.githubusercontent.com/54361737/72980493-f7eeab00-3dda-11ea-90d5-cdccdd817969.png)
![image](https://user-images.githubusercontent.com/54361737/72980546-12288900-3ddb-11ea-8d6f-4e1d6c4bc1b2.png)

#### Version Information
- **Operating System**: Server 2019 Std
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8.2 Enterprise
- **UD Hosting Method**: IIS

**Comment by adamdriscoll** [comment]
Fixed in tonight's build.
