### ISSUE TITLE
Validation dont occure on checkbox changes

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/universal-dashboard#1475]
#### Describe the Issue
see https://forums.universaldashboard.io/t/inputfields-and-submit-button/2049

#### To Reproduce
shown in the above link

#### Expected behavior
expect that the save button get activated on checkbox changes if the "form" validate successfully

#### Screenshots
gif in above link

#### Script Sample
script  in above link

#### Version Information
- **Operating System**: windows server 2016
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.8.2
- **UD Hosting Method**: IIS

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/inputfields-and-submit-button/2049/3
