### ISSUE TITLE
Themes should just consist of options

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#1476]
We shouldn't necessarily be theming each individual component in each theme. Instead, we should be defining the theme options\colors. The ThemeService should be responsible for applying these to the various elements. This will make it WAY easier to maintain themes. 

So our default theme would just be something like: 

```
@{
FontColorDark = "#111111"
FontColorLight = "#FFFFFF"
FontFamily = '"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif'

BackgroundColorPrimary = "#EEEEEE"
BackgroundColorLighter = "#FAFAFA"
BackgroundColorDarker = "#BDBDBD"
BackgroundColorBright = "#FFFFFF"

PrimaryColor = "#3F51B5"
PrimaryColorDark = "#2C387E"
PrimaryColorLight = "#6573C3"
SecondaryColor = '#dd2c00'
SecondaryColorLight = '#e35633'
SecondaryColorDark = '#9a1e00'

PrimaryFontColor = $FontColorDark
AlternateFontColor = $FontColorLight
PrimaryBackgroundColor = $BackgroundColorPrimary
AlternativeBackgroundColor = $BackgroundColorLighter
AlternativeBackgroundColor2 = $BackgroundColorDarker
AlternativeBackgroundColor3 = $BackgroundColorBright
}
```

Theme's should still allow you to override the individual components and use CCS tags but for the built in stuff, we shouldn't be doing that.

**Comment by adamdriscoll** [comment]
Thinking about this more, there needs to be a way for components to utilize the theme colors. Cascading colors via CSS for every possible component isn't managable. We need a way for components to get access to these various colors\options. I think we should add the new type of theme onto the Dashboard object. Then the components could get the theme as a prop and apply that theme themselves. 

I know libraries like Material UI implement theming similar to this so it might fit well.

**Comment by AlonGvili** [comment]
React.context as theme provider

**Comment by adamdriscoll** [comment]
Yep. Exactly what I'm thinking about this.
