### ISSUE TITLE
Dashboard on IIS

### ISSUE THREAD

**Issue by MR-ITdude** [ironmansoftware/universal-dashboard#1480]
Hi,

First of all. Thank you for this awsome module!!!!!!

This is more a question then a bug. 
When i run the dashboard using IIS the powershelluser ($env:USERNAME) is $servername.

How can i change the powershelluser to my service account? Do I need to config an windows UDAuthenticationMethod or do something with IIS?

When i run the dashboard as a powershell or service. $env:USERNAME is myuser or serviceuser

Another thing is that when i run the dashboard as a powershell session or service. I need to refresh the page several times before the home page loads if not it is just blank. (the color of my background)

Thanks.

**Comment by BoSen29** [comment]
Hi @MR-ITdude 
Check out the forums:
https://forums.universaldashboard.io/
For non-bug report / enhancement requests.

When running UD in IIS, the $env:USERNAME is determined by the user defined in your application pool, see: 
http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc00586.1250/doc/html/hfr1271968941503.html

As for the loading issues, id suggest making a forumpost, where you share the relevant code, and i'll sure someone will share some wisdom!

**Comment by adamdriscoll** [comment]
Please feel free to reopen this issue if you do have a problem but I'd do as @BoSen29 suggested and open a forum post. Thanks!

**Comment by MR-ITdude** [comment]
I found the my answer under a forum post. I need to set Load User Profile = True.
Thanks for the help.

Have you tried setting the option under the Application Pool -> Advanced Settings -> Process Model -> Load User Profile = True?

https://forums.universaldashboard.io/t/iis-app-pool-id-and-iis-service-account-problem/1138/10
