### ISSUE TITLE
[Bug] After updating to 2.8.2 the sign out button is missing

### ISSUE THREAD

**Issue by e1ze** [ironmansoftware/universal-dashboard#1481]
#### Describe the Issue
As requested by @adamdriscoll, here is the issue.

After updating from 2.8.0 to 2.8.2 the sign out button is gone. I have not added the `-PassThru` parameter to `New-UDLoginPage` and have not changed anything except the new universaldashboard release.
I have tested it with Firefox, Edge Chromium, Chrome and Brave. Same behavior (Cache/Cookies deleted)
The login is working fine .

Check https://forums.universaldashboard.io/t/iis-setup-windows-auth-logoff/289/13 for more information.

#### To Reproduce
Add a login page with the default authentication method without '-PassThru' parameter and use version 2.8.2. No sign out button appears. In version 2.8.1 and 2.8.0 the sign out button is there.

#### Script Sample
Check https://forums.universaldashboard.io/t/iis-setup-windows-auth-logoff/289/13 for more information.

#### Version Information
- **Operating System**: Windows 10 1909 & Windows Server 2019 LTSB
- **PowerShell Version**: 5.1, 6.2.3, 7.0 RC2
- **Universal Dashboard Version**: 2.8.2
- **UD Hosting Method**: Powershell, IIS

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/iis-setup-windows-auth-logoff/289/15

**Comment by adamdriscoll** [comment]
Fixed in tonight's build.
