### ISSUE TITLE
Manually executing scheduled endpoint

### ISSUE THREAD

**Issue by wsl2001** [ironmansoftware/universal-dashboard#1489]
#### Is your Enhancement request related to a problem? Please describe
$Endpoint = New-UDEndpoint -Id test -Schedule $Schedule1 -Endpoint { } will execute the endpoint based on $Schedule1 value .
unable to find a way to execute manually from button onclick { }

#### Describe the solution you'd like
Adding the ability to do so will help increase UD performance for scheduled endpoints that runs in x seconds and collect data since these scheduled endpoints builds up memory fast. 

#### Describe how this would improve your Universal Dashboard Quality of Life
Manual execution of scheduled endpoint will improve UD performance since memory consumption will be reduced.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/controlling-scheduler-for-endpoint/2487/7
