### ISSUE TITLE
Title of uddashboard not updating when pages as endpoints

### ISSUE THREAD

**Issue by free-neo** [ironmansoftware/universal-dashboard#1496]
#### Describe the Issue
I have a dashboard (2.8.2) that uses pages that call scripts in endpoints:

New-UDPage -Name "Home" -Icon globe -Title "HOME" -Endpoint{}

This however affects the -Title on the dashboard and does not allow it to update for each page, it remains as the title defined in the line:

$Dashboard = New-UDDashboard -Title "BASIC" -Pages $Pages -Navigation $Navigation

Also the tab text remains ‘Powershell Universal Dashboard’.

If i then change the endpoint to -Content (New-UDPage -Name “Home” -Icon globe -Title “HOME” -Content{}) it all works as expected, the title and tabs all update…

https://forums.universaldashboard.io/t/title-of-uddashboard-not-updating-when-pages-as-endpoints/2136

#### To Reproduce
Run this dashboard and navigate (see code below):

#### Expected behavior
Expect the tab and title to update as it does with -Content

#### Script Sample
Get-UDDashboard | Stop-Uddashboard

# Create Dashboard - Pages
$Pages = @()
$Pages += New-UDPage -Name "Home" -Icon globe -Title "HOME" -Endpoint{
}
$Pages += New-UDPage -Name "Test" -Icon globe -Title "Test" -Endpoint{
} 

# Create Dashboard - Navigation
$Navigation = New-UDSideNav -Fixed -Width 225 -Content {
    New-UDSideNavItem -Text "Home" -PageName "Home" -Icon Home
    New-UDSideNavItem -Text "Test" -PageName "Test" -Icon hourglass_half
}

# Dashboard Start
$Dashboard = New-UDDashboard -Title "BASIC" -Pages $Pages -Navigation $Navigation
Start-UdDashboard -Dashboard $Dashboard -Wait

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/title-of-uddashboard-not-updating-when-pages-as-endpoints/2136/5

**Comment by free-neo** [comment]
Hi Adam, thats the thread that lead to this bug being reported.

Cheers.
