### ISSUE TITLE
2.8.3 - Azure theme Navigation

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#1498]
#### Describe the Issue
2.8.3 changed:
```
.ud-navbar"= @{
    'z-index'= "0"
}

z-index should be 9999 to ensure it is always on top

```

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard with Azure theme
2. Click on the Hamburger
3. Behold the Navbar being under cards and other such elements

#### Expected behavior
Navigation to be ontop

#### Screenshots
https://forums.universaldashboard.io/t/2-8-3-azure-theme/2139

#### Script Sample
Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/2-8-3-azure-theme/2139/7

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/did-i-miss-a-change-to-iis-deployment/2092/22
