### ISSUE TITLE
2.8.2 Broke my dashboard

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#1500]
2.8.1 works fine. Tried to use the latest nightly build, and i get a gray page, no login prompt. So i tried latest release, 2.8.3, and then 2.8.2, same issue.

Only version that works is 2.8.1.. no idea where to start to look. I get no warning/errors in the console.

**Comment by adamdriscoll** [comment]
When you say console, is that the PS console or browser console?

**Comment by mkellerman** [comment]
PS Console

**Comment by adamdriscoll** [comment]
Can you check in the browser console to see if there are errors? Can you also make sure you've cleared your browser cache?

**Comment by mkellerman** [comment]
It worked! *facepalm*
