### ISSUE TITLE
HTML bulletpoints/lists

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/universal-dashboard#1513]
#### Describe the Issue
HTML Bulletpoints/lists when using either new-udhtml -markup or new-udelement;
ul/li components do not show their bullets.

It has been suggested that something from MaterializeCss is causing this.

#### To Reproduce
```
new-udhtml -markup "
            <ul style='list-style-type:circle;'>
            <li>Item 1</li>
            <li>Item 2</li>
            </ul>
"
```
OR
```
New-UDElement -Tag ul -Attribute @{ style = @{ 'listStyleType' = 'circle !important' } } -Content {
                New-UDElement -Tag li -Content {"test1"}
                New-UDElement -Tag li -Content {"test2"}
  }
```

#### Expected behavior
Bullets should show next to listed items

#### Version Information
- **Universal Dashboard Version**: 2.8.2
- **UD Hosting Method**: IIS

#### Additional context
https://forums.universaldashboard.io/t/html-bulletpoints-lists/2194/5

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/html-bulletpoints-lists/2194/7

**Comment by adamdriscoll** [comment]
This has been resolved in v3.
