### ISSUE TITLE
502 Error after updating to 2.9.0

### ISSUE THREAD

**Issue by SConstantinou** [ironmansoftware/universal-dashboard#1515]
#### Describe the Issue
I have updated from 2.8.3 to 2.9.0 and I receive 502 error. No other changes made on the dashboard. 502 error is reported on favicon.ico. I have tried with my custom favicon file and the original one. The behavior is the same.

I have replaced the files again back to 2.8.3 and the dashboard is running normally.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard with IIS
2. Error 502 is received immediately

#### Expected behavior
Dashboards should load normally

#### Screenshots
![image](https://user-images.githubusercontent.com/35262217/74644365-d89b3180-517e-11ea-955a-45d62839a756.png)

#### Script Sample
Start-UDDashboard -Wait -Dashboard (
    New-UDDashboard -Title "Hello, IIS" -Content {
        New-UDCard -Title "Hello, IIS"
    }
)

#### Version Information
- **Operating System**: Windows 2019 Core
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.9.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) IIS

**Comment by adamdriscoll** [comment]
@SConstantinou - Have you updated your web.config to point to PowerShell rather than UniversalDashboard.Server.exe? https://docs.universaldashboard.io/webserver/running-dashboards/iis

**Comment by SConstantinou** [comment]
Thanks. This resolved my issue.
