### ISSUE TITLE
REST API: Support for the HTTP OPTIONS method

### ISSUE THREAD

**Issue by tiwood** [ironmansoftware/universal-dashboard#1524]
We would like to implement the `HTTP OPTIONS` Method to provide the caller with additional information about our endpoint.

This would enable scenarios like responding with a json that describes your endpoint.

[Forum post](https://forums.universaldashboard.io/t/add-support-for-http-method-options/2247/2)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/add-support-for-http-method-options/2247/4

**Comment by tiwood** [comment]
Hi @adamdriscoll, any chance to get this feature added in the next version?
