### ISSUE TITLE
Published Dashboard - Remote access issues

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#153]
I published my dashboard locally, and tried to access it remotely from other computers, the same way I usually do, and the get an 404. I tried playing around with ports, and nothing works.

**Comment by adamdriscoll** [comment]
I tested this on a Server 2016 machine running UD installed as a service and was able to access it remotely. Can you go into your F12 developer tools in your browser and see what request the browser is making to receive a 404?

**Comment by Phyziik** [comment]
I saw the issue multiple times last week, but I deployed on a 2016 this week, and I don't seem to be getting the error anymore. I tried reproducing it on the original system, and it's connecting now... Can't really complain, sorry for false bug. I'll let you know if I can reproduce it
