### ISSUE TITLE
Cmdlets are not exported in v1.6.1

### ISSUE THREAD

**Issue by RCDS1** [ironmansoftware/universal-dashboard#154]
![missingcommands2](https://user-images.githubusercontent.com/39102853/39781840-daed4948-52ff-11e8-8fdf-76539c5255e5.jpg)

Cmdlets are not being exported

PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

- .Net Version

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033]
"Version"="4.7.02053"
"CBS"=dword:00000001
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:00070805

**Comment by adamdriscoll** [comment]
@RCDS1 Looks like an issue with v5.0 vs v5.1. Try changing the UniversalDashboard.psd1 manifest to: 

```
$DebugFormat = Test-Path "$PSScriptRoot/PowerShellProTools.UniversalDashboard.dll"
if ($DebugFormat) {
	Import-Module "$PSScriptRoot/PowerShellProTools.UniversalDashboard.dll"
}
else 
{
	if ($PSEdition -eq "Core") {
		Import-Module -Name "$PSScriptRoot/netstandard2.0/PowerShellProTools.UniversalDashboard.dll" | Out-Null
	} else {
		Import-Module -Name "$PSScriptRoot/net462/PowerShellProTools.UniversalDashboard.dll" | Out-Null
	}	
}

if (-not $IsRunningInUniversalDashboard -and (Test-Path (Join-Path $PSScriptRoot "license.lic"))) {
	Set-UDLicense -License (Get-Content (Join-Path $PSScriptRoot "license.lic"))
}

Import-Module (Join-Path $PSScriptRoot "UniversalDashboardServer.psm1")
Import-Module (Join-Path $PSScriptRoot "UniversalDashboard.Controls.psm1")
```

**Comment by adamdriscoll** [comment]
Fixed in 1.6.2.

**Comment by TheStanzx85** [comment]
Sorry for the elementary question but are you replacing the entire contents of the UniversalDashboard.psd1  file with your code above or adding to it?

**Comment by adamdriscoll** [comment]
@TheStanzx85 Just replace the entire contents of that file.

**Comment by TheStanzx85** [comment]
No luck, I'll wait for the new release.
