### ISSUE TITLE
NivoChart Line - Non responsive

### ISSUE THREAD

**Issue by mcgurdan** [ironmansoftware/universal-dashboard#1548]
#### Describe the Issue
When using the Line option for New-UDNivoChart the chart itself is completely unresponsive, currently on an enterprise licence and would really like for this to work! I used the Line chart example on the page here:
https://docs.universaldashboard.io/components/data-visualizations/nivo

Again this did not work. Tested in both Chrome and Internet Explorer. Looking at the console logs in Chrome, it did report an issue trying to source the bundle.map

![image](https://user-images.githubusercontent.com/16016044/76073790-1dea9c00-5f92-11ea-95cb-f701764c00b9.png)

**Comment by adamdriscoll** [comment]
Sorry for the delay. I've updated the nivo charts in v3 to support hovering over line charts again. This is in tonight's nightly build and will be in v3-beta2
