### ISSUE TITLE
cant start dashboard from integrated console in visual code

### ISSUE THREAD

**Issue by rddoove** [ironmansoftware/universal-dashboard#1550]
Hi there,

I cant seem to start a dashboard form visual code.
I get the error:
Application startup exception: System.MissingMethodException: Method not found: ‘Microsoft.Extensions.Logging.ILoggerFactory NLog.Extensions.Logging.ConfigureExtensions.AddNLog(Microsoft.Extensions.Logging.ILoggerFactory)’.
at UniversalDashboard.ServerStartup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime lifetime)
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

I am using the preview powershell extentions (beacuse is has psreadline support)

I can start it from a regular powershell console

Any idea’s?

**Comment by jmiranto** [comment]
Just got the same issue. VS Code did a PowerShell Integrated Console update automatically. After that, trying to run the dashboard in VS code produces this error:

Application startup exception: System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory NLog.Extensions.Logging.ConfigureExtensions.AddNLog(Microsoft.Extensions.Logging.ILoggerFactory)'.
   at UniversalDashboard.ServerStartup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime lifetime)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Running the dashboard directly in PowerShell 5.1 still works.

**Comment by psDevUK** [comment]
Damn I got this too now after an update in vscode
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:37:31.640Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.18362

**Comment by jmiranto** [comment]
Rolling back the PowerShell extension in VS Code to 2020.1.0 from 2020.3.0 worked for me. Until vs-code tries to update to the new version again.

**Comment by psDevUK** [comment]
Awesome @jmiranto  for sharing....so I did this roll-back, then went file preferences, typed in UPDATE then turned off extensions automatically updating.

**Comment by dtnyc9005** [comment]
Worked for me thanks guys this was very helpful!

**Comment by Atreidae** [comment]
Adding a #MeToo to this, Rolling back to 2020.1.0 fixed it for me.
Googling for "universal dashboard logger factory" lead me to an old un-answered forum post.
hoping if I add certain keywords here it will help other first-timers (Trying to follow the first run guide)

**Comment by crmii** [comment]
Nice. Thank you!

**Comment by adamdriscoll** [comment]
This issue is resolved by running UD in PowerShell Universal as Universal loads the UD dashboard in a separate PS process so it won't conflict with VS Code. 1.1.1 PSU should load your dashboard. 1.2 PSU will have a much more complete UD implementation so might be worth waiting a week for that to come out before trying again.
