### ISSUE TITLE
Advanced formatting for Grids?

### ISSUE THREAD

**Issue by jholl016** [ironmansoftware/universal-dashboard#156]
The New-UDGrid cmdlet includes a parameter for specifying font color, but there are many other things it would be nice to customize, font size and row height for example.  Using the default style, I can only get about 12 rows to display on a 1080 screen height.  There's a lot of padding in the row height that could be reduced to get more data on the screen at a time.

Is there any way to accomplish this today (version 1.6.1)?  Or, in a future release, would it be possible to expose the underlying CSS that's defining these styles so that we can customize to our needs?

**Comment by ChrisMagnuson** [comment]
Adding my 2 cents, the abstraction that @adamdriscoll has created on top of technologies like html, websockets, javascript, css, etc. is amazing and one of the amazing things is how little the abstraction currently [leaks](https://en.wikipedia.org/wiki/Leaky_abstraction).

I have seen a number other attempts at this that tried to support custom css , like [PowerShellPipeworks](https://github.com/StartAutomating/Pipeworks) and the abstraction started breaking down. 

I don't know what the right way to provide this level of control without breaking the abstraction that has been built but I would be more in favor of less configuration and an acceptance of some standardized defaults which I believe is what is being done currently.

It would be nice of there was a standardized way for styling things, like a theme system, but I would hate to descend into having a -css parameter or the like on various commandlets.

**Comment by adamdriscoll** [comment]
I've had other people complain about the size of the rows. I will try and put together a sample that resolves this with the current implementation and will think about how to tackle this in future releases to make it easier.

**Comment by adamdriscoll** [comment]
I've reduced the grid cell padding by about 2/3s and you will be able to fit a lot more rows in the next version.
