### ISSUE TITLE
Have AutoReload watch for child items of folders

### ISSUE THREAD

**Issue by forevanyeung** [ironmansoftware/universal-dashboard#1563]
AutoReload only watches for file changes on the top level directory. My file structure places pages and endpoints in their own folder and are automatically loaded when starting Universal Dashboard. Similar to how https://github.com/adamdriscoll/ud-activedirectory is structured.

This may be fixed by setting the FileSystemWatcher.IncludeSubdirectories property to True

#### Describe alternatives you've considered
I have seen other issues https://github.com/ironmansoftware/universal-dashboard/issues/48 and they point to UDHotReloader, however that blog post no longer exists.

**Comment by adamdriscoll** [comment]
This has been implemented in PowerShell Universal 1.2.
