### ISSUE TITLE
AppBar is not loaded

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1571]
#### Describe the Issue
The AppBar is not loaded for my pages:

**Startup.ps1**
```
 $Pages = Get-ChildItem (Join-Path $PSScriptRoot 'Pages') -Recurse -File | ForEach-Object {
        & $_.FullName
    } 

    $Dashboard = New-UDDashboard -Title 'AdminCenter' -EndpointInitialization $EndpointInitialization -Pages $Pages
    
    $StartDashboard = Start-UDDashboard -Name 'AdminCenter' -Dashboard $Dashboard -Port 10005
```

**HomePage.ps1**
```
New-UDPage -Name 'Home' -Content {
    $Drawer = New-UDDrawer -Children {
        New-UDList -Children {
            New-UDListItem -Label "Home"
            New-UDListItem -Label "Getting Started" -Children {
                New-UDListItem -Label "Installation" -OnClick {}
                New-UDListItem -Label "Usage" -OnClick {}
                New-UDListItem -Label "FAQs" -OnClick {}
                New-UDListItem -Label "System Requirements" -OnClick {}
                New-UDListItem -Label "Purchasing" -OnClick {}
            }
        }
    }

    New-UDAppBar -Position relative -Children { New-UDElement -Tag 'div' -Content { "Title" } } -Drawer $Drawer
    
    New-UDTextbox -Id 'txtTextfield' -Label 'test' 
}
```

The AppBar function has been used 1:1 from the v3 hosted doc https://universaldashboard-dev.azurewebsites.net/appbar

Instead of the expected configured AppBar the AppBar is listing some (one page /test/temp) of my loaded pages.

![image](https://user-images.githubusercontent.com/23495782/77828922-b6ea7e00-711e-11ea-9216-7ccb2e65e0f9.png)

#### Version Information
- **Operating System**: Win10
- **PowerShell Version**: 5.1.17763.1007
- **Universal Dashboard Version**: 3.0.0-beta1
- **UD Hosting Method**: Powershell

**Comment by augiaugi** [comment]
@adamdriscoll please assign the v3 label to this issue. :)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/v3-is-not-showing-any-component/2418/2

**Comment by adamdriscoll** [comment]
This has been resolved. It happens when authentication isn't enabled.
