### ISSUE TITLE
DefaultHomePage cannot have an Url

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1572]
#### Describe the Issue
A DefaultHomePage cannot have an Url, this would be great.
And I dont see a reason against this.

#### Expected behavior
I think it makes sense to have a default home page also defined with an Url.

#### Script Sample
```
New-UDPage -Url '/home' -DefaultHomePage -Content { }

Exception: New-UDPage : Object reference not set to an instance of an object.
```

#### Version Information
- **Operating System**: Win10
- **PowerShell Version**: 5.1.17763.1007
- **Universal Dashboard Version**: v3.0.0-beta1
- **UD Hosting Method**: Powershell

**Comment by adamdriscoll** [comment]
Resolved in tonight's build.
