### ISSUE TITLE
full size pages

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1574]
As far as I remember the page position (centered) and size (spaces left and right) is new coming from v3.0.0-beta1 right?
If this is the case how can this be adjusted to full size pages?

![image](https://user-images.githubusercontent.com/23495782/77844572-03c66700-71a8-11ea-8ca3-df71a080bf3d.png)

Adam: "I think it is. I think by default it’s applying the Material UI container: https://material-ui.com/components/container/

We should make it so you can remove that."

**Comment by augiaugi** [comment]
@adamdriscoll  please assign v3.0.0-beta1 label

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/page-position-and-size/2421/4

**Comment by AlonGvili** [comment]
@adamdriscoll do we have to use the container ?
or maybe the container would be the main wrapper of the page ?

**Comment by adamdriscoll** [comment]
I think I'm going to remove it from the default UDPage and just create a new component so people can choose to use the container if they want.
