### ISSUE TITLE
conflicting api path

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1576]
#### Describe the Issue
cannot use enpoint path /user and /user/:id (I cannot test this with v3 because of another bug, but this was the case in v2.9)

I am having two endpoints this are in conflict.

* /user - static page
* /user/:ID - dynamic page with params
after changing the dynamic page to e.g. /object/user/:ID anything is working fine.

It would be great if i can use the endpoint /user/:ID (this should be possible as I am using the same structure in ASP.Net Core)
And maybe the error message should also be changed or maybe this is only confusing me 

#### Script Sample
```
New-UDPage -Url '/user' -Endpoint {
    New-AppBar -Titel 'User'

    New-UDTextbox -Id 'txtTextfield' -Label 'First Name' 
}

New-UDPage -Url "/user/:ID" -Endpoint {
    param($ID)

    New-AppBar -Titel "User [$ID]"
    
    New-UDTextbox -Id 'txtUser' -Label 'user' -Value $ID
}
```

#### Version Information
- **Operating System**: Win10
- **PowerShell Version**: 5.1.17763.1007
- **Universal Dashboard Version**: v3.0.0-beta1
- **UD Hosting Method**: Powershell

**Comment by augiaugi** [comment]
@adamdriscoll please assign v3.0.0-beta1 label

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/empty-page-error/2420/9

**Comment by adamdriscoll** [comment]
This is resolved in tonight's build.
