### ISSUE TITLE
pages with -Endpoint not working

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1577]
#### Describe the Issue
pages using `-Endpoint` instead of `-Content` doesnt work anymore - `There was an error with your Endpoint for this page. You need to return at least one component from the Endpoint.`

This is a huge problem as far as I can see an dynamic page requires  `-Endpoint` in order to work.

#### Version Information
- **Operating System**: Win10
- **PowerShell Version**: 5.1.17763.1007
- **Universal Dashboard Version**: v3.0.0-beta1
- **UD Hosting Method**: Powershell

**Comment by augiaugi** [comment]
@adamdriscoll please assign v3.0.0-beta1 label

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/empty-page-error/2420/9
