### ISSUE TITLE
Dynamic page missing Endpoint error message

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1578]
#### Describe the Issue
As far as I can see a dynamic page requires a `-Endpoint` block instead of `-Content`.
This error message appears:

`New-UDPage : Object reference not set to an instance of an object.`

I thing it is good to change that message to a more meaningful one.

#### Version Information
- **Operating System**: Win10
- **PowerShell Version**: 5.1.17763.1007
- **Universal Dashboard Version**: v3.0.0-beta1
- **UD Hosting Method**: Powershell

**Comment by augiaugi** [comment]
@adamdriscoll please assign v3.0.0-beta1 label

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/empty-page-error/2420/9
