### ISSUE TITLE
After 1.60 BETA2, CPU goes to 100%

### ISSUE THREAD

**Issue by NJK-Work** [ironmansoftware/universal-dashboard#158]
This code used to work (private info replaced with BLAH) with 1.60 BETA 2:

```PowerShell
#region Settings
$SQLServer = "BLAH"
$SQLDatabase = "BLAH"
$SelectStatement = "BLAH"

$Port = 10000
$Title = "BLAH"
$Welcome = "BLAH"
#endregion

#region Modules
Import-Module UniversalDashboard
#endregion

#region Main
$Headers = @("BLAH","BLAH","BLAH","BLAH","BLAH")
$Properties = @("BLAH","BLAH","BLAH","BLAH","BLAH")
$ServerList = Invoke-Sqlcmd -Query $SelectStatement -ServerInstance $SQLServer -Database $SQLDatabase

$PageHome = New-UDPage -Name "Home" -Icon home -Content {New-UDCard -Title "Home" -Text $Welcome}
$PageServerList = New-UDPage -Name "BLAH" -Icon bookmark -Content {New-UDGrid -Headers $Headers -Properties $Properties -Endpoint {$ServerList | Out-UDGridData} -Title $Title}

$Dashboard = New-UDDashboard -Title "BLAH" -Pages @($PageHome, $PageServerList)
Start-UDDashboard -Dashboard $Dashboard -Port $Port -Name "WSADashboard" -AutoReload
#endregion
```

Now with anything past BETA 2, this is what happens:
1) Dashboard loads - all is good
2) User connects to dashboard on port 10000 and home page loads - all is good
3) User opens the page "ServerList" page and no data is displayed in the grid.  CPU on the server goes to 100%
4) I Issue a "stop-uddashboard" on the server, CPU remains at 100%.
5) I close ISE on the server and an instance of ISE still shows as running is process list using 100% CPU (but the GUI is gone), even though I just closed ISE.  Have to END TASK on the ISE process to get rid of it and free up the CPU.

This worked in BETA 2.  But BETA3, release, and 1.61 all have this problem.  My SQL statements are sound - I have verified they return good data.  I have them redacted for privacy reasons.  Is there something wrong with my code.  I am new to UD, so I am just learning how to use it.  Assuming a bug in my code - why does it work with BETA 2?

Thanks
NK

**Comment by adamdriscoll** [comment]
This is a bug with SQL DataRows and ConvertTo-Json. Can you try creating a hashtable or PSCustomObject from your SQL DataRows? 

```
$Servers = $Servers | ForEach-Object {
   [PSCustomObject]@{
        Prop1 = $_.Prop1
   }
}
```

Like you, I thought this was resolved in an earlier release. I will have to put in a regression test for this to make sure it remains fixed. 

What I ended up doing previously was limiting the Depth on ConvertTo-Json cmdlet in Out-UDGridData.
