### ISSUE TITLE
UDModal is missing

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1591]
I cannot find the UDModal in v3.0.0-beta1.

https://docs.universaldashboard.io/components/modal

**Comment by augiaugi** [comment]
@adamdriscoll please assign label v3

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/v3-udmodal-is-missing/2436/5
