### ISSUE TITLE
AutoReload does not work with Visual Studio 2017 as IDE

### ISSUE THREAD

**Issue by TheVonguru** [ironmansoftware/universal-dashboard#16]
Hello,

I am using Visual Studio 2017 as my editor. When making edits, AutoReload does not work. When I edit the same file using Visual Studio Code, AutoReload works as expected.

This is ironic since PowerShell Pro Tools is for Visual Studio, which is why I am using that as my editor.

Von

**Comment by adamdriscoll** [comment]
Very interesting! I'll look into that. I hadn't noticed that before.

**Comment by TheVonguru** [comment]
I am still having this issue - and I am also now having it work VS Code too...

**Comment by jagrock** [comment]
New UD.Community install for me (fresh install 2 days ago).  AutoReload is not working for any dashboard I create as well.

**Comment by jagrock** [comment]
Update-UDDashboard only works if the dashboard was started pointing to a file such as below.

`Start-UDDashboard -Name "TestUsingFilePath" -UpdateToken test -FilePath $DashboardFile -Port 8081`

**Comment by adamdriscoll** [comment]
Autoreload is now implemented as part of PowerShell Universal and this will no longer be a problem.
