### ISSUE TITLE
UDButton clientEvent onClick not found

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1609]
I am getting the following error for all my UDButtons using the parameter `-ArgumentList`

 `An unexpected error occurred invoking 'clientEvent' on the server. Exception: Endpoint 36308dac-ada4-4ce9-a74e-4c12befdfbb8onClick not found.`

```
$MyVariable = "Some Text"
New-UDButton -Text "Click me!" -OnClick (
    New-UDEndpoint -Endpoint {
        Show-UDToast -Message $ArgumentList[0]
    } -ArgumentList @($MyVariable)
)
```
>this example is coming directly from the UD doc -https://docs.universaldashboard.io/components/button#passing-variables-to-a-button-onclick-handler

I already tried to spot any local issues on my machine by clearing the browser cache, restarting my computer and installing the latest nightly build, but its still not working.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/udbutton-clientevent-onclick-not-found/2502/8

**Comment by augiaugi** [comment]
@adamdriscoll please assign the v3 label

**Comment by adamdriscoll** [comment]
This is been resolved and will be in tonight's nightly build.

**Comment by augiaugi** [comment]
@adamdriscoll what is the related PR?

**Comment by adamdriscoll** [comment]
https://github.com/ironmansoftware/universal-dashboard/commit/4607728147b75abc429624bb4ee77be71aab3e3b

**Comment by adamdriscoll** [comment]
That said, it just happened to me again....

**Comment by adamdriscoll** [comment]
My issue was a problem with the enterprise caching the endpoint incorrectly. This is now resolved. It looks like it's working fine on the hosted version as well.

**Comment by augiaugi** [comment]
@adamdriscoll please reopen this as described in the forum

https://forums.universaldashboard.io/t/udbutton-clientevent-onclick-not-found/2502/9
