### ISSUE TITLE
New-UDDashboard is not recognized as a cmdlet

### ISSUE THREAD

**Issue by TheStanzx85** [ironmansoftware/universal-dashboard#161]
Excuse me if this this a newbie issue but I had a working dashboard yesterday (i'm learning PSUD and PS at the same time)
Just updated my module and I no longer can use New-UDDashboard cmdlet to run my dashboard. I am getting 
#####################################################################
The term 'New-UDDashboard' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1
char:16
+ $MyDashboard = New-UDDashboard -Title "Hello, World" -Content {
+                ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-UDDashboard:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

When I use 

 (Get-Module UniversalDashboard).exportedcommands
Did something change?
This is the list I get:

Key                        Value
---                        -----
Get-UDContentType          Get-UDContentType
Get-UDCookie               Get-UDCookie
New-UDBarChartDataset      New-UDBarChartDataset
New-UDBarChartOptions      New-UDBarChartOptions
New-UDButton               New-UDButton
New-UDCard                 New-UDCard
New-UDCategoryChartAxis    New-UDCategoryChartAxis
New-UDChartDataset         New-UDChartDataset
New-UDChartLayoutOptions   New-UDChartLayoutOptions
New-UDChartLegendOptions   New-UDChartLegendOptions
New-UDChartOptions         New-UDChartOptions
New-UDChartTitleOptions    New-UDChartTitleOptions
New-UDChartTooltipOptions  New-UDChartTooltipOptions
New-UDCheckbox             New-UDCheckbox
New-UDCollapsible          New-UDCollapsible
New-UDCollapsibleItem      New-UDCollapsibleItem
New-UDCollection           New-UDCollection
New-UDCollectionItem       New-UDCollectionItem
New-UDColumn               New-UDColumn
New-UDDoughnutChartDataset New-UDDoughnutChartDataset
New-UDDoughnutChartOptions New-UDDoughnutChartOptions
New-UDHeading              New-UDHeading
New-UDIcon                 New-UDIcon
New-UDIFrame               New-UDIFrame
New-UDImage                New-UDImage
New-UDLayout               New-UDLayout
New-UDLinearChartAxis      New-UDLinearChartAxis
New-UDLineChartDataset     New-UDLineChartDataset
New-UDLineChartOptions     New-UDLineChartOptions
New-UDLogarithmicChartAxis New-UDLogarithmicChartAxis
New-UDParagraph            New-UDParagraph
New-UDPolarChartDataset    New-UDPolarChartDataset
New-UDPolarChartOptions    New-UDPolarChartOptions
New-UDPreloader            New-UDPreloader
New-UDRadarChartDataset    New-UDRadarChartDataset
New-UDRadio                New-UDRadio
New-UDRow                  New-UDRow
New-UDSelect               New-UDSelect
New-UDSelectGroup          New-UDSelectGroup
New-UDSelectOption         New-UDSelectOption
New-UDSpan                 New-UDSpan
New-UDSwitch               New-UDSwitch
New-UDTable                New-UDTable
New-UDTextbox              New-UDTextbox
Out-UDChartData            Out-UDChartData
Out-UDGridData             Out-UDGridData
Out-UDMonitorData          Out-UDMonitorData
Out-UDTableData            Out-UDTableData
Publish-UDDashboard        Publish-UDDashboard
Remove-UDCookie            Remove-UDCookie
Set-UDContentType          Set-UDContentType
Set-UDCookie               Set-UDCookie
Update-UDDashboard         Update-UDDashboard
Write-UDLog                Write-UDLog

**Comment by adamdriscoll** [comment]
Can you please get the output from: 

Import-Module UniversalDashboard -Verbose

it seems like its not loading the module correctly

**Comment by TheStanzx85** [comment]
`VERBOSE: Loading module from path 'C:\Program Files
(x86)\WindowsPowerShell\Modules\UniversalDashboard\1.6.1\UniversalDashboard.psd1'.
VERBOSE: Importing function 'Get-UDContentType'.
VERBOSE: Importing function 'Get-UDCookie'.
VERBOSE: Importing function 'New-UDBarChartDataset'.
VERBOSE: Importing function 'New-UDBarChartOptions'.
VERBOSE: Importing function 'New-UDButton'.
VERBOSE: Importing function 'New-UDCard'.
VERBOSE: Importing function 'New-UDCategoryChartAxis'.
VERBOSE: Importing function 'New-UDChartDataset'.
VERBOSE: Importing function 'New-UDChartLayoutOptions'.
VERBOSE: Importing function 'New-UDChartLegendOptions'.
VERBOSE: Importing function 'New-UDChartOptions'.
VERBOSE: Importing function 'New-UDChartTitleOptions'.
VERBOSE: Importing function 'New-UDChartTooltipOptions'.
VERBOSE: Importing function 'New-UDCheckbox'.
VERBOSE: Importing function 'New-UDCollapsible'.
VERBOSE: Importing function 'New-UDCollapsibleItem'.
VERBOSE: Importing function 'New-UDCollection'.
VERBOSE: Importing function 'New-UDCollectionItem'.
VERBOSE: Importing function 'New-UDColumn'.
VERBOSE: Importing function 'New-UDDoughnutChartDataset'.
VERBOSE: Importing function 'New-UDDoughnutChartOptions'.
VERBOSE: Importing function 'New-UDHeading'.
VERBOSE: Importing function 'New-UDIcon'.
VERBOSE: Importing function 'New-UDIFrame'.
VERBOSE: Importing function 'New-UDImage'.
VERBOSE: Importing function 'New-UDLayout'.
VERBOSE: Importing function 'New-UDLinearChartAxis'.
VERBOSE: Importing function 'New-UDLineChartDataset'.
VERBOSE: Importing function 'New-UDLineChartOptions'.
VERBOSE: Importing function 'New-UDLogarithmicChartAxis'.
VERBOSE: Importing function 'New-UDParagraph'.
VERBOSE: Importing function 'New-UDPolarChartDataset'.
VERBOSE: Importing function 'New-UDPolarChartOptions'.
VERBOSE: Importing function 'New-UDPreloader'.
VERBOSE: Importing function 'New-UDRadarChartDataset'.
VERBOSE: Importing function 'New-UDRadio'.
VERBOSE: Importing function 'New-UDRow'.
VERBOSE: Importing function 'New-UDSelect'.
VERBOSE: Importing function 'New-UDSelectGroup'.
VERBOSE: Importing function 'New-UDSelectOption'.
VERBOSE: Importing function 'New-UDSpan'.
VERBOSE: Importing function 'New-UDSwitch'.
VERBOSE: Importing function 'New-UDTable'.
VERBOSE: Importing function 'New-UDTextbox'.
VERBOSE: Importing function 'Out-UDChartData'.
VERBOSE: Importing function 'Out-UDGridData'.
VERBOSE: Importing function 'Out-UDMonitorData'.
VERBOSE: Importing function 'Out-UDTableData'.
VERBOSE: Importing function 'Publish-UDDashboard'.
VERBOSE: Importing function 'Remove-UDCookie'.
VERBOSE: Importing function 'Set-UDContentType'.
VERBOSE: Importing function 'Set-UDCookie'.
VERBOSE: Importing function 'Update-UDDashboard'.
VERBOSE: Importing function 'Write-UDLog'.`

**Comment by TheStanzx85** [comment]
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Thanks for any help you can provide. Been stumped all morning.

**Comment by TheStanzx85** [comment]
I tried an update-module again and then running the import-module universaldashboard -verbose again
and here's what i get:

VERBOSE: Loading module from path 'C:\Program Files
(x86)\WindowsPowerShell\Modules\UniversalDashboard\1.6.1\U
niversalDashboard.psd1'.
VERBOSE: Cannot verify the Microsoft .NET Framework
version 4.7 because it is not included in the list of
permitted versions.
VERBOSE: Populating RepositorySourceLocation property for
module UniversalDashboard.
VERBOSE: Loading module from path 'C:\Program Files
(x86)\WindowsPowerShell\Modules\UniversalDashboard\1.6.1\U
niversalDashboard.psm1'.
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.At C:\Program
Files (x86)\WindowsPowerShell\Modules\UniversalDashboard\1.6.1\UniversalDashboard.psm1:10 char:3
+         Import-Module -Name "$PSScriptRoot/netstandard2.0/PowerShellP ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

VERBOSE: Exporting function 'Find-Object'.
VERBOSE: Exporting function 'Get-UDCacheData'.
VERBOSE: Exporting function 'Get-UDContentType'.
VERBOSE: Exporting function 'Get-UDCookie'.
VERBOSE: Exporting function 'Get-UDSessionData'.
VERBOSE: Exporting function 'New-UDBarChartDataset'.
VERBOSE: Exporting function 'New-UDBarChartOptions'.
VERBOSE: Exporting function 'New-UDCategoryChartAxis'.
VERBOSE: Exporting function 'New-UDChartDataset'.
VERBOSE: Exporting function 'New-UDChartLayoutOptions'.
VERBOSE: Exporting function 'New-UDChartLegendOptions'.
VERBOSE: Exporting function 'New-UDChartOptions'.
VERBOSE: Exporting function 'New-UDChartTitleOptions'.
VERBOSE: Exporting function 'New-UDChartTooltipOptions'.
VERBOSE: Exporting function 'New-UDDoughnutChartDataset'.
VERBOSE: Exporting function 'New-UDDoughnutChartOptions'.
VERBOSE: Exporting function 'New-UDLayout'.
VERBOSE: Exporting function 'New-UDLinearChartAxis'.
VERBOSE: Exporting function 'New-UDLineChartDataset'.
VERBOSE: Exporting function 'New-UDLineChartOptions'.
VERBOSE: Exporting function 'New-UDLogarithmicChartAxis'.
VERBOSE: Exporting function 'New-UDPolarChartDataset'.
VERBOSE: Exporting function 'New-UDPolarChartOptions'.
VERBOSE: Exporting function 'New-UDRadarChartDataset'.
VERBOSE: Exporting function 'Out-UDChartData'.
VERBOSE: Exporting function 'Out-UDGridData'.
VERBOSE: Exporting function 'Out-UDMonitorData'.
VERBOSE: Exporting function 'Out-UDTableData'.
VERBOSE: Exporting function 'Publish-UDDashboard'.
VERBOSE: Exporting function 'Remove-UDCookie'.
VERBOSE: Exporting function 'Set-UDCacheData'.
VERBOSE: Exporting function 'Set-UDContentType'.
VERBOSE: Exporting function 'Set-UDCookie'.
VERBOSE: Exporting function 'Set-UDSessionData'.
VERBOSE: Exporting function 'Update-UDDashboard'.
VERBOSE: Exporting function 'Write-UDLog'.
VERBOSE: Exporting function 'New-UDButton'.
VERBOSE: Exporting function 'New-UDCard'.
VERBOSE: Exporting function 'New-UDCheckbox'.
VERBOSE: Exporting function 'New-UDCollapsible'.
VERBOSE: Exporting function 'New-UDCollapsibleItem'.
VERBOSE: Exporting function 'New-UDCollection'.
VERBOSE: Exporting function 'New-UDCollectionItem'.
VERBOSE: Exporting function 'New-UDColumn'.
VERBOSE: Exporting function 'New-UDHeading'.
VERBOSE: Exporting function 'New-UDIcon'.
VERBOSE: Exporting function 'New-UDIFrame'.
VERBOSE: Exporting function 'New-UDImage'.
VERBOSE: Exporting function 'New-UDModal'.
VERBOSE: Exporting function 'New-UDParagraph'.
VERBOSE: Exporting function 'New-UDPreloader'.
VERBOSE: Exporting function 'New-UDRadio'.
VERBOSE: Exporting function 'New-UDRow'.
VERBOSE: Exporting function 'New-UDSelect'.
VERBOSE: Exporting function 'New-UDSelectGroup'.
VERBOSE: Exporting function 'New-UDSelectOption'.
VERBOSE: Exporting function 'New-UDSpan'.
VERBOSE: Exporting function 'New-UDSwitch'.
VERBOSE: Exporting function 'New-UDTable'.
VERBOSE: Exporting function 'New-UDTextbox'.
VERBOSE: Importing function 'Get-UDContentType'.
VERBOSE: Importing function 'Get-UDCookie'.
VERBOSE: Importing function 'New-UDBarChartDataset'.
VERBOSE: Importing function 'New-UDBarChartOptions'.
VERBOSE: Importing function 'New-UDButton'.
VERBOSE: Importing function 'New-UDCard'.
VERBOSE: Importing function 'New-UDCategoryChartAxis'.
VERBOSE: Importing function 'New-UDChartDataset'.
VERBOSE: Importing function 'New-UDChartLayoutOptions'.
VERBOSE: Importing function 'New-UDChartLegendOptions'.
VERBOSE: Importing function 'New-UDChartOptions'.
VERBOSE: Importing function 'New-UDChartTitleOptions'.
VERBOSE: Importing function 'New-UDChartTooltipOptions'.
VERBOSE: Importing function 'New-UDCheckbox'.
VERBOSE: Importing function 'New-UDCollapsible'.
VERBOSE: Importing function 'New-UDCollapsibleItem'.
VERBOSE: Importing function 'New-UDCollection'.
VERBOSE: Importing function 'New-UDCollectionItem'.
VERBOSE: Importing function 'New-UDColumn'.
VERBOSE: Importing function 'New-UDDoughnutChartDataset'.
VERBOSE: Importing function 'New-UDDoughnutChartOptions'.
VERBOSE: Importing function 'New-UDHeading'.
VERBOSE: Importing function 'New-UDIcon'.
VERBOSE: Importing function 'New-UDIFrame'.
VERBOSE: Importing function 'New-UDImage'.
VERBOSE: Importing function 'New-UDLayout'.
VERBOSE: Importing function 'New-UDLinearChartAxis'.
VERBOSE: Importing function 'New-UDLineChartDataset'.
VERBOSE: Importing function 'New-UDLineChartOptions'.
VERBOSE: Importing function 'New-UDLogarithmicChartAxis'.
VERBOSE: Importing function 'New-UDParagraph'.
VERBOSE: Importing function 'New-UDPolarChartDataset'.
VERBOSE: Importing function 'New-UDPolarChartOptions'.
VERBOSE: Importing function 'New-UDPreloader'.
VERBOSE: Importing function 'New-UDRadarChartDataset'.
VERBOSE: Importing function 'New-UDRadio'.
VERBOSE: Importing function 'New-UDRow'.
VERBOSE: Importing function 'New-UDSelect'.
VERBOSE: Importing function 'New-UDSelectGroup'.
VERBOSE: Importing function 'New-UDSelectOption'.
VERBOSE: Importing function 'New-UDSpan'.
VERBOSE: Importing function 'New-UDSwitch'.
VERBOSE: Importing function 'New-UDTable'.
VERBOSE: Importing function 'New-UDTextbox'.
VERBOSE: Importing function 'Out-UDChartData'.
VERBOSE: Importing function 'Out-UDGridData'.
VERBOSE: Importing function 'Out-UDMonitorData'.
VERBOSE: Importing function 'Out-UDTableData'.
VERBOSE: Importing function 'Publish-UDDashboard'.
VERBOSE: Importing function 'Remove-UDCookie'.
VERBOSE: Importing function 'Set-UDContentType'.
VERBOSE: Importing function 'Set-UDCookie'.
VERBOSE: Importing function 'Update-UDDashboard'.
VERBOSE: Importing function 'Write-UDLog'.

**Comment by adamdriscoll** [comment]
Ok. This is because of this issue: https://github.com/ironmansoftware/universal-dashboard/issues/154

Please follow the work around in there. It will be fixed in 1.6.2.
