### ISSUE TITLE
New-UDButton -IconAlignment Is not working

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/universal-dashboard#1624]
New-UDButton -IconAlignment parameter is not working, icons are currently always on the left.
Example: New-UDButton -Text "Button" -Icon cloud -IconAlignment right
UD version: 2.9.0 - potentially earlier versions too.

Linked Thread: https://forums.universaldashboard.io/t/new-udbutton-iconalignment/2670/3

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/new-udbutton-iconalignment/2670/4

**Comment by adamdriscoll** [comment]
This is fixed in PowerShell Universal 1.2 (UDv2.9.1-beta3)
