### ISSUE TITLE
[2.9.0] - ID not used in UDRow

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#1629]
#### Describe the Issue
New-UDrow does not support Sync udelement Bosen has more info here:
https://forums.universaldashboard.io/t/what-components-support-sync-udelement/2713/4

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Start Dashboard
2. Click on the Hamburger
3. Press ALT-F4
4. Browser Closes...

#### Script Sample
Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information
- **Operating System**:
- **PowerShell Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by adamdriscoll** [comment]
Fixed in PowerShell Universal 1.2 (UDv2.9.1-beta3)
