### ISSUE TITLE
Implement Azure Application Insights

### ISSUE THREAD

**Issue by Entech-Ramon** [ironmansoftware/universal-dashboard#1631]
#### Is your Enhancement request related to a problem? Please describe
Integrate performance monitoring with Azure Application Insights, server side.

#### Describe the solution you'd like
Add Application Insights nuget packages to UD.
[Base Package](https://www.nuget.org/packages/Microsoft.ApplicationInsights)
May require additional nuget packages to be installed.

#### Describe how this would improve your Universal Dashboard Quality of Life
This will allow more in-depth performance indicators to be monitored when hosted in azure app services.

#### Additional context
https://forums.universaldashboard.io/t/azure-application-insights/2719/

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/azure-application-insights/2719/8

**Comment by adamdriscoll** [comment]
This has been implemented in PowerShell Universal v1.2. You'll be able to configure your AppInsights instrumentation key in the appsettings.json.  https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core
