### ISSUE TITLE
UDGrid filter do not search within UD-Components

### ISSUE THREAD

**Issue by xcabur1** [ironmansoftware/universal-dashboard#1633]
#### Describe the Issue
I had some content with a line break but the UDGrid doesn’t show the line break. So I enclosed the content in a UDHTML and replaced the line break with '\<br/>' The line break is now displayed but the filter does not work anymore. It looks like the grid will only search for text, and not a UD-Component rendered within it.

#### To Reproduce
    New-UdGrid -Title "Test" -Endpoint {
        $content = @()
        $content += [pscustomobject]@{Test = "A" + [environment]::Newline + "B"}        
        $content += [pscustomobject]@{Test = "X" + [environment]::Newline + "Y"}        
        $content[0].Test = New-UDHTML -Markup $($content[0].Test-replace [environment]::Newline,"<br/>")
        $content | Out-UDGridData
    }
Search a --> Do not work
Search x --> Work

#### Expected behavior
UDGrid should support line breaks native or UDGrid Filter should search within UDHTML components

#### Version Information
- **Operating System**: Windows 2012 R2, Windows 10
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.9.0
- **UD Hosting Method:** Powershel

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/output-multiline-string-with-line-breaks/2742/7

**Comment by adamdriscoll** [comment]
This has been resolved in the UDv3 table component.
