### ISSUE TITLE
New-UDExpansionPanelGroup does not work with only one child

### ISSUE THREAD

**Issue by BenevolentD** [ironmansoftware/universal-dashboard#1634]
#### Describe the Issue
If an expansion panel in universal dashboard 3 beta 2 (or nightly) only has one child the entire panel is not rendered.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. add universal dashboard 3 UDExpansionPanelGroup with one child
2. Expansion panel is not rendered

#### Script Sample
This works:
```
New-UDExpansionPanelGroup -Children {
            New-UDExpansionPanel -Title "Hello" -Children {}

            New-UDExpansionPanel -Title "Hello" -Id 'expContent' -Children {
                New-UDElement -Tag 'div' -Content { "Hello" }
            }
        }

```
This does not:
```
New-UDExpansionPanelGroup -Children {
            New-UDExpansionPanel -Title "Hello" -Id 'expContent' -Children {
                New-UDElement -Tag 'div' -Content { "Hello" }
            }
        }

```

**Comment by adamdriscoll** [comment]
This has been fixed in UD 3.0.0-beta5.
