### ISSUE TITLE
Add Date/Time picker to possible inputs in New-UDInput

### ISSUE THREAD

**Issue by bielawb** [ironmansoftware/universal-dashboard#164]
At the moment most of the inputs that are useful are supported by `New-UDInputField -Type`.
One type I miss is date/time picker.

Not sure if there are any technical limitations that would prevent it, but if not - it would be great addition to the existing set of controls.

**Comment by adamdriscoll** [comment]
No technical limitation. Should be able to make it happen!

**Comment by PorreKaj** [comment]
Isn't this implemented?
New-UDInputField -Type date -Name "Startdate" -Placeholder "Start Date (00:00)"

**Comment by adamdriscoll** [comment]
Yep! Thanks for pointing this out.
