### ISSUE TITLE
Having an issue with making a custom footer after getting a Premium License

### ISSUE THREAD

**Issue by catagris** [ironmansoftware/universal-dashboard#1642]
#### Describe the Issue
Having an issue with making a custom footer after getting a Premium License.
The text and link saying "Created with Powershell Universal Dashboard" does dissappear and gets smashed together with the link that I added.

![2debee8e95c7750fc94819cab7ed4efcd93b3efe](https://user-images.githubusercontent.com/1514273/82572807-86d1c100-9b4a-11ea-82fa-20859a2e6b39.png)

#### To Reproduce
Code I used:
`Set-UDLicense -License (Get-Content "C:\*\license.txt" -Raw)`
`$Footer = New-UDFooter -Copyright "Telstar National ©2020" -Links @(`
`   New-UDLink -Text "Telstar Support" -Url "*"`
`)`
`$Nav = New-UDDashboard -Pages @($Page1, $Page2, $Page3, $Page4, $Page5) -Title "****" -NavBarColor "#ff9b3d" -BackgroundColor "#ffffff" -Navigation $Navigation -Footer $Footer`
`#Start Dashboard`
`Start-UDDashboard -Dashboard $Nav -Port 1001 -Force`

I also uninstalled Universal Dashboard and installed with this command:
`
Install-Module UniversalDashboard
`

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1.18362.752
- **Universal Dashboard Version**: Newest stable
- **UD Hosting Method**: Powershell

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/having-an-issue-with-making-a-custom-footer-after-getting-a-premium-license/2789/3

**Comment by catagris** [comment]
> This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:
> 
> https://forums.universaldashboard.io/t/having-an-issue-with-making-a-custom-footer-after-getting-a-premium-license/2789/3

I am assuming this was automatically posted?

**Comment by adamdriscoll** [comment]
@catagris - It was. This has been fixed and will be in PowerShell Universal 1.2 (UD-v2.9.0-beta3)
