### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by xtqqczze** [ironmansoftware/universal-dashboard#1652]
#### Describe the Issue

<https://docs.universaldashboard.io/> not available using HTTPS

#### To Reproduce
<https://docs.universaldashboard.io/>

#### Expected behavior
`http://docs.universaldashboard.io/ -> 200`

#### Actual behaviour
`https://docs.universaldashboard.io/ -> Error: FetchError: request to https://docs.universaldashboard.io/ failed, reason: Hostname/IP does not match certificate's altnames: Host: docs.universaldashboard.io. is not in the cert's altnames: DNS:*.gitbooks.io, DNS:gitbooks.io`

**Comment by Barokai** [comment]
just wanted to report the same, thx

**Comment by xtqqczze** [comment]
Issue is resolved, closing.
