### ISSUE TITLE
Publish-UDDashboard -Manual fails.

### ISSUE THREAD

**Issue by bielawb** [ironmansoftware/universal-dashboard#167]
Looks like code that sets parameters for sc.exe command contains a bug.

In `Publish-UDDashboard` I see this:

```powershell
$ServiceStart = 'auto'
 if ($Manual) {
    $ServiceStart = 'manual'
}
```

Help for sc.exe create:
```
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (default = demand)
```

Running `Publish-UDDashboard` with that parameter will result in an error message about incorrect sc.exe syntax.

**Comment by adamdriscoll** [comment]
This is has been resolved in the 1.6.2 release
