### ISSUE TITLE
Allow more customization with Publish-UDDashboard

### ISSUE THREAD

**Issue by bielawb** [ironmansoftware/universal-dashboard#168]
At the moment Publish-UDDashboard is very limiting in what user can get out of it.
I'd love to see few more options:
- possibility to pick service name (e.g. if I want to have multiple)
- less strict on the file name (perhaps UniversalDashboard should take a path to script as a parameter?)
- enable option to specify credentials 

At the moment I'd be tempted to just use DSC to install the service and skip publish command (except for initial, how-he-does-that, step).

**Comment by adamdriscoll** [comment]
Removing Publish-UDDashboard in favor of better documentation on how to run UD as a service.
