### ISSUE TITLE
Universal Dashboard 3.3.0 - Issue with New-UDProgress

### ISSUE THREAD

**Issue by LiquoriChris** [ironmansoftware/universal-dashboard#1680]
Hello,

I have just upgraded Universal Dashboard to version 3.3.0 and have an issue with the `New-UDProgress` function. When trying to call it, I am receiving the following error. 

```
PS C:\Windows\system32> New-UDProgress
Cannot find an overload for ".ctor" and the argument count: "1".
At C:\ProgramData\PowerShellUniversal\Dashboard\Frameworks\UniversalDashboard\3.3.0\UniversalDashboard.MaterialUI.psm1:
3185 char:9
+         [Parameter("indeterminate")]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

Thanks,

**Comment by LiquoriChris** [comment]
Looks like it is missing `ParameterSetName` for the `BackgoundColor` parameter. 

```
[Parameter("indeterminate")]
[Parameter("determinate")]
[UniversalDashboard.Models.DashboardColor]$BackgroundColor,
```

**Comment by adamdriscoll** [comment]
@LiquoriChris - Yep. That's correct. You should be able to tweak the file in <installdir>\UniversalDashboard\Frameworks\v3\UniversalDashboard.MaterialUI.psm1

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/new-uddynamic-with-loadingcomponent-new-udprogress-no-longer-works-in-1-5-11-release/4440/2

**Comment by LiquoriChris** [comment]
@adamdriscoll Yes. That is how I confirmed this is the issue. Thank you for taking a look and responding quickly.

Just want to give a shout out too with PowerShell Universal. Awesome work!

**Comment by adamdriscoll** [comment]
Thanks! Really appreciate it!

**Comment by LiquoriChris** [comment]
Confirmed working on 1.5.12. Thanks!
