### ISSUE TITLE
Splash screen made optional ?

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#17]
Let's say I would be interested in not disclosing technologies / product used. I don't think there's any way to hide the "Powershell Universal Dashboard" splash screen currently. Is it something you might consider ?

**Comment by adamdriscoll** [comment]
Sure. The main issue with hiding it now is that the splash is shown before the dashboard definition is download. That said, it's certainly possible to make the configurable.

**Comment by adamdriscoll** [comment]
This has been implemented in the upcoming 1.6.0. There will be a New-UDLoadingPage used to customize this or hide the text.
