### ISSUE TITLE
Allow for multiple datasets for Bar and Line charts to stack on top of each other.

### ISSUE THREAD

**Issue by mattcorr** [ironmansoftware/universal-dashboard#174]
We have a need to report a count of failed and passed steps within one of our processes.
It would be a nice feature to allow users to specify an optional positioning field for the `New-UDChart` function. 

At the moment, with bar charts, dataset values are shown side by side like:
![2018-05-16_12-35-40](https://user-images.githubusercontent.com/516136/40093621-6a68d888-5906-11e8-87ac-9bd6fb70577b.png)

With this feature, you would be able to display something like this:
![2018-05-16_12-35-40 copy](https://user-images.githubusercontent.com/516136/40093634-763e9224-5906-11e8-9f57-1792afc8879f.png)

Also a similar thing for line charts. At the moment all dataset values are overlapping each other.

**Comment by adamdriscoll** [comment]
This is possible. Here is an example: https://docs.universaldashboard.io/components/charts#stacked-bar-charts
