### ISSUE TITLE
Documentation update : .NET Framework requirements for Windows PowerShell

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#175]
In order to make UD work with Windows PowerShell there's a minimum .NET Framework version requirement.

On some Windows Server 2012R2 with the stock version of .NET Framework (which was in my case 4.5.51641) with whenever I launched a dashboard I got this error message:

```
Start-UDDashboard : Method not found: '!![0] System.Array.Empty()'.
```

To resolve the issue, I upgraded to .NET Framework version 4.7.02053.

Here's the code to get the .NET Framework version installed:
```PowerShell
Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\'
```

I think it should be mentioned in the documentation.
Furthermore I think you should also specify the minimum version of PowerShell and Windows PowerShell.

**Comment by apetitjean** [comment]
Perfecto 👍

**Comment by adamdriscoll** [comment]
I added a system requirements page to the documentation:
