### ISSUE TITLE
New-UDCounter : Allow to specify a locale format

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#176]
In a UDCounter there's the -Format parameter which is great to specify a Numeral.js format. 

I've an issue to display large numbers with another separator the the coma.
For instance the number '1234' is currently displayed '1,234' which is fine in the US, but in France it should be displayed this way '1 234'. How can I speficy a format right now?

I've read that Numeral.js supports locale, but I don't know how to inject that in the -Format parameter of New-UDCounter. Is that possible?

[Numeral.js Custom formats](http://numeraljs.com/#custom-formats)

**Comment by adamdriscoll** [comment]
I don't think this is possible right now but I will add it in a future release. Seems like UD could expose a bunch of locales to select from: http://numeraljs.com/#locales

**Comment by apetitjean** [comment]
Do you mean by replacing a file?

**Comment by adamdriscoll** [comment]
What I'm thinking is registering a bunch of locales with Numeral.JS and then you could do something like this from UD: 

```
New-UDCounter -Locale 'fr' ...
```

Then the number would be formatted to the proper locale. It might also be possible to do something like: 

```
New-UDCounter -DetectLocale
```

Then you could try and detect the user's locale and load the proper format.

**Comment by apetitjean** [comment]
Sounds perfect to me! 👍

**Comment by adamdriscoll** [comment]
UDCounter has been removed from v3. You can achieve the same result with UDCard and specify whatever data you like in it.
