### ISSUE TITLE
Out-ChartData : BorderWidth property is missing

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#177]
On the Chart.js library it's possible to specify the BorderWidth property but we cannot set it with UD.

Please implement this property. This way we could display nicer doughnuts and pies like this one here: https://www.chartjs.org/docs/latest/charts/doughnut.html

**Comment by adamdriscoll** [comment]
Implemented in PowerShell Universal 1.2 (UDv2.9.1-beta3)
