### ISSUE TITLE
Splash screen issue with light themed dashboard & refresh page.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#18]
There's a "visual bug" currently when you use the product with a light-colored themed dashboard. 

The process goes that way: 
F5   
Blank screen
Powershell universal dashboard DARK background splash (around 20 ms) 
White dashboard

The splash is barely noticeable on a dark themed dashboard on refresh but on a white dashboard, it is slightly harrassing.

To reproduce, create any simple dashboard with no theme applied.

**Comment by adamdriscoll** [comment]
Related to #17 - I'll make this configurable as well.

**Comment by adamdriscoll** [comment]
This has been implemented in the upcoming 1.6.0. There will be a New-UDLoadingPage used to customize this.
