### ISSUE TITLE
New-UDCheckbox -OnChange scriptblock can't retrieve all variables?

### ISSUE THREAD

**Issue by oitptobbe** [ironmansoftware/universal-dashboard#181]
```
foreach ($adgrp in $session:adgroups) {
 if ($userinfo.memberof -contains $adgrp.DistinguishedName) {
  New-UDCheckbox -Id $adgrp.Name -Label $adgrp.Name -Checked -OnChange {
   Send-UDToast -Message "I got $eventdata" -Duration 2000
   if ($eventdata) {
     Send-UDToast -Message "Added $($userinfo.samAccountName) to $($adgrp.Name)"
      #Add-ADGroupMember -Identity $adgrp.Name -members $userinfo.samAccountName
   }
   else {
     Send-UDToast -Message "Removed $($userinfo.samAccountName) from $($adgrp.Name)"
     #Remove-ADGroupMember -Identity $adgrp.Name -members $userinfo.samAccountName
    }
  }
}

```
After this comes a else where the default Checked is not set if the user is not a member of the group.
However the $adgrp.Name is empty which I can understand because the foreach has ended already. But I don't see a way to see which checkbox has been changed? $eventdata only contains a true/false statement.

![skarmavbild 2018-05-18 kl 13 34 14](https://user-images.githubusercontent.com/23454638/40232736-45e96dd8-5aa0-11e8-98f9-700d1d0ed96d.png)
![skarmavbild 2018-05-18 kl 13 34 18](https://user-images.githubusercontent.com/23454638/40232737-4604cb32-5aa0-11e8-8be1-adc7337ef723.png)

**Comment by adamdriscoll** [comment]
This can be resolved by using manual variable scoping: https://docs.universaldashboard.io/endpoints/event-handler-endpoints#manual-variable-scoping
