### ISSUE TITLE
Memory leak on dashboard background task

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#185]
I ran my dashboard for 3 days, with a for loop in a runspace, inside of an endpoint. That's the solution we discussed on skype last time for a background task. Problem is that memory leaked, and got up to 8Gb of RAM out of 16Gb.

![task manager](https://user-images.githubusercontent.com/37376232/40355671-0dba3716-5d85-11e8-96f3-bbbf81b31280.png)

**Comment by Phyziik** [comment]
How should I use it? on every iteration?

**Comment by adamdriscoll** [comment]
Try it on every iteration just to see if it would help. You should be able to limit it depending on how often you are iterating but I would just try it to see if it helps at all first.

**Comment by Phyziik** [comment]
Ran it overnight : 
![image](https://user-images.githubusercontent.com/37376232/40419330-038b849c-5e53-11e8-9441-61869fe874fd.png)
I believe it might be better, but the 8.5Gb refered to a 3 days in row run. So I would have to test it throughout the weekend to see if I go higher than 2.5Gb, or if GC maintains it there.

**Comment by Phyziik** [comment]
Oops, misclicked..!

**Comment by adamdriscoll** [comment]
Seems like it might creep up still. Do you think you could share your code that is causing this?
