### ISSUE TITLE
OnChange & OnClick Event are not working with Posh v 5.0.10586.117 ....IE, Firefox or Chrome

### ISSUE THREAD

**Issue by RCDS1** [ironmansoftware/universal-dashboard#190]
OnChange Event ....error line 200 Unable to get property '0' of undefined or null reference

import React from 'react';
import createReactClass from 'create-react-class';
import renderComponent from './render-service.jsx';
import PubSub from 'pubsub-js';
import {fetchGet} from './services/fetch-service.jsx';
import {getApiPath} from 'config';
import ReactInterval from 'react-interval';
import ErrorCard from './error-card.jsx';

export default class UdElement extends React.Component {
    constructor() {
        super();

        this.state = {
            hidden: false
        }
    }

    componentWillMount() {
        this.pubSubToken = PubSub.subscribe(this.props.id, this.onIncomingEvent.bind(this));
    }

    onIncomingEvent(eventName, event) {
        if (event.type === "removeElement") {
            this.setState({
                hidden: true
            })
        }
    }

    componentDidUpdate() {
        if (this.state.hidden) {
            PubSub.unsubscribe(this.pubSubToken);
        }
    }

    componentWillUnmount() {
        PubSub.unsubscribe(this.pubSubToken);
    }

    render() {   
        if (this.state.hidden) {
            return null;
        }
        return <UDElementContent {...this.props} />
    }
}

class UDElementContent extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            content : props.content,
            tag : props.tag,
            attributes: props.attributes,
            events: props.events,
            loading: true,
            hasError: false,
            errorMessage: ''
        }
    }

    loadData()
    { 
        fetchGet("/component/element/" + this.props.id, function(data) {
            if (data.error) {
                this.setState({
                    hasError: true, 
                    errorMessage: data.error.message
                })
                return;
            }

            this.setState({
                content: data,
                loading: false
            });
        }.bind(this));
    }

    componentDidCatch(error, info) {
        this.setState({ hasError: true, errorMessage: error.message });
    }

    componentWillMount() {
        this.pubSubToken = PubSub.subscribe(this.props.id, this.onIncomingEvent.bind(this));
        if (this.props.js) {
            $.getScript(getApiPath() + "/js/" + this.props.js, function() {
                this.setState({
                    loading: false
                })
            }.bind(this));
        }
        else {
            if (this.props.hasCallback) {
                this.loadData();
            }
            else 
            {
                this.setState({
                    loading: false
                })
            }
        }
    }

    componentDidMount() {
        if (this.state.tag === 'input' && this.state.attributes != null && this.state.attributes["type"] === 'text') {
            Materialize.updateTextFields();
        }
        
        $('.collapsible').collapsible();
        $('.modal').modal();

        if (this.state.tag === 'select') {
            $(this.refs.element).material_select(this.onUserEvent.bind(this));
        }
    }

    componentDidUpdate() {
        if (this.state.tag === 'input' && this.state.attributes != null && this.state.attributes["type"] === 'text') {
            Materialize.updateTextFields();
        }
    }

    onTextboxChanged(e) {
        var val = e.target.value;
        this.state.attributes.value = val;

        this.setState({
            attributes : this.state.attributes
        });
    }

    onCheckboxChanged(e) {
        var val = e.target.value;
        val = e.target.checked;
        this.state.attributes.checked = val;

        this.setState({
            attributes : this.state.attributes
        });

        for(var i = 0; i < this.state.events.length; i++) {
            if (this.state.events[i].event === 'onChange') {
                PubSub.publish('element-event', {
                    type: "clientEvent",
                    componentId: this.props.id,
                    eventName: 'onChange',
                    eventData: val
                });
            }
        }
    }

    componentWillUnmount() {
        PubSub.unsubscribe(this.pubSubToken);
    }

    onIncomingEvent(eventName, event) {
        if (event.type === "setState") {
            this.setState(event.state);
        }
        else if (event.type === "requestState") {
            PubSub.publish('element-event', {
                type: "requestStateResponse",
                state: this.state,
                requestId: event.requestId
            });
        } else if (event.type === "removeElement") {
            this.setState({
                hidden: true
            })
        } else if (event.type === "addElement") {

            var content = this.state.content;
            if (content == null) {
                content = []
            }

            content = content.concat(event.elements);

            this.setState({
                content
            })
        } else if (event.type === "clearElement") {
            this.setState({
                content: null
            })
        } else if (event.type === "syncElement") {
            this.loadData();
        }
    }

    onUserEvent(eventName, e) {

        var val = null;
        if (this.state.tag === 'select') {
            val = this.refs.element.selectedOptions[0].value
            eventName = 'onChange'
        }
        else {
            val = e.target.value;
            if (val != null && val.checked != null) {
                val = e.target.checked;
            }
        }

        this.state.attributes.value = val;
        this.setState(this.state);

        PubSub.publish('element-event', {
            type: "clientEvent",
            componentId: this.props.id,
            eventName: eventName,
            eventData: val
        });
    }

    render() {
        if (this.state.hidden) {
            return null;
        }

        if (this.state.hasError) {
            return <ErrorCard message={this.state.errorMessage} />
        }

        if (this.props.error) {
            return <ErrorCard message={this.props.error.message} />
        }

        if (this.state.loading) {
            return <div></div>
        }

        if (this.props.js) {
            return React.createElement(eval(this.props.moduleName + "." + this.props.componentName), this.props.props);
        }

        var children = null;
        
        if (this.state.content) {
            children = this.state.content.map(function(x) {
                if (x.type != null) {
                    return renderComponent(x, this.props.history);
                } 
                return x;
            }.bind(this));
        }

        var attributes = this.state.attributes;

        if (attributes == null) {
            attributes = {}
        }

        if (attributes.id == null) {
            attributes.id = this.props.id;
        }

        if (this.state.events != null) {
            this.state.events.map(function(event) {
                attributes[event.event] = function(e) {
                    this.onUserEvent(event.event, e);
                }.bind(this);
                return null;
            }.bind(this));
        }

        if (this.state.tag === "input") {
            if (attributes.type === "text") {
                attributes.onChange = this.onTextboxChanged.bind(this);
            }

            if (attributes.type === "checkbox") {
                attributes.onChange = this.onCheckboxChanged.bind(this);
            }
        }

        if (this.state.tag === "textarea") {
            attributes.onChange = this.onTextboxChanged.bind(this);
        }

        attributes.ref = 'element';
        attributes.key = this.props.id;

        this.element = React.createElement(this.state.tag, attributes, children);

    return [this.element, 
            <ReactInterval timeout={this.props.refreshInterval * 1000} enabled={this.props.autoRefresh} callback={this.loadData.bind(this)}/>];
    }
}

// WEBPACK FOOTER //
// ./src/app/ud-element.jsx

**Comment by RCDS1** [comment]
OnClick Code 

New-UDPage -Name "Dynamic Interfaces" -Icon bolt -Content {
     New-UDElement -Tag "div" -Id "Placeholder" 

     New-UDButton -Text "Click me" -OnClick {
         Set-UDElement -Id "Placeholder" -Content { "Dude! You clicked the button!" }
     }


    New-UDElement -Tag "ul" -Id "AListOfDateTimes" 

     New-UDButton -Text "Click me" -OnClick {
         Add-UDElement -ParentId "AListOfDateTimes" -Content {
             New-UDElement -Tag "li" -Content { (Get-Date).ToString('G') }
         }
     }
     New-UDButton -Text "I don't like dates" -OnClick {
         Clear-UDElement -Id "AListOfDateTimes"
     }
    }

**Comment by RCDS1** [comment]
OnChange Code

New-UDSelect  -Option {

                        New-UDSelectOption -Name "All" -Value 0
                        
                        New-UDSelectOption -Name "Desktop - Active Directory" -Value DAD
    
                        New-UDSelectOption -Name "Desktop - Application" -Value DAPP
    
                        New-UDSelectOption -Name "Desktop - Citrix" -Value 3
    
                    } -OnChange { 
                        Set-UDElement -Id "Placeholder" -Content { "Dude! $Eventdata You clicked the button!" }
                    }

**Comment by RCDS1** [comment]
Issue still exists in 1.6.2

![ud-newdate](https://user-images.githubusercontent.com/39102853/41058473-71033706-69b9-11e8-8779-b6a53662aba4.jpg)


    `New-UDPage -Name "Dynamic Interfaces" -Icon bolt -Content {
     New-UDElement -Tag "div" -Id "Placeholder" 

     New-UDButton -Text "Click me" -OnClick {
         Set-UDElement -Id "Placeholder" -Content { "Dude! You clicked the button!" }
     }


    New-UDElement -Tag "ul" -Id "AListOfDateTimes" 

     New-UDButton -Text "Click me" -OnClick {
         Add-UDElement -ParentId "AListOfDateTimes" -Content {
             New-UDElement -Tag "li" -Content { (Get-Date).ToString('G') }
         }
     }
     New-UDButton -Text "I don't like dates" -OnClick {
         Clear-UDElement -Id "AListOfDateTimes"
     }
    }`

**Comment by RCDS1** [comment]
@adamdriscoll  Hi Adam, any thoughts on this?

**Comment by adamdriscoll** [comment]
@RCDS1 Sorry about not responding to this. How are you hosting this dashboard? It seems like WebSockets is failing to connect.

**Comment by RCDS1** [comment]
IIS

**Comment by adamdriscoll** [comment]
Can you make sure you to this feature installed? 

![image](https://user-images.githubusercontent.com/1256531/41366590-2dfbbaa2-6f02-11e8-80a9-810d8216e0c1.png)

**Comment by RCDS1** [comment]
@adamdriscoll  That fixed it! Thanks

**Comment by petercovach** [comment]
Is WebSocket required for all UD dashboards or only those with buttons?  I have an application that has 2 UD dashboards.  One is acting as the web service; the other is the front end.  The web service dashboard is not exposed to the internet; the front end is and published on another server.  I have a web application proxy that is publishing the front end out to the internet.  Web application proxies do not currently support Web Sockets.  The dashboard that is published to the internet is a dynamic page.

**Comment by petercovach** [comment]
I am currently on 1.6.2 and I do receive the following errors:

![image](https://user-images.githubusercontent.com/33557969/42509527-d6c5acd2-8411-11e8-9d5a-14e17426b500.png)

**Comment by PorreKaj** [comment]
The documentation (https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/iis.html) should be updated to include dependencies.

**Comment by adamdriscoll** [comment]
@petercovach The functionality that requires WebSockets includes: 

- Add-UDElement
- Sync-UDElement 
- Clear-UDElement 
- Remove-UDElement
- Invoke-UDRedirect
- Show-UDModal
- Hide-UDModal
- AutoRefresh on Start-UDDashboard

@PorreKaj I've open a doc issue for this and will update it when i get a chance. 

https://github.com/adamdriscoll/universal-dashboard-documentation/issues/5

**Comment by petercovach** [comment]
@adamdriscoll Thank you for clarifying the requirements.  I was worried I was going to have to find another way to publish apps.

**Comment by adamdriscoll** [comment]
I've updated the documentation with info about enabling the WebSocket Protocol on IIS and the cmdlets that use the protocol.
