### ISSUE TITLE
New-UDModal not exported

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#193]
In v1.6.1, the New-UDModal cmdlet/function is not available. 

I think it's just a matter of editing the UniversalDashboard.psd1 manifest file.

**Comment by Phyziik** [comment]
No, it was removed on purpose. He is reworking it, with a different behavior. It will most probably be in 1.6.2, or 1.7.0.

**Comment by Phyziik** [comment]
#140

**Comment by apetitjean** [comment]
Ok, thanks @Phyziik for the info. Hence, I'm closing it.
