### ISSUE TITLE
Email exposure through /license URL (privacy concern) 

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#195]
Hi, see by yourself : https://www.poshud.com/license   
Your gmail email address  is exposed as you registered the product through it.

That is a concern to me and could be to other as I do not necessarily want to expose that possibly personal email I used to register the product.

**Comment by adamdriscoll** [comment]
Totally agree. Will take care of this in the next version.

**Comment by adamdriscoll** [comment]
This has been resolved for 1.6.2
