### ISSUE TITLE
REST API Authentication

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#20]
The proposal is to provide the ability to generate and use [JSON Web tokens](https://jwt.io/)

A new cmdlet could be defined to grant tokens. These tokens could then be used via the bearer header in HTTP requests to the REST API. 

```
Grant-UDJsonWebToken -UserName -Expiration -Claims -Certificate
```

To configure authentication, a New-UDAuthenticationMethod could be specified on New-UDRestApi. For tokens generated by UD, you could specify the certificate and allow UD to decrypt and process the tokens.

```
New-UDAuthenticationMethod -Certificate
```

UD would also be able to be configured to validate tokens against a third-party service that provided the JWTs.  

```
New-UDAuthenticationMethod -ValidateIssuerSigningKey -ValidateIssuer -ValidIssuer -IssuerSigningKey 
```

Then in order to use the key, you can just include it with the HTTP request via Invoke-RestMethod headers. 

```
Invoke-RestMethod http://localhost:10000/api/resource -Headers @{Authorization = 'bearer TOKEN' }
```

**Comment by petercovach** [comment]
That would be AWESOME!  Thank you for your  work

**Comment by bielawb** [comment]
Would love to easily use it for authorization too. Not really sure what implementation might look like, but as a minimum I would like to be able to know the user that is connecting to API.

**Comment by adamdriscoll** [comment]
This is finished and will be in the next version. I'll be pushing a beta release today or tomorrow for people to try out.
