### ISSUE TITLE
Trial license never resets

### ISSUE THREAD

**Issue by toledotown** [ironmansoftware/universal-dashboard#202]
Now that trial licenses are set to 1 hour, they do not appear to reset. Testing UD halted while reading docs since the dashboard was running. Unsure how to reset this state.

**Comment by adamdriscoll** [comment]
@toledotown You can reset the dashboard by doing a Get-UDDashboard | Stop-UDDashboard and then a Start-UDDashboard. I think the bug here is that if you are running the default dashboard, it should run forever.

**Comment by adamdriscoll** [comment]
Fixed in 1.7.0.
