### ISSUE TITLE
Microsoft Org endpoint (enhancement) and/or custom oauth endpoints. 

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#204]
Using Microsoft provider, I can connect on consumer endpoint but not on the Org endpoint 
(Through AAD)

Following message is received: 

`AADSTS90130: Application '5031111b-2118-4116-b11a-9111111111f1' (poshud-test) is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.`

It would  be nice to have Microsoft Org endpoint added at some point and / or have the ability to add custom Oauth endpoint.

**Comment by adamdriscoll** [comment]
@itfranck Yep. This is totally planned for 2.0. I will make sure that your scenario with groups works well.

**Comment by adamdriscoll** [comment]
Just finished implementing and testing this. You'll be able to put in your domain, application ID and tenant ID to enable AAD authentication. 

![image](https://user-images.githubusercontent.com/1256531/44696541-3a208b00-aa35-11e8-8aa7-1bef6fd06aff.png)

In my AAD environment, I have a group that my user is a part of. 

![image](https://user-images.githubusercontent.com/1256531/44696580-60dec180-aa35-11e8-8610-f3e4cd3e01cf.png)

That claim is added to the identity and will be available via authorization policies that have been added to UD 2.0. 

![image](https://user-images.githubusercontent.com/1256531/44696570-51f80f00-aa35-11e8-9c90-189b50b7ac04.png)

**Comment by itfranck** [comment]
I am really looking forward to test that out and live the experience 😄 
Any way you can make the UD login page itself optional ?

Multi-logins sites will of course benefit from the current login page but when one method is selected and that method depends on external login, It would be a nice touch to have the possibility to land directly on the login page (ex: https://portal.azure.com). Just a thought.

**Comment by adamdriscoll** [comment]
@itfranck Great idea! Feel free to open another issue with the details for that. It's not possible with the current design but could certainly be done.
