### ISSUE TITLE
New-UDDashboard -Scripts — ReferenceError: file is not defined - fetch-service.jsx:22

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#205]
Error with New-UdDashboard -Scripts parameter. 
CSS works as expected. 
As soon as I remove the offending parameter, dashboard work as expected. 

**Code sample** 

```
$dash = New-UDDashboard -Title "test" -EndpointInitializationScript $init -NavbarLinks $EmailLink -Theme $Theme -Footer $Footer -LoginPage $Login `
-Scripts '222.js' -Stylesheets '222.css' `
-Content { ... 
```

Here's the error: 
```
ReferenceError: file is not defined - fetch-service.jsx:22
at t.value (ud-dashboard.jsx:148)
at Array.map (<anonymous>)
at t.<anonymous> (ud-dashboard.jsx:165)
```

From the JSX : 
(seems like "file" should be "url" )
```
loadJavascript(url) {
        var jsElm = document.createElement("script");
        jsElm.type = "application/javascript";
        jsElm.src = file;
        document.body.appendChild(jsElm);
    }

```

Other details of my configuration: 
- Using 1.6.1
- deployed as a Windows Service
- SSL / custom port / login page with Microsoft provider
- **222.js** can be found in the Client folder and is available through https://Contoso:4434/222.js

**Comment by adamdriscoll** [comment]
Fixed in 1.6.2.
