### ISSUE TITLE
UDGrid Sorting Broken?

### ISSUE THREAD

**Issue by jholl016** [ironmansoftware/universal-dashboard#206]
I just recently noticed that sorting a UDGrid by clicking on the various column headers does not seem to be working correctly.  Sorting works on the first column ('Device Name' in my screenshot below), but fails to sort by any obvious method for all other columns in the grid.  For instance, in the sample image below, you'll see that I'm trying to sort on the date column.  Those are just string objects, but they're obviously not sorting alphanumerically.
![image](https://user-images.githubusercontent.com/30354773/40925595-184f3d44-67e8-11e8-9809-87fe55669028.png)

**Comment by adamdriscoll** [comment]
Are you using `ServerSideProcessing` or is this just a basic grid?

**Comment by jholl016** [comment]
Not using `ServerSideProcessing`.  Here's my element definition:
```
New-UDGrid -Title "System Summary" -Id "SummaryGrid" `
        -Headers @("Device Name", "Room Name", "Skype Account", "Heartbeat Status", "Hardware Status", "Last Report") `
        -Properties @("SRSLink", "Heartbeat.DisplayName", "Heartbeat.Alias", "Heartbeat.ResourceState", "Hardware.ResourceState", "Heartbeat.Timestamp") `
        -Endpoint { [code to build table data here] }
```

**Comment by jholl016** [comment]
I've been unable to reproduce this issue in other dashboards with a similar UDGrid definition.  How do I go about troubleshooting this on my main dashboard site that's having the issue?

**Comment by jholl016** [comment]
@adamdriscoll I just figured out what the issue is.  Sorting doesn't work on properties inside nested hashtable objects.  Display of the data still works fine, and filtering seems to work fine.  It's just sorting that breaks.  Here's a sample dashboard you can run to duplicate my issue:
```
$port = 1000
## For command line execution env
Get-UDDashboard | ?{$_.Port -eq $port} | Stop-UDDashboard


## Page Home
$Homepage = New-UDPage -Name "Home" -Icon home -Content {
    New-UDGrid -Title "Test Grid" -Id "TestGrid" `
        -Headers @("Col 1", "Col 2", "Col 3", "Col 4", "Col 5", "Hash 1", "Hash 2") `
        -Properties @("Col1", "Col2", "Col3", "Col4", "Col5", "hash.Prop1", "hash.Prop2") `
        -Endpoint {
            $tabledata = [System.Collections.ArrayList]@()
            
            $tabledata.Add(@{
                Col1 = 'A1234'
                Col2 = 'This String'
                Col3 = 'bob@email.com'
                Col4 = 'Good'
                hash = @{
                    Prop1 = '1'
                    Prop2 = 'Z'
                }
                Col5 = '2018-06-08 12:00:00'
            }) | Out-Null

            $tabledata.Add(@{
                Col1 = 'A2345'
                Col2 = 'That String'
                Col3 = 'jane@email.com'
                Col4 = 'OK'
                hash = @{
                    Prop1 = '2'
                    Prop2 = 'X'
                }
                Col5 = '2018-06-06 12:00:00'
            }) | Out-Null

            $tabledata.Add(@{
                Col1 = 'A3456'
                Col2 = 'Another String'
                Col3 = 'susan@zmail.com'
                Col4 = 'Awesome'
                hash = @{
                    Prop1 = '3'
                    Prop2 = 'Y'
                }
                Col5 = '2018-06-06 12:30:00'
            }) | Out-Null

            $tabledata | Out-UDGridData
        } -AutoRefresh -RefreshInterval 60 -FontColor "black"
}



#region Dashboard Assembly

## Create Dashboard
$dashboard = New-UDDashboard -Title "Testing UDGrid Sorting" -Pages @($Homepage)


## Start Dashboard
Start-UDDashboard -Port $port -Dashboard $dashboard

#endregion
```
Sorting works correctly on every column except for the 'Hash 1' and 'Hash 2' columns.

**Comment by jholl016** [comment]
@adamdriscoll Do you experience the same misbehavior of the sorting when running the sample code I provided?  If so, can this be addressed in a future build?

**Comment by adamdriscoll** [comment]
I'm not seeing this issue. Please reopen if you are seeing it on the latest 2.5 builds
