### ISSUE TITLE
Set-UDContentType not working properly along with $Response variable. 

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#207]
When calling an endpoint , the response type match the call type.
Set-UDContentType is being ignored. 

I have a Slack endpoint (using a POST  x-www-form-urlencoded) which needs to be answered JSON arguments. However, whether I set **$Response.ContentType** directly or use **Set-UDContentType** to set the response to JSON, the Format is not respected.

The $Response variable is set properly through the cmdlet or manual intervation but the actual response content-type ignore it. 

Here is my code and call to view the behavior: 
```
$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
Import-Module UniversalDashboard


$Endpoint = New-UDEndpoint -Url "/slack/kb" -Method "POST"   -Endpoint {
  param($Body,$Command)
  Set-UDContentType -ContentType 'application/json' 

  return @{'text'=$Response.ContentType} | ConvertTo-Json
}

$cert = ( Get-ChildItem -Path cert:\CurrentUser\My\695911118b4d29af8ffe71919eb94689ef343dda )
Start-UDRestApi  -Endpoint $Endpoint -Certificate $cert -wait
```

```
cls
$FormPost = $null
$FormPost = (Invoke-WebRequest -Uri 'https://vault.nzt.ca:4435/api/slack/kb' -ContentType 'application/x-www-form-urlencoded' -Method POST  -Body (@{FilePath = "code"; Arguments = "script.ps1" } | ConvertTo-Json))
$FormPost.RawContent
```

This is the returned **RawContent**

```

HTTP/1.1 200 OKContent-Length: 37
Content-Type: application/x-www-form-urlencoded
Date: Mon, 04 Jun 2018 21:01:08 GMT
Server: Kestrel
X-Powered-By: ASP.NET

{
    "text":  "application/json"
}

```
the $Response.ContentType was indeed set to **JSON** but actual Content-Type returned is  **application/x-www-form-urlencoded**

**Comment by itfranck** [comment]
I found a workaround until this get fixed. 
For anyone in the same situation.

Since Response Content Type match Request Content Type without consideration for assignments made through Set-UDContent and $Response.ContentType, I tried to change the RequestType once I was in the endpoint and as a result, response content type is changed properly. 

**$Request.ContentType = 'application/json'**  in the UDEndpoint endpoint send a response of type application/json even though my request was x-www-form-urlencoded 

(As mentionned in original post, set-udcontent and $Response.ContentType didn't change anything to the actual response returned)

**Comment by adamdriscoll** [comment]
If you return an IActionResult from your endpoint, you can now have control of the entire response. UD won't overwrite the content-type. 

```
New-UDEndpoint -Url '/myEndpoint' -Endpoint {
    $Response.ContentType = 'myCustomType' 
    $Result = [System.Web.Mvc.JsonActionResult]::new()
    $Result.Data = $Data 
    $Result
} 
```

**Comment by augiaugi** [comment]
@adam would be great to see this in the documentation

**Comment by adamdriscoll** [comment]
@augiaugi - I'll be doing a big doc refresh for v3 so this will be in there.
