### ISSUE TITLE
Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory

### ISSUE THREAD

**Issue by ServerCare** [ironmansoftware/universal-dashboard#212]
After updating the module from 1.5.1 to 1.6.2 my application now reports when starting:

Application startup exception: System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory NLog.Extensions.Logging.ConfigureExtensions.AddNLog(Microsoft.Extensions.Log
ging.ILoggerFactory)'.
   at UniversalDashboard.ServerStartup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime lifetime)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

What can I do to resolve this?

**Comment by adamdriscoll** [comment]
This is usually a symptom of another module bringing in a different version of the NLog assembly. 

Can you run Get-Module to the modules that are loaded?

**Comment by ServerCare** [comment]
Sure:

ModuleType Version    Name                                ExportedCommands                                                                                                                              
---------- -------    ----                                ----------------                                                                                                                              
Manifest   1.0.0.0    ActiveDirectory                     {Add-ADCentralAccessPolicyMember, Add-ADComputerServiceAccount, Add-ADDomainControllerPasswordReplicationPolicy, Add-ADFineGrainedPasswordP...                                                                                                                    
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                           
Binary     2.7.1.7    ISESteroids                         {Add-SteroidsContextMenuCommand, Add-SteroidsEditorTabCommand, Add-SteroidsLicense, Add-SteroidsTextChange...}                                
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                            
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                                     
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                     
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                                                               
Script     0.6.1.2... posh-git                            {Add-SshKey, Enable-GitColors, Get-AliasPattern, Get-GitDirectory...}                                                                         
Script     1.6.2      UniversalDashboard                  {Add-UDElement, Clear-UDElement, ConvertTo-JsonEx, Disable-UDLogging...}

**Comment by adamdriscoll** [comment]
@ServerCare Can you try running this within a PowerShell.exe console? 

Can you also check to see if you have multiple versions of UD installed?

**Comment by adamdriscoll** [comment]
Closing as I haven't heard back. Please reopen if you are still interested in getting this resolved.
