### ISSUE TITLE
New-UDImage in version 1.6.2 has not the -Path anymore.

### ISSUE THREAD

**Issue by Stephanevg** [ironmansoftware/universal-dashboard#213]
I updated today UD from 1.2 to 1.6.2
I was surprised to see that 

![image](https://user-images.githubusercontent.com/6302961/41106791-14b7bc8e-6a71-11e8-9abf-00191659d880.png)

In the background, I use 

```Powershell
New-UDDashboard -Path $path
```
When I look at syntax:

![image](https://user-images.githubusercontent.com/6302961/41106905-64e3a18c-6a71-11e8-815b-bd0b69cee672.png)

The parameter seems to have wanished. (On the help page online, in 1.6 it is still mentionned, I guess this has been removed by mistake.

**Comment by adamdriscoll** [comment]
Fixed with #373
