### ISSUE TITLE
Publish docker container with UniversalDashboard 

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#214]
Is it ok to build a docker container and publish it to docker hub that includes the UniversalDashboard module in the container as long as it doesn't include a license key?

In this case someone could docker run the container and it would run for an hour serving up a UniversalDashboard but after an hour it would stop working.

It would be possible to just download the UniversalDashboard from the powershell gallery when the container starts but I would like to include all dependencies so that I know when I have created a docker container it is a completely self contained deployable unit that will never change.

In theory I could also do this by creating my own internal docker registry but I would rather use the hosted service if possible.

**Comment by adamdriscoll** [comment]
I think that would be a great idea! Would be very cool to be able to just pull down the image and have an up and running dashboard. 

I could see that you can even include a dashboard for a particular need within the image. Then you could pull down a fully functioning dashboard to run right in a container to collect data and display data about a particular system.

**Comment by ChrisMagnuson** [comment]
Sounds good, thanks!
