### ISSUE TITLE
Add Credential Parameter to Publish-UDDashboard

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-dashboard#216]
Feature Request:

Allow `Publish-UDDashboard` to take a credential so that the resultant dashboard will be able to access network/domain content. Currently the runas has to be set manually afterwards in order for the example which I have provided for Active Directory authentication on the login page to work.

Could potentially be folded under #30

**Comment by adamdriscoll** [comment]
Removing Publish-UDDashboard in favor of better documentation on how to configure UD as a service.
