### ISSUE TITLE
Input content shrink when inside New-udlayout or new-UDRow

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#222]
Hi

When I place a 'New-UDInputField -Type 'select' ' inside a 'New-UDInput' inside a 'New-UDLayout -Columns 1 '; the width of the combobox is very limited, with no apparent option to define the width.

If the New-UDlayout is removed, the combobox width fills its parent

This means having to scroll horizontally when a line in the drop down is longer than 16-ish characters.

3 columns:
![image](https://user-images.githubusercontent.com/20628942/41439397-e4dae2ec-702a-11e8-9043-977b6b317d69.png)

1 column:
![image](https://user-images.githubusercontent.com/20628942/41439426-0a287d0c-702b-11e8-87fb-8412b6070026.png)

No Layout:
![image](https://user-images.githubusercontent.com/20628942/41439447-1dbce90c-702b-11e8-80f8-f3ee46f2c31b.png)

`New-UDLayout -Columns 1 -Content {  
        New-UDInput -Title "Standard Request Change" -Id "StandardForm" -Content {

            New-UDInputField -Type 'select' -Name 'TypeOfAction' -Placeholder 'Type of Action' -Values @("Please Select","Asset_Commisioning", "CI_Decommisioning", "CI_Restart", "CI_Configuration_Change") -DefaultValue "Please Select"

            
            } -Endpoint {
            param($TypeOfChange,$TypeOfAction)
               
            }`

Edit: Spelling and phrasing.

**Comment by artvandelay440** [comment]
This is a big one here - makes it hard to use any selects when the only choice is full width.
