### ISSUE TITLE
Endpoint script block persisting variables accross multiple calls of New-UDInput

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#223]
# Steps to reproduce
```
Get-UDDashboard | where port -eq 10000 | Stop-UDDashboard
$Dashboard = New-UDDashboard -Title "Input Quantity" -Content {
    New-UDInput -Title "Input that should have ID" -Id "TestInput" -Endpoint {
        param (
            $Quantity
        )
        Wait-Debugger
        $Var = $Quantity
    }
}
Start-UDDashboard -Port 10000 -Dashboard $Dashboard
```
- Submit the form with a Quantity of 1
- `get-runspace | where {$_.Debugger.InBreakpoint} | Debug-Runspace`
- Enter `c` to continue
- Submit the form with a Quantity of 4
- In the debug session output the value of `$Var`
   - The value is `1` not nothing

The value of `$Var` the frist time the form is submitted is set to 1 but debugging the 2nd submission we see that the value is 1 before it is assigned 4.

This feels confusing as the way the New-UDInput is written with the param block makes it feel like your declaring a function which would lead you to expect that all variable assignment performed within the function goes away unless the variables are defined globally.

The documentation on endpoints talks about how global values may not show up but it doesn't talk about this behavior.

This also seems confusing even with the normal behavior of a script block.

If I run: 
```
$Scriptblock = {param ($Quantity) $Var=$Quantity;$var}
& $Scriptblock 1
$Var
```
The execution of the script block returns 1 but the variable `$Var` remains undefined and doesn't have a value of one outside of the execution of the script block.

To work around this I could call `Remove-Variable` for a list of variables I know am going to use or I could immediately pass the parameters to another function and never do any variable assignment within the scope of the endpoint itself.

This feels awkward and at least something that needs more documentation as I have encountered bugs in my code due to variables existing that I didn't expect to exist due to them persisting across multiple submissions of `New-UDInput`.

**Comment by ChrisMagnuson** [comment]
Thinking about this more, the current behavior is as if you opened a powershell terminal, declared and assigned the values of variables that matched the names of the parameters in your New-UDInput param block, and finally copy and pasted the code from the endpoint parameter excluding the param block  into the powershell terminal.

On each subsequent run of New-UDInput you do the same thing with the already opened powershell terminal so that if you go to run New-UDInput with a parameter not set, you don't delcare that variable, but because you still have the same powershell terminal open and because your not calling a function but just assigning a variable withing that open terminal, the previous value is still present and used when you paste in the code from the endpoint parameter excluding the param block.

**Comment by adamdriscoll** [comment]
Something is wrong with the scoping and this shouldn't be happening. I will take a look at it. Thanks for reporting it.

**Comment by alaaelmahdy** [comment]
I think the issue still persist
