### ISSUE TITLE
Endpoints stop working after 20-30 minutes

### ISSUE THREAD

**Issue by JomackSilvey** [ironmansoftware/universal-dashboard#224]
[
![capture](https://user-images.githubusercontent.com/32070721/41488903-ff00c772-70bb-11e8-9a62-bd77e56d9f92.PNG)
](url)

UD Version: 1.6.1
After 20 minutes or so my dashboard no longer loads the UD cards for my page.  They are supposed to be regenerated every time the page is refreshed through the endpoints. This seems to work for a period of time and then just stops? Any idea what would cause this behavior?

**Comment by itfranck** [comment]
@JomackSilvey  
From which environment are your running it ?
From IIS ? 
If so, go into the application pool and under Process Model, set Idle Time-out (minutes) value from 20 to 0 to see if it changes anything.

**Comment by skest3qc** [comment]
I am having the same problem with 1.6.2.

My dashboard loads fine but auto refresh and pressing F5 in the browser is not working anymore.

**Comment by JomackSilvey** [comment]
@itfranck Yes, I am hosting the dashboard with IIS. I changed the idle Time-out for all thje application pools from 20 to 0, and am still experiencing the safe issue with the page not reloading my UD-Cards after 30 minutes or so.

**Comment by adamdriscoll** [comment]
This is a problem with UD. Endpoints are falling out of the cache when they shouldn't. It typically happens when they aren't used for 10 or more minutes. Can you guys try this test build to see if it resolves your issue? 

https://www.dropbox.com/s/atna39u2u26kmwc/Build.zip?dl=0

**Comment by skest3qc** [comment]
@adamdriscoll This test build works for me again.

THX

**Comment by ChrisMagnuson** [comment]
We have been running on the test build for an hour without issue, thank you!

**Comment by adamdriscoll** [comment]
Great. I hope to get this kit out by the end of the month.
