### ISSUE TITLE
Start-UDDashboard -Filepath & New-UDDashboard with endpoint parameter

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#225]
Minor enhancement request. 

Add -Endpoint parameter to New-UDDashboard so we can define endpoint associated to UDDashboard: 
`New-UDDashboard -Title 'test' -Endpoint $Endpoint1,$Endpoint2`

Combined with Start-UDDashboard -Filepath parameter, it would allow to pass the endpoint from the target file and externalize everything outside **dashboard.ps1**  except the Start parameter.

edit: 
That being said,  I could simply do an import-module to any path then use the start-uddashboard from there. My goal is to avoid "dashboard.ps1" as name since it becomes visually more confusing when i have 3-4 dashboard.ps1 tab in visual code from each small project I work in parallel.

**Comment by adamdriscoll** [comment]
PowerShell Universal organizes all the various inputs (endpoints, dashboards, scripts) into their own separate files.
