### ISSUE TITLE
IE - changes fails to appear (pages cached forever ?) 

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#226]
If developping in IE, then restarting the app pool, modifications does not appears upon refresh. 
For IE, it reuses the cached page always. 
Chrome and Firefox does not have this issue.

Steps to reproduce. 
1. Create any dashboard with an ud card.
2. load the dashboard and IE and Chrome
3. Edit PS1 to change UdCard text.
4. Restart Webapp pool 
5. Reload both browser. 

Behavior, IE displays the cached version of the page.
Chrome / Firefox displays the page properly. 

Now, i'm using mainly not IE and I know that I can enable "force refresh from server" in IE but for intent and purposes, any visitor should get the actual version of the dashboard and not the cached one...

Tested using: 
- POSHUD 1.6.2
-  Windows 10 pro (latest IE / Chrome / Firefox) 
- Deployed on IIS

**Comment by adamdriscoll** [comment]
Fixed in this commit: https://github.com/ironmansoftware/universal-dashboard/commit/a1b03819b00da0268593b05830c369b278343d19
