### ISSUE TITLE
Running New-UDInputAction -RedirectUrl "/<PathToThePageYourOn>" doesn't reload the current page

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#229]
# Issue

Running `New-UDInputAction -RedirectUrl "/<PathToThePageYourOn>"` doesn't end up reloading the page.

# Work around

To refresh the page I add `New-UDElement -Tag div -Id RedirectParent` somewhere on the page and run the following from an Endpoint when I need to refresh:

```
Add-UDElement -ParentId "RedirectParent" -Content {
            New-UDHtml -Markup @"
            <meta http-equiv="refresh" content="0; URL='/WarrantyChild'" />
"@
```

This works in Chrome and doesn't work in Firefox and probably shouldn't work in Chrome as I am not sure your technically allowed to have meta tags outside the `<head>` tag.

# Context

I can imagine a future where things like this won't be needed but right now we don't have a way to trigger another control to update its content that is sourced external to UD based on a form submission, like adding items to a cart.

In the [chat room example](https://poshtools.com/2018/02/17/building-real-time-web-apps-powershell-universal-dashboard/) this is handled by using `Add-UDElement` to some known parent and inserting the chat message in a database.

It is possible for [this line](https://github.com/ironmansoftware/ud-chatroom/blob/master/dashboard.ps1#L49) to fail in ways that would silently result in no message being written to the database but a message still being displayed on the page.

In my case instead of dealing with doing try catches and trying to keep the client side state in sync incrementally over time (all CRUD performed client side and server side with logic to validate success or failure on both sides and reconcile when one side succeeds and the other doesn't) I would rather just refresh a component when an event happens so that it pulls the data form the back end like what [this line](https://github.com/ironmansoftware/ud-chatroom/blob/master/dashboard.ps1#L12) does.

Since we don't have a way to trigger a refresh of an individual component I need to refresh the page itself.

**Comment by ChrisMagnuson** [comment]
PS, the refresh process from the backend is also expensive enough that I don't want to do something like `-AutoFresh 2` forcing it to refresh every 2 seconds so that it almost feels like it is updating when an event happens.

Setting `-AutoRefresh 1` made things almost unusable so generally having an autorefresh time that low is not a good idea.

**Comment by adamdriscoll** [comment]
We are removing New-UDINputAction in v3. You can use Invoke-UDRedirect to achieve this.
