### ISSUE TITLE
UniversalDashboard.exe analogue for linux/core

### ISSUE THREAD

**Issue by gpduck** [ironmansoftware/universal-dashboard#23]
Is there an executable that can be run for the netcore version or is that only available as a module in pwsh?  I'm trying to get a dashboard setup as a CloudFoundry application running on a linux container, but I can't figure out a command line to run to start the app.

**Comment by gpduck** [comment]
Ok, I found this: `dotnet .\PowerShellPro
Tools.UniversalDashboard.dll`, and now I'm getting `A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '.\netcoreapp2.0\'` (and the same but libhostpolicy.so on linux).  Neither of those files appear in the netcoreapp2.0 directory tree.

**Comment by adamdriscoll** [comment]
Seems like a bug. I actually haven't tried that before. I will have to look into it.

**Comment by adamdriscoll** [comment]
You know what, I just realized that there should be a UniversalDashboard.dll. You should be able to run `dotnet UniversalDashboard.dll`.

**Comment by gpduck** [comment]
I think I tried that and got an error but I'm not at a computer to reproduce.

**Comment by adamdriscoll** [comment]
Here's an example of running UD with nginx on linux: https://blog.natelab.us/running-universal-dashboard-with-ubuntu-and-nginx-with-https
