### ISSUE TITLE
Not an Issue: Is it possible to get all the servers data for each page by hosting in one server

### ISSUE THREAD

**Issue by BharathMannem** [ironmansoftware/universal-dashboard#231]
Suppose i want to collect some information from each server, Can we do it using universal dashboard? Guide me to the right path. 
I dint see an option to execute the script on server. if there is a way please do let me know.

**Comment by ChrisMagnuson** [comment]
@BharathMannem I am not sure I follow you. 

Pulling the data isn't really something UniversalDashboard handles but more of a general powershell thing and you will like get more assistance if you ask specific questions about what you data you want to pull on a site like [StackOverflow.com](StackOverflow.com).
