### ISSUE TITLE
Licensing when using containers

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#232]
We plan to be running UD inside of docker containers using code [like this](https://github.com/Tervis-Tumbler/PowerShellApplication/blob/master/PowerShellApplication.psm1#L179) to build out PowerShell based containers.

There are a couple of questions that have come up around licensing:

- Does a single server license cover a Kuberetes cluster host including all the containers on that host?
  - In this case we would license the number of hosts in the Kubernetes cluster where UD will be running
- What is the appropriate license method when using hosted Kubernetes like [Azure Kubernetes Service](https://azure.microsoft.com/en-us/services/kubernetes-service/)?
  - Would a [site license](https://poshtools.com/buy-powershell-pro-tools/buy-powershell-universal-dashboard-site-license/) cover this use case?
  - Is there any less expensive options that scale based on some form of usage?
  - Does a site license cover maintenance for a year and so would need to be purchased each year to continue to get all updates?

**Comment by adamdriscoll** [comment]
@ChrisMagnuson - Can you email me at adam[at]poshtools.com? We can chat about it and put something together that works. You're not the first to ask about container deployments so it would be good to come up with something that works for users\companies that makes more sense than the current licensing structure. 

I'm currently traveling so I might not be able to reply right away but will get back to you as soon as possible.

**Comment by apetitjean** [comment]
Adam, could you publicly communicate on that point please?

**Comment by adamdriscoll** [comment]
I've moved to a dashboard based license model to avoid defining exactly what a server is: https://ironmansoftware.com/universal-dashboard-simplified-licensing-and-support/
