### ISSUE TITLE
New-UDInput with Validate Set generates drop downs that cannot easily be tabbed through

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#234]
Normally in a html form with a drop down you can tab into the drop down and it doesn't automatically exapnd the list of options, you can then type the text of the option you want, and hit tab to proceed to the next option.

The closest workflow for filling out an html form with just a keyboard that includes a drop down in UD I have found so far is:
- `Tab` into a drop down field
  - Ignore the fact that it expanded the list of options
- Type the text of the option you want to select in lower case
  - In a validate set of capitalized states you can only type the lower case letters of the state
- Press `Enter`
- Press `Tab`
- Press `Tab`

Here is a gif showing that process:
![select state by typing](https://user-images.githubusercontent.com/2277702/41666461-94542a16-7478-11e8-8eba-aad08aaff3b0.gif)

**Comment by ChrisMagnuson** [comment]
I thought I might have a work around for this by using [MaterializeCSS's select class of `browser-default`](https://materializecss.com/select.html) but it appears UD is not using MaterliazeCSS's select.

Maybe moving to use MaterlizeCSS's select for select UD input fields could provide a resolution to this.

**Comment by adamdriscoll** [comment]
Upgraded to the latest version of Materialize and now use the materialize selects.
