### ISSUE TITLE
New-UdTable Incorrect Row Ordering

### ISSUE THREAD

**Issue by theabraxas** [ironmansoftware/universal-dashboard#24]
When setting up a New-UdTable with the below code, the page will render it in a separate order (presumably by order the queried data arrives). Any way to force a certain order or to load empty place-holders while the data is queried to ensure everything ultimately is rendered properly?

Here's the code I'm using for the table:
```
New-UdTable -Title "Server Information" -Headers @(" ", " ") -Endpoint {
        @{
            'Computer Name' = $ComputerName
            'Operating System' = Get-WmiObject -class Win32_OperatingSystem -computername $ComputerName | select-object -ExpandProperty Caption
            'Total Disk Space (C:)' = (Get-CimInstance -ComputerName $ComputerName -ClassName Win32_LogicalDisk -Filter "DeviceID='C:'").Size / 1GB | ForEach-Object { "$([Math]::Round($_, 2)) GBs " }
            'Free Disk Space (C:)' = (Get-CimInstance -ComputerName $ComputerName -ClassName Win32_LogicalDisk -Filter "DeviceID='C:'").FreeSpace / 1GB | ForEach-Object { "$([Math]::Round($_, 2)) GBs " }
            'Last Boot Time' = (Get-CimInstance -ComputerName $ComputerName -ClassName win32_operatingsystem | select-object -ExpandProperty lastbootuptime)
            'View Live Data' = New-UDLink -Text "Click Here" -Url "/computer/live/$ComputerName"
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name", "Value")
```

Here's the resulting table:
![image](https://user-images.githubusercontent.com/6147260/36614067-5296e4c2-1890-11e8-97b9-a199efe432a0.png)

**Comment by theabraxas** [comment]
It is worth noting that the ordering appears to be consistently wrong - as in it order in the same wrong way every time.

I believe the issue might be with system uptime, it appears to change the format when writing to the table: 
![image](https://user-images.githubusercontent.com/6147260/36921639-f0fbcc3e-1e19-11e8-96cf-5873f7b75507.png)

However, when viewing the data in the New-UDTable object from the above code, the date looks like this:

![image](https://user-images.githubusercontent.com/6147260/36921660-07875a72-1e1a-11e8-9a95-2e24696aadbf.png)

Additionally, when I remove that row from the table, the ordering goes back to what would normally be expected.

**Comment by rdbartram** [comment]
I got around this by defining an ordered dictionary. i.e. 

```
([ordered]@{
    'Computer Name' = $ComputerName
    'Operating System' = Get-WmiObject -class Win32_OperatingSystem -computername $ComputerName | select-object -ExpandProperty Caption
    'Total Disk Space (C:)' = (Get-CimInstance -ComputerName $ComputerName -ClassName Win32_LogicalDisk -Filter "DeviceID='C:'").Size / 1GB | ForEach-Object { "$([Math]::Round($_, 2)) GBs " }
    'Free Disk Space (C:)' = (Get-CimInstance -ComputerName $ComputerName -ClassName Win32_LogicalDisk -Filter "DeviceID='C:'").FreeSpace / 1GB | ForEach-Object { "$([Math]::Round($_, 2)) GBs " }
    'Last Boot Time' = (Get-CimInstance -ComputerName $ComputerName -ClassName win32_operatingsystem | select-object -ExpandProperty lastbootuptime)
    'View Live Data' = New-UDLink -Text "Click Here" -Url "/computer/live/$ComputerName"
}).GetEnumerator()
```

**Comment by theabraxas** [comment]
Thanks @rdbartram this worked for me! Perhaps there could be a `-Ordered` flag which would emulate this? Otherwise, maybe just a note in the docs to put it in a dictionary with the ordered remark.
