### ISSUE TITLE
Default dashboard showing instead of error.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#241]
Default dashboard is loaded instead of nothing when there's an error that prevent the proper dashboard from starting. 

For instance, the malformed statement below

`  Get-Process | Select Name,ID,WorkingSet,CPU,@{n='hidden';e={$array = 'aaaa','bbbb','cccc','dddd','eeee','ffff';$array(Get-Random -Maximum $array.count)]}} | Out-UDGridData`

in the following : 

```
$Page2= New-UDPage -Name 'home' -Content {
    New-UDCard -Title 'Debug' -Content {
        New-UDButton -Text 'Restart' -OnClick {Import-Module WebAdministration; Restart-WebAppPool 'Tempalte'}
    }
    New-UDCard -Title 'Grid' -Content {
        New-UdGrid -Title "Processes" -Headers @("Name", "ID", "Working Set", "CPU") -Properties @("Name", "Id", "WorkingSet", "CPU") -AutoRefresh  -RefreshInterval 60 -Endpoint {
            

            Get-Process | Select Name,ID,WorkingSet,CPU,@{n='hidden';e={$array = 'aaaa','bbbb','cccc','dddd','eeee','ffff';$array(Get-Random -Maximum $array.count)]}} | Out-UDGridData
     }
    }
}
```

loads the POSHUD dashboard instead of a 502.5 or other error code. 
As soon as I fix the erroneous code, my dashboard is shown but I would expect getting an error instead of the default dashboard.

**Comment by adamdriscoll** [comment]
PowerShell Universal doesn't have this behavior any more so this shouldn't be a problem.
