### ISSUE TITLE
Dynamic page - endpoint <Guid> not found - works with static page. 

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#243]
When using a dynamic page, I get an endpoint not found on my UDButton endpoint block. 

I have 2 identical pages, except one is static and the other dynamic. 
-Home2 uses a static page.
Pressing the UDButton does restart a webapp pool named "Tempalte" 
It works !
 
- Home  uses a dynamic page .
Pressing the UDButton does not perform the action and produce the following error.

signalr-clientES5-1.0.0-alpha2-final.min.js:1 Uncaught (in promise) Error: Endpoint 7219208c-612c-4d9c-9363-f4763968a14conClick not found.
    at signalr-clientES5-1.0.0-alpha2-final.min.js:1
    at e.value (signalr-clientES5-1.0.0-alpha2-final.min.js:1)
    at e.connection.onreceive (signalr-clientES5-1.0.0-alpha2-final.min.js:1)
    at WebSocket.a.onmessage (signalr-clientES5-1.0.0-alpha2-final.min.js:1)

Here is the example I used.
```

$HomePage= New-UDPage -url '/home' -Endpoint {
    New-UDCard -Title 'Debug' -Content {
        New-UDButton -Text 'Restart' -OnClick {Import-Module WebAdministration; Restart-WebAppPool 'Tempalte'}
        New-UDTextbox -Label  "$(($ClaimsPrinciple.claims | where type -like '*emailaddress' ).Value )"
    }
 
} 
$HomePage.Name = 'Home' # So it appears in the menu

$HomePage2= New-UDPage -name 'home2' -Content {
    New-UDCard -Title 'Debug' -Content {
        New-UDButton -Text 'Restart' -OnClick {Import-Module WebAdministration; Restart-WebAppPool 'Tempalte'}
        New-UDTextbox -Label  "$(($ClaimsPrinciple.claims | where type -like '*emailaddress' ).Value )"
    }
 
} 

$Dashboard = New-UDDashboard -Title 'home' -Pages $HomePage,$HomePage2 
```

Noticed using the last build found [here - Endpoints stop working after 20-30 minutes](https://github.com/ironmansoftware/universal-dashboard/issues/224), 

I am deployed on IIS using Windows 10 and the latest Chrome.

**Comment by petercovach** [comment]
I have also experienced this issue.  Do you have all you need to troubleshoot?

**Comment by adamdriscoll** [comment]
I think so. I will update this issue if I need more information.

**Comment by adamdriscoll** [comment]
@itfranck I added a test to validate this and can't reproduce. Can you see something wrong with it at all? 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.UITest/Integration/Element.Tests.ps1#L189

**Comment by itfranck** [comment]
@adamdriscoll 
Yes, I believe I found out why your test isn't working. 
You are currently testing the static page (which worked fine) instead of the dynamic one, hence why you are not getting any errors. 

The URL to browse should be 'home' ( [line 209](https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.UITest/Integration/Element.Tests.ps1#L209))
and therefore that page should have the UD-button too. 

I submitted a [pull request](https://github.com/ironmansoftware/universal-dashboard/pull/267/commits/1189977a3368b7fd2b1b7cc0e0c3e5acbccf4ce6)

**Comment by adamdriscoll** [comment]
Thanks! The test is now failing and I'll see what I can figure out.

**Comment by adamdriscoll** [comment]
@itfranck Can you test with the latest AppVeyor build? 

This test is now passing: https://ci.appveyor.com/project/adamdriscoll/universal-dashboard/builds/19888464/artifacts

![image](https://user-images.githubusercontent.com/1256531/47672318-4df08680-db77-11e8-80e8-d4b8bf1919ec.png)

I tried it locally as well and it's passing here. I'm running PSv5.1 and running in Chrome and Firefox.

**Comment by itfranck** [comment]
@adamdriscoll Using your referenced build, it works as expected. I do not have endpoint errors anymore (Firefox / Chrome / IE on PS 5.1 )
