### ISSUE TITLE
Docker Contianer ENTRYPOINT

### ISSUE THREAD

**Issue by urskog84** [ironmansoftware/universal-dashboard#246]
Hello! I am trying to get universaldasbord running in a docker contiander.

I am using a setup like this
```
FROM microsoft/powershell
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Install-Module universaldashboard -Force
RUN Install-Module SqlServer -AllowClobber -Force
RUN Install-Module Invoke-SqlCmd2 -Force
RUN Install-Module UniversalDashboard.MaterialDesign -AllowClobber -Force

ADD ./src/ /src/

SHELL ["pwsh"] 
ENTRYPOINT ./src/UDD.ps1
```

If i run the continer with
`docker run -it -p 8080:8080 <image>`
i can access the universaldasbord page 

But if a start the continer without the -it (interacetive) the continer starts. 
`docker run -p 8080:8080 <image>`
and it execute the "./src/UDD.ps1" and after execution is done the continer stops.

Please somone help me
Best regards Petter

**Comment by adamdriscoll** [comment]
Inside your UDD.ps1 script, how are you using Start-UDDashboard? You might need to use the -Wait parameter to prevent the PWSH console from terminating.

**Comment by urskog84** [comment]
Thanks adam. After adding the -Wait parameter the container runs as accepted.

```
$MyDashboard = New-UDDashboard -Title "Hello, World" -Content {
    New-UDCard -Title "Hello, Universal Dashboard" 
}

Start-UDDashboard -Port 8080 -Dashboard $MyDashboard -Wait
``` 

Start command `docker run -it -p 9090:9090 184a01b0fb75`
