### ISSUE TITLE
Dashboard monitor element with data from VMware PowerCLI shows error

### ISSUE THREAD

**Issue by csandfeld** [ironmansoftware/universal-dashboard#25]
When creating a monitor to show data from a VMware PowerCLI command an error is shown instead of the expected data.

**Error:**
```You have modified the global:DefaultVIServer and global:DefaultVIServers system variables. This is not allowed. Please reset them to $null and reconnect to the vSphere server.```

I found [an issue](https://github.com/RamblingCookieMonster/Invoke-Parallel/issues/22) logged for Warren Frames 'Invoke-Parallel' function that show the same error, with a comment suggesting a [possible fix](https://github.com/RamblingCookieMonster/Invoke-Parallel/issues/22#issuecomment-297233420).

**Sample Dashboard:**
```PowerShell
Param(
    [string] $VIServer,
    [pscredential] $Credential
)

Import-Module -Name UniversalDashboard, VMware.VimAutomation.Core
[void](Connect-VIServer -Server $VIServer -Credential $Credential)

Start-UDDashboard -Port 1000 -AutoReload -Content {
    New-UDDashboard -Title 'Test Dashboard' -Content {
        New-UDMonitor -Title 'Test Monitor' -Type Line -DataPointHistory 30 -RefreshInterval 10 -Endpoint {
            (Get-Datastore | Measure-Object -Property FreeSpaceGB -Sum).Sum | 
            Out-UDMonitorData
        }
    }
}
```

**Module versions:**
```
Version       Name                            
-------       ----                            
1.4.2         UniversalDashboard              
6.5.2.6234650 VMware.VimAutomation.Core       
```

**PowerShell Version:**
```
Name                           Value                                                                                
----                           -----                                                                                
PSVersion                      5.1.16299.248                                                                        
PSEdition                      Desktop                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                              
BuildVersion                   10.0.16299.248                                                                       
CLRVersion                     4.0.30319.42000                                                                      
WSManStackVersion              3.0                                                                                  
PSRemotingProtocolVersion      2.3                                                                                  
SerializationVersion           1.1.0.1 
```

**Comment by adamdriscoll** [comment]
Moving this to the 1.6.0 release because this is going to require a feature to be implemented to OutOfProc the runspace (the work around you suggested) in order to get this to work. I couldn't find a better solution without doing this.

**Comment by csandfeld** [comment]
No worries - thank you for the update

**Comment by devonfury** [comment]
I am also having an issue with PowerCLI.  I am importing the appropriate VMWare modules in the EndpointInitializationScript parameter, however when the dashboard runs I get:  Get-VM cmdlet was found, but the module could not be loaded error.

$dashboard = New-UDDashboard -Title 'VM Finder' -Content {                   
    New-UDRow {
        New-UDColumn -Size 12 {
            New-UDInput -Title "VM Name" -Content {
                New-UDInputField -Type textbox -Name "VMName" -Placeholder 'VM Name'                    
            } -Endpoint {
                param([string]$VMName)
                $myVM = Get-VM -Name $VMName -ErrorAction SilentlyContinue
            }                
        }
    }
    
    New-UDRow {
        New-UDColumn -Size 12 {
            if($myVM -ne $null)
            {
                New-UDInputAction -Content @(
                    New-UDGrid -Title $Name -Headers @('Name','PowerState','CPUs','RAM') -Properties @('Name','PowerState','NumCpu','MemoryGB') -Endpoint {
                        $myVM | Out-UDGridData
                    }                    
                )
            }             
        } 
    }                
} -EndpointInitializationScript {
    Import-Module VMware.VimAutomation.Core
    
    $vCenters = @(
        'vcenter-01',
        'vcenter-02',
        'vcenter-qa-01'
    )
    
    Connect-VIServer $vCenters | Out-Null
}

Start-UDDashboard -Dashboard $dashboard -Port 1000

**Comment by PowerShellCrack** [comment]
I am having the same issue. I have tried adding all these options as well:
```
New-UdRow {
                    New-UdColumn -Size 12 {
                        New-UdGrid -Title "VM's" -Headers @("Name", "State", "CPU", "Memory") -Properties @("Name", "PowerState", "Num CPUs", "MemoryGB") -AutoRefresh -RefreshInterval 60 -Endpoint {
                            #login to Vcenter
                            Import-Module VMware.PowerCLI
                            $global:DefaultVIServer = $null
                            $global:DefaultVIServers = $null
                            Disconnect-VIServer * -Confirm:$false | Out-Null
                            Set-PowerCLIConfiguration -DefaultVIServerMode Multiple -Scope User -ParticipateInCEIP $false -Confirm:$false | Out-Null
                            Connect-VIServer -Server 'vcenter01.domain.org' -User 'serviceaccount@domain.org' -Password 'SecurePassword'
                            Get-VM | Out-UDGridData
                        }
                    }
                }
```

but I get an error:  

> An item with the same key has already been added. 

If I change the Import-module command 
`Import-Module -Name "VMware.VimAutomation.Core"`
 I get:

> The specified mount name 'vis' is already in use

....but then after a 60 minute refresh minutes its changes to 

> You have modified the global:DefaultVIServer and global:DefaultVIServers system variables. This is not allowed. Please reset them to $null and reconnect to the vSphere server.

**Comment by Deurnieur** [comment]
Any update ?

**Comment by oitptobbe** [comment]
There is a workaround this.
https://forums.universaldashboard.io/t/work-with-vmware-vcenter-connections/198
