### ISSUE TITLE
PoshUD.com Demo site is not loading data

### ISSUE THREAD

**Issue by jawn** [ironmansoftware/universal-dashboard#250]
Go to https://www.poshud.com/Home

Expected result: dashboard shows data 

Actual result: dashboard site does not load data

![image](https://user-images.githubusercontent.com/1705112/42151671-0afbfff4-7dde-11e8-8b62-1435cdfe3c22.png)

**Comment by jawn** [comment]
The javascript console in Chrome shows the following error:

GET https://www.poshud.com/component/element/a0090fa8-59ba-4456-83a4-31d5ea591f41 404 (Not Found)

**Comment by acr-varonis** [comment]
@adamdriscoll I hate to be that guy but is there an ETA for the 1.7.0 ?
I am working on a dashboard for my job and the "disappearing" endpoint is a show stopper.

Thanks.

**Comment by adamdriscoll** [comment]
Shooting for July 9th
