### ISSUE TITLE
when referencing cache: variables, incorrect data is sometimes represented

### ISSUE THREAD

**Issue by dukeofcool199** [ironmansoftware/universal-dashboard#252]
when attempting to use scheduled endpoints to alleviate stress on element endpoints sometimes the data seems to get corrupted. 
ex: the counter element refreshes every ten seconds. its only job is to retrieve a number from a cache:  variable, when this refreshes sometimes it will show the correct value, 0, or it will have another digit appended to it.

not sure if this means anything:
the script that actually creates the value takes longer than 4 mins to run and is running within a scheduled endpoint

**Comment by adamdriscoll** [comment]
We use the cache for many tests, including scheduled endpoint tests, in v3 and are not running into problems. Going to close this issue as it is probably stale.
