### ISSUE TITLE
Add cmd to manage the navbar

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#253]
Can you add commands to manage the navbar like new-udnavbar and new-udnavbaroptions so we can set materialize css class's on it for example 
Hide the navbar , make the navbar extended..

**Comment by acr-varonis** [comment]
+1

**Comment by ArtisanByteCrafter** [comment]
Any docs on how to do this?

**Comment by adamdriscoll** [comment]
@ArtisanByteCrafter - https://docs.universaldashboard.io/components/navigation

I need to start putting the links to the docs in the release notes. Sorry about that.

**Comment by ArtisanByteCrafter** [comment]
no worries!
