### ISSUE TITLE
Add "file" type support to New-UDInputField

### ISSUE THREAD

**Issue by acr-varonis** [ironmansoftware/universal-dashboard#254]
I would like to be able to upload a CSV file and digest its input and preform an action based on it.
In order to do that I would need an `<input type="file"> `

Thanks.
-AR

**Comment by H4nYolo** [comment]
would be awesome to have this functionality.

**Comment by psDevUK** [comment]
This would be a great feature to add to upload files

**Comment by psDevUK** [comment]
Thanks for adding this in latest release, I will try to implement this now
