### ISSUE TITLE
New-UDGrid DateTimeFormat not working

### ISSUE THREAD

**Issue by skest3qc** [ironmansoftware/universal-dashboard#258]
Hi Adam,

it seems that DateTimeFormat parameter is not working since 1.6:

`
$Data = @(
    (Get-ChildItem -Path C:\TEMP) | Select-Object Name, LastWriteTime 
)

$Dashboard = New-UDDashboard -Title "DateTimeFormat Test" -Content {
    New-UDGrid -Title "DateTimeFormat Test" -Headers @("Name", "LastWriteTime") -Properties @("Name", "LastWriteTime") -Endpoint {
        $Data | Out-UDGridData
    } -DateTimeFormat "LLLL"
}

Start-UDDashboard -Dashboard $Dashboard -Port 10000

`

**Comment by fvanroie** [comment]
I'm having the same issue
