### ISSUE TITLE
Adding Attributes that start with the letters 'on' does not work.

### ISSUE THREAD

**Issue by acr-varonis** [ironmansoftware/universal-dashboard#259]
When i'm trying to add attributes to an A tag that start with the word on fails 
Example: `New-UDElement -Tag A  -Attributes @{onclick = 'kaboom'} -Content {'IAMME'}` - Fail!

This works
Example: `New-UDElement -Tag A  -Attributes @{o1nclick = 'kaboom'} -Content {'IAMME'}` - Works!

I even tried other make up stuff for example 
`New-UDElement -Tag A  -Attributes @{onmydeadbody = 'kaboom'} -Content {'IAMME'}` - Fail!
`New-UDElement -Tag A  -Attributes @{omydeadbody = 'kaboom'} -Content {'IAMME'}` - Works

Let me know if you have any questions.
-ACR.

**Comment by adamdriscoll** [comment]
@acr-varonis How is this failing for you? I wrote a test to validate this and it looks like its working: https://github.com/ironmansoftware/universal-dashboard/commit/98ca7aa9b6c4fb3ed5469eea9e452e7cd9fd384f

**Comment by acr-varonis** [comment]
@adamdriscoll  i ran this
`Get-UDDashboard | Stop-UDDashboard
 
$dashboard = New-UDDashboard -Title "PowerShell Universal Dashboard" -Content {
    New-UDElement -Tag A -Id "element" -Attributes @{onclick = 'kaboom'} -Content {'IAMME'}
}

Start-UDDashboard -Port 10001 -Dashboard $dashboard `

when checking the source using chrome's Dev tools the element looks like this
`<a id="element">IAMME</a>`
as you can see the onclick is missing

**Comment by adamdriscoll** [comment]
Ah, I see. I thought you were getting an error.

**Comment by adamdriscoll** [comment]
This is an issue with react itself. You can add arbitrary attributes since react 16.0.0 but it does not output attributes that start with on. I would open an issue on the react GH page if you want to see this implemented.
