### ISSUE TITLE
New-UDTable not using RefreshInterval

### ISSUE THREAD

**Issue by BryanDM** [ironmansoftware/universal-dashboard#26]
I'm having an issue with New-UDTable. It does not appear to be using the -RefreshInterval set. I have it set to 60 seconds (example below) but the script inside the endpoint block is running non stop. I can post the endpoint script if needed.

New-UDTable -Title "Offline Servers" @Colors -Headers @("System Name", "Offline For:") -AutoRefresh -RefreshInterval 60 -Endpoint { }

**Comment by BryanDM** [comment]
It's also worth noting, i'm using the exact same endpoint script within a New-UDGrid and am not experiencing this issue.

**Comment by adamdriscoll** [comment]
This was resolved in the 1.6.1 release. If you can still reproduce, please feel free to reopen this.
