### ISSUE TITLE
Typed and Cache Scoped variables don't seem to work correctly

### ISSUE THREAD

**Issue by ghjlr** [ironmansoftware/universal-dashboard#263]
I'm trying to load XML data into a cache scoped variable and it doesn't seem to work correctly. Here is what I'm doing:

$cache:data = [xml](Get-Content C:\Path\to\file.xml)

New-UDCounter -Title "Test" -Endpoint {
   ($Cache:data.SelectNodes("//data/xpath")).Count
}

It works fine when I remove the cache scope.

**Comment by adamdriscoll** [comment]
I can't reproduce this. I added a test to validate this works. Can you give me some more information about browser, PS version etc? 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.UITest/Integration/Cache.Tests.ps1#L22

**Comment by ghjlr** [comment]
Browser: IE 11 and Chrome 67
PS Version: 5.1
