### ISSUE TITLE
Microsoft Edge - Object doesn't support property or method 'updateTextFields'

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#265]
This specific message 
Object doesn't support property or method 'updateTextFields' is shown 

From all the tested browsers (Microsoft Edge / Firefox / Chrome / IE ), only Microsoft Edge did produce the issue at this time. 
 

Sample to reproduce the issue. 
```
Import-Module universaldashboard
Get-UDDashboard | Stop-UDDashboard
$dasg = New-UDDashboard -Content {
New-UDCard -Title 'test' -Content {
    New-UDTextbox -Placeholder 'hey' -Label 'hello' 
    
    }
} -Title 'aa'

Start-UDDashboard -Name 'dd' -Dashboard $dasg -Port 8082
```

**Comment by adamdriscoll** [comment]
https://www.powershellgallery.com/packages/UniversalDashboard/2.0.0-beta2

**Comment by itfranck** [comment]
It does it. 
However, when I load the page, it loads fine.
If I it refresh, then it shows immediately. 

Additionally, I replaced the New-UDTextbox line by : 
New-UDTextbox -Placeholder "hey UD V$((get-module | where Name -EQ UniversalDashboard).Version.ToString())" -Label 'hello' 

and now it does it every single time. 
Maybe you want to replace that line to see if it changes something. 

https://i.imgur.com/GYkvZ4K.gif


Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
With latest UniversalDashboard Beta 2

-------------- Console log

HTML1300: Navigation occurred.
home (1,1)

 HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
home (8,5)

 HTML1521: Unexpected "/body>" or end of file. All open elements should be closed before the end of the document.
home (9,84)

 Information: Normalizing '/dashboardhub' to 'http://localhost:8082/dashboardhub'

 TypeError: Object doesn't support property or method 'updateTextFields'

 Information: WebSocket connected to ws://localhost:8082/dashboardhub?id=0166d909-55cf-4a7c-b4cc-488c5d16d05d

 Information: Using HubProtocol 'json'.

 Unhandled promise rejection Error: Cannot send data if the connection is not in the 'Connected' State
