### ISSUE TITLE
Floating Action Button

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#268]
Great feature to add would be the floating action button 

[https://materializecss.com/floating-action-button.html](url)

**Comment by acr-varonis** [comment]
@mylabonline  a floating button already exists in UD.
you can create it using this command:
`New-UDButton` -Floating -Icon plus`

you can find more info here
[](https://www.poshud.com/Button)

**Comment by AlonGvili** [comment]
In materialize the Floating action button is stuck on the buttom right cornner of the screen, and when it clicked it open a mini menu on top of it.

**Comment by mylabonline** [comment]
Yes, the floating action button where it pops out the menu to select other options (Horizontal & Click-only FAB) would be a great feature.

Thanks!

**Comment by BryanDM** [comment]
I have created this using New-UDElement. I'll post the functions below if you would like to use them. 

@adamdriscoll I tried to model this after everything else in ud-controls, but i'm open to suggestions on how to improve it.
```
function New-UDFab {
    param(
        [Parameter()]
        [string] $Id = (New-Guid),
        [Parameter(Mandatory = $true, Position = 0)]
        [ScriptBlock]$Content,
        [Parameter()]
        $ButtonColor,
        [Parameter()]
        $Icon,
        [Parameter()]
        [ValidateSet("Small", "Large")]
        $Size = "Large",
        [Parameter()]
        [Switch]$Horizontal,
        [Parameter()]
        [ScriptBlock]$onClick
    )
    
    if ($Horizontal) {
        $direction = "horizontal"
    }


    New-UDElement -Tag "div" -Attributes @{class = "fixed-action-btn $direction"} -Content {
        New-UDElement -Tag "a" -Attributes @{class = "btn-floating btn-$Size $ButtonColor"; onClick = $onClick} -Content {
            New-UDElement -Tag "i" -Attributes @{class = "$Size material-icons"} -Content {
                $Icon
            }  
        }
        New-UDElement -Tag "ul" -Content $Content
        
    }

}
```


```
function New-UDFabButton {
    param(
        [Parameter()]
        [string] $Id = (New-Guid),
        [Parameter()]
        $ButtonColor,
        [Parameter()]
        $Icon,
        [Parameter()]
        [ValidateSet("Small", "Large")]
        $Size = "Large",
        [Parameter()]
        [ScriptBlock]$onClick
    )

    New-UDElement -Tag "li" -Content {
        New-UDElement -Tag "a" -Attributes @{class = "btn-floating btn-$Size $ButtonColor"; onClick = $onClick} -Content {
            New-UDElement -Tag "i" -Attributes @{class = "$Size material-icons"} -Content {
                $Icon
            }
        }
    }
}
```


And an Example:

```
New-UdFab -Icon "add" -Size "large" -ButtonColor "red" -onClick {
        Send-UDToast "from Main Button"
    } -Content {
        New-UDFabButton -ButtonColor "green" -Icon "edit" -size "small"
        New-UDFabButton -ButtonColor "yellow" -Icon "delete" -size "large" -onClick {
            Send-UDToast "Execute onClick Action!"
        }
    }
```

![fab](https://user-images.githubusercontent.com/36564688/44430187-ec54e000-a567-11e8-927d-530aad80a0d0.png)

**Comment by adamdriscoll** [comment]
@BryanDM That's awesome!! I can get those into the code base and out in the next version. Looks great.

**Comment by mylabonline** [comment]
Hey @BryanDM - DId you get your onClick to work? I pasted your code directly into a new UD Page the action button works great but the click event does not.

**Comment by PorreKaj** [comment]
@mylabonline I'm in the same situation, I remember seeing something about Websockets being needed for OnClick Event, but I cant find any official docs on it, It was in the Gitter chat some time ago.

The documentation really could need an update.

**Comment by BryanDM** [comment]
What version of UD are you guys running? What about PowerShell? 

I'm using UD: 1.7.0 and PS: 5.1.16299.251 and am not having any trouble with onClick. I'm currently running it from PowerShell ISE or on IIS and have not had issues. Can you post the code your using?

I tested the following a few minutes ago and it's working.

```
function New-UDFab {
    param(
        [Parameter()]
        [string] $Id = (New-Guid),
        [Parameter(Mandatory = $true, Position = 0)]
        [ScriptBlock]$Content,
        [Parameter()]
        $ButtonColor,
        [Parameter()]
        $Icon,
        [Parameter()]
        [ValidateSet("Small", "Large")]
        $Size = "Large",
        [Parameter()]
        [Switch]$Horizontal,
        [Parameter()]
        [ScriptBlock]$onClick
    )
    
    if ($Horizontal) {
        $direction = "horizontal"
    }


    New-UDElement -Tag "div" -Attributes @{class = "fixed-action-btn $direction"} -Content {
        New-UDElement -Tag "a" -Attributes @{class = "btn-floating btn-$Size $ButtonColor"; onClick = $onClick} -Content {
            New-UDElement -Tag "i" -Attributes @{class = "$Size material-icons"} -Content {
                $Icon
            }  
        }
        New-UDElement -Tag "ul" -Content $Content
        
    }

}

function New-UDFabButton {
    param(
        [Parameter()]
        [string] $Id = (New-Guid),
        [Parameter()]
        $ButtonColor,
        [Parameter()]
        $Icon,
        [Parameter()]
        [ValidateSet("Small", "Large")]
        $Size = "Large",
        [Parameter()]
        [ScriptBlock]$onClick
    )

    New-UDElement -Tag "li" -Content {
        New-UDElement -Tag "a" -Attributes @{class = "btn-floating btn-$Size $ButtonColor"; onClick = $onClick} -Content {
            New-UDElement -Tag "i" -Attributes @{class = "$Size material-icons"} -Content {
                $Icon
            }
        }
    }
}

$dashboard = New-UDDashboard -Title "test" -Content {

    New-UDRow {
        New-UDColumn -Size "12" {
        
            New-UdFab -Icon "add" -Size "large" -ButtonColor "red" -onClick {
                Send-UDToast "from Main Button"
            } -Content {
                New-UDFabButton -ButtonColor "green" -Icon "edit" -size "small"
                New-UDFabButton -ButtonColor "yellow" -Icon "delete" -size "large" -onClick {
                    Send-UDToast "Execute onClick Action!"
                }
            }

        }
    
    }
}

Start-UDDashboard -Dashboard $dashboard
```

The only issue I had with the above was the icons not showing, which requires the following code inserted somewhere in the page. I believe this is just temporary as Adam is changing it over to use the UD FontAwesome icons instead of Google's Material Icons, which i'm currently using.

`New-UDElement -Tag "link" -Attributes @{ href = "https://fonts.googleapis.com/icon?family=Material+Icons"; rel = "stylesheet" } `

**Comment by mylabonline** [comment]
I copied and pasted your code from above into a new PS window and the onClick does not work. I'm running UD 1.7.0 and PSVersion 5.1.17134.228. I also tried with UD 2.0-beta with no luck :(

Later today I will try in an Azure Web App and IIS server

**Comment by ArtisanByteCrafter** [comment]
@BryanDM This is great! Would it be a possibility be able to add a -Text parameter to show to the side what each Fab Button icon does prior to clicking it?
