### ISSUE TITLE
Tree view component for files and folder

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#274]
https://github.com/storybooks/react-treebeard

I think it will be cool component to ud.

**Comment by AlonGvili** [comment]
I just see your blog post 
https://poshtools.com/2018/07/21/creating-universal-dashboard-components-part-1/
dude your the man 
THANK YOU!

and thank you for all the time and effort that u put on this project

**Comment by adamdriscoll** [comment]
This has been implemented. Will be writing up the part 2 of that blog post this week.
