### ISSUE TITLE
Add watermark to a New-UDCard

### ISSUE THREAD

**Issue by damienvanrobaeys** [ironmansoftware/universal-dashboard#279]
First many thanks for your work, it's awesome.

Maybe this is me, i may missed something, but I'm trying to add an icon to a Card and have some issue.
According to [this link ](https://github.com/adamdriscoll/universal-dashboard-documentation/blob/master/api/1.6.0/New-UDCard.md), to add an icon to a UDCard there is a switche -watermark.

I used it like this : New-UDCard  -Title "Welcome" -Text "toto" -Watermark cog

However in my report, it indicates that a watermark parameter can't be found.

Many thanks for your help.

**Comment by adamdriscoll** [comment]
This is making a comeback in 2.0. It got removed some how but is already back in the code base. https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Controls/src/card.ps1#L37

**Comment by damienvanrobaeys** [comment]
Many thanks for the quick answer Adam
