### ISSUE TITLE
New-UDInputField Validate Text in textbox/textarea

### ISSUE THREAD

**Issue by pldmgg** [ironmansoftware/universal-dashboard#282]
Add validation for text entered into the input field types textbox and textarea.

**Comment by pldmgg** [comment]
Just wanted to leave a note here...

I think this is something I want to take on and contribute to this project (although I might not get to it for a few weeks).

I've made several different forms (`New-UDInput`) for different UD Modules that I'm working on, and I've been doing some pretty ugly if/else/elseif statements to validate how certain fields should/shouldn't interact with each other, so I was thinking I could implement some kind of syntax similar to CmdletBinding Parameter Sets used in PowerShell functions to make things a bit more readable.

**Comment by artvandelay440** [comment]
I ended up doing the same ugly if/else route. At first I did parameter validations, but I never got it where the toast could be customized to throw a custom error instead of the native PS ones. Interested very much in this feature.

**Comment by DillonHansen71** [comment]
This would be an amazing feature. I'm trying to build a form with New-UDInputField and tried the validate switch and the form never finishes validating. For now I will be building forms with New-UDInput.
