### ISSUE TITLE
New-UDInputAction Conflicting With Each Other

### ISSUE THREAD

**Issue by pldmgg** [ironmansoftware/universal-dashboard#284]
I just wrote a function to stand up a new Dashboard that has this issue:

https://github.com/pldmgg/misc-powershell/blob/master/UDProjects/Testing/Get-CustomPUDIATest.ps1

The Dashboard has 4 pages - Home, ServerReporting, NetworkMonitor, and Metrics.

Both the ServerReporting and NetworkMonitor pages use `New-UDInputAction`.

When I create a new Dashboard with all 4 pages...

```powershell
[Sytem.Collections.ArrayList]$Pages = @()
...
$null = $Pages.Add($HomePage)
...
$null = $Pages.Add($ServerReportingPage)
...
$null = $Pages.Add($NetworkMonitorPage)
...
$null = $Pages.Add($MetricsPage)
...
$MyDashboard = New-UDDashboard -Pages $Pages
```

...the `$NetworkMonitorPage` works, but the `$ServerReportingPage` complains about the value provided to the `-Content` parameter being an empty array when I hit the 'Submit' button. (The only time that the  `-Content` parameter is an array in my code is with the `New-UDInputAction` function, so I'm guessing that's where the issue is).

However, if I simply remove `$NetworkMonitorPage` from the `$Pages` ArrayList (or never add it in the first place by commenting out that line), then the `$ServerReportingPage` works without issue.

Somehow `New-UDInputAction` for `$NetworkMonitorPage` is stomping on `New-UDInputAction` for `$ServerReportingPage` (or visa versa)...

Thoughts?

**Comment by adamdriscoll** [comment]
The ID field is what is used to store the Endpoint for the `New-UDInput` so even though those two inputs are on different pages, one endpoint is overwriting the other. The simple workaround here would be to use different IDs for the inputs. This should really be, at minimal, a warning in UD to provide some feedback that this is happening.

**Comment by pldmgg** [comment]
Awesome, thanks Adam!

**Comment by pldmgg** [comment]
@adamdriscoll Good to know. I think I'm probably going to run into that for the project I'm currently working on.

**Comment by adamdriscoll** [comment]
Pages in v3 are now all dynamic. If you have 2 pages with the same UDForm (new lingo for UDInput in v3) ID, they won't conflict because once one page unloads and the next one loads it will remove and add the new UDForm. If you have 2 UDForms with the same ID on the same page, you will have this problem but I'm going to say that is expected behavior.
