### ISSUE TITLE
Documention for all the build in veriables

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#285]
I could not find any docs on all the buildin veriables that ud create , or i dont know how to search :unamused:

**Comment by adamdriscoll** [comment]
@AlonGvili Is this what you're looking for? https://docs.universaldashboard.io/endpoints/variables-defined-in-endpoints

**Comment by AlonGvili** [comment]
I think ud have more buildin veriables no?

**Comment by adamdriscoll** [comment]
There are some additional variables that are set but kind of for internal use. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Execution/ExecutionService.cs#L95

The other variables that will be set will be any of the parameters or scope variables for the endpoint. I think some documentation is missing around additional variables for UDGrid. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Controllers/ComponentController.cs#L182

**Comment by AlonGvili** [comment]
Thanks

**Comment by adamdriscoll** [comment]
I added documentation for the UDGrid variables. Closing this issue.  https://docs.universaldashboard.io/components/grids
