### ISSUE TITLE
Restarting UDDashboard caused it to break

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#298]
After a couple of reloading of the dashboard, it stops working.

![image](https://user-images.githubusercontent.com/9411143/43860986-52f6497e-9b0a-11e8-903c-b395e08e7c84.png)

I have a feeling that it's a Session issue. (i don't know why)

UDLogging stops working as well in this state. I have to reboot the entire PC for it to work again.

**Comment by mkellerman** [comment]
sometimes i get:
```
Start-UDDashboard : An item with the same key has already been added.
```

And Get-UDDashboard doesn't show the loaded dashboard.

**Comment by nelsonsiva** [comment]
Start-UDDashboard : Failed to bind to address http://0.0.0.0:10000: address already in use
Tied Get-UDDashboard | Stop-UDDashboard
Still getting the same error
![Start-UDDashboard_Error](https://user-images.githubusercontent.com/44152635/65936439-3500ed00-e43a-11e9-9844-3fce6665ecd5.jpg)

**Comment by adamdriscoll** [comment]
The web server is now part of PowerShell Universal and starts a separate process. https://ironmansoftware.com/ud-ua-powershell-universal/
