### ISSUE TITLE
Possible to call function only once on page load for UDChart and UDGridData with AutoRefresh

### ISSUE THREAD

**Issue by skest3qc** [ironmansoftware/universal-dashboard#3]
Hi,

I am using an UDChart and UDGridData with AutoRefresh

Both are running the same function (Get-Compliance)  to display data in the chart and grid. 

Is it somehow possible to call the function only once, for both, but to get also AutoRefresh to work?

Because now I am using it like so:

Get-Compliance | Out-UDGridData
Get-Compliance | Out-UDChartData

I could call the function on top of the UDPage, but how should I do it for AutoRefresh?

Thanks

**Comment by adamdriscoll** [comment]
This would be a good place to take advantage of server side caching. It's been in the backlog for awhile but hasn't be fleshed out.

**Comment by adamdriscoll** [comment]
We are going to implement this via a set of "SharedData" cmdlets that will allow you to create and cache data in a very simple way and use it between multiple endpoints. The initial dev is done but will be testing and finishing up the feature for 1.6.0.

**Comment by adamdriscoll** [comment]
Shared data is implemented in 1.6.0.
