### ISSUE TITLE
Publish-UDDashboard

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#30]
Should support a couple options:

- [x] Publish as a stand alone service
- [ ] Publish to Azure (#1041)
- [ ] Publish to IIS (#1040)
- [ ] Publish as docker container

**Comment by adamdriscoll** [comment]
UniversalDashboard.exe can be used as the service executable.

**Comment by ducke** [comment]
Maybe docker is also an option

**Comment by adamdriscoll** [comment]
Removing Publish-UDDashboard in favor of better documentation on how to configure UD as a service.
