### ISSUE TITLE
New-UDCard - Image Card doesn't display Image

### ISSUE THREAD

**Issue by RCDS1** [ironmansoftware/universal-dashboard#303]
See example https://www.poshud.com/Card#!

Image card does not display thumbnail image 

example image: http://materializecss.com/images/sample-1.jpg

How do you display an image in the New-UDCard?

**Comment by v2kiran** [comment]
Had the same issue this morning and discovered that the  `new-udcard`  does set the image but with a height and width of 0px so while it is displayed you cant see it :). 

You could either set the height and width parameter values of `new-udcard` or set the image using UDElement

`$image = New-UDElement -Tag img -Attributes @{src=image.jpg}
New-UDImage -Image $Image
`
