### ISSUE TITLE
[Question][IIS] Is there a way to trigger Powershell code when shutting down a web site ?

### ISSUE THREAD

**Issue by LaurentDardenne** [ironmansoftware/universal-dashboard#304]
I run a dashboard in IIS (Start-UDRestApi), is there a way to trigger Powershell code when shutting down a web site?

**Comment by adamdriscoll** [comment]
There isn't a good way to do this at the moment that I'm aware of.

**Comment by LaurentDardenne** [comment]
Ok, thanks.
Can I restrict an API  to a user group ?
I have not read / tested all the [documentation](https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/rest-apis/rest-api-authentication.html), can we do something like this:
```powershell
$Endpoint = @(
 New-UDEndpoint -Url "/Start" -Method "POST" -Endpoint {
   start X
 } -restricted
 
 New-UDEndpoint -Url "/Job" -Method "POST" -Endpoint {
   Out-Job xyz
 } -Public

 New-UDEndpoint -Url "/Stop" -Method "POST" -Endpoint {
   stop X
 } -restricted
)
Start-UDRestApi -Endpoint $Endpoint
```

**Comment by adamdriscoll** [comment]
@LaurentDardenne Not at the moment but I love that idea. I'm working on adding role-based access for 2.0 and I think I'll sneak this in as well since it's very much related. 

See #307

**Comment by LaurentDardenne** [comment]
Thanks :-)
