### ISSUE TITLE
UDGrid - AutoRefresh resets filter/pages to zero

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#311]
When AutoRefresh is set on a UD Grid, you'll run into incidents where you apply a filter/click Next and then has the table reset when the refresh occurs.

Ideally a refresh should be skipped if a filter is applied or if the table is on any page other than 1.

**Comment by dtaboada** [comment]
The same thing occurs in general, when you have AutoRefresh parameter set on UDGrid, and for instance you're on the 2nd page of your datagrid, is there a way to manually refresh this data?

**Comment by adamdriscoll** [comment]
Adding manual refresh. Also fixed issues where the page\filter would be changed on refresh. 

![image](https://user-images.githubusercontent.com/1256531/59864616-7286b200-9344-11e9-95e3-bfc547dbd626.png)
