### ISSUE TITLE
Dashboard not loading unless IIS restarted recently

### ISSUE THREAD

**Issue by TCSimon** [ironmansoftware/universal-dashboard#314]
When a client requests our dashboard, it will only load properly if IIS was restarted within the last 30 minutes or so. It loads just fine on several clients' browsers, as long as the requests are made soon after the IIS service is restarted. If a browser request is done after say 30 minutes or so, the page will load, but only the blue standard header and footers, with just white in between - no content. The previous requests that were successful will still continue updating, it's just the new ones that won't work.

**Comment by adamdriscoll** [comment]
What version are you running? In 1.6.1 there was an issue were endpoints would "disappear". If you're running 1.7.0, I worry there is a regression.
