### ISSUE TITLE
LoginPage - RedirectURL support

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#319]
It would be a nice addition to have the RedirectURL support in the login page.

For instance, using these pages will simply redirect me to the login page, then to home without considering the initial request URL .

https://localhost:9999/home?Param=1
https://localhost:9999/SettingsPage

**Comment by adamdriscoll** [comment]
Sure. I'll pull it into the 2.3 release milestone.

**Comment by itfranck** [comment]
@adamdriscoll It looks like the feature is not working using 2.3.2.  
In my initial example, these urls : 
https://localhost:9999/home?Param=1
https://localhost:9999/SettingsPage

are not getting translated to : 
https://localhost:9999/login?RedirectURl=home%3FParam%3D1
https://localhost:9999/login?RedirectURL=SettingsPage

Instead, users are still redirected to /login,
therefore ignoring the initial intent and bringing the user on the home page no matter what.
