### ISSUE TITLE
Trafic light support

### ISSUE THREAD

**Issue by PeterSkoglund** [ironmansoftware/universal-dashboard#325]
A new usercontrol, Traffic Light, the control is a simplified three-state indicator that shows whether a KPI metric falls into one of its pre-defined states and the number of seconds the state has to occure before shifting state. The KPI can also be disabled and the Trafic light color is the GREY.

Ex

10 seconds and

CPU <85%                             --> GREEN
CPU >85% and CPU <90%    --> ORANGE
CPU >=90%                           -->  RED

**Comment by Southpaw018** [comment]
Suggestion to expand this to gauge support. Meters, bars, traffic lights, etc. Right now, I have a one-bar bar graph chart with a custom scale to display free space on a disk. A gauge could handle that easily :)

**Comment by adamdriscoll** [comment]
This component now exists here: https://forums.universaldashboard.io/t/gauge-component/1775/13
