### ISSUE TITLE
PowershellGet Version 2.0 required

### ISSUE THREAD

**Issue by kaband** [ironmansoftware/universal-dashboard#332]
I'm getting the following message using Powershell 5.1 on Win 10.  The latest version of PowerShellGet for 5.1 I see is 1.6.7.  It's a warning, but the dashboard does not actually install.  Using Save-Module also results in an error.

Install-Module UniversalDashboard.Community -Force
_**WARNING: The specified module 'UniversalDashboard.Community' with PowerShellGetFormatVersion '2.0' is not supported by
the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module,
'UniversalDashboard.Community'**_

C:\\> Find-Module universalDashboard.Community | FL

Name                       : UniversalDashboard.Community
Version                    : 2.0.0
Type                       : Module
Description                : Cross-platform module for developing websites and REST APIs.
Author                     : Adam Driscoll
CompanyName                : adamdriscoll
Copyright                  : 2018 Ironman Software, LLC
PublishedDate              : 8/31/2018 1:42:56 AM
InstalledDate              :
UpdatedDate                :
LicenseUri                 : https://poshtools.com/universal-dashboard-license/
ProjectUri                 : https://poshtools.com/powershell-universal-dashboard/
IconUri                    : https://raw.githubusercontent.com/ironmansoftware/universal-dashboard/master/images/logo.p
                             ng
Tags                       : {dashboard, web, linux, windows...}
Includes                   : {Function, RoleCapability, Command, DscResource...}
**PowerShellGetFormatVersion : 2.0**
ReleaseNotes               : For release notes, see: https://docs.universaldashboard.io/updates/v2.0.0
Dependencies               : {}
RepositorySourceLocation   : https://www.powershellgallery.com/api/v2/
Repository                 : PSGallery
PackageManagementProvider  : NuGet

**Comment by BryanDM** [comment]
Hey Kaband,

I ran into this too. I solved it by upgrading my .net to 4.7.2

**Comment by kaband** [comment]
Ah!  Ok. Thanks, Bryan.  When I saw 2.0 I thought it was talking about the module version.  Not the case.  
Let me get 4.7.2 installed. Thanks again!

**Comment by kaband** [comment]
Ok, I closed it too soon.  Looks like I have 4.7.2 installed already.
From my Registry for .NET:   Release       : 461808  
According to MS this release is 4.7.2 for Windows 10 April 2018.

Bryan, did you take any other steps by chance?

**Comment by BryanDM** [comment]
I also updated my PSGet module

**Comment by kaband** [comment]
Great, thx.  I had done that as well, but I managed to have both versions of Powershellget installed causing some trouble. All fixed and the new UD is installed.  Thx again for the help.
