### ISSUE TITLE
Get-UDElement does not work

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#333]
SignalR is waiting for one request to complete before processing another.

**Comment by jmknight2** [comment]
I believe this bug has reappeared in 2.4.1. I'm unable to get the value of a UDSelect when `Get-UDElement` is called within the `-OnClick` handler of a button. It should be noted that I can get the value when I call `Get-UDElement` from the `-OnChange` handler of `New-UDSelect`, however. From what I've seen so far, this seems to only effect UDSelect fields.

Working example:
```
New-UDSelect -Id 'test-select' -Option {
    New-UDSelectOption -Name 'test' -Value 'stuff'
    New-UDSelectOption -Name 'another test' -Value 'other stuff'
} -OnChange {
    Show-UDToast -Message (Get-UDElement -Id 'test-select').Attributes['value'] -Title 'Debug' -Position topRight -Duration 6000
}
```

Broken Example:
```
New-UDSelect -Id 'test-select' -Option {
    New-UDSelectOption -Name 'test' -Value 'stuff'
    New-UDSelectOption -Name 'another test' -Value 'other stuff'
}

New-UDButton -Id 'test-btn' -Text 'Click Me!' -OnClick {
    Show-UDToast -Message (Get-UDElement -Id 'test-select').Attributes['value'] -Title 'Debug' -Position topRight -Duration 6000
}
```

I'm also receiving this error in Chrome's console: 
![image](https://user-images.githubusercontent.com/28332566/59370333-49e13580-8d10-11e9-8aee-d919591c10fb.png)
