### ISSUE TITLE
[Question] Did Variable Scoping for Dynamic Pages Change with 2.0.0?

### ISSUE THREAD

**Issue by pldmgg** [ironmansoftware/universal-dashboard#335]
Prior to UD Community 2.0.0, if I had a Dynamic Page like `/ToolSelect/:RemoteHost`, within that Page Endpoint (i.e. `New-UDPage -Url "/ToolSelect/:RemoteHost" -Endpoint {param($RemoteHost) ...}`), I was able to refer to `$RemoteHost` in almost any context (inside/outside a component -Endpoint or -Content block/array, etc) and it would pickup the `$RemoteHost` string value from the URL. But with 2.0.0, it doesn't seem like it `$RemoteHost` is honored (at least not consistently) within certain scriptblocks (I'm having problems with -Endpoint and -OnClick specifically). It does seem to work within -Content scriptblocks and outside UD Components altogether.

My current workaround for -Endpoints is to define $Session:ThisRemoteHost at the top of each Dynamic Page with something like...

```powershell
New-UDPage -Url "/ToolSelect/:RemoteHost" -Endpoint {
    param($RemoteHost)

    New-UDColumn -Endpoint {
        $Session:ThisRemoteHost = $RemoteHost
    }

    ...
}
```

...and use that `$Session:` variable within -Endpoints, but I'm still having issues with -OnClick (for UDButtons) picking up the string value.

**Comment by adamdriscoll** [comment]
Not intentionally. Will have to look into it.

**Comment by adamdriscoll** [comment]
@pldmgg Can you try the latest kit? I think I've resolved this issue. There was a race condition where this could work...sometimes. 

https://ci.appveyor.com/project/adamdriscoll/universal-dashboard/build/artifacts

**Comment by pldmgg** [comment]
I'll test it out tonight and report back :)

**Comment by pldmgg** [comment]
Just finished testing this out in the UD version of Windows Admin Center that I'm building and everything worked fine. Since it has a *ton* of features, I was able to test `$RemoteHost` in a bunch of different contexts, and everything seems to work without issue, so thanks for taking care of this one!

**Comment by adamdriscoll** [comment]
Great! Thanks for doing that. I'll likely release a 2.0.1 version tomorrow to fix this and some other hairy issues that popped up with the big 2.0 release.
