### ISSUE TITLE
UDInput type 'select' breaks formatting

### ISSUE THREAD

**Issue by CBVista** [ironmansoftware/universal-dashboard#344]
Using the following code, the 'select' input breaks html formatting and sits on top of textbox
```
New-UDInputField -Name 'JobTitle' -Placeholder 'Job Title' -Type 'textbox'
New-UDInputField -Name 'Office' -Placeholder 'Office' -Type 'select' -Values @('NZ', 'CN', 'UK', 'US', 'ZA')
New-UDInputField -Name 'Manager' -Placeholder 'Manager' -Type 'textbox'
```

**Comment by artvandelay440** [comment]
Can confirm this as well.

**Comment by nicoeat614** [comment]
Confirming this as well. I tried to sit a New-UDInputField -Type Select above a New-UDInputField -Type Textbox and both labels and/or placeholders sit on top of each other.

**Comment by adamdriscoll** [comment]
Trying this with the latest 2.2.0-beta1 and it looks ok. Can someone else please confirm? 

![image](https://user-images.githubusercontent.com/1256531/48802955-de7d3b00-eccd-11e8-8b1b-62e3cfa77140.png)

**Comment by adamdriscoll** [comment]
I tried in IE, Chrome and Firefox.
