### ISSUE TITLE
Publish-UDDashboard uses wrong path in 2.0

### ISSUE THREAD

**Issue by bielawb** [ironmansoftware/universal-dashboard#346]
It looks like even though location of the UniversalDashboard.Server.exe changed in 2.0, Publish-UDDashboard is still using old location, making published service failing with `The system cannot find the file specified.` error.

It's perhaps better to lookup file path instead of hardcoding it (see [here](https://github.com/ironmansoftware/universal-dashboard/blob/e912dd9f9cfdf3d54655b1d59341192249738ebc/src/UniversalDashboard/UniversalDashboardServer.psm1#L1516)).

**Comment by BenHimsel** [comment]
Issue still present in 2.0.1, updating Service ImagePath for new .Net location and removing an extra \ works around this issue. Also I believe line of code that Bartek linked, $TargetPath already contains a \ so using Join-Path may be safer.
