### ISSUE TITLE
Does UD Support Embedded Functions?

### ISSUE THREAD

**Issue by dprice** [ironmansoftware/universal-dashboard#347]
[dashboard_bug.ps1.txt](https://github.com/ironmansoftware/universal-dashboard/files/2352725/dashboard_bug.ps1.txt)

I created a very simple dashboard (see attached) that attempts to check the online status of a list of servers using a couple of embedded functions in the dashboard file.

When I run the script everything renders except for this message in the UDTable:
```
The term 'Test-MyServersAvailability' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I am running UD v2.0 on Windows PS 5.1.

Suggestions on how to use external functions within the dashboard cards, tables, etc.?

Thanks,
Derek

**Comment by BryanDM** [comment]
Derek,

Which version of UD are you running? This is done differently in 2.0+ than 1.7 and below.

**Comment by dprice** [comment]
My version is 2.0
