### ISSUE TITLE
Display percentage with % sign but sort like an integer in grid

### ISSUE THREAD

**Issue by murrahjm** [ironmansoftware/universal-dashboard#350]
Is there a way to have a column in a UDGrid display a value as a percentage (99.2 %) but have the column sortable as if the values were integers?  All the ways I've found to add a % sign to something turns it into a string, which then can only be sorted like a string (100% comes before 99%, etc.)

**Comment by adamdriscoll** [comment]
You'll have to implement server side processing if you want to sort that way: https://github.com/ironmansoftware/universal-dashboard/blob/master/examples/grid/high-performance-sql-grid.ps1

https://docs.universaldashboard.io/components/grids
