### ISSUE TITLE
Not able to update Powershell UDD

### ISSUE THREAD

**Issue by mariusbekk** [ironmansoftware/universal-dashboard#352]
`Install-Module -Name UniversalDashboard -Force`

WARNING: The specified module 'UniversalDashboard' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module, 'UniversalDashboard'.

Latest version of PowerShellGet is installed:
1.6.7      PowerShellGet                       PSGallery

**Comment by AlonGvili** [comment]
What version of packagemanagement do you have

**Comment by ericshoemaker** [comment]
I too have this issue. I have Windows 10 1803 (April 2018) which has .Net 4.7.2 built-in. I'm showing the various outputs I get from save-module and install-module. There is also debug output. Note that there is a hash mismatch message in the debug.




**Save-Module UniversalDashboard.Community -Path C:\temp**
Output: WARNING: The specified module 'UniversalDashboard.Community' with PowerShellGetFormatVersion '2.0' is not supported by
the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module,
'UniversalDashboard.Community'.
PackageManagement\Save-Package : Unable to save the module 'UniversalDashboard.Community'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1598 char:21
+             $null = PackageManagement\Save-Package @PSBoundParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Except
   ion
    + FullyQualifiedErrorId : ProviderFailToDownloadFile,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage

**Install-Module UniversalDashboard.Community -Force**
WARNING: The specified module 'UniversalDashboard.Community' with PowerShellGetFormatVersion '2.0' is not supported by
the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module,
'UniversalDashboard.Community'.


**Install-Module UniversalDashboard.Community -Force -Debug**
NOTE THE MESSAGE AFTER THE DOWNLOAD COMPLETES: Hash for package 'UniversalDashboard.Community' does not match hash provided from the server.
DEBUG: 00:00:00.0000236 Force: True
DEBUG: 00:00:00.0000361 Debug: True
DEBUG: 00:00:00.0000477 Name: UniversalDashboard.Community
DEBUG: 00:00:00.0007601 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0013017 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0021852 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0069073 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0069421 Force: True
DEBUG: 00:00:00.0069574 Debug: True
DEBUG: 00:00:00.0069704 Name: UniversalDashboard.Community
DEBUG: 00:00:00.0078293 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0096663 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0114666 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0157374 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0157588 Force: True
DEBUG: 00:00:00.0157704 Debug: True
DEBUG: 00:00:00.0157815 Name: UniversalDashboard.Community
DEBUG: 00:00:00.0165101 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0171250 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0213022 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0268910 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0269110 Force: True
DEBUG: 00:00:00.0269230 Debug: True
DEBUG: 00:00:00.0269342 Name: UniversalDashboard.Community
DEBUG: 00:00:00.0285731 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0295290 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0338044 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.3407795 Calling SearchForPackages. Name='UniversalDashboard.Community'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:01.3432523 PackageProvider::FindPackage with name UniversalDashboard.Community
DEBUG: 00:00:01.3443788 Calling SearchForPackages After Select 1
DEBUG: 00:00:06.3502682 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:06.3503406 ProviderName: PowerShellGet
DEBUG: 00:00:06.3503753 Type: Module
DEBUG: 00:00:06.3504055 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:06.3504194 Force: True
DEBUG: 00:00:06.3504329 Debug: True
DEBUG: 00:00:06.3504444 Scope: AllUsers
DEBUG: 00:00:06.3504574 Name: UniversalDashboard.Community
DEBUG: 00:00:06.3512199 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:06.3517977 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:06.3527665 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:06.3530531 OPTION: Type => Module
DEBUG: 00:00:06.3532934 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:06.3538680 OPTION: Force => True
DEBUG: 00:00:06.3539607 OPTION: Debug => True
DEBUG: 00:00:06.3546235 OPTION: Scope => AllUsers
DEBUG: 00:00:06.3548317 OPTION: Name => UniversalDashboard.Community
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is
'NuGet'.
DEBUG: 00:00:06.3625107 PackageProvider::FindPackage with name UniversalDashboard.Community
DEBUG: 00:00:06.3646074 Calling 'NuGet'::'FindPackage' - name='UniversalDashboard.Community',
requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:06.3646381 Iterating 'UniversalDashboard.Community'.
DEBUG: 00:00:06.3648486 There are '0' registered sources in 'NuGet' provider.
DEBUG: 00:00:06.3648899 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in
'NuGet' provider.
DEBUG: 00:00:07.8276487 Source 'https://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:07.8277558 Calling 'NuGetRequest'::'GetPackageById', 'UniversalDashboard.Community'.
DEBUG: 00:00:08.0277281 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'UniversalDashboard.Community'.
DEBUG: 00:00:08.0278970 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'' for ''.
DEBUG: 00:00:08.0281339 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'&$skip=0&$top=40'.
DEBUG: 00:00:08.4708190 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'&$skip=0&$top=40'.
DEBUG: 00:00:08.4741966 '4' packages received in the last request.
VERBOSE: Total package yield:'1' for the specified package 'UniversalDashboard.Community'.
DEBUG: 00:00:08.4749382 Completed iterating for 'UniversalDashboard.Community'.
DEBUG: 00:00:08.4823306 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:19.3784750 Calling New() : MethodName = 'GetInstalledPackages'
DEBUG: 00:00:19.3785015 ProviderName: PowerShellGet
DEBUG: 00:00:19.3785154 Type: Module
DEBUG: 00:00:19.3785284 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:19.3785413 Force: True
DEBUG: 00:00:19.3785534 Debug: True
DEBUG: 00:00:19.3785650 Scope: AllUsers
DEBUG: 00:00:19.3785775 Name: UniversalDashboard.Community
DEBUG: 00:00:19.3795528 INVOKING PowerShell Fn Get-InstalledPackage with args UniversalDashboard.Community, 2.0.1, ,
that has length 4
DEBUG: 00:00:19.3817659 In PowerShellGet Provider - 'Get-InstalledPackage'.
DEBUG: 00:00:19.3818934 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:19.3820502 OPTION: Type => Module
DEBUG: 00:00:19.3821221 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:19.3821921 OPTION: Force => True
DEBUG: 00:00:19.3823261 OPTION: Debug => True
DEBUG: 00:00:19.3823962 OPTION: Scope => AllUsers
DEBUG: 00:00:19.3824643 OPTION: Name => UniversalDashboard.Community
DEBUG: 00:00:19.3952115 PowerShell Script 'PSModule' Function 'Get-InstalledPackage' returns null.
D
DEBUG: 00:00:21.6580920 Calling New() : MethodName = 'InstallPackage'
DEBUG: 00:00:21.6581435 ProviderName: PowerShellGet
DEBUG: 00:00:21.6581834 Type: Module
DEBUG: 00:00:21.6582256 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:21.6583281 Force: True
DEBUG: 00:00:21.6583652 Debug: True
DEBUG: 00:00:21.6583902 Scope: AllUsers
DEBUG: 00:00:21.6584171 Name: UniversalDashboard.Community
DEBUG: 00:00:21.6593985 INVOKING PowerShell Fn Install-Package with args
NuGet|UniversalDashboard.Community|2.0.1|https://www.powershellgallery.com/api/v2/|Module that has length 1
DEBUG: 00:00:21.6606251 In PowerShellGet Provider - 'Install-Package'.
DEBUG: 00:00:21.6612493 In PowerShellGet Provider - 'Install-PackageUtility'.
DEBUG: 00:00:21.6616162 The FastPackageReference is
'NuGet|UniversalDashboard.Community|2.0.1|https://www.powershellgallery.com/api/v2/|Module'.
DEBUG: 00:00:21.6624292 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:21.6627125 OPTION: Type => Module
DEBUG: 00:00:21.6629426 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:21.6631591 OPTION: Force => True
DEBUG: 00:00:21.6633836 OPTION: Debug => True
DEBUG: 00:00:21.6635302 OPTION: Scope => AllUsers
DEBUG: 00:00:21.6636535 OPTION: Name => UniversalDashboard.Community
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
DEBUG: 00:00:21.6644735 ArtifactType is Module
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'UniversalDashboard.Community' with version '2.0.1' from the repository
'https://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:21.7062366 Calling 'NuGet'::'InstallPackage',
'$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8=\VW5pdmVyc2FsRGFzaGJvYXJkLkNvbW11bml0eQ==\Mi4wLjE=\aHR0cHM6Ly
93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8=\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:21.7062807 Calling 'NuGetRequest'::'GetPackageByFastpath',
'$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8=\VW5pdmVyc2FsRGFzaGJvYXJkLkNvbW11bml0eQ==\Mi4wLjE=\aHR0cHM6Ly
93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8=\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:21.7064245 Calling 'NuGetRequest'::'ResolvePackageSource', 'https://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:21.7064727 Calling 'NuGetRequest'::'FindRegisteredSource', 'https://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:21.7065029 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in
'NuGet' provider.
DEBUG: 00:00:22.2570097 Calling 'HttpClientPackageRepository'::'FindPackage', 'UniversalDashboard.Community'.
DEBUG: 00:00:22.2570584 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'' for ''.
DEBUG: 00:00:22.2571521 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'&$skip=0&$top=40'.
DEBUG: 00:00:22.7101170 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'&$skip=0&$top=40'.
DEBUG: 00:00:22.7143470 '4' packages received in the last request.
DEBUG: 00:00:22.7180966 'Package version' is '2.0.1'.
DEBUG: 00:00:22.7181796 'Request's Destination' is 'C:\Users\admin\AppData\Local\Temp\163396991'.
DEBUG: 00:00:22.7183925 Calling 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:22.7185692 Returning the call 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:22.7189151 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='UniversalDashboard.Community',
version='2.0.1',destination='C:\Users\admin\AppData\Local\Temp\163396991'
VERBOSE: DownloadPackage' - name='UniversalDashboard.Community',
version='2.0.1',destination='C:\Users\admin\AppData\Local\Temp\163396991\UniversalDashboard.Community\UniversalDashboar
d.Community.nupkg', uri='https://www.powershellgallery.com/api/v2/package/UniversalDashboard.Community/2.0.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/UniversalDashboard.Community/2.0.1'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/UniversalDashboard.Community/2.0.1'.
VERBOSE: Completed downloading 'UniversalDashboard.Community'.
VERBOSE: Hash for package 'UniversalDashboard.Community' does not match hash provided from the server.
DEBUG: 00:00:33.1411754 Calling 'NuGetClient'::'InstallPackageLocal'.
VERBOSE: InstallPackageLocal' - name='UniversalDashboard.Community',
version='2.0.1',destination='C:\Users\admin\AppData\Local\Temp\163396991'
DEBUG: 00:00:33.1415019
C:\Users\admin\AppData\Local\Temp\163396991\UniversalDashboard.Community\UniversalDashboard.Community.nupkg
DEBUG: 00:00:35.0448463 Returning the call 'NuGetClient'::'InstallPackageLocal'.
DEBUG: 00:00:35.1902740 Returning the call 'NuGetClient'::'InstallSinglePackage'.
WARNING: The specified module 'UniversalDashboard.Community' with PowerShellGetFormatVersion '2.0' is not supported by
the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module,
'UniversalDashboard.Community'.

**Comment by ericshoemaker** [comment]
Just a note. UD 1.7.0 installs successfully using the following command while version 2.0.0 and 2.0.1 do not.

**Install-Module -Name UniversalDashboard -RequiredVersion 1.7.0**

**Comment by mariusbekk** [comment]
@adamdriscoll I looked at my own folder, I only have one version of PowerShellGet installed.

**Comment by adamdriscoll** [comment]
@mariusbekk They've put out another version of PowerShellGet. Can you please update to the latest and try again?

**Comment by ericshoemaker** [comment]
Thank you Adam! I was able to get this to work for me on both a new Win10 machine and a new Server 2016 deployment:

- Open PowerShell as Administrator
- Run Command:  Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
- Run Command:  Install-Module PowerShellGet -Force -AllowClobber
- Close PowerShell and Reopen as Administrator
- Run Command:  Install-Module UniversalDashboard.Community -force -AcceptLicense

Again, thank you for being responsive on this issue!

**Comment by mariusbekk** [comment]
Updated PowerShellGet, tested update of UniversalDashboard = OK.
Thank you all for your help.
