### ISSUE TITLE
Importing UniversalDashboard 2.0 fails with information about netstandard.

### ISSUE THREAD

**Issue by bielawb** [ironmansoftware/universal-dashboard#353]
I'm trying to use UD on machine that has 4.7 installed, but import module fails with information about netstandard:
```
> ipmo 'C:\Program Files\Optiver\UniversalDashboard\net471\UniversalDashboard.dll'
Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system
cannot find the file specified.
```

It worked fine with older version so not sure if something was changed and now we really have to install netstandard even if we want to use full clr version? I probably will roll back to version 1.7 (I'm not using any of the newest features yet) but it may be a breaking change for others that do need 2.0.

**Comment by adamdriscoll** [comment]
@bielawb What version of 4.7 do you have installed?

**Comment by bielawb** [comment]
I installed NDP47-KB3186497-x86-x64-AllOS-ENU on this box.
Looking at the registry information:
```
> (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\').Version
4.7.02053
```
Thanks for pointing it out, on my box (where 2.0 works fine) I have a newer version. Will try to update and let you know if it helped.

**Comment by bielawb** [comment]
OK, after updating .NET to 4.7.1 all works fine - still, exception is misleading at best. Perhaps it would be a better idea to verify that version and provide a bit more helpful error message?
