### ISSUE TITLE
Emojis dont work

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#354]
![image](https://user-images.githubusercontent.com/1256531/45168254-0d4c4080-b1b8-11e8-912b-1a5766d76ff0.png)

```powershell
$MyDashboard = New-UDDashboard -Title "🐬 demo!" -Content {
```

**Comment by leeberg** [comment]
Most important feature!!!!!

**Comment by adamdriscoll** [comment]
This was actually an encoding problem. If you save it with the BOM for UTF8, it works!

![image](https://user-images.githubusercontent.com/1256531/52710783-6e3d2900-2f4d-11e9-91ac-371c507f4323.png)
