### ISSUE TITLE
Get-UDUser / Get-UDVisitor

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#358]
In a Microsoft environment (using IIS), it would be a great feature to be able to get information about the (authenticated) Windows user, for SSO purposes. 

Could be an addition to the enterprise edition.

**Comment by PorreKaj** [comment]
This would be solved by the ISS SSO enhancement I guess.
https://github.com/ironmansoftware/universal-dashboard/issues/474

**Comment by adamdriscoll** [comment]
This is implemented with the SSO IIS support. You can get the user with $ClaimsPrincipal.
