### ISSUE TITLE
UD 2.0.2: Nordic Characters

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#361]
Hi,

I created a new Site using the lastest stable UD Community (2.0.2).

On this site I can't seems to get nordic Characters to display correctly.

ÆØÅ is displayed as Ã¦Ã¸Ã¥

ÆØÅ is displayed correctly on another site on the same server using 1.7.x.

Both running on IIS 10.

**Comment by PorreKaj** [comment]
I really hope there is a solution to be found to this one.
I have a project comming up where UD would be perfect, but it will be displaying alot of Scandinavian names, which would look very strange :-)

**Comment by PorreKaj** [comment]
Actually, the issue is not present in tables, but on cards' title.

**Comment by fraefel** [comment]
Using UTF-8 ? Sounds like ISO8859-1 to me ?

\Thomas

**Comment by PorreKaj** [comment]
I wouldn't really know, i'm not even sure where to change encoding settings.

**Comment by adamdriscoll** [comment]
@PorreKaj I was able to get this to work with 2,0.2. You need to set the encoding of your PS1 to UTF8 with BOM. 

Click this: 

![image](https://user-images.githubusercontent.com/1256531/47628030-307cd780-daf9-11e8-9732-8e3f8962b0be.png)

Then this:

![image](https://user-images.githubusercontent.com/1256531/47628027-278c0600-daf9-11e8-8447-4b76ecbfd7bc.png)

And you should see this: 

![image](https://user-images.githubusercontent.com/1256531/47628042-3e325d00-daf9-11e8-88fb-6059138e220d.png)
