### ISSUE TITLE
New-UDFooter -Links doesn't do anything

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#362]
There is no way to remove the "Created with Universal Dashboard" link. Also, adding new links doesn't seem to work.

**Comment by artvandelay440** [comment]
Still doesn't seem to remove the default, unless I'm missing something? It just appends text and links to the existing "Created with Universal Dashboard".

```
$Dashboard = New-UDDashboard -Title "Test"  -Footer (New-UDFooter -Links (New-UDLink -Text 'test' -Url 'https://www.google.com'))
```
![capture](https://user-images.githubusercontent.com/2523522/47792201-857f4000-dce9-11e8-96dd-f82bbf29b109.PNG)
