### ISSUE TITLE
Title bar should link to home page, or be configurable

### ISSUE THREAD

**Issue by murrahjm** [ironmansoftware/universal-dashboard#363]
It appears that all the Title bar link does is append '#!' to the current page URL.  I'd like to be able to modify this link to redirect to the /Home URL from any other page.

I'm currently using many dynamic pages, and the only way currently to get home is to open the side bar and click on home (incidentally, home is the only page in this list, since dynamic pages don't appear there for obvious reasons).

Maybe the -title parameter of New-UDDashboard could be modified to take a New-UDLink value in addition to text?

**Comment by adamdriscoll** [comment]
Yeah I could see having a link there for sure!
