### ISSUE TITLE
New-UDEndpointInitialization doesnt load module

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#366]
Seems like -Module doesn't work if i provide a Name of a module loaded in Get-Module.

We tent to not install modules on a given machine, but provide a path to the module and load it as script.

Example:
Import-Module ".\Modules\Invoke-SQLCommand"

And Get-Module would indeed show that 'Invoke-SQLCommand' is loaded.

But i can't get it to load this module inside the Endpoint in 2.0.1

**Comment by adamdriscoll** [comment]
I think this is the same issue as #326
