### ISSUE TITLE
Markdown render component

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#370]
Hi there!

I'd really want to use UD to make a website, hence I need a UD-Card like component but being able to render markdown inside of it. 

@adamdriscoll I narrowed down a selection of React Markdown components that may be integrated
 into UD:
  - https://github.com/jonschlinkert/remarkable
  - https://github.com/rexxars/react-markdown

That would be really awesome feature to have! I know I could implement it by myself but JavaScript/react is far above my head.

Thanks! :-)

**Comment by AlonGvili** [comment]
> Hi there!
> 
> I'd really want to use UD to make a website, hence I need a UD-Card like component but being able to render markdown inside of it.
> 
> @adamdriscoll I narrowed down a selection of React Markdown components that may be integrated
> into UD:
> 
> * https://github.com/jonschlinkert/remarkable
> * https://github.com/rexxars/react-markdown
> 
> That would be really awesome feature to have! I know I could implement it by myself but JavaScript/react is far above my head.
> 
> Thanks! :-)

Hey,

I working on new ud custom component that let you render markdown in ud.
hope to publish it to the PowerShell gallery in a day or two.

Im using [React-Markdown]( https://github.com/rexxars/react-markdown)
![image](https://user-images.githubusercontent.com/34351424/46038056-be3c6000-c112-11e8-941f-23ec411f1ce1.png)

**Comment by dtaboada** [comment]
@AlonGvili This would be great, have the following dashboard - cannot figure out how to format the "card-title" inside the loop with out it inheriting from the parent theme definition, looks like the component you mentioned will alleviate this?

    $Theme = New-UDTheme -Name "Basic" -Definition @{
        '.card-content'     = @{
            'font-size' = '14px'
        }
        '.card .card-title' = @{
            'font-size'   = '20px'
            'font-weight' = '400'
        }
        'test'              = @{
            'font-size' = '12px'
        }
    } -Parent "Azure"


    $Schedule = New-UDEndpointSchedule -Every 20 -Second

    $Endpoint = New-UDEndpoint -Schedule $Schedule -Endpoint {

        $cache:GetSvc = get-service -ComputerName SOMECOMPUTER | ? {$_.DisplayName -like "*w*"}

    } 

    $HomePage = New-UDPage -Name "Home" -Content {
        
        New-UDCard -Title "Independant Formating" @Colors -Content {"TESTING.... - Inherits from THEME"}
        New-UDLayout -Columns 3 -Content {
            New-UDRow -Endpoint {
                New-UDCard -Title "Services" @Colors -Content {
                    New-UDLayout -Columns 3 -Content {
                        foreach ($psitem in $cache:GetSvc) {
                            $backgroundcolor = "#F0FF00"
                            if ($_.Status -eq "Running") {
                                $backgroundcolor = "#02B30F"
                            }
                            if ($_.Status -eq "Stopped") {
                                $backgroundcolor = "#D21D1D"
                            }
                            New-UDCard -Title "$($_.DisplayName)" -BackgroundColor $BackgroundColor -Watermark "wpexplorer" -Content {
                                New-UDElement -Tag "test" -Content {$($_.MachineName) ; "Other Independant formatting - WORKS"}
                            }
                        }
                    }
                }
            } -AutoRefresh
        }
    }

**Comment by AlonGvili** [comment]
Hey, today i was released UniversalDashboard.Markdown hope it will help you.
https://www.powershellgallery.com/packages/UniversalDashboard.Markdown/1.0.0

Or

Install-Module UniversalDashboard.Markdown

**Comment by AlonGvili** [comment]
@apetitjean https://github.com/AlonGvili/UniversalDashboard.Markdown/blob/master/Source/PowerShell/dashboard.ps1

Look at this file it create demo ud site.

**Comment by apetitjean** [comment]
I haven't take the time yet to test it, but be assured to get a feedback
from me very soon!

Yes, I'll update this thread.

Le ven. 19 oct. 2018 à 15:25, Alon Gvili <notifications@github.com> a
écrit :
