### ISSUE TITLE
New-UDAuthenticationResult has a default value for ErrorMessage contrary to help

### ISSUE THREAD

**Issue by exactmike** [ironmansoftware/universal-dashboard#371]
There is a default value for the ErrorMessage attribute provided in the output object of New-UDAuthenticationResult although the documentation says that there is no default value.  The default value is 'Bad username or password'.  If you run New-UDAuthenticationResult as shown in the examples, even with a -Success scenario, the output object still contains the default 'Bad username or password'.  UD seems to ignore this in the dashboard itself, but it still should probably be resolved so that in a -success scenario ErrorMessage is NULL. 

This is with Module version 2.0.1 running on WindowsPowerShell version 5.1.

**Comment by adamdriscoll** [comment]
Resolved in 2.1.0.
