### ISSUE TITLE
Cache variable not working as expected in UDEndpoint

### ISSUE THREAD

**Issue by dtnyc9005** [ironmansoftware/universal-dashboard#372]
Hi all, having some issues with UDEndpoint, below is a snip of the code. I'm executing, same code on  another page in an endpoint with out issues, I want to utilize UDEndpoint cmdlet with a schedule endpoint for performance reasons, my list will include couple hundred servers @ the end, but cannot get the cache variable to work nice, when this runs I only see the date variable update, but nothing happens with the $cache:webitems variable, not sure if this a bug, or am I doing something wrong?

`
#TESTPAGE#####################################################################

$PageTest = New-UDPage -Name "PageTest" -Content {
    New-UDRow -Endpoint {
        New-UDCard -Title "$Cache:WSepDATE" -Text
        $Cache:WebItems | % { New-UDCard -Title $_.Computername }
    } -AutoRefresh

}

#SCHEDULE#####################################################################

$Schedule1 = New-UDEndpointSchedule -Every 5 -Second 

#ENDPOINT#####################################################################

$WebLFWSep = New-UDEndpoint -Schedule $Schedule1 -Endpoint {

    
    $Cache:WSepDATE = (get-date -Format G )

    $cache:WebItems = foreach ($server in $webservers) {
        $RootFolder = "http://{0}/homepage.aspx"
        $uri = $RootFolder.Replace("{0}", $server)
  
        try {
            $uri = $RootFolder.Replace("{0}", $server)

            $Webrequest = Invoke-WebRequest -Uri $uri -ErrorAction Stop 
            $WebReqStatus = switch ($Webrequest.StatusCode) {
                {$_ -ge '200'} {"Success - $($Webrequest.StatusCode)"}
                {$_ -ge '300'} {"Redirection - $($Webrequest.StatusCode)"}
                {$_ -ge '400'} {"Client error - $($Webrequest.StatusCode)"}
                {$_ -ge '500'} {"Server error - $($Webrequest.StatusCode)"}
                Default {"No Code Returned"}
            }
        }
        catch {
            $WebReqStatus = switch ($_.exception.message) {
                'Unable to connect to the remote server' {"WebSite Stopped State"} 
                'Unable to connect to the remote server.exception.message' {"IIS Service Issue"}
                {$_ -like 'The remote server returned an error*'} {"App Pool Issue"}
                Default {"$_.exception.message"}
            }
        }
        try {
            $IISResult = (get-service -name "W3SVC" -ComputerName $server).Status
        }
        catch {
            $IISResult = switch ($_.exception.message) {
                'Unable to connect to the remote server' {"Could not retrieve service"} 
                Default {"$_.exception.message"}
            }
        }

        [pscustomobject]@{
            #Tier              = $Tier
            Computername      = $server
            WebReqStatus      = $WebReqStatus
            IISResult         = $IISResult
            StatusDescription = $Webrequest.StatusDescription   
        }
    }
 
}#EndpointEND

`

**Comment by dtaboada** [comment]
Does anyone know of a better way to get around this? Is there something in particular with pscustom objects, when passed in a UDEndpoint?
