### ISSUE TITLE
Only with IE11 Error 404

### ISSUE THREAD

**Issue by LudoP76** [ironmansoftware/universal-dashboard#374]
Hi Adam

1: Good Job and Thank you for your incredible work. 
2: sorry for my very poor English

3: My Issue.

Since version 2.0.1 (I don't tested 2.0), with Internet explorer 11 when i tested to connect to the dashboard with URL 

Http://localhost:1000
Http://127.0.0.1:1000

i have web page with Error 404. But with Firefox or Chrome the dashboard display correctly.

My setup
- Computer with Windows 7 SP1 (Full patched) / Idem an other computer
- Net Framework 4.7.2 (tested with 4.7.1 too)
- PS-V5-WMF5.1 (Win7AndW2K8R2-KB3191566-x64.msu)
- UniversalDashboard 2.0.1

Did you have an idea ?

**Comment by adamdriscoll** [comment]
Others have reported issues with IE. I think it's broken in the current version.
