### ISSUE TITLE
New-UDLoginPage -LoginFormFontColor does not change font color when using AzureAD

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#376]
If you set the background color to white, you won't be able to see the login with azure text even when setting the text color.

**Comment by artvandelay440** [comment]
I have the same issue, using Microsoft OAuth2 as provider.

**Comment by adamdriscoll** [comment]
I added -LoginButtonFontColor and -LoginButtonBackgroundColor. Now you can do beautiful things like this. 

![image](https://user-images.githubusercontent.com/1256531/47734300-b602a380-dc2f-11e8-880e-dd972eeba649.png)
