### ISSUE TITLE
New-UDInputField date parameter

### ISSUE THREAD

**Issue by Sup3rLativ3** [ironmansoftware/universal-dashboard#388]
I have found a couple of "problems" with the date parameter for New-UDInputField.

* It only goes back 7 years in the drop down.
* If you select anything on the popup it will close e.g. choosing the year closes without a date being selected.
* It is missing from the majority of the documentation.

Is the date parameter being deprecated? I notice that on the link below you also have a time parameter but it is commented out.
https://github.com/ironmansoftware/universal-dashboard/blob/c40b933edb07d6024de595c29a5a791c280530d4/src/UniversalDashboard.UITest/Integration/Input.Tests.ps1

**Comment by adamdriscoll** [comment]
I'd say it was more never totally implemented than being deprecated. ;)

**Comment by Sup3rLativ3** [comment]
Ah, good to know. I guess that would be why the doco is also incomplete on it.

I totally understand that you have a lot to work through but is this likely to be fixed in the near future? If not, what would you suggest as a work around?
