### ISSUE TITLE
Struggling to gett Dashboard working via cmdline on Windows 2012 Server with Powershell 6

### ISSUE THREAD

**Issue by adenjago** [ironmansoftware/universal-dashboard#389]
Hi 

Im not sure if the is correct place, but im really struggling to the get the Cmdline or the IIS parts installed on a Vanailla Windows 2012 R2 server.

I can get the UniversalDashboard working on my Laptop using PowerShell 6, when using Powershell 5.1 the cmdlets do not to install and are missing on both my Laptop and the server.

Im currently using PS6 and the  Installation guide\walkthrough from https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/running-dashboards/command-line.html

On the 2012 server trying to access the CMDLINE (using the same steps as on my laptop) I get the below 

![screenshot - 08_10_2018 16_31_24](https://user-images.githubusercontent.com/28042936/46618562-c1265000-cb17-11e8-9400-f44da484f85c.png)

When trying to configure the Dashboard via a Website using IIS ( ASP.NET Core is installed) I get the below...I have checked with Netstat and the ports are not in use and no other websites are running

and gone through a few of the workarounds and possible causes of this error but not yet found a solution.

![screenshot - 08_10_2018 16_28_39](https://user-images.githubusercontent.com/28042936/46618594-de5b1e80-cb17-11e8-9a52-5c96d0781388.png)

Any help would be greatly appreciated 

Cheers 

Ade

**Comment by psDevUK** [comment]
Dude you need to put the port in the url. Http://localhost:4444

**Comment by psDevUK** [comment]
Or whichever port you assign your dashboard to.

**Comment by adamdriscoll** [comment]
Please open an topic on the forums if you are still experiencing this is as I believe it to be a configuration issue. https://forums.universaldashboard.io/
