### ISSUE TITLE
Question about new-udelement

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#393]
let say i have this function

```powershell

function New-UDTest {
    param(
        [Parameter()]
        [string]$Id = (New-Guid).guid,
        [parameter()]
        [string]$Name,
        [parameter()]
        [scriptblock]$Column,
        [parameter()]
        [hashtable]$Styles
    )


    New-UDElement -JavaScriptPath $JsFile -ModuleName "UDTest" -Properties @{
        id = $Id
        name = $Name
        styles = $Styles
        column = $Column.invoke()
    }
```

in the column parameter i pass content in script block and the content is a result of another function  trying to invoke that command i get error, react aspected to string or function but  column parameter return a CliXml object and not the content.

How can i return  the output that i get from the nested command ?

**Comment by adamdriscoll** [comment]
I think this might be a bug. I will have to do some more research but it seems like there is some weird serialization going on. I think this was reported way back in the day but you're one of the few people creating custom controls with JS so I don't think it was ever properly addressed.

**Comment by AlonGvili** [comment]
> I think this might be a bug. I will have to do some more research but it seems like there is some weird serialization going on. I think this was reported way back in the day but you're one of the few people creating custom controls with JS so I don't think it was ever properly addressed.

for now, I using an array or hashtable but I need to invoke those function like this it is weird

PowerShell
                    (New-UDTest -Title 'Task 01' -Content (
                        'Create New Test'
                    ) -Styles @{
                            'margin-top'= '35px';
                            'padding'= '10px';
                            'font-size' = '16px';
                            'background-color' = 'rgb(210, 210, 210)';
                    }).properties
```

this way I get the props I needed, didn't try it with nested functions.
and I must tell you to combine Powershell and React we can do some crazy things.

**Comment by adamdriscoll** [comment]
i've done a but of work around this use case in 2.3 to make including custom components better. I fixed that CliXml error and now provide access to a lot more of the underlying features of UD so you can more easily request stuff from the server and fire off events. I'll doc all this for the 2.3 release.
