### ISSUE TITLE
UDButton or Events in Dynamic pages

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#399]
Hi.
I hooked my Dashboard up with a Dynamic page, where i'd like to have a button that either shows a modal or a toast.
This works on Static homepage, but nothing happens on the Dynamic page. No Browser errors either.
`New-UDButton -Text "Option 1" -OnClick {Show-UDToast -Message "Det virker woo" -Duration 5000 -Title "Message" -Position topCenter}`

Is there a magic switch needed for Dynamic pages?

**Comment by AlonGvili** [comment]
I think there is an open issue on this one

**Comment by PorreKaj** [comment]
Indeed https://github.com/ironmansoftware/universal-dashboard/issues/243.
