### ISSUE TITLE
Implement some Default Color Pallets for Charts

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-dashboard#400]
Feature Request: Add some default color pallets for charts.

I suggest that you use the colors provided by the ColorBrewer library as the source of color scales as it is pretty robust and supports nice-to-haves like a colorblind friendly mode.

Alternately you could use the d3.js implementation of same. I suggest defaulting to a qualitative scale for visual contrast and allowing switching to sequential and divergent color scales using a parameter. This could help to significantly speed up the development of chart rich dashboards by removing the color selection/contrast checking steps from the process.

https://bl.ocks.org/mbostock/5577023
http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by adamdriscoll** [comment]
This has been implemented in the nivo library. You'll be able to select from this set of schemes. https://nivo.rocks/guides/colors
