### ISSUE TITLE
Tables and Grids default sorting issues

### ISSUE THREAD

**Issue by nicoeat614** [ironmansoftware/universal-dashboard#402]
I don't know whether to call this an issue or not because I have seen what I am about to describe happen in regards to PowerShell before. That is the **ASCIIbetical order vs the natural order** and It is somewhat annoying.  In the past, I have tried to mimic the presentation _"sorting files & folders"_ in Windows Explorer via PowerShell for my customer (smh) and it was such a headache to overcome it. Now I am seeing it in both New-UDTable and New-UDGrid.

With both UDGrid and UDTable, I passed this data in below (short version):

| Prize    |   At Start    |  Remain |
|----------|:-------------:|--------:|
| $10,000,000 |  4 | 2   |
| $1,000,000 |   12  |   8   |
| $20,000  | 13 |   9   |
| $4,000 | 180 | 125  |    
| $500 | 3,185 | 2,273 |

I specifically made every item a string object because I wanted to add the commas to make it more human-readable. I know with either the table or grid, the sorting would be easier due to the ASCII value; however, anytime I tried to do a Sort-Object specifically with the UDTable or use the Server Side Processing parameter, along with the $SortColumn variable with the UDGrid, I always got this:

| Prize    |   At Start    |  Remain |
|----------|:-------------:|--------:|
| $30 |  1,747,261 | 1,234,880   |
| $1,000,000 |   12  |   8   |
| $20,000  | 13 |   9   |
| $4,000 | 180 | 125  |    
| $200  |  188,597  | 133,549 |

I was able to overcome this in the UDTable by using a RegEx object as a calculated property for the Sort-Object cmdlet:
```
New-UDTable -Title "Prize Information" -BackgroundColor "#2C3446" -FontColor "#FB667A" -Headers @("Prize", "At Start", "Remain") -Endpoint {
        $Cache:GridData = $data | Sort -Property @{Expression={ [int][RegEx]::Match($_.Prize, "(?:\d+)").captures.groups[1].value } }  |  Select Prize, 'At Start', Remain
        $Cache:GridData | Out-UDTableData -Property @("Prize", "At Start", "Remain")       
    }             
```
The table came out perfectly, even though it was already sorted and the RegEx is ***wrong*** ha. In regards to the UDGrid, I just don't know to overcome that one because implementing the same trick didn't work. 

I know your documentation and your examples on poshud are amazing, but when dealing with numeric strings or trying to illustrate big integers in a readable fashion, there's has to be some possible "natural ordering" applied. Or maybe not have the data auto sort when it comes in. I don't know. Let me know what you think and sorry for this long post. Thanks.

-Nicos

**Comment by psDevUK** [comment]
I'm connecting to SQL and the sorting of money values is perfect in the grid. Sorts exactly as I would expect. So most likely your variable datatype is wrong?

**Comment by nicoeat614** [comment]
@psDevUK with SQL, are you using the custom variables such $sortcolumn and using a custom query?? Without specifically using SQL, let's say you tried to sort files in a directory, have you tried that before?

**Comment by adamdriscoll** [comment]
This is resolved in the current v3 branch. The new UDTable now separates the rendering from the sorting so you can present data however you want and still allow the sorting to work as you would expect.
