### ISSUE TITLE
-TextSize Param on New-UDCard Crashes Dashboard

### ISSUE THREAD

**Issue by L-Skywalker** [ironmansoftware/universal-dashboard#403]
When attempting to use New-UDCard any time I try to specify the -TextSize parameter the dashboard crashes.

Example Command:

New-UDCard -Title 'General Failure Rate' -TextAlignment 'Center' -TextSize 'Large' @Colors -Content{ Write-Output "Hello World"}

**Comment by psDevUK** [comment]
I have used this parameter without issues. Does this happen all different browsers Ie,chrome,Firefox etc?  Just to confirm are you using latest module version, have you tried any other version to see if it happens there too?  I’m using latest version and all ok for me

**Comment by L-Skywalker** [comment]
I am on 2.0.1 I actually just started with this module a few days ago. I've tried numerous combos to recreate and narrow it down and every time I add the textsize param it crashes.

**Comment by L-Skywalker** [comment]
I should clarify that it is only when using New-UDCard that it crashes.

**Comment by L-Skywalker** [comment]
Also, I get an error:

"Process is terminated due to StackOverflowExecption."

**Comment by adamdriscoll** [comment]
@L-Skywalker Please reopen if the build does not fix the issue.
