### ISSUE TITLE
Initial Get when visiting IIS site receives a 404 when site is not default site (wwwroot)

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#407]
So this is a fun one, I always thought that Universal Dashboard didn't support IE11, but it seems that Disabling Friendly HTTP Error messages actually makes it work.

Looking in the developer tools, I see that the Initial http get when going to my page, gets a 404, regardless of browser, but in IE with Friendly HTTP error codes enabled (default), you get a 404.

The response body in the request that gets 404'd is this:

`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>PowerShell Universal Dashboard</title>
</head>
<body>
    <div id="app" class="app"/>
<script type="text/javascript" src="/main.aabfabb0b15f0a170afa.bundle.js"></script></body>
</html>`

Is there something that needs to be edited?

**Comment by PorreKaj** [comment]
I just created a new IIS site, to rule out any of the HTTPS, URL redirect, and other settings I made on the original site.
As you can see on the screenshot below, the initial requests 404's, but continues to load the page, which is fine, unless Friendly HTTP Error codes in IE11 is enabled, which it is by default, then it stops loading when it hits the 404.

![image](https://user-images.githubusercontent.com/20628942/47603495-de4e9000-d9ec-11e8-8775-dcfc5b3bd283.png)

**Comment by adamdriscoll** [comment]
@PorreKaj This will be fixed in the next version. 

Was fixed in commit: https://github.com/ironmansoftware/universal-dashboard/commit/af0b108b556c8dfc4235f41a3ee05c5f6d730c78

If you grab latest from AppVeyor you can try it out: https://ci.appveyor.com/project/adamdriscoll/universal-dashboard/builds/19845755
