### ISSUE TITLE
UDColumn isn't refreshing

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#41]
Hi,

I want to refresh a UDCard and since there is no param for that on it, I resfresh the UDColumn : 
```
New-UDColumn -AutoRefresh -RefreshInterval 5 -Size 1 -Content {
               $status = Get-Status  # Returns "Online" by default, and $null in other cases
               if($status -eq "Online")
               {
                  New-UDCard -Title "Directory Status" -Text "$(Get-Random -Minimum 0 -Maximum 100)"
               }
               else
               {
                  New-UDCard -Title "Directory Status" -Text "Offline"
               }
                  
            }
```

This example displays the first random, but then, never changes. So I assume the Refresh doesn't work?

Thanks

**Comment by adamdriscoll** [comment]
@Phyziik @Crowbar3 The `-Content` parameter is always static content. Try specifying `-Endpoint` rather than content. 

The parameter sets need to be fixed to prevent you from specifying AutoRefresh with Content. 

```
   New-UDColumn -Size 4 -AutoRefresh -Endpoint {
         $servername = "test"
                 try {
                     $Ping = Test-Connection -ComputerName $servername -Count 1 -ErrorAction Stop
                     New-UDCard -Title "Server is online!" -BackgroundColor darkgreen -FontColor white -Text $servername
                     }catch {
                     New-UDCard -Title "Server is offline!" -BackgroundColor darkred -FontColor white -Text $servername
                     }
         }
```

**Comment by Phyziik** [comment]
Well, that might have been my mistake, I was playing around with Endpoint and Content. Felt like I understood that Endpoint was refreshed and content was static, but I wasn't getting that behavior.

All in all, it works with Endpoint.

Thanks for that!
