### ISSUE TITLE
Improve form input validation (ValidateLength, ValidatePattern, etc.)

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#417]
Please improve form input validation methods.

I want to use UD as a day-to-day tool but currently with the actual limitations of the forms I cannot. In my scenario, this is a blocker for broadly adoption in the company I work for and the companies I work with.

ValidateLength, and ValidatePattern decorators make the form hang when they are triggered.

I haven't tested all the decorators but what I need is:
   - Length validation,
   - Regex pattern validation,
   - Range validation (~ValidateRange)
   - Null or emptiness  (~ValidateNotNullOrEmpty)
   - ValidateSet : worked today in the actual implementation. But it would be great if you could provide a mecanism to make it more dynamic. I mean it's not easy to pass a dynamically constructed list of values. 

It would be awesome if the validation occured on the client side. 
Thanks Adam! ;-)

**Comment by adamdriscoll** [comment]
Check this out: 

![validation](https://user-images.githubusercontent.com/1256531/48316294-1a622300-e59f-11e8-9cfb-7b009c6ebf92.gif)

```
New-UDInput -Title 'Test' -Endpoint {
     param(
                [ValidatePattern('.*Rules.*')]
                $String
     )
}
```

It doesn't actually work client side but it will work with any validation attribute. I have a bit more work but would love your feedback. If you want to play with it, try the latest build here: https://ci.appveyor.com/project/adamdriscoll/universal-dashboard/builds/20213996
