### ISSUE TITLE
Display a recap when submitting a form

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#418]
It would be very cool to have like a recap form already made to show a user when he press "submit" in a form. 

The recap form would display all the user input he made when filling up the form. This is a task I always do, but it could save me some work if UD had this functionnality.

Furthermore the recap page would offer 2 buttons: one for an ultimate validation, one for cancelling

Please also provide a way to redirect the user whenever he clicks a button or show a toast (or both).

**Comment by adamdriscoll** [comment]
Rolling into #737
