### ISSUE TITLE
New-UDGrid/ServerSideProcessing

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#42]
No navigation bar is showing up.

<img width="1592" alt="screen shot 2018-03-16 at 6 01 37 pm" src="https://user-images.githubusercontent.com/9411143/37548250-7fa74884-2944-11e8-817a-b1c2ea26953a.png">

**Comment by mkellerman** [comment]
If I remove the -ServerSideProcessing, and do a query that returns more than 10 records, the navigation shows up.

**Comment by adamdriscoll** [comment]
@mkellerman Can you try setting TotalItems on Out-UDGridData? 

```
$totalRows = Invoke-SqlCmd "SELECT COUNT(*) FROM xyz"
Invoke-SqlCmd "SELECT * FROM xyz" | Out-UDGridData -TotalItems $totalRows
```

**Comment by mkellerman** [comment]
Will do a test today

On Mar 22, 2018, at 7:18 AM, Adam Driscoll <notifications@github.com<mailto:notifications@github.com>> wrote:


@mkellerman<https://github.com/mkellerman> Can you try setting TotalItems on Out-UDGridData?

$totalRows = Invoke-SqlCmd "SELECT COUNT(*) FROM xyz"
Invoke-SqlCmd "SELECT * FROM xyz" | Out-UDGridData -TotalItems $totalRows

**Comment by adamdriscoll** [comment]
After some more testing, I found that Invoke-SqlCmd was not returning a scalar value. This test passes integration:

```
$Dashboard = New-UDDashboard -Title "5k Downloads!" -Content {
    New-UDGrid -Title "Tweets" -Headers @("Id","User Name", "Tweet", "Date Time") -Properties @("id", "user", "tweet", "datetime") -Endpoint {
        $Count = (Invoke-SqlCmd -Database twitter -Query "SELECT COUNT(*) as tweetCount FROM tweets").tweetCount
        Invoke-SqlCmd -Database twitter -Query "SELECT id, [user], tweet, datetime FROM tweets WHERE id LIKE '%$filterText%' ORDER BY $sortColumn OFFSET $skip ROWS FETCH NEXT $take ROWS ONLY"  | Out-UDGridData -TotalItems $Count
    } -ServerSideProcessing -PageSize 4
}

Start-UDDashboard -Dashboard $Dashboard -Port 10001
```

I fixed the issue where piping Invoke-SqlCmd to Out-UDGridData (#43) didn't work so try adjusting accordingly but the above script works fine with the 1.5.2 code base.
