### ISSUE TITLE
Hidding the hamburger menu

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#421]
How to hide it? It should be possible to create pages that are not linked to the hamburger menu. 

That would offer the ability to display another menu bar (let say horizontally) and link the pages manually.

Today I think it's not possible to create a page that is not linked to the hamburger menu, right?

**Comment by ArtisanByteCrafter** [comment]
I'll drop this here in case anyone wants to know how to do this in v2.3

From `Get-Help New-UDSideNav -Full`

```
    -------------------------- Example 2 --------------------------

    $Page1 = New-UDPage -Name "Page Name" -Content { New-UDCard -Id 'page-1' }
    $Page2 = New-UDPage -Name "Page Name 2" -Content { New-UDCard -Id 'page-2'}

    $Navigation = New-UDSideNav -None

    New-UDDashboard -Title "Navigation" -Pages @($Page1, $Page2) -Navigation $Navigation

    Hides the side navigation menu and hamburger icon.
```

**Comment by adamdriscoll** [comment]
Full docs are here too: https://docs.universaldashboard.io/components/navigation
