### ISSUE TITLE
New-UDTheme cmdlet disappeared in v2.0.1

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#422]
Before updating to v2.0.1 I had a dashboard running in 1.6.1 that used New-UDTheme.

Apparently New-UDTheme is not accessible anymore in v2.0.1. Hence my dashboard is broken :-(

```PowerShell
Get-Command -Module universaldashboard -name New-UdTheme

get-command : The term 'New-UdTheme' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

My machine is running under Windows Server 2012R2 with Windows PowerShell 5.1.
.Net Framework version:

```Powershell
PS > Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\'


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full


Name                           Property
----                           --------
1033                           Version       : 4.7.02053
                               CBS           : 1
                               TargetVersion : 4.0.0
                               Install       : 1
                               Servicing     : 0
                               Release       : 460805
```

**Comment by adamdriscoll** [comment]
@apetitjean Do you have .NET 4.7.2 installed?

**Comment by apetitjean** [comment]
It's 4.7. See in my original message for the details.

What's is strange though, is I have the exact same version number on my WS2016 machine and UD works very well.
For the records, some other commands are missing as well, such as Start-UDDashboard.

**Comment by adamdriscoll** [comment]
Whoops. Sorry. I'm blind sometimes ;) 

Can you please check the Release number on the WS2016 box? MSFT doesn't update the Version to 4.7.2. They only update the Release number. 👎 

Here is the release number that UD will be checking for in the next version. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/UniversalDashboard.psm1#L4

This page has a list of release numbers: 

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by apetitjean** [comment]
Yep you were right Adam! It was a matter of .Net Framework version number.

It works much better with .Net Framework 4.7.2.

Here's what I have now on my WS2012R2 box:
```
    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full


Name                           Property
----                           --------
1033                           Version       : 4.7.03062
                               CBS           : 1
                               TargetVersion : 4.0.0
                               Install       : 1
                               Servicing     : 0
                               Release       : 461814
```

So yes,  testing .Net version to be at least 461814 sounds good.
Thanks Adam
