### ISSUE TITLE
Out-UDGridData/DataTable

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#43]
Out-UDGridData is not accepting Invoke-SqlCmd result directly.

$Query = "SELECT id, name, text FROM table WHERE text LIKE '%$filterText%' ORDER BY $sortColumn $sortOrder OFFSET ($skip) ROWS FETCH NEXT ($take) ROWS ONLY " 
$Result = Invoke-SqlCmd -Query $Query
$Result | Out-UDGridData

A workaround is to do a Select-Object, and specify the fields:

$Result = Invoke-SqlCmd -Query $Query
$Result | Select-Object id, name, text | Out-UDGridData

**Comment by adamdriscoll** [comment]
This is fixed in 1.5.2
