### ISSUE TITLE
How to do a stacked bar chart?

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#435]
Thinking my data would be better displayed in a stacked bar chart, but cannot figure how I would accomplish this? I know I need to use the bar chart setting, and I found the following on chartjs:-
var stackedBar = new Chart(ctx, {
    type: 'bar',
    data: data,
    options: {
        scales: {
            xAxes: [{
                stacked: true
            }],
            yAxes: [{
                stacked: true
            }]
        }
    }
});
 So I tried using the x and y axes in the options of the chart but couldn't get it to work. Can you please be so kind to provide an example of how to do a stacked bar chart please?

**Comment by adamdriscoll** [comment]
@psDevUK I added a section to the docs for this: https://docs.universaldashboard.io/components/charts#stacked-bar-charts

Hope that works!
