### ISSUE TITLE
Overriding the Default UDButton Color

### ISSUE THREAD

**Issue by nicoeat614** [ironmansoftware/universal-dashboard#437]
This is probably a stupid question, but is there anyway to change the default color of the buttons in UDButton or -type Select of the New-UDInputField from the green to something else? Thanks.

**Comment by urskog84** [comment]
I suggest you use CSS site for this.  
Pleas read -> https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/themes.html

```
$theam = New-UDTheme -Name "Basic" -Definition @{
    '.btn'      = @{
        'color'            = "#555555"
        'background-color' = "#f44336"
    }

$MyDashboard = New-UDDashboard -Title "Hello, World" -Pages @($page1) -Theme $theam

```

**Comment by nicoeat614** [comment]
Thanks @urskog84. That worked. I already had a New-UDTheme in place and have been over-thinking things. I didn't think to do it within the definition block.

**Comment by artvandelay440** [comment]
Also, to update the button's hover class:

```
'.btn:hover'      = @{
        'color'            = "#ffffff"
        'background-color' = "#C70303"
    }
```

**Comment by nicoeat614** [comment]
@artvandelay440 yeah I did that on the day that I submitted this. I appreciate the feedback!!!
