### ISSUE TITLE
New-UDElement event handler does not work within UDGrid

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#44]
Related to #40

**Comment by adamdriscoll** [comment]
Moving to 1.6.0 because this is way more than a simple bug fix.

**Comment by BryanDM** [comment]
Adam,

I believe i'm experiencing this issue within UDCollapsible as well. onClick works fine outside, but inside it does not.

**Comment by adamdriscoll** [comment]
@BryanDM That will be fixed in 1.6.0 as well.

**Comment by adamdriscoll** [comment]
Implemented in 1.6.0
