### ISSUE TITLE
Request to add -OpenInNewWindow to Invoke-UDRedirect

### ISSUE THREAD

**Issue by artvandelay440** [ironmansoftware/universal-dashboard#440]
Sometimes it's super handy to have a quick button link, like so:

```
New-UDButton -Flat -Text "Google" -IconAlignment left -Icon link -OnClick {
    Invoke-UDRedirect -Url 'https://www.google.com/'
}
```

It works great, but I wonder if it's possible to add something like `New-UDLink`'s `-OpenInNewWindow` parameter?

**Comment by adamdriscoll** [comment]
Yep. Should be possible. Right now we are just setting the location.href which changes the current location but if we used window.open we could open a new tab. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/client/src/app/ud-dashboard.jsx#L109

https://developer.mozilla.org/en-US/docs/Web/API/Window/open
