### ISSUE TITLE
Enhancement Request: Migrate "font-awesome" to "fortawesome/fontawesome"

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-dashboard#455]
Looks like the NPM "font-awesome" is 2 years old. There are a lot more icons available in the new NPM package for Font Awesome: "fortawesome/fontawesome-free"

**Font Awesome Documentation** : https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

It just so happens that a lot of the icons I want to use are in the new package 🤷‍♂️

**Comment by PorreKaj** [comment]
Crossing my fingers for getting this in 2.3.
There's many good new icons :-)

**Comment by BlueArcherX** [comment]
This would be great! I would love to use the new 7x and 9x sizes for some of my projects.

**Comment by AlonGvili** [comment]
@BlueArcherX you can use it already in the 2.4 beta

_Sent from my P20 Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BlueArcherX** [comment]
I might be doing something wrong, but I have loaded 2.4-beta1, and it still has the FA 4.7 and 7x, 9x aren't working.  Would love to see FA 5.0.

**Comment by adamdriscoll** [comment]
New-UDIcon now uses the 5.0 fortawesome library. Will be available in 2.4-beta2
