### ISSUE TITLE
Easy way to link to JavaScript and CSS CDN's

### ISSUE THREAD

**Issue by randalleverhart** [ironmansoftware/universal-dashboard#458]
Looking for a way to link to CDN in order to use New-UDElement and implement other libraries. In this instance, I'm trying to utilize [QuillJS](https://quilljs.com/docs/quickstart/) in order to implement a rich text editor into my UD application. 

I've attempted using New-UDHtml and using the -Markup parameter, but that didn't work when creating the <div> via like... New-UDElement -Tag 'div' -Attributes @{'id' = 'editor'} -Content {'test'}

Not really an issue, just curious if this feature has been implemented yet, or if it's even possible with pure PowerShell.

**Comment by adamdriscoll** [comment]
This is a hack...but I made this UDJSLoader component awhile ago. It lets you run any javascript you want. 

[udjsloader.zip](https://github.com/ironmansoftware/universal-dashboard/files/2567689/udjsloader.zip)

```
 New-UDHTML -Markup '<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">'
    New-UDHTML -Markup '<div id="editor"></div>'
    New-UDElement -JavaScriptPath "$PSScriptRoot\udjsloader.js" -ModuleName "UDJSLoader" -Properties @{
        "javascript" = "
        var script = document.createElement('script');
        script.onload = function() {
            var quill = new Quill('#editor', {
                theme: 'snow'
            });
        }
        script.src = 'https://cdn.quilljs.com/1.3.6/quill.js';
        document.head.append(script);


        "
    }
```

![image](https://user-images.githubusercontent.com/1256531/48291131-e837b080-e43a-11e8-887f-96b7522f1fce.png)
