### ISSUE TITLE
Adding Materialize functionality not yet implemented in UD

### ISSUE THREAD

**Issue by camusicjunkie** [ironmansoftware/universal-dashboard#463]
What is the best way to implement new functionality in to Universal Dashboard? Let's take Tabs for example. Since Tabs is not yet in UD I'm trying to create them using New-UDElement. At the very bottom is the code I've written but it doesn't really work as expected.

In all browsers I get the output below except for Edge. In Edge it actually works as expected. Another weird interaction that is seemingly random is that sometimes on an autoreload, after a save of the dashboard, the broken browsers will display the correct output. As soon as I manually refresh the page it goes back to the image below.

Any help would be greatly appreciated.

### **Edge:**

![image](https://user-images.githubusercontent.com/33888807/48398407-eccfc380-e6dd-11e8-8f97-84f04b488861.png)
### **Other Browsers (Chrome, Firefox, IE)**

![image](https://user-images.githubusercontent.com/33888807/48398187-513e5300-e6dd-11e8-80c6-a10b5d43d2f7.png)

```powershell
Start-UDDashboard -Dashboard (
    New-UDDashboard -Title "TEST" -Content {
        New-UDElement -Tag "div" -Attributes @{
            className = "row container"
        } -Content {
            New-UDElement -Tag "div" -Attributes @{
                className = "col s12"
            } -Content {
                New-UDElement -Tag "ul" -Attributes @{
                    className = "tabs"
                } -Content {
                    New-UDElement -Tag "li" -Attributes @{
                        className = "tab col s6"
                    } -Content {
                        New-UDElement -Tag "a" -Attributes @{
                            href = "#tab1"
                        } -Content {
                            "Tab 1"
                        }
                    }
                    New-UDElement -Tag "li" -Attributes @{
                        className = "tab col s6"
                    } -Content {
                        New-UDElement -Tag "a" -Attributes @{
                            href = "#tab2"
                        } -Content {
                            "Tab 2"
                        }
                    }
                }
            }
            New-UDElement -Id "tab1" -Tag "div" -Attributes @{
                className = "col s12"
            } -Content {
                "Tab 1 Content"
            }
            New-UDElement -Id "tab2" -Tag "div" -Attributes @{
                className = "col s12"
            } -Content {
                "Tab 2 Content"
            }
        }
    }
) -AutoReload -Port 8080
```

**Comment by adamdriscoll** [comment]
Honestly, there isn't a good way to this without writing some custom JavaScript. The problem is that the tabs need to be initialized via the `tabs()` function call. 

```
  $(document).ready(function(){
    $('ul.tabs').tabs();
  });
```
You could do this with a custom JS component but it's a hairy API that doesn't work very well. 

https://docs.universaldashboard.io/components/custom-components/javascript-elements

You could also use this hack that I developed awhile back: https://github.com/ironmansoftware/universal-dashboard/issues/458

I hope to make a much better JS API to bring in custom components in the near future to make it way easier to do this kind of stuff.

**Comment by camusicjunkie** [comment]
I apologize in advance for my ignorance and lack of proper terminology but I've only just barely scratched the surface of web development. Looking through the repo though it looks as though you've implemented some things in to UD that require initialization like the collapsible, select, or modals to name a few. Could tabs not be implemented in a similar way? Does it require a new React component?

**Comment by camusicjunkie** [comment]
Closing this issue. Moved to https://forums.universaldashboard.io/t/adding-materialize-functionality-not-yet-implemented-in-ud/79
