### ISSUE TITLE
Multiple counters in a table

### ISSUE THREAD

**Issue by BisherSH** [ironmansoftware/universal-dashboard#465]
Hello,
Im trying to populate multiple performance counters in a table , but it is taking long time to load .
I tried to start each get-counter command using Start-Job but it didnt work

Could you please point me to the right direction

**Comment by psDevUK** [comment]
Look at New-UDEndpointSchedule and New-UDEndpoint to decrease the amount of time it takes your counters to load.  Using these allows you to use the $Cache scoping which really does improve proformance. This is all documented https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/endpoints/scheduled-endpoints.html happy reading

**Comment by BisherSH** [comment]
It worked , thank you so much 👍 :)

**Comment by BisherSH** [comment]
> 
> 
> It worked , thank you so much 👍 :)

Well , after testing it looks line not working correctly ,
the dashboard freezes when I added more counters for multiple servers

I will keep trying

**Comment by BisherSH** [comment]
Im trying the following code but it is not working correctly,
some times it gives error , some times it works , some times it freezes ! 
could you help please ?

Get-UDDashboard | Stop-UDDashboard
$Schedule = New-UDEndpointSchedule -Every 90 -Second 

$Endpoint = New-UDEndpoint -Schedule $Schedule -Endpoint {


$MBXServers = "MBX01","MBX02","MBX03","MBX04"
$ExTrCounters = @()
$OutCounters = @()
$ExTrCounters = 
                    ("MSExchange ActiveSync","Requests/sec","","1000"),
                    ("MSExchange ActiveSync","Sync Commands/sec","","1000"),
                    ("MSExchange ActiveSync","Ping Commands Pending","","1000"),
                    ("MSExchange RpcClientAccess","Connection Count","","20000"),
                    ("MSExchange RpcClientAccess","RPC Averaged Latency","","250"),
                    ("MSExchange RpcClientAccess","RPC Requests","","40"),
                    ("MSExchange Database","Database Page Fault Stalls/sec","Information Store","0"),
                    ("MSExchange Database","Log Record Stalls/sec","Information Store","10"),
                    ("MSExchange Database","Log Threads Waiting","Information Store","10"),
                    ("MSExchange Database","I/O Database Reads Average Latency","Information Store","50"),
                    ("MSExchange Database","I/O Database Writes Average Latency","Information Store","100"),
                    ("MSExchange Database","I/O Database Reads/sec","Information Store","9999999"),
                    ("MSExchange Database","I/O Database Writes/sec","Information Store","9999999"),
                    ("MSExchange Submission Store Driver","Outbound: Submitted Mail Items Per Second","","200"),
                    ("MSExchange Submission","Failed Submissions Per Second","","0"),
                    ("MSExchange Submission","Successful Submissions Per Second","","200"),
                    ("MSExchange Submission","Pending Submissions","","50"),
                    ("MSExchange Submission Store Driver Database","Submission attempts per minute over the last 5 minutes","_total","200"),
                    ("MSExchange Submission Store Driver Database","Submission failures per minute over the last 5 minutes","_total","0"),
                    ("MSExchangeIS Store","Messages created/sec","_total","1000"),
                    ("MSExchangeIS Store","Messages deleted/sec","_total","1000"),
                    ("MSExchangeIS Store","Messages opened/sec","_total","1000"),
                    ("MSExchangeIS Store","Messages delivered/sec","_total","1000"),
                    ("MSExchangeIS Store","Messages submitted/sec","_total","1000")

 foreach ($item in $ExTrCounters)
        {
          $OutCounters += @([pscustomobject]@{

        'Counter' = "$($item[1])".Trim();
        'MBX01' = [int](Get-Counter "\$($item[0])($($item[2]))\$($item[1])" -ComputerName $MBXServers[0] -ErrorAction SilentlyContinue).CounterSamples.CookedValue; 
        'MBX02' = [int](Get-Counter "\$($item[0])($($item[2]))\$($item[1])" -ComputerName $MBXServers[1] -ErrorAction SilentlyContinue).CounterSamples.CookedValue; 
        'MBX03' = [int](Get-Counter "\$($item[0])($($item[2]))\$($item[1])" -ComputerName $MBXServers[2] -ErrorAction SilentlyContinue).CounterSamples.CookedValue;
        'MBX04' = [int](Get-Counter "\$($item[0])($($item[2]))\$($item[1])" -ComputerName $MBXServers[3] -ErrorAction SilentlyContinue).CounterSamples.CookedValue 
})
}

$Cache:Counter = $OutCounters} 

$Dashboard = New-UDDashboard -Title "Test" -Content {New-UDTable -Title "Test" -Headers @("Counter","MBX01","MBX02","MBX03","MBX04") -Endpoint {$Cache:Counter|Out-UDTableData -Property @("Counter","MBX01","MBX02","MBX03","MBX04")} -AutoRefresh -RefreshInterval 100}
Start-UDDashboard -Endpoint $Endpoint -Dashboard $Dashboard -Port 1004

**Comment by adamdriscoll** [comment]
Can you please continue this conversation on the forums? I do not believe this to be a bug with UD.
