### ISSUE TITLE
Table cell color

### ISSUE THREAD

**Issue by BisherSH** [ironmansoftware/universal-dashboard#469]
Hi,

Is there a way to change a cell color in a table ?

**Comment by adamdriscoll** [comment]
There currently isn't a way to do this directly with UDTable. You could use New-UDElement to create an element with the background of your choosing within the  cell.

**Comment by adamdriscoll** [comment]
Here's an example of what I'm talking about: https://forums.universaldashboard.io/t/coloring-elements-in-a-table-based-on-a-property/57

**Comment by BisherSH** [comment]
I will definitely try that, 
Many thanks
