### ISSUE TITLE
Case-Sensitive Properties for Grids and Tables

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#471]
More information on potential fixes for this issue here: https://forums.universaldashboard.io/t/case-sensitive-udgrid-sorting/2152

**Comment by dtnyc9005** [comment]
The issue can be reproduced if the ComputerName property is renamed to Computername

`

      $cache:CollectionNew = @(
       foreach ($item in $cache:500sColNew) {

     [PSCustomObject]@{
         ComputerName = $item.ComputerName
         Sitename     = $item.Sitename
         State        = $item.state
         Found        = $item.found
         Count500s    = $item.Count
         AppPoolName  = $item.AppPoolName
         AppPoolState = $item.AppPoolState
         ActionOption = (New-UDSelect -Option {New-UDSelectOption -Name "Restart AppPool" -Value 1; New-UDSelectOption -Name "IIS Reset" -Value 2; New-UDSelectOption -Name "Restart Server" -Value 3 } )
         Action       = (New-UDButton -Text "Do This..." -OnClick {})
     }
 }
)

`

PSVersion 5.1.14409.1012
UD 2.1.0.281 | Enterprise
.NET 4.7.2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/case-sensitive-udgrid-sorting/2152/1
