### ISSUE TITLE
UD Dashboard and highlighting services that are stopped in red

### ISSUE THREAD

**Issue by patgn3** [ironmansoftware/universal-dashboard#472]
I have a script that produces the output of a service on servers via out-udtabledata but I was wondering what the logic would be to get the service that is stopped to be highlighted in red.
here is the output example
![image](https://user-images.githubusercontent.com/17296341/48495855-d66d5900-e7fe-11e8-9604-bde3903d682b.png)

here's the script....

Get-UDDashboard | Stop-UDDashboard
###########
$ud_sqlserver = new-uddashboard -title "SQL Service" -color "red" -content {

    New-udtable -title "SQL Agent Service" -headers @("SystemName", "Name", "Displayname", "State")  -endpoint {

        $r = get-content c:\hold\_powershell\vsc\rfile.txt
        foreach ($s in $r) {
            Get-ciminstance Win32_Service -computername $s -Filter "displayname LIKE '%sql server agent%'" |  Where-Object {$_. displayname -match 'sql server agent' -AND $_. Name -ne 'sqlagent$Trackit'} | foreach-object {
                [pscustomobject]@{
                    SystemName  = $_.SystemName
                    Name        = $_.name
                    displayname = $_.DisplayName
                    state       = $_.State
                    start       = New-UDButton -text "start" -OnClick {$_ | invoke-cimmethod -name startservice}
                    stop        = new-udbutton -text "stop" -onclick {$_ | Invoke-CimMethod -name stopservice }

                }
            }    |out-udtabledata -Property @("SystemName", "Name", "Displayname", "State", "Start", "Stop")

        }
        ###
    } -style highlight -AutoRefresh -RefreshInterval 3
}
start-uddashboard -port 10007 -dashboard $ud_sqlserver

**Comment by AlonGvili** [comment]
This is the part you need to change in your script

```powershell
                    state       = if($_.State -eq 'Running'){
                        # I use materializeCSS className for Background color and Text color
                        New-UDElement -Tag 'p' -Attributes @{className='green white-text'} -Content {$_.State.toString()}
                    }else{
                        New-UDElement -Tag 'p' -Attributes @{className='red white-text'} -Content {$_.State.toString()}
                    }
```

**Comment by patgn3** [comment]
That did it.....awesome.   thank you for your knowledge

**Comment by AlonGvili** [comment]
My pleasure 👍
