### ISSUE TITLE
SSO via IIS and Active Directory

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#474]
Requirements 

- Single sign-on into UD without a logon page
- Ability to restrict certain pages within UD to particular groups

**Comment by Juanito99** [comment]
Please also for the REST endpoint :smile:

**Comment by PorreKaj** [comment]
I'm excited to see how this pans out.

**Comment by adamdriscoll** [comment]
This has been completed for UD 2.2. You will be able to take advantage of IIS Windows Auth for both dashboards and REST APIs. 

![iisosso](https://user-images.githubusercontent.com/1256531/49760273-45649300-fc81-11e8-86d1-646646ba25e3.gif)
