### ISSUE TITLE
New-UDSelect OnChange inconsistent Value with MultiSelect

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#482]
I have created the following UDSelect

            New-UDSelect -Id "State" -Label "State" -Option {
                New-UDSelectOption -Name "Basic" -Value 1
                New-UDSelectOption -Name "Cost Management" -Value 2 -Selected
                New-UDSelectOption -Name "Operations Management" -Value 3
                
            } -OnChange{
            Show-UDToast -Message $EventData -Title "EventData" -Position "topRight"
            } -MultiSelect

But when clicking through the select options the result of $EventData is inconsistent. Sometimes I get only the first value regardless of the other values, sometimes I get the correct value. But in all cases, if I select multiple values only 1 of the values is returned.

Also notice in the GIF below, when selecting Value 1, then selecting others, if I unselect Value 1 the entire Select collapses, but if the select option in $EventData is still selected I can continue to select and the select menu does not disappear.

![multi-select](https://user-images.githubusercontent.com/22712034/48621526-bad68f80-e971-11e8-82c6-729fb706c52b.gif)

**Comment by adamdriscoll** [comment]
Ewww. 👎 Will take a look.
