### ISSUE TITLE
Expose Authorization Policy

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#491]
Would be nice to expose the Users Authorization Policy to use throughout the UD Page. Example

$AuthorizationPolicy = New-UDAuthorizationPolicy -Name "Admins" -Endpoint {
    param($User)

    $User.HasClaim("Groups", "a34efc00")
}

Then have the ability to use the users Policy to enable/disable elements within the page.
**_$userpolicy = Get-UDAuthorizationPolicy_** 
if ($userpolicy -eq "Admins") {
New-UDButton
} else {
New-UDHeading "No button because you are not an Admin"
}

**Comment by Jacob-Evans** [comment]
Would love to see this come to pass. Especially with the new navigation options being able to hide pages from people who don't have access to the pages.
