### ISSUE TITLE
UDJSLoader is not defined

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#495]
Upgraded my project to v2.2.0-beta1, and UDJSLoader stopped working.

![image](https://user-images.githubusercontent.com/9411143/48807884-cf998700-ecd3-11e8-8846-c7e42c7ea13a.png)

**Comment by adamdriscoll** [comment]
I removed the need for this. You can update your `New-UDDropdown` function like this: 

```
function New-UDDropdown {
            param(
                [Parameter()]
                [string]$Id,
                [Parameter()]
                [string]$Text,
                [Parameter()]
                [ScriptBlock]$Content
            )
        
            New-UDElement -Tag "a" -Id "btn$id" -Attributes @{ className = "dropdown-button btn"; href = "#"; "data-activates" = $Id} -Content { $Text }
            New-UDElement -Tag "ul" -Id $id -Attributes @{ className = "dropdown-content"} -Content {
                $Content.Invoke()
            }

            New-UDElement -Tag 'div' -OnMount "`$('.dropdown-button').dropdown({constrainWidth: false})" -Content {} -Attributes @{ display = "none"} 
        }
```

UDJSLoader has been replaced with the `New-UDElement` `-OnMount` parameter that lets you run any JS you want after the component has mounted.

**Comment by mkellerman** [comment]
Hi Adam,

I have beta2 installed.. and getting this error:

[cid:410252DC-FCFA-4936-B73D-4665A88865D4]

Should I be downloading a special release?

In the mean time, I’ve improvised, and doing a collapsible item list with buttons.. hehe.

[cid:E6D05074-7289-4A2E-9BC7-FA584C457A05]

Marc

On Dec 6, 2018, at 3:06 PM, Adam Driscoll <notifications@github.com<mailto:notifications@github.com>> wrote:


I removed the need for this. You can update your New-UDDropdown function like this:

function New-UDDropdown {
            param(
                [Parameter()]
                [string]$Id,
                [Parameter()]
                [string]$Text,
                [Parameter()]
                [ScriptBlock]$Content
            )

            New-UDElement -Tag "a" -Id "btn$id" -Attributes @{ className = "dropdown-button btn"; href = "#"; "data-activates" = $Id} -Content { $Text }
            New-UDElement -Tag "ul" -Id $id -Attributes @{ className = "dropdown-content"} -Content {
                $Content.Invoke()
            }

            New-UDElement -Tag 'div' -OnMount "`$('.dropdown-button').dropdown({constrainWidth: false})" -Content {} -Attributes @{ display = "none"}
        }


UDJSLoader has been replaced with the New-UDElement -OnMount parameter that lets you run any JS you want after the component has mounted.

**Comment by mkellerman** [comment]
Hi Adam,

I have beta2 installed.. and getting this error:

[cid:410252DC-FCFA-4936-B73D-4665A88865D4]

Should I be downloading a special release?

In the mean time, I’ve improvised, and doing a collapsible item list with buttons.. hehe.



Marc

On Dec 6, 2018, at 3:06 PM, Adam Driscoll <notifications@github.com<mailto:notifications@github.com>> wrote:


I removed the need for this. You can update your New-UDDropdown function like this:

function New-UDDropdown {
            param(
                [Parameter()]
                [string]$Id,
                [Parameter()]
                [string]$Text,
                [Parameter()]
                [ScriptBlock]$Content
            )

            New-UDElement -Tag "a" -Id "btn$id" -Attributes @{ className = "dropdown-button btn"; href = "#"; "data-activates" = $Id} -Content { $Text }
            New-UDElement -Tag "ul" -Id $id -Attributes @{ className = "dropdown-content"} -Content {
                $Content.Invoke()
            }

            New-UDElement -Tag 'div' -OnMount "`$('.dropdown-button').dropdown({constrainWidth: false})" -Content {} -Attributes @{ display = "none"}
        }


UDJSLoader has been replaced with the New-UDElement -OnMount parameter that lets you run any JS you want after the component has mounted.
