### ISSUE TITLE
Unable to adjust New-UDImageCarousel container height when *not* using the -FullWidth switch

### ISSUE THREAD

**Issue by pldmgg** [ironmansoftware/universal-dashboard#496]
Below tested on UniversalDashboard.Community 2.1.0 and 2.2.0-beta.

I'm using the `New-UDImageCarousel` cmdlet **without** the `-FullWidth` switch so that I get a small carousel with small square images. I'm trying to set the Carousel container's height to 100px (as opposed to its default 400px), but the `-Height` parameter only seems to work if you use the `-FullWidth` switch (which is **not** what I'm going for).

Since the `New-UDImageCarousel` cmdlet doesn't have an `-Attributes` parameter, I thought I would use `Set-UDElement` to ultimately get something like:

    <div id="CarouselA" class="carousel initialized" data-namespace="DIVCarouselAcarousel0" style="height: 100px;">

So, I tried the below on my test dashboard.

```powershell
New-UDRow -Endpoint {
    New-UDColumn -Size 4 -Endpoint {
        New-UDImageCarousel -Id "CarouselA" -Items {
            foreach ($Pic in $Cache:PicList) {
                $Slide = @{
                    BackgroundImage = "/AppAssets/$Pic.png"
                    BackgroundRepeat = 'no-repeat'
                    BackgroundSize = 'contain'
                    BackgroundPosition = '0% 0%'
                    BackgroundColor  = 'white'
                    Url  = "/Overview"
                }
                New-UDImageCarouselItem @Slide
            }
        }
        Set-UDElement -Id "CarouselA" -Attributes @{style = @{height = "100px"}}
    }
}
```

Unfortunately, the Carousel div doesn't get updated.

Is there a workaround to change the height of the Carousel container (small-square-image-style)? Am I using `Set-UDElement` properly?

**Comment by AlonGvili** [comment]
I need to look into this, no work around for this , adam can u tag it as a bug

**Comment by adamdriscoll** [comment]
This issue now has a bounty: https://www.bountysource.com/teams/ironmansoftware/issues?tracker_ids=84524150
