### ISSUE TITLE
Fix Performance Dashboard Example

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-dashboard#5]
[Performance Dashboard example's](https://github.com/adamdriscoll/poshprotools/blob/master/examples/universal-dashboard/server-performance-dashboard.ps1) disk usage bar chart (as published to [the gallery](https://www.powershellgallery.com/packages/server-performance-dashboard/)) is not showing as zero indexed, giving a false impression of the relative sizes of the total and used disk space.

**Comment by Chirishman** [comment]
Additional bug: if you leave the dashboard open for a while you will eventually get this error:
![2018-05-02 17_16_04-it ops dashboard](https://user-images.githubusercontent.com/7658840/39549666-b3fea246-4e2c-11e8-8905-681682c9d1ea.png)

**Comment by adamdriscoll** [comment]
The source for this is found here. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/examples/server-performance-dashboard.ps1

You should be able to just install UniversalDashboard from the gallery via `Install-Module UniversalDashboard` and then run this PS1 to test it out.

**Comment by adamdriscoll** [comment]
Bounty can be found here: https://www.bountysource.com/issues/54818717-fix-performance-dashboard-example
