### ISSUE TITLE
Color values of dataset are not recognized in New-UDNivoChart (2.2.0-beta2)

### ISSUE THREAD

**Issue by psott** [ironmansoftware/universal-dashboard#503]
As an example, this should give you 10 random colored pie charts, but it is allways the same color of the standard color set. Also tested with line chart.
````
1..10 | foreach{
    New-UDNivoChart -Id 'pieChart' -Pie -Height 600 -Width 600 -Data @(
    @{
        id = 'python'
        label = 'python'
        value = (Get-Random -Maximum 100 -Minimum 10)
        color = "hsl($(Get-Random -Minimum 1 -Maximum 359), 70%, 50%)"
    })
}
````
Parameter -Color <colorset> is working

**Comment by adamdriscoll** [comment]
This has been resolved. There will be a `-UseDataColor` switch to allow you to do that.
