### ISSUE TITLE
Switch to Material UI

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#506]
@AlonGvili and I have been floating the notion of replacing Materialize CSS with [Material UI](https://material-ui.com/). Some benefits of this migration:

- React-based library integrates well with UD as it is React-based
- Material UI offers more built in [components](https://material-ui.com/demos/app-bar/) 
- Material UI contains a [theme provider](https://material-ui.com/css-in-js/advanced/)

As an example of how well it integrates into UD, I made [a small patch](https://github.com/ironmansoftware/universal-dashboard/commit/99723805a5835f2215a69ae96529dfbb7a2bc94f) to the existing UD code-base to include Material-UI and adjust how UDElement works a bit (a hack for now). 

From there I was then able to use the Material UI element directly in UD with New-UDElement. 

```
Start-UDDashboard -Content {
    New-UDDashboard -Title "Material UI Test" -Content {

        $Style = @{
            margin = 12
        }

        New-UDElement -Tag 'MU-Button' -Attributes @{
            variant = "contained"
            style = $Style
            onClick = {
                Show-UDToast -Message 'Default' -Position topLeft
            }
        } -Content { "Default "}
        New-UDElement -Tag 'MU-Button' -Attributes @{
            variant = "contained"
            style = $Style
            color = 'primary'
            onClick = {
                Show-UDToast -Message 'Primary'  -Position topLeft
            }
        } -Content {
            "Primary"
        }
    }
} -Port 10001 
```

The event handlers even work!

![material-ui](https://user-images.githubusercontent.com/1256531/49606634-200a1900-f951-11e8-90f2-75c72cab4e37.gif)

This will likely be UD 3.0 work as I'm sure there will be breaking changes moving from one UI framework to another. 

Please review Material UI, chime in and let us know what you think!

PS: This will not affect UDChart, UDMonitor or UDNivoChart.

**Comment by artvandelay440** [comment]
I love the possibilities here. Do you know offhand if all of the existing features would be available using this new framework, or would we need to plan deprecations of certain things? (charts/grids/monitors/whatever)

Porting or re-coding these objects is fine, I'd just hate to have to remove existing functionality if they are not offered in Material-UI.

**Comment by adamdriscoll** [comment]
Charts, monitors, grids will all still be there. Some things might look a little different (like tables) but we hope to limit the breaking changes as much as possible.

**Comment by AlonGvili** [comment]
@artvandelay440 and you have new things like icon buttons with badge options, search field option in AppBar and so on..

![image](https://user-images.githubusercontent.com/34351424/49688646-ec301e80-fb1d-11e8-8c85-509b9134e450.png)

**Comment by dtnyc9005** [comment]
SICK.... love to see all this come to UD, awesome work guys!
