### ISSUE TITLE
Alternative menu (in addition to the hamburger menu)

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#51]
It would be cool to have multiple fashions to create menus. 

Hamburger menu are very cool and easy to use and create but I would like to have more choice. Like for example  this kind of very simple menu : https://www.hotjar.com/

Do you think you could implement it? Thanks and long life to UD!

**Comment by adamdriscoll** [comment]
You can now hide the menu with `New-UDSideNav -None` and then use the `-NavBarLinks` of `New-UDDashboard` to create a similar experience.
