### ISSUE TITLE
"On-Demand" Support? (Command to return raw HTML rather than run webserver)

### ISSUE THREAD

**Issue by JustinGrote** [ironmansoftware/universal-dashboard#511]
Hello,

Did a search and couldn't find anything related, but is it supported to make a universal dashboard, and just have it provide HTML on-demand from a cmdlet rather than running the Kestrel webserver?

I ask because I have a use case where running this in AWS Lambda or Azure functions would be extremely cost effective, so if I can just tie the function call to a cmdlet that will in turn generate the HTML to return for the request, it'd be better than standing up a bunch of different app services or containers to run the webserver.

Hope that makes sense, and not a big deal if I have to run it in App Service, it just would be great if "serverless" is a supported scenario.

**Comment by adamdriscoll** [comment]
You might be able to produce a dashboard that is more or less static HTML that you could expose via a serverless architecture but being that UD is so interactive, I think you'd run into problems.

You might want to check out [PSHtml](https://github.com/Stephanevg/PSHTML) for something like that.

**Comment by JustinGrote** [comment]
@adamdriscoll I assumed as much, just wasn't sure if I was missing something. Not a big deal, I'll have my function warm it up into a container first. Thanks!
