### ISSUE TITLE
Error starting dashboard with Windows Auth in IIS (2.2.0)

### ISSUE THREAD

**Issue by beb-bang** [ironmansoftware/universal-dashboard#513]
Just installed 2.2.0 and am trying to prototype the Windows Auth. The error in the stdout log file indicates a missing parameter name "Windows".  This makes me think I don't have the right version of the module but Get-Module tells me it's 2.2.0. The entire module is copied into the IIS site, license.lic added to the net472 and netstandard2.0, IIS configured, web.config updated (https://docs.universaldashboard.io/security/authentication/windows). 

I feel like I'm missing something obvious. Any suggestions would be appreciated!

Thx!
Bryan

```
Start-UDDashboard -Content {
    $Auth = New-UDAuthenticationMethod -Windows
    $LoginPage = New-UDLoginPage -AuthenticationMethod @($Auth) -PassThru

    New-UDDashboard -Title "Line" -Content { 
        New-UDRow -Columns {
            New-UDColumn -Size 12 -Endpoint  {
                New-UDHeading -Text "Logged in as $user"
            }
        }
    } -LoginPage $LoginPage 
} -Wait -AllowHttpForLogin
```

```
Starting Universal Dashboard service. 
 Dashboard Script: C:\inetpub\wwwroot\net472\..\dashboard.ps1 
 Assembly Base Path: C:\inetpub\wwwroot\net472\..\dashboard.ps1
Error starting dashboard: 
 A parameter cannot be found that matches parameter name 'Windows'. 
 at <ScriptBlock>, C:\inetpub\wwwroot\dashboard.ps1: line 11
at <ScriptBlock>, C:\inetpub\wwwroot\dashboard.ps1: line 10
at <ScriptBlock>, <No file>: line 1

Unhandled Exception: System.Exception: Failed to start dashboard
   at UniversalDashboard.DashboardManager.Start()
   at UniversalDashboard.Program.Main(String[] args)
```

**Comment by psott** [comment]
It is also important to install IIS first and then .Net Core. Otherwiese IIS is not able to interpret the web.config file. (that was the main bumper with my first iis prototype)

Have you double checked "Windows Authentication" in IIS sole services is enabled? 
And Windows Auth ist the only enabled Auth in your wegsite? First two screenshots: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2#iis-configuration)

**Comment by adamdriscoll** [comment]
@beb-bang Can you also make sure you don't have UD installed anywhere else on the machine? It does sound like you have an incorrect version somewhere.

It might be trying to load it from $PSModulePath or something.

**Comment by beb-bang** [comment]
Thank you @psott and @adamdriscoll. After another review everything still looked correct and IIS had been service 2.1.0 with Forms auth already. After performing some very aggressive purging of all copies of the Module and then Forcing a re-installation, Windows Auth is working! I suspect there may have been a side-by-side install of the v2.1.0 module somewhere. I couldn't find it in the $PSModulePath, but after a manual search and destroy I seemed to eliminated all the old versions.

Thanks again!
Bryan
