### ISSUE TITLE
New look to the demo site what do u think

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#514]
Do you like the new look or should we go back to the old one ?

![dec 13 2018 9_12 am](https://user-images.githubusercontent.com/34351424/49922306-facd5b80-feb8-11e8-9d69-2ab4371c90e4.gif)

**Comment by adamdriscoll** [comment]
That looks SO awesome dude!!!

**Comment by dtnyc9005** [comment]
Fresh Look!

**Comment by adamdriscoll** [comment]
Cleaning up issues
