### ISSUE TITLE
New-UDSelect access to $Cache variable (v2.1.0 vs v2.2.0)

### ISSUE THREAD

**Issue by beb-bang** [ironmansoftware/universal-dashboard#515]
Greetings!

I have two computers running UniversalDashboard. One is still running v2.1.0 and the other v2.2.0. 
In 2.1.0 this snippet works great for generating a dropdown list of computers. 
```
New-UDSelect -Option {
    New-UDSelectOption -Name "Select a computer" -Value "None"
    $Cache:Computers | ForEach-Object {
        New-UDSelectOption -Name $_.Name -Value $_.Name
    }
} -OnChange {
    $Session:ComputerToScan = $EventData
}
```
In 2.2.0 however, New-UDSelctionOption throws this error:
> Exception calling "Invoke" with "0" argument(s): "Exception calling "Invoke" with "0" argument(s): "Cannot bind argument to parameter 'Name' because it is an empty string.""

$Cache:Computers should be available in this script block, yes? I tried passing a "Computers" object into New-UDSelect in the -ArgumentList, but was told "A parameter cannot be found that matches parameter name 'ArgumentList'".

FWIW, $Cache:Computers is available in the New-UDCollapsibleItem that this New-UDSelect is in. So it seems to be an issue specific to the UDSelect and to v2.2.0.

Any suggestions? 

Thx!
Bryan

**Comment by adamdriscoll** [comment]
Will have to futz with it myself. I don't know why the cache wouldn't work in just the select.

**Comment by beb-bang** [comment]
Thanks, Adam. It's entirely possible I just don't know what I'm doing :-) If there is a better way to load up a select from a cache object, I'll give it a try. I was excited to see the foreach work since I had read in the doc there could be scoping issues. For now I'm just running the query directly on the page and not using the cache object. 

Cheers!
Bryan
