### ISSUE TITLE
Add -Color to New-UdButton

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#517]
Nice to have different color buttons and not one color for the entire theme.

Just adding a -Color Param then adding $Color to the a Tag className

className = "$btnClass $disabledClass $Color"

Works Great!

![image](https://user-images.githubusercontent.com/22712034/50293321-4fd11a80-0441-11e9-832d-0e60ff67b594.png)

**Comment by AlonGvili** [comment]
This option will be available in ud 3.0

**Comment by adamdriscoll** [comment]
PR #747 fixes for materialize.
