### ISSUE TITLE
Add -TitleAlignment Param to New-UDCard

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#518]
Add ability to align the Title of a Card

Added this to my local module and works great

[ValidateSet('left', 'center', 'right')]        
[String]$TitleAlignment = 'left',

Then within the span element added $TitleAlignment to className

![image](https://user-images.githubusercontent.com/22712034/50293538-d685f780-0441-11e9-85f0-4ccf3e0b060e.png)

**Comment by AlonGvili** [comment]
Look great

**Comment by adamdriscoll** [comment]
This issue now has a bounty: https://www.bountysource.com/issues/67797215-add-titlealignment-param-to-new-udcard

**Comment by psDevUK** [comment]
How about keep it simple, and set the theme for the card like so:-
     '.left-align' = @{
         'text-align' = "center"
     }
Keeps the look and feel the same across all pages then....

**Comment by adamdriscoll** [comment]
Hmm. That's a good point but I think it'd be nice to have it configurable per card as well. We could also create a theme that was a "centered card" theme or somethin.
