### ISSUE TITLE
Dashboard chart error: An unexpected error occured invoking 'clientEvent' on the server.

### ISSUE THREAD

**Issue by phobos711** [ironmansoftware/universal-dashboard#520]
When clicking anywhere in a dashboard chart, the following error appears on the screen: 
"An unexpected error occured invoking 'clientEvent' on the server. Exception: Endpoint *endpointonClick* not found." 

This only occurs in version 2.2.0. Does not happen in 2.0.1.

![screen shot 2018-12-20 at 8 24 48 pm](https://user-images.githubusercontent.com/46038258/50324689-5b4e3100-0495-11e9-8c3e-fd11022058d9.png)

**Comment by adamdriscoll** [comment]
Can you please provide an example of the script causing this issue?

**Comment by adamdriscoll** [comment]
Strange. Looks fine to me. I'll have to take a look.

**Comment by grayo24** [comment]
Is there any way to hide this exception from showing in the browser while we wait for 3.0.0??

**Comment by grayo24** [comment]
> @grayo24 Yep. If you put an empty event handler on the chart it should suppress it.
> 
> ```
> New-UDChart -OnClick {}  #other options
> ```

**Comment by grayo24** [comment]
Awesome thanks!
