### ISSUE TITLE
POST Size Limitation?

### ISSUE THREAD

**Issue by ericshoemaker** [ironmansoftware/universal-dashboard#527]
I'm writing an API that I intend to use as a data collector, however I get an internal server error that appears to be related to the amount of data being sent to the api. Is there a limit to how much data can be sent per request? If so, is it adjustable?

Here is the endpoint:

###############################################
New-UDEndpoint -Url "/Concentrator" -Method POST -Endpoint {
    param($Body)
    $Data=$Body | ConvertFrom-Json
    $ProjectID=$Data.ProjectID
    $ProjectDir="$Cache:CustomerDir\$ProjectID"
    # VALIDATING PROJECT ID
    If (-not ($Cache:OpenProjects | where ProjectID -eq $ProjectID))
    {
        "PROJECT ID NOT FOUND"
        break
    }
    If (-not (Get-Item $ProjectDir -ErrorAction SilentlyContinue))
    {
        New-Item $ProjectDir -ItemType Directory -Force
    }
    $Data.Data | Out-File "$ProjectDir\$($Data.Filename).txt"
}
###############################################

This request succeeds:
###############################################
$Tempobj="" | Select ProjectID, FileName, Data
$Tempobj.ProjectID="100001"
$Tempobj.FileName="TEST"
$Tempobj.Data="$(1..520)"
$Body=$Tempobj | ConvertTo-Json
Invoke-RestMethod -Uri "http://localhost/api/concentrator" -Body $Body -Method Post
###############################################

This request fails. Note the only difference is the range is 1..521 rather than 1..520
###############################################
$Tempobj="" | Select ProjectID, FileName, Data
$Tempobj.ProjectID="100001"
$Tempobj.FileName="TEST"
$Tempobj.Data="$(1..521)"
$Body=$Tempobj | ConvertTo-Json
Invoke-RestMethod -Uri "http://localhost/api/concentrator" -Body $Body -Method Post
############################################### 

> Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
> At C:\FilePath\Concentrator-Pester.ps1:6 char:1
>  Invoke-RestMethod -Uri "http://localhost/api/concentrator" -Body $Bod ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>  CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke- RestMethod], WebException
> FullyQualifiedErrorId :  WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by petercovach** [comment]
I believe I am also running up against a POST body size limitation.  It seems that larger JSON POST bodies get cut off.  I am receiving an error back from UD of "Invalid object passed in, ':' or '}' expected (405):".  If I shorten the contents of the JSON document, then the POST is successful.  Let me know if you need more information.

**Comment by bbomgardner** [comment]
It seems like this problem (or something similar) is still present on 2.5.3. I can POST only up until a certain payload size before I get a 500 internal error. PUT appears to handle very large payloads without issue.
