### ISSUE TITLE
[Suggestion] UDEndpoint refresh/"autoreload"

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#532]
It would be super nice to be able to refresh the endpoints when developping them without restarting the server, just like we can do through Autoreload and the [UDHotReloader](https://poshtools.com/2018/11/30/faster-universal-dashboard-development-with-udhotreloader/).

I'd love to see the same structure as the dashboard have with a -EndpointFilePath that must point to a file returning a Rest API (New-UDRestAPI) and be updated through the hotreload / future autoreload at the same time. 

---
Edit:  Here's my IIS suitable workaroud which restart the webapp pool tied to the application. 
https://forums.universaldashboard.io/t/faster-ud-dashboard-development-with-udhotreloader/141

**Comment by adamdriscoll** [comment]
This is now possible. If you just run New-UDEndpoint, it will register itself. No need to pass it to anything. Then you can just overwrite the endpoint that's already there. 

```
PS F:\universal-dashboard\src> Start-UDRestApi -Port 10001

Name        Port Running DashboardService
----        ---- ------- ----------------
Dashboard0 10001    True UniversalDashboard.Services.DashboardService
PS F:\universal-dashboard\src> New-UDEndpoint -Url test -Endpoint { "Hello" } | out-Null
PS F:\universal-dashboard\src> Invoke-RestMethod http://localhost:10001/api/test
Hello
PS F:\universal-dashboard\src> New-UDEndpoint -Url test -Endpoint { "Hello, World" } | Out-Null
PS F:\universal-dashboard\src> Invoke-RestMethod http://localhost:10001/api/test
Hello, World
```

**Comment by mkellerman** [comment]
Can you please provide an example with pages?

````powershell
$UDPages = Get-ChildItem .\Pages\*.ps1 -Recurse | ForEach-Object { . $_.FullName }
New-UDDashboard -Pages $UDPages -Port 10001
````

Content example of one of the pages:
````powershell
New-UDPage -Name "Home" -Endpoint {
New-UDElement -Tag 'div' -Content 'Hello World!'
}
````

How would you go about to change the content of the page, without reloading the dashboard?
