### ISSUE TITLE
New-UDInput - Pressing enter doesn't submit form

### ISSUE THREAD

**Issue by davegreen** [ironmansoftware/universal-dashboard#535]
I'm having trouble figuring out how to make the form submit when enter/return is pressed after typing in the input box. I have to click the button instead to get it to work.

I can't for the life of me figure out how to make it do what I want, I can also reproduce this on all of my machines. I suspect it's more likely me not understanding something than it being a bug, but any help at all would be appreciated!

Machine is running PowerShell 5.1 on Windows 10 1809, although I've unsuccessfully tested it on other versions (Windows Server 2016 and earlier Windows 10 builds).

Version of UniversalDashboard is 2.2.0, although this was the same in 2.1.0 as well.

The code to reproduce is below:

```powershell
$PageData = New-UDPage -Url '/page' -Endpoint {
    New-UDInput -Title "Search" -SubmitText 'Search' -Content {
        New-UDInputField -Type 'textbox' -Name 'Data' -Placeholder 'Data'
    } -Endpoint {
        Param($Data)
        New-UDInputAction -RedirectUrl "/search/$Data"
    }
}

$Dash = @{
    Pages                  = $PageData
}

$Dashboard = New-UDDashboard @Dash
Start-UDDashboard -Dashboard $Dashboard -Port 1002
```

**Comment by adamdriscoll** [comment]
@davegreen I bet this is a bug ;) I'm a bit surprised it hasn't been mentioned before!
