### ISSUE TITLE
New-UDDashboard -Stylesheets parameter broken

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#543]
Custom CSS is not included when using the -Stylesheets parameter. 

Dashboard used

```
Get-UDDashboard | Stop-UDDashboard
$dash = New-UDDashboard -Title 'a' -Pages @(
 New-UDPage -Name 'home' -Content {New-UDCard -Title 'test' -Text 'hello'}
 New-UDPage -Name 'home2' -Content {New-UDCard -Title 'test' -Text 'hello'}
    ) -Stylesheets 'C:\Users\itfranck\Documents\GitHub\PoshUD-IIS\rest\src\Main\Styles\MyStyle.css'
Start-UDDashboard -Dashboard $dash -Port 9991 
```

Associated CSS file. 

```
.nav-wrapper {
    background-color: black !important;
}

.ud-navbar {
    background-color: blueviolet;
}
```

**Comment by McAndersDK** [comment]
is this not the url to include? I am using this to get the link added to the header.
I have published a folder with the css in it, and then use that parameter to get the link added to the header.

**Comment by itfranck** [comment]
@McAndersDK Indeed, it does work using the URL. My bad. 
Thanks for pointing that out. I'll use that for now.

That being said, Javascript include also work when referencing the file directly. 

When I tested, I noticed, using the filepath, that Javascript was included so I only tried to include the CSS using the filepath and didn't think of trying an URL reference for that reason.

I will leave this open and let Adam decide the proper course of action.
In my mind, one of the following should apply

- CSS includes should be possible with filepath too (like javascript) for consistency
- New-UDDashboard cmdlet documentation should specify that it expects an URL for the css and that it can accept both (filepath/url) for the -scripts parameter.

In any cases, it would be nice to have the filepath working for CSS too so file can be let in the same directory structure as the dashboard (or anywhere else for that matter).

**Comment by itfranck** [comment]
Closing this. I was mistaken. Using the filepath to include javascript does not work either. It does add the filepath as reference but since it is a filepath, it won't work anyway. Both Stylesheet and Javascript requires an URL reference.
