### ISSUE TITLE
date inputfield jumping backup to 1918

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#544]
Simple Input form:

`New-UDInput -SubmitText "Go" -Title "Select Date range" -Content {
        
                New-UDInputField -Type date -Name "Startdate" -Placeholder "Start Date (00:00)"
                New-UDInputField -Type date -Name "EndDate" -Placeholder "End Date (23:59)"
            }-Endpoint {
                 param($Startdate, $EndDate)
                Show-UDToast -Message "From $Startdate to $EndDate"
        
            }`

If I Select the input fields it displays the current month. If I hit 'Go' the toast displays the values as it should.
If I then select the fields again, it places me in december 1918.

It only happens after hitting' Go'

![image](https://user-images.githubusercontent.com/20628942/50904133-cdc08a00-141f-11e9-967a-b4e88128d1e0.png)

This is on 2.2

**Comment by PorreKaj** [comment]
You know, this particular site WASN'T updated to 2.2 (2.1) - updating solved the issue.

**Comment by PorreKaj** [comment]
It only worked first time, ugh.

**Comment by adamdriscoll** [comment]
I see it too. I will see if I can fix this in the 2.2.1 release.

**Comment by adamdriscoll** [comment]
This is more involved than a simple fix. Looks like a problem with the materializecss library. We are currently moving to material-ui and will be taking advantage of their controls moving forward: https://material-ui.com/demos/pickers/#complementary-projects

I'll make sure this is addressed there.

**Comment by PorreKaj** [comment]
Bugger. 
Since it only allows one to select +-50years, it won't let users select anything newer than 1968, unless first using the "Today" Button.

Looking forward to Material-UI :-)
