### ISSUE TITLE
Error invoking clientEvent / endpoint not found loading modal from sorted/filtered grid

### ISSUE THREAD

**Issue by beb-bang** [ironmansoftware/universal-dashboard#545]
I've got a grid loaded with data on a dynamic page. There is a button in each row that opens a modal with more information (in table in the modal). It works great!!

![grid-button-modal](https://user-images.githubusercontent.com/19676403/50937822-56442800-142a-11e9-9154-66b7b4c9a3f1.png)

Until I sort or filter the grid. Then it generates this endpoint not found error.
![grid-button-modal after sort or filter](https://user-images.githubusercontent.com/19676403/50937828-593f1880-142a-11e9-94a2-de5b8f936cd1.png)

Refreshing the page fixes the missing endpoint error, but then sorted or filtered results are lost. 

We're using v2.1.0 Enterprise.

Any suggestions?

Thx!
Bryan

**Comment by adamdriscoll** [comment]
Neat use case! I will have to take a look at this. I've never tried this exact thing before.

**Comment by adamdriscoll** [comment]
This has been resolved in 2.3.

**Comment by dtnyc9005** [comment]
Hey Guys, Is this the same issue? I ran the debugger and can see that $itemdata has values but just isnt being passed through in table thats in show-udmodal.

`$DBSpaceEndPoint = New-UDEndpoint -Schedule $DBSchedulurEP -Endpoint {
    
    $cache:DBSpaceCheckQuery = Invoke-DbaQuery -Query 'select * FRom dbo.sqldbspace Where Date = cast(getdate() as date)' -ServerInstance "########" -Database WebMgmt -Credential $DBCreds
    
    $cache:DBSpaceCheck = foreach ($item in $cache:DBSpaceCheckQuery) {
       
        [pscustomobject]@{

            Date         = $item.Date
            ComputerName = $item.ComputerName
            InstanceName = $item.InstanceName
            SqlInstance  = $item.SqlInstance
            Database     = $item.Database
            FileName     = $item.FileName
            PhysicalName = $item.PhysicalName
            FileType     = $item.FileType

            Details      = (New-UDButton -Text "Details..." -OnClick {

                    $ItemData = @{
                        ComputerName = $item.ComputerName
                        InstanceName = $item.InstanceName
                        SqlInstance  = $item.SqlInstance
                        Database     = $item.Database
                        FileName     = $item.FileName
                        PhysicalName = $item.PhysicalName
                        FileType     = $item.FileType
                    }
              
                    Show-UDModal -Header {
                        New-UDHeading -Size 5 -Text "Database Object Details for: $($item.Database)"
                    } -Content {
                        New-UDCard -Title "$($item.Database) - Details" -Content {
                                                             
                            New-UDTable -Headers @("Name", "Value") -FontColor "#FFFFFFFF" -BackgroundColor "#FF252525" -Endpoint {
                                Wait-Debugger
                                $ItemData   | Out-UDTableData -Property @("Name", "Value")
                            }
                        }
                    }
                } 
            )
        } #>PSCustomObject Close
    }
}`

**Comment by dtnyc9005** [comment]
So I used the example above from @beb-bang and it worked - not sure why though, in addition any formatting that I attempt to perform inside the object it not showing? any suggestions?

 $ItemData = @(
                        [pscustomobject]@{Name = "ComputerName"; Value = $item.ComputerName}
                        [pscustomobject]@{Name = "InstanceName"; Value = $item.InstanceName}
                        [pscustomobject]@{Name = "SqlInstance"; Value = $item.SqlInstance}
                        [pscustomobject]@{Name = "Database"; Value = $item.Database}
                        [pscustomobject]@{Name = "FileName"; Value = $item.FileName}
                        [pscustomobject]@{Name = "FileGroup"; Value = $item.FileGroup}
                        [pscustomobject]@{Name = "PhysicalName"; Value = $item.PhysicalName}
                        [pscustomobject]@{Name = "FileType"; Value = $item.FileType}
                        [pscustomobject]@{Name = "SpaceUntilMaxSizeGB"; Value = [math]::round($item.SpaceUntilMaxSizeGB) / 1GB}
                        [pscustomobject]@{Name = "AutoGrowthPossibleGB"; Value = [math]::round($item.AutoGrowthPossibleGB) / 1GB}
                        [pscustomobject]@{Name = "UnusableSpaceGB"; Value = [math]::round($item.UnusableSpaceGB) / 1GB}
                    )
