### ISSUE TITLE
UD v2.2 - Show-UDModal Not working on button click.

### ISSUE THREAD

**Issue by grayo24** [ironmansoftware/universal-dashboard#546]
Trying the snippet from the Get-Help example and this is not working for me in v2.2. Seems like it works on v2.1

New-UDButton -Text "Show Modal" -OnClick {
        Show-UDModal -Header {
            New-UDHeading -Size 4 -Text "Modal"
        } -Context {
            "This is a modal"
        }
    }

**Comment by adamdriscoll** [comment]
Can you open the F12 developer tools in your browser and see if there are any errors in the console?

**Comment by grayo24** [comment]
@adamdriscoll 

I created a blank page with just a button. Here is the code: 


New-UDPage  -Name "Test" -Icon male  -Content { 

    New-UDButton -Text "Test"  -OnClick {
        Show-UDModal -Header {
            New-UDHeading -Size 4 -Text "Modal"
        } -Context {
            "This is a modal"
        }

    }


}


Here is a screenshot of what I see in chrome:

![image](https://user-images.githubusercontent.com/24198800/50992713-84367480-14dd-11e9-9a54-c46146fc8b2e.png)
