### ISSUE TITLE
Roles and Redirect using new Windows auth

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#547]
The ability to redirect based on for example group membership your login script was very valuable.

`$group = "PoshUDLovers"
        $members = Get-ADGroupMember -Identity $group -Recursive | Select -ExpandProperty SamAccountName
        If ($members -contains $($Credentials.UserName)) 
        {
            New-UDAuthenticationResult -Success -UserName $($Credentials.UserName) -Role @("Manager", "AllContractorViewer") -RedirectUrl "/Consultants-Dashboard/"
        } `

Can anything similar be done with Windows Auth?

**Comment by adamdriscoll** [comment]
You should be able to accomplish this by creating a home page that does the redirect using Invoke-UDRedirect. 

Maybe something like this: 

```
New-UDPage -Name 'MyHomePage' -Endpoint { 
$members = Get-ADGroupMember -Identity $group -Recursive | Select -ExpandProperty SamAccountName If ($members -contains $($Credentials.UserName)) { Invoke-UDRedirect "/Consultants-Dashboard/"
}
```

Not perfect but could work.

**Comment by PorreKaj** [comment]
Won’t that require the $myhomepage to be the first page? I thought first page had to be static. Or maybe that’s changed?
I’ll be trying that out on my beta site in the morning.


________________________________

**Comment by adamdriscoll** [comment]
Try the 2.2.1 build. You should be able to have dynamic first pages now.

**Comment by PorreKaj** [comment]
Indeed.
Now of course the "Redirect page" is visible in the site menu, but I guess there's no way around that until the menu overhaul.

**Comment by adamdriscoll** [comment]
You can now customize the menu so I think you should be able to work around that.
