### ISSUE TITLE
UD not loading in IIS application under default web site

### ISSUE THREAD

**Issue by camusicjunkie** [ironmansoftware/universal-dashboard#548]

**Comment by camusicjunkie** [comment]
Powershell version: 5.1.17763.134
UD version: 2.2.1
Chrome version: 71.0.3578.98
IIS version: 10.0.17763.1

I'm running in to a problem with UD loading in IIS but at this point I'm not sure if it's a problem with IIS or with UD. I've got an application created under the default website called dashboard where I have all the UD files located. It has it's own application pool with the identity set to LocalSystem.

![image](https://user-images.githubusercontent.com/33888807/51012312-c9789780-1519-11e9-91d3-1c830589040b.png)

When I browse to http://localhost/dashboard I just get a blank white screen. When I go in to network tab under the developer tools I can see I'm getting some 404 errors on two of the initial js files being loaded.

![image](https://user-images.githubusercontent.com/33888807/51012480-8b2fa800-151a-11e9-9a14-160607d42681.png)

If I navigate to the request url shown above I get that below detailed error information. Those files are trying to load from the default web site under wwwroot and not under dashboard.

![image](https://user-images.githubusercontent.com/33888807/51012590-1dd04700-151b-11e9-9575-88559aa4f0e9.png)

If I add dashboard to the request url the js file will load properly in the browser.

![image](https://user-images.githubusercontent.com/33888807/51012687-a18a3380-151b-11e9-9c57-0e829867ab6b.png)

Is this truly a UD problem or are my newbie IIS skills getting the better of me?

**Comment by adamdriscoll** [comment]
I think this is a problem with UD. It seems like something is routing incorrectly which is leading to the issue. I will mark this issue as such.

**Comment by itfranck** [comment]
For additional reference, here's another ticket I opened tied to that same issue:  #249
