### ISSUE TITLE
New-UDIcon returns error with color parameter

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-dashboard#549]
I attempted to use UDIcons in grid fields as such:

```
[PSCustomObject]@{Property1 = $null; $Property2 = New-UDIcon -Icon check -Color Green}
```

However, this resulted in the error:

![image](https://user-images.githubusercontent.com/6998507/51046220-80fdc000-1593-11e9-9db0-d0ce375a93c6.png)

Removing the `-Color` parameter resolved this issue. Some additional discussion around this is [here](https://forums.universaldashboard.io/t/can-i-use-an-icon-in-a-grid-field/265/2)

**Comment by McAndersDK** [comment]
I have the same issue, just with new-udelement

> $NeglectedSmiley = @{n= 'Neglected';e = {if($_.IsNeglected) {New-UDElement -Tag i -Attributes @{class = 'fas fa-skull'; style = @{color = "red"; 'font-size' = "19px"}}}else {''}}}

note: Using font 5 css by loading the css file for it.

but it give the same error
