### ISSUE TITLE
UDRestAPI not working 

### ISSUE THREAD

**Issue by Stephanevg** [ironmansoftware/universal-dashboard#55]
Hi,

Universal Dashboard 1.5.1

I have created a very simple rest endpoint based on the example provided in the documentation. I have change it a bit with the following code:

```powerhell
$Endpoint = New-UDEndpoint -Url "/ComputerReport/:ComputerName" -Method "GET" -Endpoint {
    param($ComputerName)

    $data = invoke-command -file C:\admin\FromProduction\Repository\scripts\Dashboards\ALL-DAT-ComputerReport.ps1 -computerName $ComputerName
    $DAta | convertto-Json
}

Start-UDRestApi -Endpoint $Endpoint

```

(C:\admin\FromProduction\Repository\scripts\Dashboards\ALL-DAT-ComputerReport.ps1 is a script that contains a few functions, and does some basic checks. It returns an object at the end).

When I call the ```invoke-REstMethod``` I have the following behaviour:

```Powershell

[A][3] C:\admin\FromProduction\Repository\scripts\Dashboards > Invoke-RestMethod http://localhost:80/ComputerReport/dc01
Invoke-RestMethod :



    PowerShell Universal Dashboard

        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        .app {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        .app>div {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }

        .paginate_button  {
            padding-left: 5px;
            padding-right: 5px;
            cursor: pointer;
        }

        .sorting {
            cursor: pointer;
        }

        .sorting_asc {
            cursor: pointer;
        }

        input[type=text]:focus {
            border-bottom: 1px solid #000000 !important;
            box-shadow: 0 1px 0 0 #464646 !important;
        }

        input[type=password]:focus {
            border-bottom: 1px solid #000000 !important;
            box-shadow: 0 1px 0 0 #464646 !important;
        }






At line:1 char:1
+ Invoke-RestMethod http://localhost:80/ComputerReport/dc01
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

```

When I open the urldirectly  via IE, I see the following page that seems like loading forever.

![image](https://user-images.githubusercontent.com/6302961/37857092-a81314e2-2ef8-11e8-8ae3-f988a6aa6028.png)

Any idea how to solve this? using REST api via powershell was something we were really looking forward to. Hope we can get this fixed

I  have the same behaviour with a simpler example as well:

```powershell
$Endpoint = New-UDEndpoint -Url "/Process" -Method "GET" -Endpoint {

    Get-Process | convertto-Json
}

Start-UDRestApi  -Port 3030 -Endpoint $Endpoint

```

Thanks in advance

**Comment by adamdriscoll** [comment]
@Stephanevg Try changing the path for your call to Invoke-RestMethod to /api/Computer/:ComputerName. 

Like this:

```
http://localhost:80/api/Computer/dc01
```

I will have to fix that issue where it is returning the HTML 404 page when the URL is not known.

**Comment by Stephanevg** [comment]
Great! it did the trick!
I double checked, this was not mentionned like that in the [docs](https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/rest-apis.html). Perhaps a quick update in there would avoid other people falling into this pitfall ;)

thanks for your fast reply!
