### ISSUE TITLE
New-UDSelect behaviour different across browsers

### ISSUE THREAD

**Issue by davegreen** [ironmansoftware/universal-dashboard#558]
Using a New-UDSelect in a UDCard (instead of an input form) seems to generate some odd behaviour when viewing in Edge or IE. Things work roughly as I expect in Chrome, although values seem to get passed in quotes that appear from nowhere.

The returned data after the redirect appears as '[]' and makes the select non-functional if the user's browser is IE or Edge.

UD v2.2.1, Windows 10

```powershell
New-UDCard -Title 'Example' -Content {
    New-UDSelect -Option {
        foreach ($option in @("one", "two")) {
            if ($option -eq $Session:Select) {
                New-UDSelectOption -Name $option -Value $option -Selected
            }
            else {
                New-UDSelectOption -Name $option -Value $option
            }
        }
    } -OnChange {
        $Session:Select = $eventdata
        Invoke-UDRedirect -Url "/$eventdata"
    }
}
```

**Comment by McAndersDK** [comment]
This is the same as #574

**Comment by davegreen** [comment]
@McAndersDK: Are you sure this is the same? This appears to still be an issue on the latest (v2.3.2)

**Comment by adamdriscoll** [comment]
This was a different issue. Now works in all browsers.
