### ISSUE TITLE
Add Buttons on every row of Grid or Table

### ISSUE THREAD

**Issue by ccgview** [ironmansoftware/universal-dashboard#560]
Is it possible to add a button on ever row of the grid or table component that when clicked would run a command with value from the row object. So like get a list of processes and and display in a grid/table with a kill button to stop each process?

would prefer to use the grid component.

**Comment by adamdriscoll** [comment]
Yep. You can do that. I just wrote a blog post about it since people ask a lot: https://poshtools.com/2019/01/17/universal-dashboard-adding-buttons-to-a-udgrid/

**Comment by ccgview** [comment]
Thanks that's just what i wanted i ran your test script and it works but if you try to use the search filter then click on a button it gives an error about invoking a client event. can this be fixed?

**Comment by adamdriscoll** [comment]
Ack. Yep. I see the same thing. Made an issue for it: #563
