### ISSUE TITLE
Implement more coloring options for charts

### ISSUE THREAD

**Issue by theabraxas** [ironmansoftware/universal-dashboard#566]
![image](https://user-images.githubusercontent.com/6147260/51411604-4d83de00-1b1d-11e9-89ab-d6443786f240.png)

The above is a common chart which I'm ending up with with the data I'm often dealing with -for example, an array with a set of things like: `name1:count, name2:count, name3:count`

If there was some default way to cast 2-dimensional data in to multiple colors would be awesome. The code I'm using is below in case there's some flag I'm misssing:

```
        New-UDChart -Title "Devices by Zone" -Type Bar -Endpoint {
            $DevicesByZone | Foreach-Object {
                [PSCustomObject]@{ 
                    Count = $_.Count;
                    Zone = $_.Name;
                    }
                } | Out-UDChartData -DataProperty Count -LabelProperty Zone -BackgroundColor '#FF530D' -BorderColor 'black' -HoverBackgroundColor '#FF9F0D' -
        }
        New-UDChart -Title "Devices by Policy" -Type Bar -Endpoint {
            $DevicesByPolicy | Out-UDChartData -DataProperty Count -LabelProperty Name -BackgroundColor '#FF530D' -BorderColor 'black' -HoverBackgroundColor '#FF9F0D'
        }
        New-UDChart -Title "Top 10 Computers with Blocked Events" -Type Doughnut -Endpoint {
            $Top10ComputersWithBlockedThreats | Out-UDChartData -DataProperty Count -LabelProperty Name -BackgroundColor '#FF530D' -BorderColor 'black' -HoverBackgroundColor '#FF9F0D'
        }
```

Thanks for any help!

**Comment by BlairKingsley** [comment]
Hi,
The -BackgroundColor property takes an array. Hope that helps. e.g. 
-BackgroundColor @("#75cac3","#2a6171","#f3d516","#4b989e","#86df4a","#b816f3","#f31651","#4e4b9e")

**Comment by theabraxas** [comment]
I had no idea there was a forum, thanks for the info! Also didn't realize I could give it an array, that's awesome. Thanks so much for your help!
