### ISSUE TITLE
Udcounter onclick 

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#568]
Any chance we can get a click event on the udcounter?

I could see it being useful for wanting to display the data behind the counter.

For example a counter showing locked accounts, and a click on that could display a modal with a grid of said locked accounts.

**Comment by adamdriscoll** [comment]
This issue now has a bounty: https://www.bountysource.com/issues/68937732-udcounter-onclick

For any bounty hunters, I suggest taking a look at the implementation of UDButton to see how to add this functionality. 

JavaScript: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Components/ud-button.jsx#L7

PowerShell: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Scripts/button.ps1#L26

Tests: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Tests/button.tests.ps1#L42

**Comment by AlonGvili** [comment]
This is what you are looking for?
![Antd](https://user-images.githubusercontent.com/34351424/63129827-43e22c00-bfc1-11e9-96a0-78264f354f31.gif)

```powershell

New-UDCounter -Title "Total Running Processes" -TextAlignment center -backgroundColor '#1890ff' -FontColor '#fff' -AutoRefresh -RefreshInterval 3  -Icon cogs -Endpoint {
    (Get-Process).Count 
} -OnClick {
    Show-UDModal -Header {
        New-UDHeading -Size 4 -Text "Process"
    } -Content {
        New-UDGrid -Title "Process List" -Id "plist" -RefreshInterval 5 -AutoRefresh -DefaultSortColumn "Name" -DefaultSortDescending -EndPoint {
            $data = Get-Process | Select Name,CPU,Company,Description
            $data | Out-UDGridData 
        } 
    }
} -TextSize Large 

```
