### ISSUE TITLE
Feature Request: Notifications back to page during endpoint execution

### ISSUE THREAD

**Issue by theabraxas** [ironmansoftware/universal-dashboard#58]
There may be a way to do this with Toasts or something I'm just missing, in which case sorry for wasting your time! If not, however, a feature I think which would be very useful is the ability to interact with webpage during executions of `-Endpoint`s in `New-UDInput` blocks.

A simple example, a program which adds users to a group based on filling in a UDInput

1) `New-UDInput` which asks for a username and a group name
2) A `-Endpoint` for the New-UDInput  which is a simple script with error handling
3a) Check if user is a valid user - if not, toast/notify somehow with 'User invalid'
3b) Check if group is a valid group - if not, toast/notify somehow with 'group invalid'
4) Attempt to add user to group -> if successful, notify that it is, if unsuccessful notify that it failed.

I know that there are some URL redirection capabilities in the `-Endpoint` blocks but think having some way to report data back to the page would be valuable.

**Comment by adamdriscoll** [comment]
What if you could use something like Send-UDToast to send a toast message back to the user during execution? See #54

**Comment by theabraxas** [comment]
Yes, I think that would work perfectly!

**Comment by adamdriscoll** [comment]
This is implemented in 1.6.0. Had it mostly implemented but just fixed a bug that was preventing it from working.
