### ISSUE TITLE
Anyone implemented a datepicker on an New-UDInput Field? 

### ISSUE THREAD

**Issue by grayo24** [ironmansoftware/universal-dashboard#583]

**Comment by grayo24** [comment]
New-UDElement -Id 'date' -Tag 'input' -Attributes @{
                          type = "date"
                           id = "date"
                           value = ""
                       }


So I got this showing but how can I set the Value attribute to grab the value of the date picker?? or this not possible?

**Comment by PorreKaj** [comment]
While a bit buggy, there actually is a date type of New-UDInputField
New-UDInputField -Type date -Name "Startdate"

```
`New-UDInput -SubmitText "Go" -Title "Select Date range" -Content {

```
            New-UDInputField -Type date -Name "Startdate" -Placeholder "Start Date (00:00)"
            New-UDInputField -Type date -Name "EndDate" -Placeholder "End Date (23:59)"
        }-Endpoint {
             param($Startdate, $EndDate)
            Show-UDToast -Message "From $Startdate to $EndDate"
    
        }`
```
```
