### ISSUE TITLE
New-UDNivoChart + Legend/Labels

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#586]
I'm building a heat map of my data, but I have no idea how to show the labels.

```powershell
New-UDNivoChart -Heatmap -Data $Data -Keys $Keys -IndexBy DayOfWeek -Height '200' -Width '900' -Colors 'oranges'
```

<img width="913" alt="image" src="https://user-images.githubusercontent.com/9411143/51793892-8c004500-217c-11e9-8f9f-f87cce484e16.png">

**Comment by adamdriscoll** [comment]
Looks like the parameter set for heatmap is missing the axis configuration properties. Will get that fix in 2.3. 

https://github.com/ironmansoftware/universal-dashboard/issues/595

**Comment by mkellerman** [comment]
I was able to make the labels visible by setting the margins! Not very intuitive, but i think there should be a default margin set, so the user get what's 'expected', and can put the margins to 0 if he wants to hide them?

**Comment by adamdriscoll** [comment]
Yeah. Sane defaults should always be the default. ;) I'll make the margins a better value by default.
