### ISSUE TITLE
New-UDNivoChart + Full width of UDColumn

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#587]
Is there a way to make the UDNivoChart take up 100% of the width/height of the UDColumn element? It's unresponsive to browser size changes, and requires a hardcoded width/height.

```powershell
New-UDNivoChart -Heatmap -Data $Data -Keys $Keys -IndexBy DayOfWeek -Height '200' -Width '900' -Colors 'oranges'
```

<img width="712" alt="image" src="https://user-images.githubusercontent.com/9411143/51793912-d71a5800-217c-11e9-8713-5e669de8e4ab.png">

**Comment by adamdriscoll** [comment]
Try using the `-Responsive` parameter

**Comment by mkellerman** [comment]
`-Responsive` makes the chart 1px by 1px or something like this. I must set `-Width -Height`, or nothing is visible.

How do you do it for your example here:
https://docs.universaldashboard.io/updates/v2.2.0-beta2#chart-types

**Comment by adamdriscoll** [comment]
This is fixed and will be in tonight's nightly build.
