### ISSUE TITLE
Command to stop all running dashboards?

### ISSUE THREAD

**Issue by theabraxas** [ironmansoftware/universal-dashboard#591]
I find myself often testing stuff rapidly in dashboards which results in typing `Stop-UDDashboard dashboard#` quite often. 

Is there a way to implement a wildcard or some other mechanism to stop all running dashboards? Something like `Stop-UDDashboard -Filter *` or just a wildcard function for the name parameter?

**Comment by grayo24** [comment]
Get-UDDashboard | Stop-UDDashboard

**Comment by theabraxas** [comment]
Well, sometimes I feel like an idiot. That definitely works. Thanks!
