### ISSUE TITLE
New-UDNivoChart -Bar (Missing labelTextColor Property)

### ISSUE THREAD

**Issue by BlairKingsley** [ironmansoftware/universal-dashboard#597]
Hi, Adam.
The New-UDNivoChart cmdlet is missing the labelTextColor property when setting up a bar chart. Seems it just inherits by default currently. This causes labels not to be visible because the chart also inherits the page background colour. The temp workaround is to wrap the chart in a UD-Card with a contrasting color.
I couldn't find the New-UDNivoChart in source to see if I could amend my fork (assuming New-UDNivoChart maybe embedded in a library)
![new-udnivochart-label-issue](https://user-images.githubusercontent.com/46717232/51852431-fef4f180-231d-11e9-90e3-096c714777a6.jpg)

**Comment by BlairKingsley** [comment]
The screenshot shows the chart wrapped in a UD-Card with a white background. If I unwrap none of the text outside the bars is visible.

**Comment by adamdriscoll** [comment]
This isn't going to make it into the 2.3 release. I might need to update the charting library to support this.

**Comment by BlairKingsley** [comment]
Sure - it's not urgent. Thanks
