### ISSUE TITLE
Sync-UDElement -Id should take [string[]]

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#598]
When click on a chart, i need to Refresh/Sync many UDElement .

having Sync-UDElement -Id accept multiple ID's would be amazing!

**Comment by adamdriscoll** [comment]
3.0 will likely have view model support which should help with this as well. 

https://twitter.com/adamdriscoll/status/1082493461322915840

**Comment by adamdriscoll** [comment]
@mkellerman Question! I just realized that this cmdlet takes pipeline input. Does that satisfy the requirement here or would you still like to see it take an array? 

```
@("1", "2", "3") | Sync-UDElement 
```

**Comment by mkellerman** [comment]
I think it would be nicer if you could give it an array. It makes it easier to read. But not mandatory.

I was using:
@array | % { Sync-UDEndpoint $_ }

Glad to see there is a shorter version ;)
