### ISSUE TITLE
Change log file

### ISSUE THREAD

**Issue by LaurentDardenne** [ironmansoftware/universal-dashboard#599]
Hi Adam,
I can not find a change.log in the repository. Is it an oversight ?

**Comment by LaurentDardenne** [comment]
Found it [here](https://github.com/adamdriscoll/universal-dashboard-documentation/tree/master/updates).
May be add a link into Readme.md  ? 
Documentation | Licensing | Live Preview | YouTube Videos | Forums | **CHANGELOG**

**Comment by adamdriscoll** [comment]
Done! 👍
