### ISSUE TITLE
Documentation link in footer is broken

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-dashboard#6]
The documentation link on the license screen in the default footer is broken.

Links to:
https://adamdriscoll.gitbooks.io/powershell-tools-documentation/content/powershell-pro-tools-documentation/universal-dashboard.html
Instead of:
https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/

**Comment by adamdriscoll** [comment]
This was broken in several places including the footer, licensing and the demo dashboard. Fix in 1.5.0.
