### ISSUE TITLE
REST-API: Get Windows-Useridentity from IIS Server

### ISSUE THREAD

**Issue by john-dederer** [ironmansoftware/universal-dashboard#602]
Is there a way to get the authenticated User credentials from within the RestAPI when it is hosted on an IIS Server with Windows authentication enabled?

If not how could we get the HTTP request information within the REST API ?

**Comment by adamdriscoll** [comment]
You can use the $ClaimsPrincipal variable to get the authenticated user. You can use the $Request variable to get the HTTP request. 

More information here: https://docs.universaldashboard.io/endpoints/variables-defined-in-endpoints
