### ISSUE TITLE
Wierd behavior with Update-UDDashboard

### ISSUE THREAD

**Issue by danaskovsende** [ironmansoftware/universal-dashboard#603]
$sb = { 
    New-UDCard -Title "Hi" -Endpoint {
        New-UDCard -Text (Get-Date -Format ":hh:mm:ss") -Title "Last refresh" 
    }
} 
$dash = New-UDDashboard -Title "Test" -Content $sb
Start-UDDashboard -Port 8000 -Dashboard $dash -UpdateToken 6699 

Everything works as expected.
Now try 
Update-UDDashboard -UpdateToken 6699 -Url http://localhost:8000 -Content { New-UDDashboard -Title "Wierd" -Content $sb }
You will get "Invoke-RestMethod : The remote server returned an error: (400) Bad Request."
but if you do unfold $sb like this
Update-UDDashboard -UpdateToken 6699 -Url http://localhost:8000 -Content { 
    New-UDDashboard -Title "Working" -Content { 
        New-UDCard -Title "Hi" -Endpoint {
            New-UDCard -Text (Get-Date -Format ":hh:mm:ss") -Title "Working" 
        }   
    }
}
Everything works as expected again
PS Version is 5.1.17763.134 Dashboard is  2.2.1 Community

**Comment by adamdriscoll** [comment]
We will not be implememtinmg this cmdlet for PowerShell Universal .
