### ISSUE TITLE
Hash for package 'UniversalDashboard.Community' does not match hash provided from the server.

### ISSUE THREAD

**Issue by mattjoyce** [ironmansoftware/universal-dashboard#609]
Module fails to load as expected.

PS C:\Windows\system32> Install-Module UniversalDashboard.Community -Verbose
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'UniversalDashboard.Community'.
VERBOSE: Performing the operation "Install-Module" on target "Version '2.2.1' of module 'UniversalDashboard.Community'".
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'UniversalDashboard.Community' with version '2.2.1' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='UniversalDashboard.Community'' for ''.
VERBOSE: InstallPackage' - name='UniversalDashboard.Community', version='2.2.1',destination='C:\Users\Matt\AppData\Local\Temp\803559472'
VERBOSE: DownloadPackage' - name='UniversalDashboard.Community', version='2.2.1',destination='C:\Users\Matt\AppData\Local\Temp\803559472\UniversalDashboard.Community\Univ
ersalDashboard.Community.nupkg', uri='https://www.powershellgallery.com/api/v2/package/UniversalDashboard.Community/2.2.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/UniversalDashboard.Community/2.2.1'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/UniversalDashboard.Community/2.2.1'.
VERBOSE: Completed downloading 'UniversalDashboard.Community'.
VERBOSE: Hash for package 'UniversalDashboard.Community' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='UniversalDashboard.Community', version='2.2.1',destination='C:\Users\Matt\AppData\Local\Temp\803559472'
WARNING: The specified module 'UniversalDashboard.Community' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the lates
t version of the PowerShellGet module to install this module, 'UniversalDashboard.Community'.

I have PowerShellGet 2.0.4 installed.
                                                                                                                               
PSVersion                      5.1.17763.134                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17763.134                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by adamdriscoll** [comment]
Have you tried with the latest builds? I'm not seeing this issue.
