### ISSUE TITLE
[Question] How to define two or more parameters into the uri ?

### ISSUE THREAD

**Issue by LaurentDardenne** [ironmansoftware/universal-dashboard#617]
Hi Adam,
it is possible to write and endpoint URI as this one ?
_https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1#use-routing-middleware_

I try to define two or more parameters into the uri but without used the 'body' parameter.
is it possible or should I split a string to retrieve the informations ?

**Comment by ChrisMagnuson** [comment]
@LaurentDardenne You will probably be able to get more rapid assistance if you ask your question on a website like StackOverflow where others can review and answer your question.

Feel free to post the link to your question back here and I will try to answer it on StackOverflow.

**Comment by adamdriscoll** [comment]
Hey @LaurentDardenne 

You can specify multiple values like this: 

```
Get-UDRestApi | Stop-UDRestApi

$Endpoint = New-UDEndpoint -Url "test/:id/value/:item" -Endpoint {
    param($id, $item)

    @($id, $item) | ConvertTo-Json
}

Start-UDRestApi -Endpoint $Endpoint -Port 10001
```

```
PS C:\Users\adamr\Desktop> invoke-restmethod http://localhost:10001/api/test/myValue/value/myItem
myValue
myItem
PS C:\Users\adamr\Desktop>
```

**Comment by adamdriscoll** [comment]
Please reopen this issue if it doesn't solve your problem.

**Comment by LaurentDardenne** [comment]
Sorry for the delay.
Yes your response resolve my problem.
One last question on this topic, the following type of construction, where '?' is a separator, is not possible at the moment?
```
   /Uril/:Value?OptionnalParameter
 ```
Or should I use the _-EvaluateUrlAsRegex_ parameter of the **New-UDEndpoint** cmdlet?
