### ISSUE TITLE
New-UDLink in New-UDGrid renders as PowerShellProTools.UniversalDashboard.Models.Link

### ISSUE THREAD

**Issue by duncansultan** [ironmansoftware/universal-dashboard#62]
Using the example for [Custom Columns Grid with Links](https://github.com/adamdriscoll/poshprotools/blob/master/examples/universal-dashboard/grid/custom-columns.ps1)

We should expect to see Hyperlinks in the Article column.  Instead the result is a text value of  **PowerShellProTools.UniversalDashboard.Models.Link**

**Comment by BryanDM** [comment]
If it helps, This was working in version 1.5.0 - Just upgraded to 1.5.3 and i'm experiencing the same issue.

**Comment by murrahjm** [comment]
using version 1.5.3 with the above example code and I'm getting output like this:

TextWikipediaUrlhttps://en.wikipedia.org/wiki/FrogIconNone
TextWikipediaUrlhttps://en.wikipedia.org/wiki/TigerIconNone
etc.

But I get the same thing with version 1.5.0 so that could just be me.

**Comment by apetitjean** [comment]
Please fix this one Adam.

**Comment by BryanDM** [comment]
This is a big one for me too, and I would also greatly appreciate a fix as soon as possible.

**Comment by adamdriscoll** [comment]
Fixed in 1.6.0-beta3.
