### ISSUE TITLE
Enterprise(2.3) / New-UDTheme / Applying theme for UDCard does not work.

### ISSUE THREAD

**Issue by BlairKingsley** [ironmansoftware/universal-dashboard#632]
Code which does not work when $Theme is used with New-UDDashboard -Theme
`
$Theme = New-UDTheme -Name 'Example' -Definition @{
    UDCard = @{
        BackgroundColor = "rgb(37,37,37)"        
        FontColor       = "rgb(255,255,255)"
    }
}
`
Workaround which works...
`
$Theme = New-UDTheme -Name 'Example' -Definition @{
    '.card-content' = @{
        'background-color' = "rgb(37,37,37)"    
    }
    '.card-title' = @{
        'color' = "rgb(255,255,255)"    
    }
}
`

Seems similar to issue mentioned in https://forums.universaldashboard.io/t/new-udcard-not-accepting-colors/303

Just wondering if all fixes are committed to both community and enterprise?

**Comment by adamdriscoll** [comment]
Yep. The forks are in sync. I will have to look at this. The issue that was resolved had to do with setting the color directly on the card and not using a theme.
