### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#636]
So, i am working on a bit of code to insert detentions into a database. Here is the code I have so far:

https://pastebin.com/ftmdFL3M 3

When I try to click the submit button after entering the Reason/Date I get the topic title in the bottom right and sadly, I am clueless on how to proceed.

Thank you!

Enable-UDLogging gave me this:

`An error occurred while starting the application.
FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
UniversalDashboard.ServerStartup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime lifetime)

FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

This Dashboard is hosted via IIS

**Comment by adamdriscoll** [comment]
@Jacob-Evans Can you let me know which version of UD you are running? I thought that logging issue was fixed.

**Comment by Jacob-Evans** [comment]
Looks like i was running an out of date version on IIS (i hadn't copied the files over). Once the logging went live, i was able to figure out what was going on in the background.

it came when i tried to pass a null variable into the INSERT query.
