### ISSUE TITLE
New-UDChart - margin-bottom ?

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#642]
Is there a way to remove the 'margin-bottom: 3rem' on every UDChart element?

![image](https://user-images.githubusercontent.com/9411143/52889877-d00cb700-3136-11e9-952d-41b3b19a52ce.png)

````html
<div class="card ud-chart" id="d24d7699-7cac-468e-9a4a-cbe679c94451" style="margin-bottom: 3rem;">
<div class="card-content" style="width: 100%; height: 400px;">
````

I can't seem to get it to dissapear. I feel like there is a lot of margin spacing all over the place in all the UD elements.

![image](https://user-images.githubusercontent.com/9411143/52889788-71473d80-3136-11e9-9309-21ac65d91f06.png)

So far, this is how i'm modifying everything.. but that UDChart is impsosible to fix.

**Comment by adamdriscoll** [comment]
Does this work? 
```
@{ 'margin-bottom' = '0px !important' }
```

**Comment by mkellerman** [comment]
Woohoo! that worked!!

put it on 'UDChart'
