### ISSUE TITLE
Custom Functions

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#648]
Hey all!

I'm working on a dashboard and at the top of it, I define a custom function:

https://hastebin.com/egaxohibed.pl

Here is what i get from UDLogging when I hit a button that triggers a set of actions that call it:

10:03:24 [Warn] ExecutionService Error executing endpoint script. The term 'Add-Log' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 

Is there a way to configure a function to be globally available? Even inside of endpoints?

**Comment by adamdriscoll** [comment]
You can use endpoint initialization for this: https://docs.universaldashboard.io/endpoints/endpoint-initialization

**Comment by Jacob-Evans** [comment]
That did it! Thank y ou!
