### ISSUE TITLE
2.3.0 - UDGrid with Server Side Processing - Sort Non Functional. 

### ISSUE THREAD

**Issue by BlairKingsley** [ironmansoftware/universal-dashboard#649]
As per my forum post...
https://forums.universaldashboard.io/t/new-udgrid-with-serversideprocessing-sort-direction/380

**Comment by BlairKingsley** [comment]
About to create pull request with probable fix.

**Comment by adamdriscoll** [comment]
Thanks. Will look at the PR today.
