### ISSUE TITLE
Display Issue Running on LInux

### ISSUE THREAD

**Issue by tonyskidmore** [ironmansoftware/universal-dashboard#652]
First off fantastic product!

I was reading the below articles for some data vizualization on a demo project and thought this would be a great mechanism to use Universal Dashboard and Azure Web Apps for Conatiners:  

[Running Universal Dashboard in a Linux Docker Container](https://stefanstranger.github.io/2018/10/02/RunningUniversalDashboardinALinuxDockerContainer/)  

[Running Universal Dashboard Docker container in Azure Web Apps for Containers](https://stefanstranger.github.io/2018/10/03/RunningUniversalDashboardContainerInwebAppForContainers/)

However, when running UD in the Linux container it was not displaying as I expected.  I tried a few variations of base container (Alpine, CentOS, Ubuntu) but with the same results.  I have simplified my tests down to running 2 VMs under VMware Workstation on my laptop and accessing UD from the same Chrome browser to the running VMs.  Here are the details and the results:  

**Windows 2012 R2**
```
Install-Module UniversalDashboard.Community -AcceptLicense -Force

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Module UniversalDashboard.Community -ListAvailable

ModuleType Version    Name                                PSEdition

---------- -------    ----                                ---------
Script     2.3.1      UniversalDashboard.Community        Desk

Start-UDDashboard -Port 1000
```

![image](https://github.com/tonyskidmore/poshud-core-example/blob/master/images/start-udddashboard-windows-core.png)

**CentOS Linux release 7.6.1810 (Core)**
```
Install-Module UniversalDashboard.Community -AcceptLicense -Force

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Get-Module UniversalDashboard.Community -ListAvailable

ModuleType Version    Name                                PSEdition

---------- -------    ----                                ---------
Script     2.3.1      UniversalDashboard.Community        Desk

Start-UDDashboard -Port 1000
```

![image](https://github.com/tonyskidmore/poshud-core-example/blob/master/images/start-udddashboard-linux-core.png)

Any ideas for the diiference in display?

**Comment by adamdriscoll** [comment]
There is an issue with the pathing. Internally, the UD server was using a lower case path while the path was actually upper case. This is why it works on windows and not linux.

**Comment by tonyskidmore** [comment]
Great thanks Adam for looking at the issues so quickly and resolving it.  Any idea when 2.3.2 will be available?  I would like to be able to demo with the fix included.

**Comment by adamdriscoll** [comment]
@tonyskidmore Apologies for not replying. 2.3.2 is on the gallery.

**Comment by tonyskidmore** [comment]
@adamdriscoll yes great thanks I tried it and it fixes my issue and works great - thanks again!
