### ISSUE TITLE
Is it possible to create chart with fixed Y-axis?

### ISSUE THREAD

**Issue by DanielSSilva** [ironmansoftware/universal-dashboard#654]
Maybe this is already possible, but I would like to have a chart that has on it's Y-axis a fixed value (let's say from 0 to 30) independent of the input data. For example, I have an object that has Dates and temperatures. if the temperature is always around the same values (let's say between 17 and 18), the graph will have spikes , appearing that there are big changes. Take into consideration the following code and the graph it generated
```powershell
New-UDChart -Title "Temperature on day X" -Type Line -Endpoint {    
            
            $30DaysBack = [DateTime]::Now.AddDays(-30)
            0..30 | ForEach-Object {
                [PSCustomObject]@{ 
                    Date = $30DaysBack.AddDays($_).ToShortDateString()
                    Temperature = (Get-Random -Minimum 17.1 -Maximum 18.1)
                }
            }| Out-UDChartData -LabelProperty "Date" -DataProperty "Temperature" -DatasetLabel "Temperature"
        }
```

![image](https://user-images.githubusercontent.com/6862119/53208297-26de2900-362e-11e9-845d-575f7d469b33.png)

**Comment by adamdriscoll** [comment]
You can do something like this. 

```
$db = New-UDDashboard -Title "Min\Max" -Content {
    New-UDChart -Type Line -Endpoint {
        1..10 | % { 
            [PSCustomObject]@{
                Name = $_
                Random = Get-Random -Minimum 1000 -Maximum 10000
            } 
        }   | Out-UDChartData -DataProperty Random -LabelProperty Name
     
    } -Options @{
        scales = @{
            yAxes = @(
                @{
                    ticks = @{
                        min= 0
                        max = 30
                    }
                }
            )
        }
    }
}

Start-UDDashboard -Port 1111 -Dashboard $db
```

For more information about axis options, check out the ChartJS docs: https://www.chartjs.org/docs/latest/axes/cartesian/linear.html

**Comment by DanielSSilva** [comment]
Thank you very much for your quick response. I will test as soon as I can. I'll close it for now and re-open if I need help
