### ISSUE TITLE
Output from Out-UDGridData missing

### ISSUE THREAD

**Issue by svbuckle** [ironmansoftware/universal-dashboard#656]
Hello All,
I am having a bit of a issue with the output of a Out-UDGridData, I am pulling in a SQL database into a variable and then trying to display this. All the fields are displayed correctly except one of them, it is showing as blank, although I can filter on the content of this field so the data is there.

My code is below:

New-UDGrid -Title "UMR Log"  -Headers @("SNOWTicket", "User","Action","THCUser","OldUserOU","LastModified","LastLogon") -Properties @("SNOWTicket", "User","Action","THCUser","OldUserOU","LastModified","LastLogon") -Endpoint {
    $results | Select-Object SNOWTicket,User,Action,THCUser,OldUserOU,LastModified,LastLogon | Out-UDGridData
} -FontColor "black"  
It is the first field that is displaying as blank, and I am not sure what is causing it.

Any help would be appreciated.

Sean Buckle

**Comment by adamdriscoll** [comment]
@svbuckle Hi Sean, what type of field is it? Is it a string or number?
