### ISSUE TITLE
New-UDEndPoint issue with accented characters

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#66]
Accented characters are not preserved. Try this :

$Endpoint = New-UDEndpoint -Url "/recherches/:recherche" -Method "GET" -Endpoint {
    param($recherche)
    [PSCustomObject]@{Value=$recherche} | ConvertTo-Json
} 

PS > $r = Invoke-WebRequest -Uri http://myserver:3000/api/recherches/téé
PS > $r.Content
{
    "Value":  "tÃ©Ã©"
}

Similar issue with this code : 

$Endpoint = New-UDEndpoint -Url "/recherches/:recherche" -Method "GET" -Endpoint {
    param($recherche)
    'éèù' | ConvertTo-Json      
} 

PS > $r = Invoke-WebRequest -Uri http://myserver:3000/api/recherches/toto
PS > $r.Content
"Ã©Ã¨Ã¹"
PS > $r.Content | convertFrom-json
Ã©Ã¨Ã¹

**Comment by adamdriscoll** [comment]
Fixed in 1.6.2. The Content-Type header just had "application/json" instead of "application/json; charset=utf8".

**Comment by apetitjean** [comment]
Very cool, thanks Adam!

2018-05-26 14:36 GMT+02:00 Adam Driscoll <notifications@github.com>:
