### ISSUE TITLE
Buttons on the same level as the Trial Warning are not functional

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#661]
![capture](https://user-images.githubusercontent.com/23514631/53359632-71e38f00-3901-11e9-8505-83f2a1761178.PNG)

The buttons to the right of the Trial window are not clickable when on smaller screens.

When we adjust zoom to move the buttons to above the window, they become functional.

**Comment by adamdriscoll** [comment]
I'll be adding a "Hide" button to 2.3.2.

**Comment by adamdriscoll** [comment]
This has been implemented.
