### ISSUE TITLE
Multiple AuthorizationPolicy entries

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#664]
Is it possible to have more then 1 entry for AuthorizationPolicy entries on a page?

I have tried:

`New-UDPage -Name "Accounts Page" -AuthorizationPolicy @("UserPolicy", "ITPolicy") -Icon "users" -Content {}`
`New-UDPage -Name "Accounts Page" -AuthorizationPolicy "UserPolicy", "ITPolicy" -Icon "users" -Content {}`
`New-UDPage -Name "Accounts Page" -AuthorizationPolicy 'UserPolicy', 'ITPolicy' -Icon "users" -Content {}`
`New-UDPage -Name "Accounts Page" -AuthorizationPolicy ["UserPolicy", "ITPolicy"] -icon "users" -Content {}`

Thank you

**Comment by adamdriscoll** [comment]
The top three examples should work. What's your experience when you do this?

**Comment by Jacob-Evans** [comment]
Trying to use the second line:

I got nothing on either account I use. I have 1 account that would have ITPolicy and 1 that would have UserPolicy.

If I swap back to using just 1 of the policies, it behaves normally and the appropriate account can access.

**Comment by adamdriscoll** [comment]
Seems buggy. I will take a look.

**Comment by adamdriscoll** [comment]
The problem was that if a policy failed, it would stop processing the other policies. So all policies would have to be successful for you to be able to access an endpoint with multiple policies. 

This has been resolved and will be in the 2.4 release.
