### ISSUE TITLE
Missing formatting/style when running  2.1.0 and newer in Docker

### ISSUE THREAD

**Issue by Claustn** [ironmansoftware/universal-dashboard#665]
I noticed that when I upgrade UniversalDashboard above 2.1.0 I loose all formatting when running it in a Docker container.
As an example running Stefan Strangers "hello world" dashboard looks like this is 2.3.1
![chrome_2019-02-27_16-07-04](https://user-images.githubusercontent.com/8179932/53499954-bca00b00-3aa9-11e9-9689-27e32d949bbc.png)
But it looks like this in 2.1.0
![2019-02-27_15-57-05](https://user-images.githubusercontent.com/8179932/53499990-c9bcfa00-3aa9-11e9-8ec6-7a9f7ea2f66c.png)

This is the dashboard script:
https://gist.github.com/stefanstranger/45d8129758eb44b44683c14dba2b8c45

I have also tried multiple different PowerShell core versions, all behave the same, they only render correct when running Universal Dashboards version 2.1.0 and lower (Have not tested all versions though)

**Comment by adamdriscoll** [comment]
@Claustn This has been fixed in 2.3.2. This is being released today.
