### ISSUE TITLE
What is the right way to add a custom http response header to a New-UDEndpoint response?

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#666]
After googling I have tried a number of things:

```
$Request.HttpContext.Response.Headers.Add("Test","Value")
$Response.Headers.Add("Test","Value")
$Response.Headers.AddValueFast("Test","Value")
```

Looking at `$Request.HttpContext.Response.Headers` I can see the type is `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders` and `Get-Member` shows two method signatures for an add function:

```
void IDictionary[string,StringValues].Add(string key, Microsoft.Extensions.Primitives.StringValues value)
void ICollection[KeyValuePair[string,StringValues]].Add(System.Collections.Generic.KeyValuePair[string,Microsoft.Extensions.Primitives.StringValues item)
```

When calling `$Request.HttpContext.Response.Headers.add("test","test")` I get the error:
```
Cannot find an overload for "Add" and the argument count: "2".
```

In the context of a New-UDEndpoint, what is the right way to add a custom http response header?

**Comment by adamdriscoll** [comment]
@ChrisMagnuson Give this a shot:

```
Import-Module UniversalDashboard 

Get-UDRestApi | Stop-UDRestApi

$Endpoint = New-UDEndpoint -Url "test" -Endpoint {
    [Microsoft.AspNetCore.Http.HeaderDictionaryExtensions]::Append($Response.Headers, 'test', 'test')

    "Test" | ConvertTo-Json
}

Start-UDRestApi -Endpoint $Endpoint -Port 10002
```

And then test with: 

```
PS C:\Users\adamr> invoke-webrequest http://localhost:10002/api/test


StatusCode        : 200
StatusDescription : OK
Content           : "Test"
RawContent        : HTTP/1.1 200 OK
                    test: test
                    Content-Length: 6
                    Content-Type: application/json; charset=utf-8
                    Date: Wed, 27 Feb 2019 17:46:57 GMT
                    Server: Kestrel

                    "Test"
Forms             : {}
Headers           : {[test, test], [Content-Length, 6], [Content-Type, application/json; charset=utf-8], [Date, Wed,
                    27 Feb 2019 17:46:57 GMT]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 6
```

**Comment by ChrisMagnuson** [comment]
Perfect, thank you!

I have used other extension methods like the `SendFileAsync` extension method below but I didn't realize there was `[Microsoft.AspNetCore.Http.HeaderDictionaryExtensions]::Append`

```
[Microsoft.AspNetCore.Http.SendFileResponseExtensions]::SendFileAsync(
            $Response, 
            $Result.PDFFilePath,
            $(New-Object -TypeName System.Threading.CancellationToken)
        ).GetAwaiter().GetResult()
```

As this seems to be a common pattern when dealing with Asp..net core, is there a pattern to figuring out what methods are available, like in this instance, how did you figure out that `Append` was available?

**Comment by adamdriscoll** [comment]
On the UD docs, I clicked this from the [Variables Defined in Endpoints](https://docs.universaldashboard.io/endpoints/variables-defined-in-endpoints) page. 

![image](https://user-images.githubusercontent.com/1256531/53515520-6621d500-3a87-11e9-96b6-9895d1dfbf8d.png)

From there, I found the headers property. 

![image](https://user-images.githubusercontent.com/1256531/53515541-71750080-3a87-11e9-844e-f305a52e4506.png)

Next, I checked out the type for the Headers property; IHeaderDictionary. 

![image](https://user-images.githubusercontent.com/1256531/53515549-7a65d200-3a87-11e9-9bdf-47aa90b5af1d.png)

Clicking on that had a list of extension methods. 

![image](https://user-images.githubusercontent.com/1256531/53515568-8356a380-3a87-11e9-927c-54be38dc39d3.png)

On the extension method page, you can see the namespace at the top a, the type name and then the methods. 

![image](https://user-images.githubusercontent.com/1256531/53515581-8f426580-3a87-11e9-8849-2bb3574cdf4b.png)

Glad that worked!
