### ISSUE TITLE
Need ability to have a New-UDEndpoint with an arbitrary URL structure

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#667]
Currently this is restricted to things under `/api`.

I have added a work around to [this](https://github.com/Tervis-Tumbler/universal-dashboard/commit/a9334cd21e25aa2482934c80aacee8061d99a800) fork but arbitrarily removing `/api` from the routes that impact UD endpoints likely breaks other parts of UD.

I personally need this only for rest endpoints that will be deployed separate from any dashboard so the work around is good enough for now but not a good solution in the long term.

**Comment by bateskevin** [comment]
This is a usecase in my company aswell.

**Comment by adamdriscoll** [comment]
This will be possible in PowerShell Universal 1.2. You will be able to specify an API with any structure.
