### ISSUE TITLE
[Question] Using NLog assembly inside an Endpoint ?

### ISSUE THREAD

**Issue by LaurentDardenne** [ironmansoftware/universal-dashboard#674]
Hi Adam,

it is possible to use inside the scriptblock (parameter _-Endpoint_ of the **New-UDEndpoint** cmdlet), the assembly NLog to log informations ? Or this assembly is internal and private to UD ?

**Comment by adamdriscoll** [comment]
You can use Write-UDLog and it will utilize the NLog assembly to write a log.

**Comment by LaurentDardenne** [comment]
Thank you.
