### ISSUE TITLE
Public switch parameter for endpoints & pages (enhancement suggestion)

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#682]
It could be nice to have a -Public switch on endpoints and page to allow anonymous when specified and ignoring the authentication in place. 

A private API might want to expose some public endpoints 

I.E. 

https://contoso.com/api/servertime 
and 
https://contoso.com/api/balance
both on the same UDDashboard with Servertime being a public endpoints while balance being restricted.

**Comment by adamdriscoll** [comment]
-Public has been implemented for REST APIs in the current build.
Now to implement for pages...

**Comment by adamdriscoll** [comment]
Dashboards can now have authentication turned on and off in PowerShell Universal.
