### ISSUE TITLE
New-UDInput font color

### ISSUE THREAD

**Issue by GarySmithPS** [ironmansoftware/universal-dashboard#683]
New-UDInput should support the theme or have a switch for font colour. Currently, only appears to support -backgroundcolor which when set to a dark colour means you can't read the text.

**Comment by adamdriscoll** [comment]
Looks like UDInput supports FontColor. Is there a specific control you're seeing that this doesn't work for? 

```
        New-UDInput -Title "hi" -Endpoint {
            param($This)
        } -BackgroundColor black -FontColor red
```

![image](https://user-images.githubusercontent.com/1256531/56064363-16ddee00-5d2f-11e9-9262-ff38696e4e24.png)

**Comment by GarySmithPS** [comment]
No. It just wasn’t doing anything when I had those same settings configured. I’ll try again when I return after Easter
