### ISSUE TITLE
Cannot pass Multiple EndpointInitialization to New-UDDashboard

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#684]
```
$addlog = New-UDEndpointInitialization -Function "Add-Log"
$cs = New-UDEndpointInitialization -Variable "ConnectionString"
New-UDDashboard -EndpointInitialization @($addlog, $cs) -Theme $Theme -Pages $Pages
```
![image](https://user-images.githubusercontent.com/23514631/53884981-b4385a80-3fea-11e9-91ec-db412b4fb0c3.png)

**Comment by adamdriscoll** [comment]
@Jacob-Evans You can do all that in one call. 

```
$cs = New-UDEndpointInitialization -Variable "ConnectionString"  -Function "Add-Log"
New-UDDashboard -EndpointInitialization @($addlog, $cs) -Theme $Theme -Pages $Pages
```

**Comment by Jacob-Evans** [comment]
Huh, i had tried that before but i did the Function before the Variable and it gave me some sort of trouble.... Do those parameters need to be in the specific order? If not, maybe i just had another typo somewhere else i missed.

Thank you!

**Comment by adamdriscoll** [comment]
Not that I'm aware of. This cmdlet really is just a wrapper around the creation of an [InitialSessionState](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.initialsessionstate?view=powershellsdk-1.1.0) object that is used to initialize the runspaces UD uses. I don't see anything in the documentation stating you wouldn't be able to do that.

**Comment by adamdriscoll** [comment]
Please reopen this issue if you still can't get it to work.
