### ISSUE TITLE
"Loading..." animation during long running scripts.

### ISSUE THREAD

**Issue by bitfrickler** [ironmansoftware/universal-dashboard#685]
Hi,

I often run rather time-consuming (~20 seconds) PowerShell reports.
I load the result into a UdGrid. Unfortunately the grid says "No results found." until the script finishes collecting the data.

Is there a way to display a "loading..." hint (e.g. a spinner animation) while the data is being collected?

Thanks in advance.

**Comment by adamdriscoll** [comment]
There isn't a built in way to do this. Will have to make that customizable.

**Comment by bitfrickler** [comment]
Hi Adam,

thanks for your response. Love the dashboard. I appreciate you considering my problem.
