### ISSUE TITLE
API DELETE method doesn´t take body parameters

### ISSUE THREAD

**Issue by sandrovj** [ironmansoftware/universal-dashboard#686]
I´m trying to run the code below:

$Endpoint = New-UDEndpoint -Url "/admwin/" -Method "DELETE" -Endpoint {
    param($Body)
    $Parameters = $Body | ConvertFrom-Json
    $Computer = $Parameters.Computer
    $User = $Parameters.User
   
 ....

}

But, when I debug the code and try to get the values of $User and $Computer, both variables are empty. 
Does DELETE method take data from body?

**Comment by adamdriscoll** [comment]
Looks like the delete method for the API was never setup to process the body. Will have to get that implemented.
