### ISSUE TITLE
Nivo chart treemap case-sensitivity

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-dashboard#691]
I'm using Nivo Treemap chart based on your example in the docs, and ran into an odd bug. The `-Identity` and `-Value` parameters appear to be case-sensitive, sort of. Here's some code:

```powershell
$TreeData = @{
    Name     = "root"
    children = @(
        @{
            Name  = "first"
            Count = 15
        },
        @{
            Name  = "second"
            Count = 21
        }
    )
}

$Splat_TreeMap = @{
    Treemap  = $true
    Data     = $TreeData
    Value    = "Count"
    Identity = "Name"
    Height   = 500
    Width    = 800
}

New-UDNivoChart @Splat_TreeMap
```

This results in essentially an empty treemap. I found that if I change the values of `-Identity` and `-Value` to lower case then it works:

```powershell
$Splat_TreeMap = @{
    Treemap      = $true
    Data         = $TreeData
    Value        = "count"
    Identity     = "name"
    Height       = 500
    Width        = 800
}
```

This seems counter-intuitive, since it's not especially case-sensitive. The first example actually matches the case of the key names, but this only works if I specify lower-case values for the above mentioned parameters.

Thanks!

**Comment by adamdriscoll** [comment]
Ah. I know whats happening. The serialization from the hashtable to a JSON object changes it to lower case to match what is usually the javascript style of casing. Since JS is case-sensitive, this is why it's done and also why it's not working. This can be fixed.

**Comment by adamdriscoll** [comment]
Resolved in tonight's build.
