### ISSUE TITLE
New-UDInput Bug?

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#694]
https://hastebin.com/oliburoxut.php

If you keep the default option of "Dual Enrollment" without entering the menu and picking it, it does not pass "Dual Enrollment" to $coReason

If you select Off-Campus Lunch, it works and passes "Off-Campus Lunch" to the variable. If you select Off-Campus Lunch and then go back to Dual Enrollment, it will pass "Dual Enrollment" to the variable.

**Comment by adamdriscoll** [comment]
This bug now has a bounty: https://www.bountysource.com/issues/71243131-new-udinput-bug

**Comment by oitptobbe** [comment]
The hastebin link is not working. @Jacob-Evans can you post a section of code so I can check?

**Comment by Jacob-Evans** [comment]
https://pastebin.com/VZJVTKN4

@oitptobbe

**Comment by Jacob-Evans** [comment]
Whoops, posted the wrong link before: https://pastebin.com/RDpyF74p

**Comment by oitptobbe** [comment]
Okay there are a couple of bugs for this issue.
The first is -DefaultValue does not set the default value property in react. I have a fix for that
Then we have a rendering issue.
That the defaultvalue is not "selected" in the dropdown menu.
I know how I can force it to be selected but that meant I can't change the value at all...

In this one I've taken your code and added -DefaultValue "Off-Campus Lunch" and also added a toast to the endpoint.
As you can see, it shows the 
[See example](https://media.giphy.com/media/ZG11cXGdYEMrgQN47t/source.gif)

I'll play around with it a bit more...

**Comment by oitptobbe** [comment]
```
$page = New-UDPage -Name page -content {
    New-UDInput -Content {
        New-UDInputField -Type "select" -Name "coReason" -Placeholder "Checking out Reason" -Values @("Dual Enrollment", "Off-Campus Lunch", "New Option") -DefaultValue "Off-Campus Lunch"
    } -Endpoint {
        param($coReason)
        Show-UDToast -Message "You selected $coReason" -Duration 4000 -Title 'coReason'
    }
}

$dash = New-UDDashboard -Title 'dashboard' -Pages $page
Get-UDDashboard|Stop-UDDashboard
Start-UDDashboard -port 8000 -Dashboard $dash -Name 'dash' -AutoReload
```

This now works, if you leave DefaultValue empty it will be set to the first option in the values list (if the values list contains more than 0 elements).
