### ISSUE TITLE
React Data Grid

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#697]
The React Data Grid has a lot more features than Griddle. Look at implementing a grid based on this component. https://github.com/adazzle/react-data-grid

**Comment by AlonGvili** [comment]
You should take alook at https://github.com/bvaughn/react-virtualized for rendering large lists

**Comment by mkellerman** [comment]
Is this still in the road map? I need a way to show a UDGrid with 20+ columns, and user can pick and chose columns. Need to allow the use to explore the data.

**Comment by mkellerman** [comment]
Something like: https://datatables.net/ ?

**Comment by adamdriscoll** [comment]
I'm looking at using material-table for the new grid\table but I was wondering if UDPivotTable by @psDevUK works for your use-case? https://github.com/psDevUK/UD-Pivot

**Comment by AlonGvili** [comment]
whatever solution you choosing it should be using react virtualize or something like that for rendered large list very fast

**Comment by adamdriscoll** [comment]
UD-Pivot is what I'm recommending for this. Feel free to reopen if you require different functionality.
