### ISSUE TITLE
creating some parameters: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Sader82** [ironmansoftware/universal-dashboard#698]
Hi all,

have been playing around with the UD dashboard for the first time, and have some issues with predefined parameter in the dashboard.ps1

my line 2
$cache:credential = Import-CliXml -Path "C:\_scripts\testService\creds\MyCredential.xml"

The error in the eventlog
Error starting dashboard: 
 The system cannot find the path specified.
 
 at <ScriptBlock>, C:\_scripts\testService\dashboard.ps1: line 2
at <ScriptBlock>, <No file>: line 1

When I do a test-path the path is fine... Am I missing something?

**Comment by Sader82** [comment]
The path is correct but github does not shows it correctly....

**Comment by adamdriscoll** [comment]
Hi Sader,

This doesn't really look like a UD issue. 

If you just do: 

```
$Credential = Import-CliXml -Path "C:\scripts\testService\creds\MyCredential.xml"
```

Does it work?

**Comment by Sader82** [comment]
Adam,

Yes when I run the commands independent it works, when I do it via the UD I receive the error 'The system cannot find the path specified'

**Comment by adamdriscoll** [comment]
Can you post more of your dashboard script?
