### ISSUE TITLE
New-UDGrid -PageSize does not seem to work

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-dashboard#7]
Setting small values in New-UDGrid -PageSize does not seem to work.

Unless I'm misunderstanding the parameter it should set to the number of rows per page which it is currently not doing.

**Comment by adamdriscoll** [comment]
Sounds like a bug. Will get it fixed for next version.

**Comment by adamdriscoll** [comment]
@Chirishman Can you please provide a sample dashboard that reproduces this? This is currently passing integration so I'm not quite sure what's different between what we are testing and what you are testing.

Thanks

**Comment by adamdriscoll** [comment]
I can't reproduce this issue. If you are still having this problem and can provide a sample dashboard, please reopen the issue.
