### ISSUE TITLE
Calling Functions from buttons

### ISSUE THREAD

**Issue by shortNviolent** [ironmansoftware/universal-dashboard#701]
Hey so I have a page that removes and creates buttons as a user progresses through. I have found a couple of issues with onclick functions.

First after a few iterations into creating and deleting buttons using New-UIElement the onclick functions stop working. Moving to New-UDButton with the -onclick option seems to work around that issue. 

The second issue (I have not tried this from other buttons) but after deleting and replacing buttons I cant call functions within my code. It just seems to ignore the call. I am not sure if this is a known issue or something else. If there is a way for me to debug this for you to help identify issues please let me know. 

Thanks

**Comment by adamdriscoll** [comment]
Could you post an example to reproduce this? Seems buggy.
