### ISSUE TITLE
Clear-UDElement not clearing collection

### ISSUE THREAD

**Issue by BenevolentD** [ironmansoftware/universal-dashboard#71]
I'm trying to run the demo code here: https://github.com/ironmansoftware/ud-chatroom

Everything seems to work great except for the button to clear the chatroom using the "Clear-UDElement" function. The onClick function is firing because if I place another action in there like a SQL insert that works as expected.

        New-UDColumn -Size 2 {
            New-UDElement -Tag "a" -Attributes @{
                className = "btn"
                onClick = {
                    Clear-UDElement -id "chatroom"
                }
            } -Content {"Clear"}
        }
    }

I'm using version 1.5.3 of UD.

**Comment by adamdriscoll** [comment]
Fixed in 1.6.0
