### ISSUE TITLE
Backslash in page name

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/universal-dashboard#715]
Hi

If I'm using a backslash in a page name, the page will not display, because I guess the link can't resolve to the page:

```powershell
$udPages = @()
$udPages += New-UDPage -Name 'Home' -Icon 'home' -Content {

    New-UDCard -Content { New-UDParagraph -Text 'Home' }
}
$udPages += New-UdPage -Name 'SQLSERVER\INSTANCE' -Icon 'database' -Content {

    New-UDCard -Content { New-UDParagraph -Text 'SQLSERVER\INSTANCE' }
}
$udPages += New-UdPage -Name 'foo/bar' -Content {

    New-UDCard -Content { New-UDParagraph -Text 'foo/bar' }
}

$udDashboard = New-UDDashboard -Pages $udPages
Start-UDDashboard -Dashboard $udDashboard -Port 80
```

The second page will not display, in the browser it's linked with a forward slash:
![image](https://user-images.githubusercontent.com/1934246/55323643-ede07200-547f-11e9-97b9-88ff31a11ab1.png)

Are there any workarounds to that?

**Comment by adamdriscoll** [comment]
Not that I'm aware of. The slashes are used to denote page levels so they would likely have to be escape within UD. I'll mark this as an enhancement though.
