### ISSUE TITLE
Dashboard on IIS not working

### ISSUE THREAD

**Issue by michael-brown-viewpoint** [ironmansoftware/universal-dashboard#719]
I am unable to get a dashboard running vis IIS on a Windows 2012 R2 server. It has 5.1 installed. I ran the.NET Core runtime installer and restarted IIS. I following the tutorial exactly, but I'm getting ta 500.19 error when I go to local host:

```
Detailed Error Information:

Module
   RequestFilteringModule 

Notification
   BeginRequest 

Handler
   aspNetCore 

Error Code
   0x8007000d 

Config Error
   Unrecognized attribute 'removeServerHeader'  

Config File
   \\?\C:\inetpub\wwwroot\web.config 
```
```
Config Source:
    7:     <security>
    8:       <requestFiltering removeServerHeader ="true" />
    9:     </security>

```

This is with the latest version of UniversalDashboard.Community. I do notice that instead of netcoreapp2.0 like in the docs, my module has a folder called netstandard2.0. I'm not sure if that's because of a change in the module or because of my runtime or something when I downloaded it. I downloaded it using PowerShell Core but its the same.

**Comment by adamdriscoll** [comment]
Ah interesting. That setting turns off sending info about the IIS web server when the HTTP request is made. It's considered a security feature in later versions of IIS. I didn't realize it was a new flag though so I will have to make a tweak so this doesn't happen to people all the time.
