### ISSUE TITLE
New-UDElement doesn't work with 'select' tag.

### ISSUE THREAD

**Issue by BenevolentD** [ironmansoftware/universal-dashboard#72]
UD 1.5.3

The select tag doesn't seem to function for New-UDElement.

This **does** work:

    New-UDRow -Columns { 
        New-UDColumn -Size 12 -Endpoint {
            $testString = '1','2','3'
            
            New-UDElement -Tag "ul" -Id "testId" -Content {
                Foreach($item in $testString) {
                    New-UDElement -Tag "li" -Content {
                        $item
                    }}
                }
                }
                }

This **doesn't** work:

    New-UDRow -Columns { 
        New-UDColumn -Size 12 -Endpoint {
            $testString = '1','2','3'
            
            New-UDElement -Tag "select" -Id "testId" -Content {
                Foreach($item in $testString) {
                    New-UDElement -Tag "option" -Content {
                        $item
                    }}
                }
                }
                }

**Comment by adamdriscoll** [comment]
1.6.0 should have a functional select for UDElement. There needs to be a JS call made after creating the markup. 

https://github.com/ironmansoftware/ud-controls/blob/master/src/select.ps1

**Comment by BenevolentD** [comment]
Thanks for the info. Is there an ETA for that version? Was hoping to use the endpoint functionality to populate a select box periodically with new data.

**Comment by adamdriscoll** [comment]
This is implemented in 1.6.0-beta1.
