### ISSUE TITLE
Show-UDModal Sizing

### ISSUE THREAD

**Issue by dtnyc9005** [ironmansoftware/universal-dashboard#720]
[FeatureRequest]

It would be great if we can control the width and height properties of Show-UDModal.

thanks,

**Comment by Jacob-Evans** [comment]
Upvoting this, The auto-sizing is nice, but if you have a Date Picker inside of a Modal, the calendar tend to be bigger then the modal if you have only a few things.

**Comment by adegutis** [comment]
I upvoted the initial request/comment because even a simple UDTable inside a Modal starts wrapping with few columns, depending on the content length.

**Comment by adamdriscoll** [comment]
I added a `-Height` and `-Width` parameter to `Show-UDModal`. You'll be able to specify pixel sizing as well as percentages.
