### ISSUE TITLE
Unused Authorization Policy equals broken site

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#724]
Trying to convert my site to using Windows Auth caused me a great deal of headache.

In the end I found out that if you add a new-UDAuthorizationPolicy that isn't used on any of your pages, the entire site breaks and you're left with a grey page (or I guess depending on theme).

```
$HRPolicy = New-UDAuthorizationPolicy -Name "HumanResources" -Endpoint {
    param($ClaimsPrincipal)
    $ClaimsPrincipal.HasClaim("http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", "S-1-5-21-1168975120-759244214-17591369-17222") 

}


$AdminPolicy = New-UDAuthorizationPolicy -Name "Admins" -Endpoint {
    param($ClaimsPrincipal)
    $ClaimsPrincipal.HasClaim("http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", "S-1-5-21-1168975120-759244214-17591369-17223")
    
}

$AuthMethod = New-UDAuthenticationMethod -Windows
$LoginPage = New-UDLoginPage -AuthenticationMethod $AuthMethod -PassThru -AuthorizationPolicy @($HRPolicy, $AdminPolicy)

```

If I misspell "HumanResources" in the -authorizationPolicy on any of my pages, the site breaks.

I don't know if its intentional or if it even something that needs to be fixed, but it did certainly bug me.

**Comment by adamdriscoll** [comment]
Oy. Yeah that is annoying.
