### ISSUE TITLE
Page with Endpoint does not work with spaces

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-dashboard#734]
# Description
When a page is defined as an endpoint it does work and enables some cool use cases, good stuff! However it seems when my Page is defined as an endpoint instead of Content I cannot have spaces in my page name. 

# Repro
Consider a Page that is initiated like this:
```New-UDPage -Name "Honey Deployment" -Icon empire -Endpoint {```

This results in a page not found:
![image](https://user-images.githubusercontent.com/274883/55599707-9e6ba180-571e-11e9-8d4b-bc0ca98ab542.png)

By removing the space in the Name Param: 
```New-UDPage -Name "HoneyDeployment" -Icon empire -Endpoint {```

Works great!

![image](https://user-images.githubusercontent.com/274883/55599758-d07d0380-571e-11e9-92d5-e98f3eb389c6.png)

This is not an issue when the page is defined with Content:

```New-UDPage -Name "Honey Deployment" -Icon empire -Content {```

**Comment by adamdriscoll** [comment]
I have to say, I love that there is a page not found now...

**Comment by leeberg** [comment]
> I have to say, I love that there is a page not found now...

It's a Feature!

**Comment by adamdriscoll** [comment]
This looks fixed in the latest. Added a test in the latest PR.
