### ISSUE TITLE
Publish-UDDashboard failing when running sc.exe

### ISSUE THREAD

**Issue by jcoelho93** [ironmansoftware/universal-dashboard#735]
I tried to publish my dashboad as a windows service using Publish-Dashboard. But the service was not being created, and this cmdlet was just displaying the sc.exe help message.

So I figured that there must be something wrong with this command.
After going through the source code I noticed the sc.exe command was not being used correctly.
There should be a [space after each argument](https://serverfault.com/questions/152393/problems-creating-service-using-sc-exe).

I was able to install my dashboad manually by changing the way sc.exe is executed by adding a space like so:

`sc.exe create UniversalDashboard DisplayName= "PowerShell Universal Dashboard" binPath= "$binPath --run-as-service" start= "$ServiceStart"
`
(notice the space ' ' after each '=' synbol)

**Comment by adamdriscoll** [comment]
Weird! Can you let me know what version of Windows you are running?

**Comment by jcoelho93** [comment]
Hi Adam,

I'm running on Windows 7 and using PowerShell 5.1.14409.1018

All the documentation on sc.exe talks about leaving a space between the '=' and the argument...

**Comment by adamdriscoll** [comment]
Ok. Thanks. Seems to work on Win10 for me. We even have an integration test that runs this on the builder so it's strange to see it not working. 

Either way, easy fix and will get this out in the next release. Thanks!

**Comment by jcoelho93** [comment]
> 
> 
> Ok. Thanks. Seems to work on Win10 for me. We even have an integration test that runs this on the builder so it's strange to see it not working.
> 
> Either way, easy fix and will get this out in the next release. Thanks!

Thank you! Great project by the way
