### ISSUE TITLE
Wizard Control

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#737]
It would be awesome to have a wizard. Something like: 

```
New-UDWizard -Steps {
        New-UDWizardStep -Title { 
               # input or something here 
        } 
}
```

I think it would be important to maintain state through the wizard. 

Could use the stepper control: https://material-ui.com/demos/steppers/

**Comment by AlonGvili** [comment]
Its on my todo list, i will start to work on it after i finish the core components.

**Comment by chrismo16** [comment]
How is this coming along? Can we expect it in an upcoming release?

**Comment by PorreKaj** [comment]
Any day now ;-)
