### ISSUE TITLE
New-UDNivoChart -Heatmap not working since 2.2.1

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#741]
Decided to try the new Prerelease 2.4.0, and the chart isn't loading correctly:

![image](https://user-images.githubusercontent.com/9411143/55924686-b2e8e780-5bbf-11e9-8913-92ac602883b0.png)

Working in 2.2.1:

![2 2 1_only](https://user-images.githubusercontent.com/9411143/55924293-238f0480-5bbe-11e9-9c65-0676db963bdc.png)

My dashboard stopped working completely on version 2.3.0+, so i didn't try it in other releases.

**Comment by adamdriscoll** [comment]
Can you please post some example code and data? I just made some docs for this on 2.4. 

https://docs.universaldashboard.io/components/data-visualizations/nivo/heatmap
