### ISSUE TITLE
New-UDGrid -NoFilter

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#742]
Add option to remove the Filter bar.

(is there a CSS workaround for now?)

**Comment by adamdriscoll** [comment]
Not that I'm aware of. You could probably select it somehow since UD grid has a class and then just set it to `display:none` but might take some messin around.

**Comment by mkellerman** [comment]
This is my workaround:
````powershell
$UDTheme = Get-UDTheme -Name Default
$UDTheme.Definition['input[name="filter"]'] = @{ 'display' = 'none' }
New-UDDashboard -Theme $UDTheme ...
````

**Comment by mkellerman** [comment]
:thumbs up:
