### ISSUE TITLE
Unicode characters not correctly shown when run in WinPS

### ISSUE THREAD

**Issue by rdbartram** [ironmansoftware/universal-dashboard#746]
ModuleVersion: 2.3.2
PSVersion: 4.0, 5.0, 51

Problem:
Similar to that described in #56, no matter whether written directly in content or dynamically pulled from a file, special characters such as "ö,ä,ü" are not shown correctly. If some of these characters are placed within an attribute i.e. title for a heading etc, the element doesn't even render.

Workaround:
Run in powershell core. tested on 6.1.2 and 6.2. There everything renders as normal.

**Comment by adamdriscoll** [comment]
The issue with #56 was actually just the file encoding of the PS1 file and there were no changes made to use. 

![image](https://user-images.githubusercontent.com/1256531/56050324-cf446b80-5d08-11e9-9055-9204bd1199b3.png)

**Comment by rdbartram** [comment]
I know but that is not the problem here. I can work with the same file in winos and pscore. One works and one doesn't. The file type is utf8. I can create a temp repo for you to see if that helps. You should be able to check though by trying to use one of those characters I mentioned before.

**Comment by adamdriscoll** [comment]
This works fine for me if I make sure to save as UTF-8 with BOM. Doesn't seem like saving just UTF8 works. 

![image](https://user-images.githubusercontent.com/1256531/56054392-e9d01200-5d13-11e9-8a69-0c0e95ac1e93.png)

```
Get-UDDashboard | Stop-UDDashboard
$Dash = New-UDDashboard -Title "Test Dash..." -Content {

	New-UDCard -Title 'ö,ä,ü' -Text 'ö,ä,ü'
	New-UDCard -Title 'Version' -Text "$($PSVersionTable.PSVersion)"
	} 
	
	Start-UDDashboard -Port 10000 -Dashboard $Dash
```

```
PS C:\Users\adamr> C:\Users\adamr\Desktop\dashboard.ps1

Name        Port Running
----        ---- -------
Dashboard3 10000    True


PS C:\Users\adamr> get-module UniversalDashboard

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.3.2      UniversalDashboard                  {Add-UDElement, Clear-UDElement, ConvertTo-JsonEx, Disable...
```

![image](https://user-images.githubusercontent.com/1256531/56054412-fbb1b500-5d13-11e9-996a-67444b633bcf.png)

**Comment by rdbartram** [comment]
If its that simple, it'd be wierd... And still doesn't explain why it works in core....

**Comment by adamdriscoll** [comment]
Yeah not sure. Regular UTF8 files work for me in PS Core as well.

**Comment by adamdriscoll** [comment]
They must have updated something in PS Core. 

dashboard.ps1 (UTF8)
```
'ö,ä,ü'
```

From WinPS: 

```
PS C:\Users\adamr> C:\Users\adamr\Desktop\dashboard.ps1
Ã¶,Ã¤,Ã¼
```

From PS Core:

```
PS C:\Users\adamr> C:\Users\adamr\Desktop\dashboard.ps1
ö,ä,ü
```

dashboard.ps1 (UTF8 with BOM)
```
'ö,ä,ü'
```

From WinPS: 

```
PS C:\Users\adamr> C:\Users\adamr\Desktop\dashboard.ps1
ö,ä,ü
```

**Comment by rdbartram** [comment]
At least I know I'm not crazy. I didn't bother changing to bom because I never thought it would be because of that. Thanks for the quick easy fix

**Comment by adamdriscoll** [comment]
Yeah sure thing!
