### ISSUE TITLE
Need the ability to send toasts at anytime with any control

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#76]
I'd like to be able to send a toast to a user when he press a button (or something else) and not only in a form with New-UDInputAction.

Thanks Adam! :-)

**Comment by adamdriscoll** [comment]
Hey Arnaud, 

This is a duplicate of #54. It's on my radar and I will try and get into 1.6.0.

**Comment by adamdriscoll** [comment]
This is implemented in 1.6.0. Had it mostly implemented but just fixed a bug that was preventing it from working.

**Comment by apetitjean** [comment]
Very cool! Thanks!
