### ISSUE TITLE
Split API Endpoints to Separate Files

### ISSUE THREAD

**Issue by petercovach** [ironmansoftware/universal-dashboard#761]
When you have an dashboard that has a collection of API endpoint, the dashboard.ps1 file becomes somewhat unruly.  Additionally, having all endpoints in the same file makes source control somewhat annoying.  I propose this enhancement:

I would like a directory next to the dashboard.ps1 called API.  Within this directory, you could have each individual endpoint associated with the dashboard.  To add an endpoint, you simply add a new .ps1 file into the API directory.

So the file structure would look like:

dashboard.ps1
API
     |
     server.CPU.Get.ps1
     server.Memory.Get.ps1

The API files would look like:

New-UDEndpoint -Url "/server/memory/:Parameter1" -Method GET -Endpoint{
    param(
             [STRING]$Parameter1
            )

    #Do Something
}

**Comment by LaurentDardenne** [comment]
For that I use files in dot source, if it facilitates the control of the sources it requires more rigor.
The difficulty, relative, occurs when several people work on this file but on different parts.

**Comment by adamdriscoll** [comment]
PowerShell Universal 1.2 will enable this functionality.

**Comment by LaurentDardenne** [comment]
Thank you Adam.
