### ISSUE TITLE
Nivo Calendar charts don't display in internet explorer and colour scheme not working

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#765]
Been designing a presentation, and was using Firefox and everything displayed great. Then as this was for a director he only has internet explorer. And although everything displayed in Firefox, the NIVO Calendar chart would simply not display in Internet Explorer. Same on my machine using internet explorer. Using the latest and greatest dashboard 2.4.0
  Two issues for the price of one here. I was also using the -colors parameter to colour in my charts. I was using 'spectral' for my heat map charts, so thought I would apply the same colouring scheme to the calendar.  But it just turned all cells that would be showing a colour to black. So was only a black and white calendar chart not the spectral effect I was hoping for.

**Comment by adamdriscoll** [comment]
Oh, yeah. Looks like the nivo charts really don't like IE: https://nivo.rocks/calendar

I'll see if there is anything I can do to resolve that but the issue inside the chart library for sure.

**Comment by psDevUK** [comment]
Thanks Adam, I know your busy doing your conference stuff at the moment, which I hope is going well. Saw no-one else had reported this issue, so thought I would.  Thank for reply

**Comment by adamdriscoll** [comment]
I'm going to close this as Nivo doesn't support IE so we cannot support it either.
