### ISSUE TITLE
Warning Module not supported PowershellGet 2.0

### ISSUE THREAD

**Issue by tomwignall** [ironmansoftware/universal-dashboard#766]
WARNING: The specified module 'UniversalDashboard.Community' with PowerShellGetFormatVersion '2.0' is not supported by
the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module, 'UniversalDashboard.Community'.

I have .NET 4.7.2 installed...
I have powershellget version 1.0.0.1 (and only one installed)
I have update to windows 10 pro 1903 insider if that has anything to do with it...

![powershell-module](https://user-images.githubusercontent.com/2325427/57095070-e542bc00-6d09-11e9-895c-d8fe17f7c265.PNG)

any help welcome :)

**Comment by adamdriscoll** [comment]
You need to update your PowerShellGet version. 

```
Update-Module PowerShellGet
```

**Comment by tomwignall** [comment]
I installed Powershell Core and that resolved by issue, thanks.
