### ISSUE TITLE
Provide different toast savors

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#77]
It would be awesome if we could display different kinds of toasts and custom them.

I found this open source project which is ultra coooooool : https://github.com/dolce/iziToast 
I don't have the skill necessary to integrate it with UD but I guess that should be totally doable.

Thanks!

**Comment by adamdriscoll** [comment]
Cool. I like it!

**Comment by apetitjean** [comment]
Awesome!!!
