### ISSUE TITLE
New-UDGrid calculated column

### ISSUE THREAD

**Issue by craibuc** [ironmansoftware/universal-dashboard#772]
Is there a way to add a calculated column to a `UDGrid`?  I was hoping that I could use the `@{name='';expression={}}` syntax, but it doesn't appear to work.

```powershell
# get data from REST API
$Data = Invoke-WebRequest $url -Headers $headers -Method Post -Body $payload | ConvertFrom-Json
...
# create a grid w/ a calculated column, `Duration`, that is 
New-UDGrid -Title "Running" -Headers @("ID", "Name", "Started","Duration") -Properties @("ID", "NAME", "START_TIME",@{name='Started'; expression={ "{0:d\.hh\:mm\:ss}" -f (new-timespan $_.START_TIME $_.END_TIME) }}) -Endpoint {
        $Data | Out-UDGridData
 }
```

**Comment by adamdriscoll** [comment]
You can format the data within the Endpoint for New-UDGrid. 

Here's an example

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.UITest/Integration/Grid.Tests.ps1#L124

**Comment by craibuc** [comment]
Thank you.
