### ISSUE TITLE
It seems UD can run out of Quartz threads

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/universal-dashboard#776]
As requested in: https://forums.universaldashboard.io/t/ud-hosted-under-iis-endpoint-not-starting-up-or-crash/674/4

it seems 10 threads can be to little.
we need someway to monitor thread count or have it logged that it need a free thread.

I would say that 10 threads is to little.
Are thies also used for "access" ?`to serve content?

**Comment by McAndersDK** [comment]
I found out how to set a higher count.
#999

**Comment by adamdriscoll** [comment]
@McAndersDK Does this resolve the issue for you? I will mark this closed if that's the case.

**Comment by McAndersDK** [comment]
Yes, in my tests it does.

MVH
Anders Andersson

Den 2. aug. 2019 kl. 18.49 skrev Adam Driscoll <notifications@github.com<mailto:notifications@github.com>>:


@McAndersDK<https://github.com/McAndersDK> Does this resolve the issue for you? I will mark this closed if that's the case.
