### ISSUE TITLE
Could not load type 'System.Runtime.InteropServices.Architecture' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#79]
> I'm having some issues getting Start-UDDashboard to run. It is throwing Could not load type 'System.Runtime.InteropServices.Architecture' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
> I verified that I have 2.1.104 installed, do I need to install an earlier version?

**Comment by RobertCGouge** [comment]
I will say that if I launch pwsh as the shell, it works just fine, but if I launch from powershell at version 5.1 it throws that error.

**Comment by adamdriscoll** [comment]
@RobertCGouge Can you check to see which version of .NET Framework you have installed? 

![image](https://user-images.githubusercontent.com/1256531/38835660-681932b2-4191-11e8-8e81-c8ffeca20ed0.png)

**Comment by RobertCGouge** [comment]
I have that version, but I will admit I did recently update to 4.7.1 to go through a Microsoft course, so it is very likely I was just on 4.6 when I tried.

**Comment by adamdriscoll** [comment]
@RobertCGouge Does it work with 4.7 installed? My machines with 4.7 seem to work. I'm considering making that a requirement for 1.6.0.

**Comment by RobertCGouge** [comment]
Yes, with 4.7.1 installed it launches with no issue.

**Comment by adamdriscoll** [comment]
Ok. Thanks. I will just make this a requirement for the 1.6.0 release so we won't run into this in the future.
