### ISSUE TITLE
New-UDInputfield unable to get file name only file content

### ISSUE THREAD

**Issue by wsl2001** [ironmansoftware/universal-dashboard#799]
when working with New-UDInputfield - file "Name" - type "file" react is pulling the content of the uploaded file and readastext.

it will be nice if we can capture the file name as well if we are trying to save the file on the server or even better have the ability to save uploaded files. like for example if someone wants to upload an image or excel file ....etc

its nice right now that it process the file but will be much nicer if we have the ability to save files

**Comment by ThePoShWolf** [comment]
I just tried uploading an Excel file to my dashboard hoping to use ImportExcel to update a table and then noticed that it reads the uploaded file as text, as @wsl2001 pointed out. It would be awesome if ```New-UDInputField``` had a ```-SavePath``` or some similar parameter to tell it where to save the file and then we could choose what to do with it.
