### ISSUE TITLE
New-UDElement is sending my custom component raw CLIXML

### ISSUE THREAD

**Issue by gpduck** [ironmansoftware/universal-dashboard#8]
I wrote a custom react component that takes 2 parameters, one of which is an array of objects converted from Invoke-RestMethod.  The array parameter is coming across to the react component as a string of CLIXML instead of being converted back to objects.

I ended up using ConvertTo-Json to pass them through as a string and then parse it out in my component.  Even doing that required me to call `.ToString()` on the output to prevent it from turning into CLIXML.

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.4.2      UniversalDashboard                  {New-UDChart, New-UDColumn, New-UDDashboard, Get-UDDashboa...

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by adamdriscoll** [comment]
@gpduck Is it possible to send me your React component? Would save me a bunch of time.
