### ISSUE TITLE
[2.3.2] Textarea in New-UDInputField submits field instead of line break

### ISSUE THREAD

**Issue by MatthewHamous** [ironmansoftware/universal-dashboard#813]
In 2.3.2 using New-UDInputField, pressing the enter key in the textarea submits the field instead of inserting a line break. I tested in 2.2.0 and 2.1.0 using the same dashboards; those enter line breaks instead. Maybe a version in between 2.2.0 and 2.3.2 causes this.

Not browser specific - tested using Firefox, Chrome, and IE.

**Comment by adamdriscoll** [comment]
This was fixed in 2.4.
