### ISSUE TITLE
this.fabInstance.destroy is not a function

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#815]
When clicking the button (https://github.com/ironmansoftware/universal-dashboard/issues/810) too fast (i guess) i get this error

![image](https://user-images.githubusercontent.com/20628942/58203135-b5b81b80-7cd9-11e9-98d0-b2b924481968.png)

The issues existing in 2.4.0 beta1 as well, though with another error message, and more frequent, described here.
https://forums.universaldashboard.io/t/udbutton-in-grid-only-works-first-time/730

**Comment by adamdriscoll** [comment]
Can you do me a favor and grab the error stack trace that is present in the F12 developer tools when this happens? I think this is a bug in Materialize but I'm not seeing it. I'm not making that destroy call in UD.

**Comment by PorreKaj** [comment]
![image](https://user-images.githubusercontent.com/20628942/58885661-e6894f00-86e2-11e9-9c1c-271fe7ba6ca5.png)

**Comment by adamdriscoll** [comment]
Awesome. Thanks!

**Comment by PorreKaj** [comment]
in 2.6.0 I'm able to spamclick the buttons all I want.
