### ISSUE TITLE
After Applying latest fixed - toast is not working from IIS but works locally

### ISSUE THREAD

**Issue by wsl2001** [ironmansoftware/universal-dashboard#829]
when applied the fix for button icons when clicking the button toast is not working from IIS but works locally.
the issue is with vendor.js file 
![image](https://user-images.githubusercontent.com/47834749/58372839-e4a8da00-7ef1-11e9-8429-380069579b90.png)

![image](https://user-images.githubusercontent.com/47834749/58372872-7f091d80-7ef2-11e9-9140-efbffe111e76.png)

**Comment by wsl2001** [comment]
![image](https://user-images.githubusercontent.com/47834749/58363861-1893e900-7e79-11e9-8b0e-63b19c0e2c03.png)

**Comment by adamdriscoll** [comment]
Can you please try a a nightly build? I cannot reproduce this. https://forums.universaldashboard.io/t/nightly-releases/756

**Comment by adamdriscoll** [comment]
Closing as this is a duplicate for #832
