### ISSUE TITLE
Bug in UD 2.4: running in IIS locally fails w/ Enterprise w/o license

### ISSUE THREAD

**Issue by bielawb** [ironmansoftware/universal-dashboard#835]
It looks like 2.4 is allowing to use UD enterprise only locally, which is fine, but it causes issues when running it in IIS. Even though I try to access the page locally I'm blocked by the banner that claims otherwise (I guess assuming that nobody would use IIS locally):

![Local-But-Remote](https://user-images.githubusercontent.com/3310142/58386993-08f6da80-8008-11e9-8f45-e270d751ddbb.png)

**Comment by adamdriscoll** [comment]
Should be fixed. You can give it a shot in tonight's nightly.
