### ISSUE TITLE
Enhancement to add the sterling pound sign to UDCounter £

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#837]
So at the moment my dashboard counters when referring to money have to show the dollar sign as it does not seem the pound sign is recognised:-
working: -Format '$0,0.00'
would like: -Format '£0,0.00' 
to work please.

**Comment by adamdriscoll** [comment]
We have removed UDCounter from v3. You'll be able to use New-UDDynamic and New-UDCard to get the same effect. You'll also be able to put a sterling pound sign in there ;)
