### ISSUE TITLE
UD 2.4 ENT, Variable Scoping

### ISSUE THREAD

**Issue by dtnyc9005** [ironmansoftware/universal-dashboard#840]
@adamdriscoll, have a scheduled endpoint that is working flawlessly in 2.3.2, after doing some test with 2.4(which I would love to move too) realized I was running into this whole manual variable scoping issue, the problem is I dont see an efficient way of accomplishing the same when I have a loops and pscustom objects, going the argument list would be immensely painful and clunky to manage. Not sure if this is a bug or not but this code has worked since early days of UD, not sure what you advise?

Thanks.

**Comment by adamdriscoll** [comment]
@dtnyc9005 Can you let me know what controls you are seeing issues with? There were some issues fixed with variable scoping in recent builds. I would suggest grabbing a nightly and giving it a shot: https://forums.universaldashboard.io/t/nightly-releases/756

**Comment by dtnyc9005** [comment]
Issues are with the New-UDButton  - > Show-UDModal, Im trying to get the nightly builds going but running into the animation and just stays there? (before merging this into the 2.4 module, I did unlock the files prior) any suggestions?

**Comment by adamdriscoll** [comment]
@dtnyc9005 I released 2.4.1 with a bunch of bug fixes that includes the one that should fix your issue. You should be able to just pull the latest from the gallery. 

I think the problem you're having is that the browser may be caching the JS files with the nightly builds. You can try to do a hard refresh of your browser (Ctrl+F5). People have reported that issue but IDK why it doesn't happen with builds that are on the gallery.

**Comment by dtnyc9005** [comment]
Cool, so I just scrapped the whole 2.4 and went 2.4.1, it loads fine, but the variables are still null, and on my chart I see - index.b7bc2c22ea0dd4a81e0f.bundle.map on titles, strange... still investigating

**Comment by adamdriscoll** [comment]
Please reopen if you are still having issues.
