### ISSUE TITLE
UDInput black text when dark theme 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#842]
Should be white text.

![image](https://user-images.githubusercontent.com/1256531/58600741-06cc9000-8243-11e9-9714-894e6eb440d6.png)

**Comment by dtnyc9005** [comment]
@adamdriscoll noticed the same deal for calendar component, when date is selected its black, another note on the calendar component, the text appears to be white, as well as buttons missing, let me know if I should file seperate issue

![Untitled](https://user-images.githubusercontent.com/33912010/58604649-24115680-8263-11e9-87c4-2c45cd354253.png)

**Comment by psDevUK** [comment]
Hi I applied a green theme for my  UDInput now only the titles show in green and all text is black.  Same thing for a text box on a UDCard text sows as black even if you define different colour in the parameter

**Comment by Jacob-Evans** [comment]
This issue also seems to be present on the Azure theme.
