### ISSUE TITLE
New-UDMuCardMedia Suggestion

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#848]
So i was playing around with this today and was wondering if it would be possible to have the Dashboard pull from a RTSP Stream from a security camera.

Turns out... Not so much... Here is the sample code i used to test this: https://pastebin.com/r8Y9nAEw

Is this something that is possible?

Edit: Media Information:
Codec: H264 - MPEG-4 AVC (part 10) (h264)
Video resolution: 640x480

**Comment by adamdriscoll** [comment]
That's a good question. I'll have to look into it

**Comment by Jacob-Evans** [comment]
So, for some more information:

I added a -Alt to the line with the Text of "Failed to Load."
When i restarted the site, it did NOT show the video or the Alt String, and the Enable-UDLogging put nothing into the log file either.

**Comment by AlonGvili** [comment]
> So, for some more information:
> 
> I added a -Alt to the line with the Text of "Failed to Load."
> When i restarted the site, it did NOT show the video or the Alt String, and the Enable-UDLogging put nothing into the log file either.

As far as i know the component not support RTSP , you need to use an external video player
