### ISSUE TITLE
Unable to use Grant-UDJsonWebToken 

### ISSUE THREAD

**Issue by BryanDM** [ironmansoftware/universal-dashboard#85]
I'm currently unable to use Grant-UDJsonWebToken in 1.6.0 Beta1

I receive error:

Grant-UDJsonWebToken : The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception.

**Comment by adamdriscoll** [comment]
Can you please provide me with your $PSVersionTable?

**Comment by BryanDM** [comment]
Name                                      Value                                                                                                                          
----                                           -----                                                                                                                          
PSVersion                                  5.1.14409.1012                                                                                                                 
PSEdition                                   Desktop                                                                                                                        
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                               10.0.14409.1012                                                                                                                
CLRVersion                                 4.0.30319.42000                                                                                                                
WSManStackVersion                   3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion                    1.1.0.1

**Comment by BryanDM** [comment]
![image](https://user-images.githubusercontent.com/36564688/39072908-0a079a16-44ba-11e8-9512-0003e6e555fa.png)

**Comment by adamdriscoll** [comment]
Fixed in 1.6.0-beta2. Should be out by Monday.
