### ISSUE TITLE
IIS Breaking change in 2.4.1

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#850]
Cause not yet determined.

Something between 2.4.0release and 2.4.1 has changed that seems to relate to IIS - at least it seems to only affect IIS users.

https://forums.universaldashboard.io/t/2-4-beta-to-2-4-1-update-page-spins-on-loading/767/6

Since updating, I cant get past the fancy loading screen.

Troubleshooting steps done so far:
- Reducing my dashboard to something simple, not authentication or anything.
- Going though the web.config to make sure changes were added
- Making a non IIS page (which works)
- Crying into my old IBM keyboard

**Comment by wsl2001** [comment]
The issue will happen if you update the files. always delete all files except your dashboard.ps1 and web.config and then copy the new ones from latest release except dashboard.ps1 and web.config and you should not see the react spinning screen.

**Comment by PorreKaj** [comment]
https://forums.universaldashboard.io/t/2-4-beta-to-2-4-1-update-page-spins-on-loading/767/17
Indeed.
