### ISSUE TITLE
Unable to initiate UD dashboard.ps1 

### ISSUE THREAD

**Issue by saqibch1** [ironmansoftware/universal-dashboard#852]
Hi, I am facing following error while running dashboard.ps1. if someone could help as I am very new to PowerShell
The term 'dashboard.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (dashboard.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by cadayton** [comment]
I assume you navigated to the directory containing 'dashboard.ps1'.

```.\dashboard.ps1```

The above should start the script.  Perhaps your are forgetting '.\' prior to the script name?

**Comment by adamdriscoll** [comment]
I agree with @cadayton. I think this is an issue just executing the script.

**Comment by saqibch1** [comment]
@cadayton you are right there is something with "dashboard.ps1". I run the script manually without run the file and now its working fine. 
Anyhow thanks for your response.
