### ISSUE TITLE
Unable to deploy on IIS

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#86]
I'm trying to deploy my dashboard on IIS and I can't seem to get it to work. I tried to run a default page from your IIS documentation : 
dashboard.ps1 :
```
Start-UDDashboard -Wait -Dashboard (
    New-UDDashboard -Title "Hello, IIS" -Content {
        New-UDCard -Title "Hello, IIS"
    }
)
```
![image](https://user-images.githubusercontent.com/37376232/39046279-94d01d78-4463-11e8-8630-bfa745c9da25.png)

License file is in net462 

![image](https://user-images.githubusercontent.com/37376232/39046218-6e8c1018-4463-11e8-8a0b-56d86e7c4b76.png)

Thanks

**Comment by adamdriscoll** [comment]
Can you check in the event log to see if there are any application errors for UniversalDashboard.exe? Did you install the ASPNET Core module? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.1

**Comment by adamdriscoll** [comment]
Can you also let me know which version you are trying to deploy?

**Comment by adamdriscoll** [comment]
@Phyziik 

I can reproduce this on 1.6.0-beta1. There is a regression in the web.config. You'll need to update it to point to the net462 folder rather than the net461 folder. 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\net462\universaldashboard.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

You'll also need to download the ASP.NET Core Module from here: 
https://go.microsoft.com/fwlink/?linkid=832756

I had it installed but had to install the new version to get it to work.

**Comment by adamdriscoll** [comment]
Fixed in 1.6.0-beta2.

**Comment by Phyziik** [comment]
Ok, so I've noticed that I didn't have to proper module. So I updated to the one you linked. I now get my dashboard to display, but I don't get the same behavior as when it's running from a powershell console. The modules that I import in my enpointinitializer don't work anymore, which gives me errors about the cmdlets not existing. I tried a simple version, with one import and one cmdlet, but I can't seem to log anything.

Here's my test : 
```
$testDash = New-UdDashboard -Title "Global Automated Acceptance Test" -NavBarColor '#FF1c1c1c' -NavBarFontColor "#FF55b3ff" -BackgroundColor "#FF333333" -FontColor "#FFFFFFF"  -Theme $theme -Content {
   Enter-SCSession
   New-UDCard -Title Test -Content {"Created"}
   #New-UDCard -Title Test -Content {"$(Get-SCSession | Out-String)"}
} -EndpointInitializationScript 
   Import-module SecurityCenter
   Enable-UDLogging -Level Error -FilePath "c:\web_logs.txt"
}
Start-UdDashboard -Port 80 -Dashboard $testDash -Wait
```

If I comment "Enter-Scsession", the udcard "Created" appears just fine, but when I put my "Enter-scsession", I get an empty page, no errors, no logs.

I have a feeling that the IIS publishing doesn't handle the module imports the same as the Powershell deployment.

**Comment by adamdriscoll** [comment]
IIS probably doesn't have access to the same paths as a regular user. You can deploy the modules into the UD IIS directory or provide an account with some permissions to access where the modules are available.

**Comment by Phyziik** [comment]
Hey, I've been messing around with IIS to figure out if the issue was on my side, and I have a feeling the endpointinitializationscript isn't working anymore. I can't seem to get anything to be logged, and I can't initialize functions either

```
$testDash = New-UdDashboard -Title "Global Automated Acceptance Test" -NavBarColor '#FF1c1c1c' -NavBarFontColor "#FF55b3ff" -BackgroundColor "#FF333333" -FontColor "#FFFFFFF"  -Theme $theme -Content {
   New-UDElement -Tag 'a' -AutoRefresh -Endpoint {
      $test = Test-me
      Set-UDElement -Id Tester -Content {"$test"}
   }
   New-UDCard -Title Test -Id Tester -Content {"Created"}
   #New-UDCard -Title Test -Content {"$(Get-SCSession | Out-String)"}

} -EndpointInitializationScript {

   function Test-Me
   {
   start notepad
   }

   Enable-UDLogging -FilePath "C:\Users\mstjean\Desktop\web_logs.txt"
   
}

Start-UdDashboard -Port 80 -Dashboard $testDash -Wait
```

**Comment by adamdriscoll** [comment]
I just tried this with beta3 (coming out in the next couple minutes) and got it to work. Rather than starting notepad, I returned a string and it updated the Tester element via the function. 

```
$testDash = New-UdDashboard -Title "Global Automated Acceptance Test" -NavBarColor '#FF1c1c1c' -NavBarFontColor "#FF55b3ff" -BackgroundColor "#FF333333" -FontColor "#FFFFFFF"  -Theme $theme -Content {
    New-UDElement -Tag 'a' -AutoRefresh -Endpoint {
       $test = Test-me
       Set-UDElement -Id Tester -Content {"$test"}
    }
    New-UDCard -Title Test -Id Tester -Content {"Created"}
    #New-UDCard -Title Test -Content {"$(Get-SCSession | Out-String)"}
 
 } -EndpointInitializationScript {
 
    function Test-Me
    {
        "String"
    }
 
    #Enable-UDLogging -FilePath "C:\Users\AdamR\Desktop\web_logs.txt"
    
 }
 
 Start-UdDashboard -Port 80 -Dashboard $testDash -Wait
```
One thing that I was missing that I hadn't thought about was the WebSocket protocol. Set-UDElement uses web sockets to communicated back and forth to the server. You'll need to enable that in IIS. 

![image](https://user-images.githubusercontent.com/1256531/39305542-18b307f4-4923-11e8-85b0-64ba57293b19.png)

We can chat about this later today as well.

**Comment by Phyziik** [comment]
Great. I installed the feature and I'm repeatedly pressing F5 on the PSGallery page haha! Oh and I had updated my code a second after I posted it, to use a string (initial test I was doing), but I guess you grabbed it too fast hehe

I'll have it tested on my side by the time we chat!

Thanks a bunch

**Comment by Phyziik** [comment]
I just tried with the beta3 and I think I isolated the issue. It is not related to IIS, but to the endpointinitializationscript.

When I run this either with -wait in console or deployed on IIS : 
```
$testDash = New-UdDashboard -Title "Global Automated Acceptance Test" -NavBarColor '#FF1c1c1c' -NavBarFontColor "#FF55b3ff" -BackgroundColor "#FF333333" -FontColor "#FFFFFFF"  -Theme $theme -Content {
   New-UDElement -Tag 'a' -AutoRefresh -Endpoint {
      $test = Test-me
      Set-UDElement -Id Tester -Content {"$test"}
   }
   New-UDCard -Title Test -Id Tester -Content {"Created"}
   #New-UDCard -Title Test -Content {"$(Get-SCSession | Out-String)"}

} -EndpointInitializationScript {

   function Test-Me
   {
    return "I wrote this"
   }

   Enable-UDLogging -FilePath "C:\Users\mstjean\Desktop\web_logs.txt"
   
}

Start-UdDashboard -Port 8085 -Dashboard $testDash -Wait
```
I get an error `One or more errors occured` and this log : 
```
10:48:07 ExecutionService Scope variables--------------
10:48:07 ExecutionService $ = 
10:48:07 ExecutionService ^ = 
10:48:07 ExecutionService ConfirmPreference = High
10:48:07 ExecutionService DebugPreference = SilentlyContinue
10:48:07 ExecutionService ErrorActionPreference = Continue
10:48:07 ExecutionService ErrorView = NormalView
10:48:07 ExecutionService FormatEnumerationLimit = 4
10:48:07 ExecutionService InformationPreference = SilentlyContinue
10:48:07 ExecutionService MaximumHistoryCount = 4096
10:48:07 ExecutionService NestedPromptLevel = 0
10:48:07 ExecutionService OutputEncoding = System.Text.ASCIIEncoding
10:48:07 ExecutionService PROFILE = C:\Users\mstjean\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
10:48:07 ExecutionService ProgressPreference = Continue
10:48:07 ExecutionService PSDefaultParameterValues = System.Management.Automation.DefaultParameterDictionary
10:48:07 ExecutionService PSEmailServer = 
10:48:07 ExecutionService PSSessionApplicationName = wsman
10:48:07 ExecutionService PSSessionConfigurationName = http://schemas.microsoft.com/powershell/Microsoft.PowerShell
10:48:07 ExecutionService PSSessionOption = System.Management.Automation.Remoting.PSSessionOption
10:48:07 ExecutionService PWD = C:\WINDOWS\system32
10:48:07 ExecutionService StackTrace = 
10:48:07 ExecutionService VerbosePreference = SilentlyContinue
10:48:07 ExecutionService WarningPreference = Continue
10:48:07 ExecutionService WhatIfPreference = False
10:48:07 ExecutionService Context variables--------------
10:48:07 ExecutionService Request = Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest
10:48:07 ExecutionService Response = Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse
10:48:07 ExecutionService User = 
10:48:07 ExecutionService MemoryCache = Microsoft.Extensions.Caching.Memory.MemoryCache
10:48:07 ExecutionService Error executing endpoint script. One or more errors occurred.
10:48:07 ComponentController {"Error":{"message":"One or more errors occurred.","location":null,"type":"error","id":null,"refreshInterval":0,"autoRefresh":false,"hasCallback":false}}
10:48:07 Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor Executing JsonResult, writing value { Error = PowerShellProTools.UniversalDashboard.Models.Error }.
10:48:07 Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://localhost:8085/af7ae505a9eed503f8b8e6982036873e.woff2  
10:48:07 Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware The file /af7ae505a9eed503f8b8e6982036873e.woff2 was not modified
10:48:07 Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 5.9104ms 304 font/woff2
```

If I refresh my page (F5), the problem goes away, and my code works (changes the UDElement to "I wrote this").

**Comment by artvandelay440** [comment]
> > IIS probably doesn't have access to the same paths as a regular user. You can deploy the modules into the UD IIS directory or provide an account with some permissions to access where the modules are available.
> 
> I'm running into this as well. I'm using the `CredentialManager` module to store and retrieve passwords, and I'm assuming IIS doesn't have rights to where it's installed. (C:\ProgramFiles\WindowsPowerShell\Modules). Moving the contents of the module to wwwroot and importing from there didn't seem to work either. I guess i could store credentials with Import-cliXml, but i'd rather not if anyone has any more light on this issue, or any other methods of retrieving credentials with IIS.

Nevermind, I changed the app pool user and got it all to work fine.

**Comment by tridionation** [comment]
Hi, Trying out community edition on IIS
Followed the installation instructions but get.
Is community version supported on IIS?

HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.

Windows 10 18362.295
IIS 10.0.18362.1
2.5.2  UniversalDashboard.Community
All IIS Application Development Feature enabled
Dot net core installed with https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.5-windows-hosting-bundle-installer
