### ISSUE TITLE
Floating Action  Button not working in 2.4.1

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#862]
It seems that the Floating Action Buttons in 2.4.1 are not working at all.

I have a Dashboard working great in 2.3.2 but when moving to 2.4.1 the first thing I noticed is my FAB just shows a red circle but none of the other FAB buttons pop up.

I also tried to load a very simple Dashboard to confirm it wasn't my code and still no FAB.

see below.

![image](https://user-images.githubusercontent.com/22712034/58901031-4c1f1080-86ce-11e9-9702-ce33da9b26ec.png)

![image](https://user-images.githubusercontent.com/22712034/58901071-6a850c00-86ce-11e9-8cc6-8b036e434a40.png)

**Comment by psDevUK** [comment]
I found the same thing when I tried to use a floating button in my 2.4.1 I never used one before, but yeah I have the exact same issue.
