### ISSUE TITLE
Footer Default Link not removeable since 2.4.0

### ISSUE THREAD

**Issue by e1ze** [ironmansoftware/universal-dashboard#863]
Hi,

as discussed in the forum thread [Created with PowerShell Universal Dashboard - Remove this](https://forums.universaldashboard.io/t/created-with-powershell-universal-dashboard-remove-this/667/10?u=mordecai) it is currently (2.4.0 and 2.4.1) not possible to remove the default footer link [Created with PowerShell Universal Dashboard](http://www.poshud.com/). I can add new links, add the copyright message etc. but i am not able to remove the default link.
In 2.3.2 the default link was removed with the same code as using in 2.4.0 and 2.4.1.
Am i missing something or doing something wrong?
You can find an example in the forum thread.

Thanks

**Comment by psDevUK** [comment]
have you tried copying your license file over from previous dashboard module, as this seemed to allow me to put custom footer in ok in 2.4.1

**Comment by e1ze** [comment]
@psDevUK Thank you for this info,
I have now copied the license file into a "new" dashboard and also put the dashboard behind an IIS webserver. Now the default link is hidden in the footer and only my link is shown. I don't know if the problem is still a bug  (so I leave the issue open), but for me it is fixed now.

**Comment by adamdriscoll** [comment]
Just verified this is working for me as well.
