### ISSUE TITLE
New-UDDashboard -NavBarColor 'black' no longer changes the colour in 2.4.1

### ISSUE THREAD

**Issue by Zuldan** [ironmansoftware/universal-dashboard#865]
Unfortunately I can no longer change the nav bar color in v2.4.1. 

-NavBarColor 'black' works perfectly in v2.2.0

**Comment by psDevUK** [comment]
Hi, yep agreed it didn't like the colour black when I tried as well...However you can easily set it in the theme.  I have created an example for you here:-
https://github.com/psDevUK/UDscripts/blob/master/BlackNavBar.ps1
 This sets both the navbar and the footer to be the colour black with white coloured text as defined in the $theme which then is applied to the dashboard. i hope this helps

**Comment by Zuldan** [comment]
@psDevUK thanks for that! The workaround worked.
