### ISSUE TITLE
Out-UDGridData does not retain custom filter when trying to sync-udelement

### ISSUE THREAD

**Issue by wsl2001** [ironmansoftware/universal-dashboard#866]
below code in previews releases retain filter and update data

$Page1 = New-UDPage -Name "Services" -Icon server -Content { 

         New-UDElement -Id "Services" -Tag div4 -EndPoint {
    
        New-UDGrid -Id "Grid" -Title "Services" -Headers @("Name","Status","Select") -Properties @("Name","Status","Select") -Endpoint {
        
                $Cache:Services | Out-UDGridData
               
                  }
                                 
              }  
                        
             New-UDButton -Text "Refresh" -OnClick {
             Sync-UDElement -Id "Grid" -Broadcast       
          } 
      } 

with 2.4.1 
the filter will be cleared when refresh button clicked and you start over.

**Comment by psDevUK** [comment]
I assume this has something to do with the built in pre-loader? Can you set the pre-loader to only load it once, as the grids did used to "silently refresh" but now it's like your pressing F5.  I do love the preloader as that works well on initial visit, but can that only run once? And would that then fix this refresh problem if it didn't run with the pre-loader everytime?

**Comment by wsl2001** [comment]
You might be right because when you have data that creates pages in out-udgriddata and you filter for something on page 3 to action on it you dont need the refresh to clear everything and have you start over to filter again to see the status.

out-udgriddata should retain your filter session and by clicking the sync element button you still have the filter applied and your data should be refreshed to match the new status.

**Comment by leeberg** [comment]
**TESTED** - Confirmed WORKS OK in 2.4.0 - ISSUE is present in 2.4.1.
2.4.0 - Sync triggers a "soft" fresh where data refreshes but filter is not affected.
2.4.1 - Sync triggers a "full" refresh of control and filter

Tested with:
```powershell
#issue866.ps1
# to test run this and find a service you can start and stop... "lfsvc" is a good choice
# in 2.4.0 clicking REFRESH does not RESET the filter
# in 2.4.1 clicking REFRESH DOES reset the filter

Get-UDDashboard | Stop-UDDashboard

Start-UDDashboard -Content {
    New-UDDashboard -Title 'Dashboard Basics' -Content {
        New-UDElement -Id "Services" -Tag div4 -EndPoint {

      
                
                New-UDGrid -Id "Grid" -Title "Services" -Headers @("Name","Status") -Properties @("Name","Status") -Endpoint {
                    
                        $Cache:Services = Get-Service | Select-Object -Property 'Name','Status'
                        $Cache:Services | Out-UDGridData
                   
                      }
                                     
                  }  
                            
                 New-UDButton -Text "Refresh" -OnClick {
                 Sync-UDElement -Id "Grid" -Broadcast       
              } 
          } 

} -Port 10000
```
