### ISSUE TITLE
-links not working on ud-counter 2.4.1

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#868]
I was hoping to make my counters link to other pages on the dashboard.  I saw the -links parameter and nothing happened when providing 
-Links @(
    New-UDLink -Text 'This is a link' -Url '#!'
)
but with valid values

**Comment by e1ze** [comment]
@psDevUK 
I am running my dashboard at version 2.4.1 with New-UDCounter and the links to other pages are working. The links are using the current directory, so as in the example below the first counter with the url to "vms" links to a page in the same directory with the url "vms".

**Example**:

<img src="https://user-images.githubusercontent.com/6794362/59252945-7708e780-8c2d-11e9-8130-36c5aa849ab3.png" alt="Example of UD Counters with links" width="800"/>

```powershell
New-UDRow {
  New-UDColumn -LargeSize 3 -Content {
    New-UDCounter -Title "vCenters" -AutoRefresh -RefreshInterval 60 -TextAlignment Left -TextSize Large -Links @(New-UDLink -Text "VMs per vCenter" -Url "vms" -FontColor blue) -Endpoint {
      $(($Cache:VCSession).count) | ConvertTo-Json
    }
  }
  New-UDColumn -LargeSize 3 -Content {
    New-UDCounter -Title "vCenter Error Events (Last 24h)" -AutoRefresh -RefreshInterval 60 -TextAlignment Left -TextSize Large -Links @(New-UDLink -Text "vCenter Events" -Url "vcenter-events" -FontColor blue) -Endpoint {
      $(($Cache:VCEvents24).count) | ConvertTo-Json
    }
  }
  New-UDColumn -LargeSize 3 -Content {
    New-UDCounter -Title "ESXi Hosts" -AutoRefresh -RefreshInterval 60 -TextAlignment Left -TextSize Large -Links @(New-UDLink -Text "ESXi Hosts" -Url "hosts" -FontColor blue) -Endpoint {
      $(($Cache:VCHosts).count) | ConvertTo-Json
    }
  }
  New-UDColumn -LargeSize 3 -Content {
    New-UDCounter -Title "Open Snapshots" -AutoRefresh -RefreshInterval 60 -TextAlignment Left -TextSize Large -Links @(New-UDLink -Text "Open Snapshots" -Url "snapshots" -FontColor blue) -Endpoint {
      $(($Cache:VCSnapshots).count) | ConvertTo-Json
    }
  }
}
```

**Comment by psDevUK** [comment]
Cool beans thanks @e1ze will give this a go, thanks for the reply.

**Comment by psDevUK** [comment]
Doh, I feel stupid. Thanks again @e1ze im using the grid layout, and it seemed increasing the height by one is now showing the link at the bottom.
