### ISSUE TITLE
Force desktop mode when viewing on mobile clients

### ISSUE THREAD

**Issue by Zuldan** [ironmansoftware/universal-dashboard#869]
Is there a way I can force a mobile client to view the dashboard page in desktop mode?

The pie charts and bar graphs look terrible (well unrecognizable) on a Samsung mobile. If I force the web browser to view the dashboard in desktop mode then everything looks perfect!

If there is no way to currently do this then maybe then I'd like to make this issue a feature request ;-)

**Comment by psDevUK** [comment]
Hi Zuldan, have you read https://docs.universaldashboard.io/components/formatting and watched https://www.youtube.com/watch?v=GMr_j8iXmas what you are asking is built into universal dashboard, you just need to incorporate the -small -medium -large into the layout sounds like you want everything to 12 on a small screen.  Hope this helps
