### ISSUE TITLE
UD Controls missing

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#87]
I've noticed that many UD Controls are missing, like UDCheckbox and others. Were you planning to release them on the following beta release?

Thanks

**Comment by adamdriscoll** [comment]
@Phyziik I realized this yesterday. I'll be pushing out a new beta this week with those in the manifest. Here's a fixed manifest for the time being. 

Just replace the PSD1 in the root with this manifest until that release is out. 

[UniversalDashboard.txt](https://github.com/ironmansoftware/universal-dashboard/files/1933274/UniversalDashboard.txt)

**Comment by adamdriscoll** [comment]
This have been fixed in 1.6.0-beta2. Will be out by Monday.

**Comment by Phyziik** [comment]
Great, thanks. I had noticed in the psd that they weren't there, but I thought it was because they weren't tested for beta1!
Thanks!

**Comment by Phyziik** [comment]
I haven't gone through the whole list of Controls, but I've noticed that UDSwitch and UDButton are not in 1.6.0-beta2.

**Comment by Phyziik** [comment]
Great! Thanks!
