### ISSUE TITLE
Separate module into multiple modules

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#880]
The UD module is getting big and I think it should be separated. This would allow people to pick and choose what they install. For the core components, I will continue to keep the source in a single repository but just publish to different modules on the gallery. I also think that they should all be versioned and released at the same time in order to maintain some sanity. 

I'm proposing that we create the following modules. 

## UniversalDashboard.Core

This module would contain the core functionality of UD. It would include the webserver, REST API support, and the framework for the client-side javascript. It would not include a UI framework by default. This would eventually allow for easy switching of frameworks. The initial frameworks would be Materialize and Material UI. 

## UniversalDashbaord.Materialize

This would include all the cmdlets and react components for Materialize. This module would provide a "framework". The idea would be that some of the cmdlets would work for all framework modules. This would include things like New-UDFooter and New-UDSideNav. 

## UniversalDashboard.MaterialUI

This would include all the cmdlets and react components for MaterialUI. This would also be a framework module. 

## UniversalDashboard.Charts

This would be the enterprise charts as a stand alone module. It could be run with UniversalDashboard.Core for people with a license. 

## UniversalDashboard.Security

This module would contain the enterprise security features for authorization and authentication. It could be run with UniversalDashboard.Core for people with a license. 

## UniversalDashboard.Community

This module would be a stub. Kind of like the Microsoft.AspNetCore.All module. It just requires all the modules that are currently included with the UD.Community module so that when you install it from the gallery it brings down all the modules with it. 

### Required Modules 

- UniversalDashboard.Core
- UniversalDashboard.Materialize
- UniversalDashboard.MaterialUI

## UniversalDashboard

This module would be a stub. Kind of like the Microsoft.AspNetCore.All module. It just requires all the modules that are currently included with the UD module so that when you install it from the gallery it brings down all the modules with it. 

### Required Modules 

- UniversalDashboard.Core
- UniversalDashboard.Materialize
- UniversalDashboard.MaterialUI
- UniversalDashboard.Charts
- UniversalDashboard.Security

**Comment by MSAdministrator** [comment]
I actually have been meaning to use UD for awhile but haven’t had a direct need. I would suggest though that you break out the components as you have them but also provide a central repository where all other components are sub-Modules (git Modules) where someone can download the entire thing or piece each component as needed.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by adamdriscoll** [comment]
I like the idea of submodules and have used them in the past. I will need to weigh whether or not that I actually want to maintain multiple git repos for all the components. A lot of other teams, like ASP.NET and dotnet in particular, are moving towards a monorepo structure because it's easier to maintain. I'll evaluate the workflow of submodules though because I do like the idea of being able to clone a repo without having to clone all the components. 

That said, the UD repo isn't really that big so I might lean towards a single repo even if it's means bringing down a little more code than might be necessary. 

I think the build tools will need to be enhanced to be more modular and do less of "building the world" and less manual steps when adding new components.

**Comment by psDevUK** [comment]
Personally I'm the type of guy, who is like if it's not broken don't fix it. Everything works really well at the moment, and the package is only like just over 30mb yeah?  Just thinking it might confuse newbies who want to try your product, but put off by the amount of modules to download?
  It does make total sense what you want to do, but having never used sub-modules myself not sure what benefits this would bring other than smaller module packages?

**Comment by adamdriscoll** [comment]
The hope here is that the newbies won't notice. You'll still install UniversalDashboard and then under the covers it will be installing all the dependencies. This module configuration is more for advanced users that want to pick and choose.

**Comment by MSAdministrator** [comment]
Yeah with Submodules the point is to segment each code base into individual repos but have a master repo that (when cloned/downloaded) will just pull all the necessary modules (repos) and in addition when viewing the master repo you’ll still see the Submodule but they actually reside in a different location (repo). 

Additional benefits are that a developer can update a single Submodule without modifying the entire master repo

**Comment by wsl2001** [comment]
Adam i like the idea and i think its very helpful.

**Comment by cadayton** [comment]
Don't have a strong opinion one way or the other.  I would go with the way that lets you have a life outside of maintaining UD.

**Comment by AlonGvili** [comment]
I think you should do it

**Comment by McAndersDK** [comment]
I would say yes, as it will also show how to extend UD, by just looking at the repository.
This would also make it possible to upgrade part of UD, and not it all.
I guess the startup time is also quicker if modules are excluded?

maybe even seperate it even more, so each chart have its own?
UniversalDashboard.Charts."ChartType" ?
UniversalDashboard.Charts could then just like the other, be an "empty" one to hold the requirement to all UniversalDashboard.Charts."ChartType" ?

**Comment by adamdriscoll** [comment]
This has been done in v3.
