### ISSUE TITLE
LoginPage - RedirectURL support not working

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#888]
It appears that the redurecit URL support is still not working at this time (#681 #319 ). 

Testing scenario 
Authentication: Azure 
Test URLs : http://localhost:9999/NotHome?Answer=42
UD Version : 4.0 and 4.1 
powershell : 5.1

Once I hit this URL, I am brought to the plain login page : http://localhost:9999/login instead of
the login page containing a RedirectURI. 

Therefore, I land on http://localhost:9999/home once I click the login button, which does not correspond to the initial link.

**Comment by adamdriscoll** [comment]
Ah. I see the issue here. It's only working with forms auth and not any of the other auth providers. Thanks for the info.

**Comment by adamdriscoll** [comment]
Actually fixed it for OAuth this time....

The fix was to store the returnUrl in local session storage and forward the user to that page after login. Azure wasn't returning the returnUrl parameter back to UD for some reason.
