### ISSUE TITLE
Custom Components for UD

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#9]
Originally from: https://github.com/adamdriscoll/poshprotools/issues/225

Here is my prototype for this functionality. I would like some feedback from the community on this. 

## New-UDElement

```
New-UDElement -Tag <string> [-Attributes <hashtable>] [-Content <scriptblock>] [-Id <string>]
```

This cmdlet lets you specify any HTML tag and attributes for those tag. Tags can be nested within each other to create the mark up for a page. 

So for example, if you wanted a header that is a link, you could do this. 

```
New-UDElement -Tag "h1" -Content {
    New-UDElement -Tag "a" -Attributes @{ href="http://www.google.com" } -Content { "Google" }
}
```

This would produce: <h1><a href="http://www.google.com">Google</a></h1> 

But! It would do it using the React virtual DOM so it is faster than just writing DOM. 

## Helper Functions

I am planning on adding functions to the UD module or possibly creating a separate module, due to the massive amount of functions included, to mimic each of the valid HTML tags.

That means, the above example can become as short as: 

```
h1 { a -a @{ href = "http://www.google.com" } { "Google" } }
```

## Events 

Although the above is helpful for creating static content, it would be possible now with New-UDHtml. With the new custom component functionality, you could also add scriptblocks to events in the Attributes Hashtable. 

This would mean that you could wire up JavaScript events to PowerShell.

```
    button -a @{ 
        onClick = {
            Start-Process Notepad
        }
    } -Content { "Open Notepad" }
```

## Set-UDElement 

Events are nice but this could be done with New-UDInput\New-UDInputField. In addition to triggering arbitrary PowerShell, you could also update the UI's state based on actions in the events. 

In this example, we update the content of the span "mySpan" to have different content after clicking the button. You could also change attributes or the tag entirely. 

```
    span -Id "mySpan" -Content {
        "Some text"
    }

    button -a @{ 
        onClick = {
            Set-UDElement -Id "mySpan" -Content {
                "Some other text"
            }
        }
    } -Content { "Click Me" }
```

![capture-1](https://user-images.githubusercontent.com/1256531/34422311-4f22dab8-ebda-11e7-83b3-d09e243f99b8.gif)

## Get-UDElement

Getting data from the UI would work the reverse of setting. If you wanted to get the value of another field in an event, you could call Get-UDElement. 

```
    input -a @{type="textbox"} -Id "txtProcessName"

    button -a @{ 
        onClick = {
            $element = Get-UDElement -Id "txtProcessName"
            Stop-Process $element.Value
        }
    } -Content { "Stop Process" }
```

## Custom Components 

All of this would lead to the ability to create custom components in PowerShell. For example, if we wanted to create a component for the [Material Design Collection](http://materializecss.com/collections.html), we could do something like this. 

```
function New-UDCollection {
    param($Items, $Header)

    ul -a @{ className = "collection with-header" } {
        li -a @{ className = "collection-header" } { h4 { $Header } }
        foreach($item in $items) {
            li -a @{ className = "collection-item" } { $item }
        }
    }
}
```

In our dashboard, we could then import the module that defines this custom component and then use it just like any other UD component. 
```
        $dashboard = New-UDDashboard -Title "Test" -Content {
            New-UDCollection -Header "Alvins" -Items @("Alvin", "Alvin", "Alvin", "Alvin")
        }
```

![image](https://user-images.githubusercontent.com/1256531/34421993-5679aafa-ebd8-11e7-819e-7d2cbfcd6ba1.png)

**Comment by adamdriscoll** [comment]
This is implemented in 1.5.0-beta1.

**Comment by Phyziik** [comment]
I just want to understand, You say that this was implemented in 1.5.0-beta1, which means that it should be in the 1.5.0 (march 7th) version, right? I'm trying to create custom buttons and work with the onclick event similar to this example : 
```
button -a @{ 
        onClick = {
            $element = Get-UDElement -Id "txtProcessName"
            Stop-Process $element.Value
        }
    } -Content { "Stop Process" }
```

I tried passing a function to the onclick event of my button like this : 
```
New-UDElement -Id "AllTests_button" -Tag "button" -Attributes @{onclick={
                              test-me
                              }} -Content {"Run All"}
```
But this doesn't do anything.

Thanks

**Comment by adamdriscoll** [comment]
@Phyziik 

Can you try this in your first example? 

```
 onClick = {
            $element = Get-UDElement -Id "txtProcessName"
            Stop-Process $element.Attributes["Value"]
        }
```

For your second example, where is your function defined? Within the same script as the dashboard?

**Comment by Phyziik** [comment]
Instead, I simplified my example : 
```
New-UDElement -Id "AllTests_button" -Tag "a" -Attributes @{className='btn';onClick={
                                    New-Item -Path c:\CreatingaFile.txt
                              }} -Content {"Run All"}
```
And nothing occurs.

My _test-me_ was initialized in the 
`-EndpointInitializationScript { test-me }`
of my New-UdDashboard.

Am I doing something wrong?

I found a src of your _New-UDButton_, but I'm not sure if I should be intergrating that, or if it's already wrapped by the _New-UDElement_ ?

**Comment by adamdriscoll** [comment]
I just reproduced this issue. It has to do with the UDElement being in the UDTable. There isn't currently a good work around for this. 

I'll get it into the maintenance release. I hope to get that out sometime this weekend. 

I'm tracking the issue in #40. 

As for the ud-controls library (New-UDButton etc), once those are complete, they will be included with UD. They should work in their current form but you will have to add them yourself. 

I'm tracking that in #29

**Comment by Phyziik** [comment]
Thank you for that, I’ll be following these!

Great work, keep it up! I really enjoy what you are offering here.

Cheers
