### ISSUE TITLE
New-UDPage endpoint + Name not working anymore.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#901]
Previously, while the New-UDPage with the url parameter did not create a menu item, it was possible to get the item there by assigning a page name afterward. 

Maybe this was not intended in the first place, but it allowed to use a dynamic page which had a corresponding menu item associated to it. 

This currently does not work anymore as the item is still produced in the side-menu but not clicked anymore. 

To test this, run the following dasshboard then click on the "P1" or "P2" page in the menu. 

```
Get-UDDashboard | Stop-UDDashboard


$p1 = New-UDPage -Url '/P1' -Endpoint {New-UDCard -Title 'Page' -text '#1'}
$p2 = New-UDPage -Url '/P2' -Endpoint {New-UDCard -Title 'Page' -text '#2'}

$p1.Name = 'P1'
$p2.Name = 'P2'

$dash = New-UDDashboard -Pages $p1,$p2

Start-UDDashboard -Dashboard $dash -Port 9999 


```

**Comment by adamdriscoll** [comment]
I fixed the parameter set so you can now use `-Name` with `-Endpoint` but it does look like clicking does not work for some reason.

```
Get-UDDashboard | Stop-UDDashboard

$p1 = New-UDPage -Name 'P1' -Endpoint {New-UDCard -Title 'Page' -text '#1'}
$p2 = New-UDPage -Name 'P2' -Endpoint {New-UDCard -Title 'Page' -text '#2'}

$dash = New-UDDashboard -Pages $p1,$p2

Start-UDDashboard -Dashboard $dash -Port 9999 
```
