### ISSUE TITLE
[Enhancement] Support for OpenID Authentication

### ISSUE THREAD

**Issue by e1ze** [ironmansoftware/universal-dashboard#910]
Hi,

it would be awesome, if the OpenID (OIDC) standard could be used during authentication process. It should be integrated by default in ASP .NET Core ([OpenIdConnectAuthentication](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/)).

[Using OpenID Connect](https://blogs.msdn.microsoft.com/mvpawardprogram/2016/09/27/using-openid-connect/)

> #### ASP.NET Core Security middleware supports third-party authentication using the code grant/flow.
> 
> - OpenIdConnectAuthentication - Configurable for any third-party.
> - OAuthAuthentication – Configurable for any third-party and pre-configured for:
>   - GoogleAuthentication
>   - FacebookAuthentication
>   - MicrosoftAccountAuthentication
>   - TwitterAuthentication

Thanks :)

**Comment by adamdriscoll** [comment]
This will be available in tonight's nightly build. There are new parameters to New-UDAuthenticationMethod for supporting OpenID.
