### ISSUE TITLE
new-UDSwitch - Cannot get state

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#92]
Created a Switch, but no way to get  the state whenever it is used. Tried New-UDElement, and doesn't return anything.

Just a note, the visual logic of your On and Off messages seems to be inverted.

**Comment by adamdriscoll** [comment]
The ID wasn't set correctly for UDSwitch. I also switch around the On\Off messages so they are correct. Will be in 1.6.0-beta3
