### ISSUE TITLE
Theme issue - UDTextbox value / Placeholder / Label customization

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#922]
For Azure theme, UDTextbox placeholder, value and label seems to be using the default color. 

For the placeholder and label, the color are visible but the value field is hard to read. 
(black text)

In any case, these values should be part of the UDTheme configuration to allow customization and changed in the default Azure theme.

The same will be true for other themes as well. 

![image](https://user-images.githubusercontent.com/1980296/60386175-d3f30300-9a5f-11e9-9653-78f6edbe0662.png)

**Comment by adamdriscoll** [comment]
I think this is fixed in 2.5 but let me validate.
