### ISSUE TITLE
New-UDFab throws error when only 1 button in content

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#926]
```
New-UdFab -Icon "plus" -Size "large" -ButtonColor "red" -IconColor 'white' -Content {
    New-UDFabButton -Icon address_book -ButtonColor 'blue' -IconColor 'white'
}
```

this.props.content.map is not a function

**Comment by ArtisanByteCrafter** [comment]
It looks like you declare `children` as an object at `{children}` - should it be an array instead? `[children]`

 - https://github.com/ironmansoftware/universal-dashboard/blob/ecdc2ef1affaf73ac76ab400d9a296d1bfebd24c/src/UniversalDashboard.Materialize/Components/ud-fab.jsx#L46

**Comment by adamdriscoll** [comment]
@ArtisanByteCrafter Kinda yeah. The problem is that the JSX file is assuming that this.props.content is an array. But if you pass a single item in, it's not so then the `map` function doesn't exist on `this.props.content`. The JSX needs to be updated to check to see that the content is an array and if not, make it an array. 

https://github.com/ironmansoftware/universal-dashboard/blob/ecdc2ef1affaf73ac76ab400d9a296d1bfebd24c/src/UniversalDashboard.Materialize/Components/ud-fab.jsx#L34

**Comment by ArtisanByteCrafter** [comment]
That makes sense, Powershell has a similar problem with it returning only the object if the result is one.

```powershell
PS> (Get-AdUser Nate).count
PS> (Get-AdUser Nate | Measure-Object).count
1
```

fix is the same, casting it explicitly to an array.

```powershell
PS> @(Get-AdUser Nate).count
1
```
