### ISSUE TITLE
"Test" Dashboard.ps1 included with module

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#927]
In the root directory of the module, there is a dashboard.ps1 file that should not be there.

**Comment by jwmoss** [comment]
Deleted test.ps1 and from C:\inetpub\wwwroot\poshud, restarted IIS and still getting universal dashboard homepage template on my IIS site. Restarted server hosting IIS and, despite dashboard.ps1 being in C:\inetpub\wwwroot, my UD page is still the UD homepage.

**Comment by adamdriscoll** [comment]
Do you have a dashboard.ps1 in the place of the one that was there? If so, can you post the contents here? Can you also check in your app data folder to see if you have a dashboard.ps1? It's actually the appData folder for the appPool user.

**Comment by jwmoss** [comment]
Dashboard.ps1 is in both C:\inetpub\wwwroot and C:\inetpub\wwroot\poshud. Test.ps1 does not exist in C:\inetpub\wwroot\poshud.

Restarted IIS pool and getting this alert when running UniversalDashboard.Server.exe:

`C:\inetpub\wwwroot\net472>UniversalDashboard.Server.exe
Starting Universal Dashboard service.
 Dashboard Script: C:\inetpub\wwwroot\net472\..\dashboard.ps1
 Assembly Base Path: C:\inetpub\wwwroot\net472\..\dashboard.ps1
Error starting dashboard:
 Exception calling "RegisterAsset" with "1" argument(s): "The given path's format is not supported."
 at <ScriptBlock>, C:\inetpub\wwwroot\Modules\UniversalDashboard.Materialize\UniversalDashboard.Materialize.psm1: line 10
at <ScriptBlock>, C:\inetpub\wwwroot\UniversalDashboard.psm1: line 15
at <ScriptBlock>, <No file>: line 1
Error starting dashboard:
 Exception calling "RegisterAsset" with "1" argument(s): "The given path's format is not supported."
 at <ScriptBlock>, C:\inetpub\wwwroot\Modules\UniversalDashboard.MaterialUI\UniversalDashboard.MaterialUI.psm1: line 15
at <ScriptBlock>, C:\inetpub\wwwroot\UniversalDashboard.psm1: line 16
at <ScriptBlock>, <No file>: line 1`

**Comment by jwmoss** [comment]
Dashboard.ps1 contents that worked in UD 2.4.1 in IIS using Default Web Site:
`$Schedule = New-UDEndpointSchedule -Every 60 -Minute

$Endpoint = New-UDEndpoint -Schedule $Schedule -Endpoint {

    $Cache:Data = Import-Csv -Path "C:\WindowsServerInventory\Live\data.csv"

}

$StatsPage = 

$Dashboard = New-UDDashboard -Title "Windows Servers" -Content {

    New-UdGrid -Title "Active Directory" -Endpoint {

        $Cache:Data | Select-Object Name, Description, DNS, OperatingSystem, Enabled | Out-UDGridData

    }

    New-UdGrid -Title "vCenter" -Endpoint {

        $Cache:Data | Select-Object Name, vCenterDescription, IpAddress, vcenter | Out-UDGridData

    }

    New-UdGrid -Title "Orion" -Endpoint {

        $Cache:Data | Select-Object Name, Environment, PatchGroup, OrionStatus, BusinessOwner | Out-UDGridData

    }

    New-UdGrid -Title "Tenable" -Endpoint {

        $Cache:data | Select-Object Name, Criticals, Highs | Out-UDGridData

    }

}

Start-UDDashboard -Dashboard $dashboard -Port 12345 -Endpoint $Endpoint
`

**Comment by adamdriscoll** [comment]
It worked without the -Wait parameter on Start-UDDashboard before? That's strange. Thought that was required. Let me give this a shot to see if I can reproduce.

**Comment by jwmoss** [comment]
Oops, updated to: 

```
$Schedule = New-UDEndpointSchedule -Every 60 -Minute

$Endpoint = New-UDEndpoint -Schedule $Schedule -Endpoint {

    $Cache:Data = Import-Csv -Path "C:\WindowsServerInventory\Live\data.csv"

}

$StatsPage = 

$Dashboard = New-UDDashboard -Title "Windows Servers" -Content {

    New-UdGrid -Title "Active Directory" -Endpoint {

        $Cache:Data | Select-Object Name, Description, DNS, OperatingSystem, Enabled | Out-UDGridData

    }

    New-UdGrid -Title "vCenter" -Endpoint {

        $Cache:Data | Select-Object Name, vCenterDescription, IpAddress, vcenter | Out-UDGridData

    }

    New-UdGrid -Title "Orion" -Endpoint {

        $Cache:Data | Select-Object Name, Environment, PatchGroup, OrionStatus, BusinessOwner | Out-UDGridData

    }

    New-UdGrid -Title "Tenable" -Endpoint {

        $Cache:data | Select-Object Name, Criticals, Highs | Out-UDGridData

    }

}

Start-UDDashboard -Dashboard $dashboard -Wait -Endpoint $Endpoint

```

Still getting a 500 error after copying the contents above to dashboard.ps1

**Comment by adamdriscoll** [comment]
Just downloaded the latest 2.5 from the Gallery and copied it into my IIS site and it's working without issue. My dashboard is much more simple so maybe try that just to validate but it seems like you are having problems even loading the module:

```
Start-UDDashboard -Dashboard (
    New-UDDashboard -Title 'Hello, IIS' -Content {
        New-UDHeading -Text (Get-Module UniversalDashboard.Community).Version
    }
) -Wait
```

I downloaded from the PSGallery using Install-Module and then copied it over to wwwroot. I'm running Windows 10 1903. Nothing special setup via IIS. Just running as ApplicaitonPoolIdentity.

**Comment by jwmoss** [comment]
Created an entirely new site, copied the below to C:\UD\Dashboard.ps1 and C:\UD\poshud\Dashboard.ps1, and it ran succesfully (but without download icon for the grid layout?):

```
$Schedule = New-UDEndpointSchedule -Every 60 -Minute

$Endpoint = New-UDEndpoint -Schedule $Schedule -Endpoint {

    $Cache:Data = Import-Csv -Path "C:\WindowsServerInventory\Live\data.csv"

}

$Dashboard = New-UDDashboard -Title "Windows Servers" -Content {

    New-UdGrid -Title "Active Directory" -Endpoint {

        $Cache:Data | Select-Object Name, Description, DNS, OperatingSystem, Enabled | Out-UDGridData

    }

    New-UdGrid -Title "vCenter" -Endpoint {

        $Cache:Data | Select-Object Name, vCenterDescription, IpAddress, vcenter | Out-UDGridData

    }

    New-UdGrid -Title "Orion" -Endpoint {

        $Cache:Data | Select-Object Name, Environment, PatchGroup, OrionStatus, BusinessOwner | Out-UDGridData

    }

    New-UdGrid -Title "Tenable" -Endpoint {

        $Cache:data | Select-Object Name, Criticals, Highs | Out-UDGridData

    }

}

Start-UDDashboard -Dashboard $dashboard -Wait -Endpoint $Endpoint

```

**Comment by adamdriscoll** [comment]
Hmmm weird. I think `Publish-UDDashboard` should be updated to be able to deploy IIS sites because everyone has issues after upgrading. 

As for the grid layout button, do you mean the design mode that's available in the enterprise version? It provides a "Copy layout to clipboard" button.

**Comment by jwmoss** [comment]
I'm referring to the new feature in 2.5.0, where you can export the download as a CSV, refresh, and pagination. That's not present in my dashboard, despite 2.5.0 module folder(s) in my IIS site.

**Comment by adamdriscoll** [comment]
Oh, I see. Can you try to do a Ctrl+F5 in your browser to make sure it's not a JavaScript caching issue?

**Comment by jwmoss** [comment]
Wow that fixed it!

**Comment by adamdriscoll** [comment]
Cool! You might have some issues with pagination and the grid but I've fixed that and will get out a release today.
