### ISSUE TITLE
New paginator in UDGrid showing '-' (minus) values

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/universal-dashboard#929]
Hi there

Almost all of my UDGrids in my app are showing strange values in the paginator.
Only one or two grids are alright, most (15+) are broken:
![2019-07-02 13_41_23-ServerManagement Dashboard 📊 DEV 🚧](https://user-images.githubusercontent.com/32512939/60510182-1e2deb80-9ccf-11e9-8be1-57730e664385.png)

**Comment by adamdriscoll** [comment]
Ugh. I hate when this type of stuff sneaks in. Have a PR with a fix incoming. Will probably release a 2.5.1 today to resolve that since it's so annoying.
