### ISSUE TITLE
New-UDCheckbox - Checked switch

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#93]
When applied to set checkbox to Checked by default, won't allow to uncheck when used.

**Comment by BryanDM** [comment]
This also applies to New-UDSwitch

I've had this issue since 1.5.0 (I had  built a switch using New-UDElement, before you added the controls into the build.)

**Comment by adamdriscoll** [comment]
This has been fixed for both the checkbox and the switch in 1.6.0-beta3
