### ISSUE TITLE
Grid Pageination contains negative numbers

### ISSUE THREAD

**Issue by e1ze** [ironmansoftware/universal-dashboard#936]
Hi, 

i have a strange problem in some grids and i do not know why this is happening. 
In some grids it's working like expected. (Starting with 1 and ending with the last page (1 2 3 4 ... 10))
As you can see in the example below it starts with a negative number and the last page is not displayed "correctly"... sometimes. In the second example there are only 3 pages.
The pageination is working if you click on the numbers 1 or above.
No errors will be logged or displayed.

![grid](https://user-images.githubusercontent.com/6794362/60597432-36733880-9dab-11e9-9b2a-e756b8f6c4ab.gif)
![grid2](https://user-images.githubusercontent.com/6794362/60597913-11cb9080-9dac-11e9-896b-7ea6a8449bed.gif)

Any ideas? Thanks.

Example Code snippet for second example above:

```powershell
$OldPWDUser = $Cache:AllUserObjects | Select-Object sAMAccountName, Name, distinguishedName, enabled, pwdlastset, lastLogonTimestamp

$OldPasswordsFilter = @($OldPWDUser).Where{ ((Get-Date).AddDays(-$PasswordAge) -gt [datetime]::FromFileTime($_.pwdlastset)) -and ($_.enabled -eq $true) } | `
        Select-Object `
        sAMAccountName, `
        Name, `
        distinguishedName, `
      @{Name = "lastLogon"; Expression = { $lastLogonDate = [datetime]::FromFileTime($_.lastLogonTimestamp); $lastlogonDays = $(New-TimeSpan $lastLogonDate).Days; if ($lastlogonDays -gt "10950") { "never" } else { $lastLogonDate } } }, `
      @{Name = "Pwdlastset"; Expression = { [datetime]::FromFileTime($_.pwdlastset) } }, `
      @{Name = "Pwdlastsetdays"; Expression = { $pwdlastsetDate = [datetime]::FromFileTime($_.pwdlastset); $(New-TimeSpan $pwdlastsetDate).Days } }

if ($OldPasswordsFilter)
    {
      $OldPasswordsFilter | Out-UDGridData
    }
```

**Comment by adamdriscoll** [comment]
@e1ze Is this running 2.5.1?

**Comment by e1ze** [comment]
@adamdriscoll Oh, ok, i didn't realized that 2.5.1 is available. 
I just made a quick upgrade to version 2.5.1. The bug is fixed. Thank you. I close the issue.
