### ISSUE TITLE
[Enhancement] Add -TextAlignment to New-UDButton

### ISSUE THREAD

**Issue by eizedev** [ironmansoftware/universal-dashboard#940]
Hi,

it would be nice if you could add a new switch f.e. '-TextAlignment' to 'New-UDButton'. (Similar to -IconAlignment)
If you use f.e. New-UDButton inside an UDGrid as flat button, the text is always centered (see screenshot). 
As addition it would also be nice if i could choose if the text should be always upper or lower case. Perhaps use "as it is" by default?.
This would cause the display of the button to line up properly in the grid.
In my example, the name of the Active Directory user is in proper case (Administrator).

![grafik](https://user-images.githubusercontent.com/6794362/60607444-8b1faf00-9dbd-11e9-8368-45284c791921.png)
```powershell
New-UDButton -Flat -Text $_.Name -OnClick { }
```

Complete Code for this screenshot:
```powershell
$AllUsersArray = @($($AllUserObjects)).foreach( {
    [PSCustomObject]@{
      Username = $($_.SamAccountName)
      Name     = $(New-UDButton -Flat -Text $_.Name -OnClick { 
          Show-UDModal -Header {
            New-UDHeading -Size 5 -Text "Description for User '$($_.SamAccountName)'" 
          } -Content {
            New-UDRow -Columns 
            { New-UDColumn -Size 8 -Content 
              {
                if ($_.Description) 
                {
                  $_.Description 
                }
                else 
                {
                  "No Description" 
                } 
              }
              New-UDColumn -Size 8 -Content {
                New-UDButton -BackgroundColor $Cache:LoginBGColor -Text "Close" -OnClick { Hide-UDModal } 
              } 
            } 
          } 
        }
      )
    } | Out-UDGridData
  }
)
```

Thanks

**Comment by e1ze** [comment]
I just realized my issue is still open. 
If someone else has the same problem, you can work around it until UD 3.0 comes with the new theming option.
You can just add the `-Style` parameter with a hashtable configuration for the `text-transform`. 
You can use `uppercase`, `lowercase` and `capitalize` as possible values.
In my case i am using `capitalize` so the text is in proper case ("As it is").

**Directly with `-Style` in `New-UDButton` cmdlet:**

```powershell
New-UDButton -Flat -Text $_.Name -Style @{'text-transform' = 'capitalize' }
```
 OR
```powershell
$Cache:ButtonTextStyle = @{'text-transform' = 'capitalize' }
New-UDButton -Flat -Text $_.Name -Style $Cache:ButtonTextStyle
```

**Or by using the `New-UDStyle` cmdlet**

```powershell
New-UDStyle -Style '.btn { text-transform : capitalize;}' -Content { New-UDButton -Flat -Text $_.Name }
```

(Of course you can use the global theme configuration of the dashboard for all buttons)

As far as I'm concerned, we can close the issue.
