### ISSUE TITLE
Unable to get UDCheckbox State in 2.5.X

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#941]
I have the following UDCheckBox 

New-UDCheckbox -Id 'CheckBox' -Label "Send Credential Email?" -OnChange {
    $CheckElement = Get-UDElement -Id 'CheckBox'
    $Session:SendCredEmail = $CheckElement.Attributes["checked"]
    } -FilledIn

This has been working in all previous versions of UD but since upgrading to 2.5.X when clicking the checkbox I get the error "Cannot Index into a Null Array" when trying to set the Session variable. 

Has something changed in order to retrieve true/false from the checkbox element or is this a bug?

thanks!

**Comment by adamdriscoll** [comment]
Seems like a bug.

**Comment by adamdriscoll** [comment]
One thing to note, you can use the $EventData variable in your OnChange handler to avoid having to use Get-UDElement at all. 

```
New-UDCheckbox -Id 'CheckBox' -Label "Send Credential Email?" -OnChange {
$Session:SendCredEmail = $EventData
} -FilledIn
```
