### ISSUE TITLE
UDInputs do not auto-resize to width when used in tab container

### ISSUE THREAD

**Issue by dcherry88** [ironmansoftware/universal-dashboard#943]
When you have UDinput box setup on a tabbed page setup the inputfields/dropdowns/etc do not resize with the width of the UDInput boxes. Code sample provided of two pages, one with tabs, one without. Setup the boxes in udgridlayout for resizing to see how the behavior differs.

Tabbed page
```powershell
New-UDPage -Name 'testpage' -Content {
    New-UDTabContainer -Tabs {
        New-UDTab -Text 'tab1' -Content {
            New-UDGridLayout -Resizable -Draggable -Content {
                New-UDInput -Id 'Input' -FontColor '#FFFFFF' -Title "Patch Remediation Setup" -Content {
                    New-UDInputField -Type textbox -Name "SystemList" -Placeholder 'List of systems, comma seperated. Ex: System01,System02'
                    New-UDInputField -Type textbox -Name "StartDateTime" -Placeholder 'Start date and time in 24hr format. Ex: 2/4/2022 22:00'
                    New-UDInputField -Type textbox -Name "EndDateTime" -Placeholder 'End date and time in 24hr format. Ex: 2/5/2022 01:00'
                    New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number. Ex: CR123456'
                    New-UDInputField -Type textbox -Name "CaseNumber" -Placeholder 'Case number'
                    New-UDInputField -Type textbox -Name "Username" -Placeholder "Enter you username for notification email"
                    New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit Systems belong to' -Values @("Select")
                    New-UDInputField -type checkbox -Name "restart" -Placeholder 'Restart System(s) automatically?'
                    New-UDInputField -Type checkbox -Name "SqlSec" -Placeholder 'Include SQL Security Updates?'
                    New-UDInputField -Type checkbox -Name "SqlSP" -Placeholder 'Include SQL Service Packs?'
                    New-UDInputField -Type checkbox -Name "OfficeSP" -Placeholder 'Include Office Service Packs?'
                    New-UDInputField -Type checkbox -Name "OS_SP" -Placeholder 'Include OS Service Packs?'
                } -Endpoint {}
            }
        }
        New-UDTab -Text 'tab2' -Content {
            New-UDGridLayout -Resizable -Draggable -Content {
                New-UDInput -Id "serverDeployment" -FontColor '#FFFFFF' -Title "Server Deployment Setup" -SubmitText 'Start Setup' -Content {
                    New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number'
                    New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit' -Values @("Select")
                    New-UDInputField -Type select -Name "PatchStage" -Placeholder 'Production or Non-Production' -Values @("Select","Non-Production","Production")
                } -Endpoint {}
            }
        }
    }
}
````

Regular page
````Powershell
New-UDPage -Name 'testpage2' -Content {
    New-UDGridLayout -Resizable -Draggable -Content {
        New-UDInput -Id 'Input' -FontColor '#FFFFFF' -Title "Patch Remediation Setup" -Content {
            New-UDInputField -Type textbox -Name "SystemList" -Placeholder 'List of systems, comma seperated. Ex: System01,System02'
            New-UDInputField -Type textbox -Name "StartDateTime" -Placeholder 'Start date and time in 24hr format. Ex: 2/4/2022 22:00'
            New-UDInputField -Type textbox -Name "EndDateTime" -Placeholder 'End date and time in 24hr format. Ex: 2/5/2022 01:00'
            New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number. Ex: CR123456'
            New-UDInputField -Type textbox -Name "CaseNumber" -Placeholder 'Case number'
            New-UDInputField -Type textbox -Name "Username" -Placeholder "Enter you username for notification email"
            New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit Systems belong to' -Values @("Select")
            New-UDInputField -type checkbox -Name "restart" -Placeholder 'Restart System(s) automatically?'
            New-UDInputField -Type checkbox -Name "SqlSec" -Placeholder 'Include SQL Security Updates?'
            New-UDInputField -Type checkbox -Name "SqlSP" -Placeholder 'Include SQL Service Packs?'
            New-UDInputField -Type checkbox -Name "OfficeSP" -Placeholder 'Include Office Service Packs?'
            New-UDInputField -Type checkbox -Name "OS_SP" -Placeholder 'Include OS Service Packs?'
        } -Endpoint {}
        New-UDInput -Id "serverDeployment" -FontColor '#FFFFFF' -Title "Server Deployment Setup" -SubmitText 'Start Setup' -Content {
            New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number'
            New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit' -Values @("Select")
            New-UDInputField -Type select -Name "PatchStage" -Placeholder 'Production or Non-Production' -Values @("Select","Non-Production","Production")
        } -Endpoint {}
    }
}
````

**Comment by AlonGvili** [comment]
> When you have UDinput box setup on a tabbed page setup the inputfields/dropdowns/etc do not resize with the width of the UDInput boxes. Code sample provided of two pages, one with tabs, one without. Setup the boxes in udgridlayout for resizing to see how the behavior differs.
> 
> Tabbed page
> 
> ```powershell
> New-UDPage -Name 'testpage' -Content {
>     New-UDTabContainer -Tabs {
>         New-UDTab -Text 'tab1' -Content {
>             New-UDGridLayout -Resizable -Draggable -Content {
>                 New-UDInput -Id 'Input' -FontColor '#FFFFFF' -Title "Patch Remediation Setup" -Content {
>                     New-UDInputField -Type textbox -Name "SystemList" -Placeholder 'List of systems, comma seperated. Ex: System01,System02'
>                     New-UDInputField -Type textbox -Name "StartDateTime" -Placeholder 'Start date and time in 24hr format. Ex: 2/4/2022 22:00'
>                     New-UDInputField -Type textbox -Name "EndDateTime" -Placeholder 'End date and time in 24hr format. Ex: 2/5/2022 01:00'
>                     New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number. Ex: CR123456'
>                     New-UDInputField -Type textbox -Name "CaseNumber" -Placeholder 'Case number'
>                     New-UDInputField -Type textbox -Name "Username" -Placeholder "Enter you username for notification email"
>                     New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit Systems belong to' -Values @("Select")
>                     New-UDInputField -type checkbox -Name "restart" -Placeholder 'Restart System(s) automatically?'
>                     New-UDInputField -Type checkbox -Name "SqlSec" -Placeholder 'Include SQL Security Updates?'
>                     New-UDInputField -Type checkbox -Name "SqlSP" -Placeholder 'Include SQL Service Packs?'
>                     New-UDInputField -Type checkbox -Name "OfficeSP" -Placeholder 'Include Office Service Packs?'
>                     New-UDInputField -Type checkbox -Name "OS_SP" -Placeholder 'Include OS Service Packs?'
>                 } -Endpoint {}
>             }
>         }
>         New-UDTab -Text 'tab2' -Content {
>             New-UDGridLayout -Resizable -Draggable -Content {
>                 New-UDInput -Id "serverDeployment" -FontColor '#FFFFFF' -Title "Server Deployment Setup" -SubmitText 'Start Setup' -Content {
>                     New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number'
>                     New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit' -Values @("Select")
>                     New-UDInputField -Type select -Name "PatchStage" -Placeholder 'Production or Non-Production' -Values @("Select","Non-Production","Production")
>                 } -Endpoint {}
>             }
>         }
>     }
> }
> ```
> 
> Regular page
> 
> ```powershell
> New-UDPage -Name 'testpage2' -Content {
>     New-UDGridLayout -Resizable -Draggable -Content {
>         New-UDInput -Id 'Input' -FontColor '#FFFFFF' -Title "Patch Remediation Setup" -Content {
>             New-UDInputField -Type textbox -Name "SystemList" -Placeholder 'List of systems, comma seperated. Ex: System01,System02'
>             New-UDInputField -Type textbox -Name "StartDateTime" -Placeholder 'Start date and time in 24hr format. Ex: 2/4/2022 22:00'
>             New-UDInputField -Type textbox -Name "EndDateTime" -Placeholder 'End date and time in 24hr format. Ex: 2/5/2022 01:00'
>             New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number. Ex: CR123456'
>             New-UDInputField -Type textbox -Name "CaseNumber" -Placeholder 'Case number'
>             New-UDInputField -Type textbox -Name "Username" -Placeholder "Enter you username for notification email"
>             New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit Systems belong to' -Values @("Select")
>             New-UDInputField -type checkbox -Name "restart" -Placeholder 'Restart System(s) automatically?'
>             New-UDInputField -Type checkbox -Name "SqlSec" -Placeholder 'Include SQL Security Updates?'
>             New-UDInputField -Type checkbox -Name "SqlSP" -Placeholder 'Include SQL Service Packs?'
>             New-UDInputField -Type checkbox -Name "OfficeSP" -Placeholder 'Include Office Service Packs?'
>             New-UDInputField -Type checkbox -Name "OS_SP" -Placeholder 'Include OS Service Packs?'
>         } -Endpoint {}
>         New-UDInput -Id "serverDeployment" -FontColor '#FFFFFF' -Title "Server Deployment Setup" -SubmitText 'Start Setup' -Content {
>             New-UDInputField -Type textbox -Name "CRNumber" -Placeholder 'Change Request number'
>             New-UDInputField -Type select -Name "BusinessUnit" -Placeholder 'Select Business Unit' -Values @("Select")
>             New-UDInputField -Type select -Name "PatchStage" -Placeholder 'Production or Non-Production' -Values @("Select","Non-Production","Production")
>         } -Endpoint {}
>     }
> }
> ```

Is this the expected behavior
![Antd (2)](https://user-images.githubusercontent.com/34351424/60773101-f42e5c00-a108-11e9-8408-34b4c8a31855.gif)

**Comment by dcherry88** [comment]
Yes, that is the behavior I am expecting to occur on tabbed pages, the same as the regular pages. Did i miss something in my coding and this is not an issue?

**Comment by AlonGvili** [comment]
> Yes, that is the behavior I am expecting to occur on tabbed pages, the same as the regular pages. Did I miss something in my coding and this is not an issue?

You didn't miss anything, its a bug will open PR for that
