### ISSUE TITLE
Invoke-RestMethod /api/login not working with UDDashboard

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#945]
I was looking at your fourm answer here : https://forums.universaldashboard.io/t/authentication-authorization-in-the-rest-api/149

and I was able to have it work with UDRestAPI. 
However, attempting the same with UDDashboard (see code below) return "Bad username or password" 

```
$uri = 'http://localhost:1002/api/login'
Invoke-RestMethod -Uri $uri -Method POST -Body @{ UserName = "Bartek"; Password = "Test" } 
```

Dashboard behind it (Work though if I use UDRestAPI instead)
```
Get-UDDashboard | Stop-UDDashboard
$auth = New-UDAuthenticationMethod -Endpoint {
    param([PSCredential]$Credential)
    $userName = $Credential.UserName
    $role = if ($userName -eq 'Bartek') {
        'admin'
    } else {
        'luser'
    }
    New-UDAuthenticationResult -Success -UserName $userName -Role $role -ErrorMessage ''
}

$endpoint = New-UDEndpoint -Url user/me -Endpoint {
    New-UDEndpoint -Url user/me -Method GET -Endpoint {
        @{
            User = $User
            Token = Grant-UDJsonWebToken -Identity $User -SigningKey abc12345abc12345
        } | ConvertTo-JsonEx
    }
    }

$loginPage = New-UDLoginPage -AuthenticationMethod $auth 
$dash = New-UDDashboard -Title 'test' -Content {} -LoginPage $loginPage 

Start-UDDashboard -Dashboard $dash -Port 1002 -Endpoint $endpoint -AllowHttpForLogin




```
Edit: 
I was able to mitigate this by login in manually, get to the api endpoint, copy my token and use it, bypassing the POST to the login page shown in the forum.

**Comment by awickham10** [comment]
I'm having the same issue.

**Comment by adamdriscoll** [comment]
I was trying to work around this by specifying another auth method but it wasn't working. I put a fix that will go into 2.6.1 into this. You can configure the dashboard like this. 

```
        $auth = @()
        $auth += New-UDAuthenticationMethod -Endpoint {
                param([PSCredential]$Credential)
                $userName = $Credential.UserName
                $role = if ($userName -eq 'Bartek') {
                    'admin'
                } else {
                    'luser'
                }
                $Token = Grant-UDJsonWebToken -Identity $UserName -Role $Role -Issuer 'Adam'
                New-UDAuthenticationResult -Success -UserName $userName -Role $role -ErrorMessage '' -Token $Token
            }
        $auth += New-UDAuthenticationMethod -Issuer 'Adam'

        $endpoint = New-UDEndpoint -Url user/me -Endpoint {
            $User
        }

        $loginPage = New-UDLoginPage -AuthenticationMethod $auth 
        $dashboard = New-UDDashboard -Title 'test' -Content {} -LoginPage $loginPage 

        $Server = Start-UDDashboard -Port 10001 -Dashboard $dashboard -AllowHttpForLogin -Endpoint $endpoint

```

Notice that I have both forms and JWT auth. Also notice that New-UDAuthenticationResult has a Token parameter now where you can generate a JWT which you can then use with future calls. 

```
            $uri = 'http://localhost:10001/login'
            $Result = Invoke-RestMethod -Uri $uri -Method POST -Body (@{ username = "Bartek"; password = "Test" } | ConvertTo-Json) -SessionVariable "Session"
            $uri = 'http://localhost:10001/api/user/me'
            Invoke-RestMethod -Uri $uri -Method GET -Headers @{ Authorization = "Bearer $($Result.Token)"} | Should be "Bartek"
```

**Comment by awickham10** [comment]
Will this work with IIS/Windows authentication?

**Comment by awickham10** [comment]
What if that's not an option (will have python/curl clients as well)?

I'm almost thinking about disabling the Windows auth and just use a form instead but authenticating against AD.

**Comment by adamdriscoll** [comment]
Hmmm. You got me on that one. I'm not sure how that's supposed to work in general. Do you have other applications that provide single-sign on via IIS that you can authenticate with via curl/python? 

If it's technically feasible I can try to implement it but I'll have to do some research.

**Comment by awickham10** [comment]
OK, I did some testing and got this all working. Basically JWT is not necessary if behind IIS and using Windows authentication. cURL and Python both support requests via NTLM. I'm not a cURL or Python guru, so these could be terrible, but they do work.

**cURL Example**
```
curl --data '{"key":"value"}' --header "Content-Type: application/json" --ntlm -u username:password http://localhost/api/search --http1.1
```

**Python Example**
```
import requests
from requests_ntlm import HttpNtlmAuth
from getpass import getpass

password = getpass()
r = requests.post('http://localhost/api/search', json={"key": "value"}, auth=HttpNtlmAuth(username, password))
```

**Comment by mponton** [comment]
I'm not sure I fully understand this new feature of v2.6.1. I understand this is a fix for UDDashboard mainly but I was hoping this would allow me to fix the issue of having to chose between REST API login endpoint with a default JWT signing key of `default_signing_key` versus another method.

I was hoping that:
```
$Token = Grant-UDJsonWebToken -Identity $UserName -Role $Role -Issuer 'Adam'
New-UDAuthenticationResult -Success -UserName $userName -Role $role -ErrorMessage '' -Token $Token
```

Would not allow me in the UDRestApi `/api/login` endpoint to provide my own token back to the user. I probably misunderstand the implementation because when I change parameters of the token like the signing key, subject etc, they are not used in the token returned to the user.

Is there a documented way of accomplishing this? I need to allow users to login via the API but I can use the default signing key in the final solution. the first thing our security team will do when they check the solution is to try to forge an JWT based on the framework I used and the information they find on the Internet.
