### ISSUE TITLE
Foreach breaks UDMuButton

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#947]
I am converting some of my UD buttons to Material buttons and found that for the OnClick events that have foreach loops I get the JSON output of the button on the page instead of the Material UI button. 
![image](https://user-images.githubusercontent.com/22712034/60749662-ea6ef200-9f6a-11e9-8047-b3bb2813142b.png)

But If I remove the foreach loop from the scriptblock the button loads fine.

![image](https://user-images.githubusercontent.com/22712034/60749673-15594600-9f6b-11e9-8563-2eb701696b67.png)

The button and foreach work as expected when using New-UDButton.

Thanks!

**Comment by AlonGvili** [comment]
@mylabonline can you give me some code example

_Sent from my P20 Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mylabonline** [comment]
I used your example above in a new page and it did work but only when using a static page (-Content) when using a dynamic page the JSON output is displayed.

Working with static page

```
New-UDPage -Name "test" -Content {
        New-UDColumn -Endpoint {
            New-UDMuButton -Text DEMO -Variant flat -Size large -OnClick {
                            0..20 | ForEach-Object {
                                Show-UDToast -Message $_
                            }
                        }
                        New-UDMuButton -Text DEMO2 -Variant flat -Size large -OnClick {
                            foreach($n in 0..20){
                                Show-UDToast -Message $n
                            }
                        }
                    }
}
```

![image](https://user-images.githubusercontent.com/22712034/60758295-c26fa500-9fe3-11e9-9b98-d0ac55a8bed5.png)

Not working with Dynamic Page - But if you change the UDMUButton to a UDButton it works, and if you remove the foreach from the MuButton it also loads.

Im running UD 2.5.2 btw :) 

```
New-UDPage -Url "/test/:dynamicpage" -Endpoint {
    param($dynamicpage)
        New-UDColumn -Endpoint {
            New-UDMuButton -Text DEMO -Variant flat -Size large -OnClick {
                            0..20 | ForEach-Object {
                                Show-UDToast -Message $_
                            }
                        }
                        New-UDMuButton -Text DEMO2 -Variant flat -Size large -OnClick {
                            foreach($n in 0..20){
                                Show-UDToast -Message $n
                            }
                        }
                    }

}
```
![image](https://user-images.githubusercontent.com/22712034/60758350-49248200-9fe4-11e9-8c3c-d0dd8234dca2.png)

**Comment by AlonGvili** [comment]
> I used your example above in a new page and it did work but only when using a static page (-Content) when using a dynamic page the JSON output is displayed.
> 
> Working with static page
> 
> ```
> New-UDPage -Name "test" -Content {
>         New-UDColumn -Endpoint {
>             New-UDMuButton -Text DEMO -Variant flat -Size large -OnClick {
>                             0..20 | ForEach-Object {
>                                 Show-UDToast -Message $_
>                             }
>                         }
>                         New-UDMuButton -Text DEMO2 -Variant flat -Size large -OnClick {
>                             foreach($n in 0..20){
>                                 Show-UDToast -Message $n
>                             }
>                         }
>                     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22712034/60758295-c26fa500-9fe3-11e9-9b98-d0ac55a8bed5.png)
> 
> Not working with Dynamic Page - But if you change the UDMUButton to a UDButton it works, and if you remove the foreach from the MuButton it also loads.
> 
> Im running UD 2.5.2 btw :)
> 
> ```
> New-UDPage -Url "/test/:dynamicpage" -Endpoint {
>     param($dynamicpage)
>         New-UDColumn -Endpoint {
>             New-UDMuButton -Text DEMO -Variant flat -Size large -OnClick {
>                             0..20 | ForEach-Object {
>                                 Show-UDToast -Message $_
>                             }
>                         }
>                         New-UDMuButton -Text DEMO2 -Variant flat -Size large -OnClick {
>                             foreach($n in 0..20){
>                                 Show-UDToast -Message $n
>                             }
>                         }
>                     }
> 
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22712034/60758350-49248200-9fe4-11e9-8c3c-d0dd8234dca2.png)

thanks for the examples will check that out

**Comment by mylabonline** [comment]
@AlonGvili I found the issue - I pulled apart my entire UD and found that on the main dashboard.ps1 I am  pulling in all the pages dynamically using this

```
 $Pages = Get-ChildItem (Join-Path $PSScriptRoot 'pages') -Recurse -File | ForEach-Object {
        & $_.FullName
     } 
```

But now if I take out that line of code and specify the pages individually, the MUButton works as expected in the above example, but all my dynamic content like $Session:Variables and loaders no longer work..... 👎 

```
$Pages = @()
$Pages += . (Join-Path $PSScriptRoot "pages\user-settings.ps1")
```

Looks like if I want to use the new Material Buttons I will need to redesign my entire UD

**Comment by AlonGvili** [comment]
>  $Pages = Get-ChildItem (Join-Path $PSScriptRoot 'pages') -Recurse -File | ForEach-Object {
>         & $_.FullName
>      }

try to change the & to . , 
i think maybe the scope and the session state is the problem, & sign will create new scope and session state, . sign will not create new scope and import to the same session state  
```
 $Pages = Get-ChildItem (Join-Path $PSScriptRoot 'pages') -Recurse -File | ForEach-Object {
        . $_.FullName
     } 
```

**Comment by mylabonline** [comment]
@AlonGvili When changing the & to a . makes no difference. Its something with the foreach loop - see below reproduce steps. I have also put this into an Azure Web app so you can see the output (broken)- https://udtestsiteazure252.azurewebsites.net/test/test 

I created a brand new UD with this test page as the only page and I'm getting the same results.

dashboard.ps1
```
Get-UDDashboard | Stop-UDDashboard
$Pages = Get-ChildItem (Join-Path $PSScriptRoot 'pages') -Recurse -File | ForEach-Object {
        . $_.FullName
     } 


$Dashboard = New-UDDashboard -Pages $Pages
Start-UDDashboard -AllowHttpForLogin -Dashboard $Dashboard -Wait
```
pages/test.ps1

```
New-UDPage -Url "/test/:dynamicpage" -Endpoint {
param($dynamicpage)
New-UDColumn -Endpoint {
    New-UDMuButton -Text DEMO -Variant flat -Size large -OnClick {
                    0..20 | ForEach-Object {
                        Show-UDToast -Message $_
                    }
                }
                New-UDMuButton -Text DEMO2 -Variant flat -Size large -OnClick {
                    foreach($n in 0..20){
                        Show-UDToast -Message $n
                    }
                }
            }
}
```

![image](https://user-images.githubusercontent.com/22712034/60807597-18fbf100-a154-11e9-965c-5750fdc536be.png)

But if I change the $Pages variable to this it works

```
Get-UDDashboard | Stop-UDDashboard
$Pages = . (Join-Path $PSScriptRoot 'pages/test.ps1')


$Dashboard = New-UDDashboard -Pages $Pages
Start-UDDashboard -AllowHttpForLogin -Dashboard $Dashboard -Wait
```
or this
```
Get-UDDashboard | Stop-UDDashboard
$Pages = & (Join-Path $PSScriptRoot 'pages/test.ps1')


$Dashboard = New-UDDashboard -Pages $Pages
Start-UDDashboard -AllowHttpForLogin -Dashboard $Dashboard -Wait
```

![image](https://user-images.githubusercontent.com/22712034/60807776-9162b200-a154-11e9-8dbe-fc43be1064f0.png)

**Comment by AlonGvili** [comment]
I will take a look at this tonight

**Comment by AlonGvili** [comment]
try this, I tested it and its working

```
$pages = foreach($page in (Get-ChildItem -Path  (Join-Path $PSScriptRoot 'pages') -Recurse )){
     . $Page.fullname
}
```

**Comment by mylabonline** [comment]
@AlonGvili  that did the trick!

![image](https://user-images.githubusercontent.com/22712034/60885387-79a33080-a21d-11e9-8383-e9657a24a43a.png)

For educational purposes, why does this work and not the other? All I gather is the placement of the foreach...?

thanks for all your help!! much appreciated.

**Comment by AlonGvili** [comment]
> @AlonGvili that did the trick!
> 
> ![image](https://user-images.githubusercontent.com/22712034/60885387-79a33080-a21d-11e9-8383-e9657a24a43a.png)
> 
> For educational purposes, why does this work and not the other? All I gather is the placement of the foreach...?
> 
> thanks for all your help!! much appreciated.

No problem, it was fun to fix, and for your question, I'm still thinking it a scope issue but I'm not 100% sure.

i need to Dig deeper into this issue

**Comment by AlonGvili** [comment]
If it working for you , please close this issue. thanks.
