### ISSUE TITLE
Get-UDAuthorizationPolicy with Endpoint - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#949]
Tested on 
UD Version: 2.5.0 and 2.5.2
OS : Windows
Methods : IIS and Through Vscode directly
Powershell : 5.1.17763.503 / latest desktop version

Get-UDAuthorizationPolicy returns Object reference not set to an instance of an object. 
I tried first with Azure authentication, then with Forms with the same results both time. 

Here's a reproducible example that need only the $LoginAuthParams value and certificate to be filled. 

```

Get-UDDashboard | Stop-UDDashboard

$LoginAuthParams = @{
    ClientID = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    Instance = 'https://login.microsoftonline.com'
    TenantId = '' 
    Domain = 'domain.com'
}

$AuthMethod = New-UDAuthenticationMethod @LoginAuthParams

$Pol = New-UDAuthorizationPolicy -Name 'Pol1' -Endpoint {
return $true
}

$lgoin = New-UDLoginPage -AuthenticationMethod $AuthMethod -AuthorizationPolicy $pol

$Page = New-UDPage -Name 'test' -Content {
 
    try {
        $Policies = Get-UDAuthorizationPolicy -ErrorAction Stop
    } 
    catch {
        New-UDCard -Title 'Error' -Text $_
    }
 
    if ($Policies -contains 'Administrator') {
        New-UDCard -Title 'Administrator' -Content { }
    }
     
}

$Dash = New-UDDashboard -Title 's' -Pages $Page -LoginPage $lgoin 

Start-UDDashboard -Dashboard $Dash -Port 1001  -Certificate (Get-Item 'cert:\\CurrentUser\\My\\69595cxxxxxxxxxxxxxxxxxxxxxxx') 

```

Edit: 
It looks like it works when using "-Content" but not "-Endpoint" in a UDPage.

**Comment by adamdriscoll** [comment]
I'm seeing the opposite here. -Content seems to throw an Object Ref but Endpoint does not. 

This works for me.

```

            New-UDPage -Name 'EndpointPage' -Endpoint {
                $AuthPolicy = Get-UDAuthorizationPolicy 

                if ($AuthPolicy -contains 'Policy2') {
                    New-UDHeading -Text "OnlyJonSeesThis" -Id "OnlyJonSeesThis"
                }  
            }
```

This does not

```

            New-UDPage -Name 'EndpointPage' -Content {
                $AuthPolicy = Get-UDAuthorizationPolicy 

                if ($AuthPolicy -contains 'Policy2') {
                    New-UDHeading -Text "OnlyJonSeesThis" -Id "OnlyJonSeesThis"
                }  
            }
```

This makes sense because the Content for the page is rendered when the cmdlet is run rather than after the user logs in. I will fix the bug and make sure a good error message is shown but I'm a big unsure why you see the error in the opposite direction.

**Comment by itfranck** [comment]
@adamdriscoll You are completely right. 

I am unable to reproduce it myself. 
My only guess is that I must have mixed my Content / Endpoint all the way through from the first encounter in IIS to me opening that ticket / updating it to mention Content was working. 

I just retested the exact same thing both in ISE / IIS including in my specific dashboard where I had had the issue and everything work fine.

Sorry for that.

**Comment by itfranck** [comment]
Hey @adamdriscoll 

Would you care to try this one ?
I am able to reproduce the issue again. 

There's a catch.
It does not happens when using the Dashboard parameter but it does when using **FilePath**


To test, I started the dashboard from VSCode using the following code: 
```
Get-UDDashboard | Stop-UDDashboard
$Certificate = 'cert:\\CurrentUser\\My\\69554j45j45j4j45j45j4_yourcertinfos'
Start-UDDashboard -FilePath "$($env:USERPROFILE)\desktop\d1.ps1" -Port 1001  -Certificate (Get-Item $Certificate) 
```

Here's the dashboard file.

D1.ps1
```
$LoginAuthParams = @{
    ClientID = '179261fa-6efb-4067-b7d4-2a45a26b533f'
    Instance = 'https://login.microsoftonline.com'
    TenantId = 'TenantID_HERE' 
    Domain = 'Domain.com'
}

$AuthMethod = New-UDAuthenticationMethod @LoginAuthParams

$Pol = New-UDAuthorizationPolicy -Name 'Pol1' -Endpoint {return $true}
$Pol2 = New-UDAuthorizationPolicy -Name 'Login' -Endpoint {return $true}

$login = New-UDLoginPage -AuthenticationMethod $AuthMethod -AuthorizationPolicy $Pol,$Pol2

$Page = New-UDPage -Name 'home' -AuthorizationPolicy 'Login'  -Endpoint {
 
    try {
        $Policies = Get-UDAuthorizationPolicy -ErrorAction Stop
        if ($Policies -contains 'Login') {
            New-UDCard -Title 'test' -Text 'Yay'
        }
    } 
    catch {
        New-UDCard -Title 'Error' -Text $_
    }
 
    if ($Policies -contains 'Administrator') {
        New-UDCard -Title 'Administrator' -Content { }
    }
     
}

$Dash = New-UDDashboard -Title 's' -Pages $Page -LoginPage $lgoin 


$Dash
```

**Comment by itfranck** [comment]
As a sidenote, when I use that sample in my scaffolding module I am slowly developping, I get the following: 

![image](https://user-images.githubusercontent.com/1980296/62405570-f26f8100-b56c-11e9-9437-b41938b3eb8c.png)

While I am unable to provide a simple way to provide a simple and reproducible dashboard for the **New Guid** error, the only special thing I am doing is loading all the pages dynamically one by one. 

It might not be relevant but I think the **Object reference not found** and the **New-Guid** errors might be one and the same. Somewhat, the error being more precise in the context of loading dynamically pages.

**Comment by adamdriscoll** [comment]
PowreShell Universal 1.2 will no longer have this cmdlet. You will have access to a $Roles variable that provide the roles that the user has been authorized for. It provides the same functionality but there isn't a need for the cmdlet.
