### ISSUE TITLE
[Help] Problem with Children in UD-TreeView and ActiveDirectory 

### ISSUE THREAD

**Issue by e1ze** [ironmansoftware/universal-dashboard#955]
Hi,

I have a problem here that I'm just not getting along with... 
Everytime i will open the TreeNode from the domain DN it does not open the child tree but it opens the root tree again because it cannot use the $_.Name variable because it is null. If i run the code manually it is working fine and i can browse the domain drive.
But for example the Schema subdirectory is working for at least one sub level.

Any ideas? Thanks :)
I am using 2.5.2 (But i had the same behavior on previous versions)

Root: {"nodeId":"Domain"}
SubTree: {"nodeId":"DC=MyDomain,DC=de"}
Anything else: {}

The area blackened is the domain name:
![TreeView](https://user-images.githubusercontent.com/6794362/60796265-5caf2480-a16d-11e9-938c-23972104afa2.png)
![subtree](https://user-images.githubusercontent.com/6794362/60795835-b06d3e00-a16c-11e9-81f3-0a9d104c6cad.png)
![subtree-manual](https://user-images.githubusercontent.com/6794362/60797117-fcb97d80-a16e-11e9-863b-340e6d32cc72.png)
![Name](https://user-images.githubusercontent.com/6794362/60797520-b1ec3580-a16f-11e9-9168-a708d4984d60.png)

Error: 
```powershell
09:38:16 [Warn] ExecutionService Error executing endpoint 8e2a5719-6a83-439c-9820-8cfdab3c2e1c. Das Argument kann nicht an den Parameter "Name" gebunden werden, da es NULL ist.
 bei <ScriptBlock>, <Keine Datei>: Zeile 14
bei <ScriptBlock>, <Keine Datei>: Zeile 13
```

So that means that the problem is somewhere in the TreeNodes, but i cannot figure out where? I also think i do not completely understand the TreeView stuff.

```powershell
if ($Obj.NodeId -eq 'domain')
        {
          @(Get-ChildItem -Path "AD:\").ForEach( {
              New-UDTreeNode -Name $_.Name -Id $_.DistinguishedName
            })
        }
        else
        {
          @(Get-ChildItem -Path "AD:\$($Obj.NodeId)").ForEach( {
              New-UDTreeNode -Name $_.Name -Id $_.DistinguishedName
            })
        }
```

I am currently using the test code from @adamdriscoll ud-activedirectory module example. It was only slightly adjusted by me. But with the [original code](https://github.com/adamdriscoll/ud-activedirectory/blob/master/pages/explorer.ps1) there was the same error message.

```powershell
New-UDPage -Url "/ad/explorer" -Icon folder -Endpoint {
  New-UDRow -Columns {
    New-UDColumn -SmallSize 12 -LargeSize 3 -Content {

      $Domain = Get-ADDomain @Cache:AD_ConnectionInfo

      $DomainNode = New-UDTreeNode -Name $Domain -Id "domain"
      New-UDTreeView -Node $DomainNode -OnNodeClicked {
        param($Body)
        $Obj = $Body | ConvertFrom-Json

        if ($Obj.NodeId -eq 'domain')
        {
          @(Get-ChildItem -Path "AD:\").ForEach( {
              New-UDTreeNode -Name $_.Name -Id $_.DistinguishedName
            })
        }
        else
        {
          @(Get-ChildItem -Path "AD:\$($Obj.NodeId)").ForEach( {
              New-UDTreeNode -Name $_.Name -Id $_.DistinguishedName
            })
        }
      }
    }
    New-UDColumn -SmallSize 12 -LargeSize 9 {
    }
  }
}
```

**Comment by leeberg** [comment]
Confirmed - seeing the same behavior on my 2.5.0 build

![image](https://user-images.githubusercontent.com/274883/60858060-78004b00-a1d2-11e9-9d6e-236be8e4b2d4.png)

**Comment by adamdriscoll** [comment]
I think that the console works because there is some special formatting happening that is hiding nodes that are $null. Try checking for $null before creating a new tree node. 

```
  if ($Obj.NodeId -eq 'domain')
        {
          @(Get-ChildItem -Path "AD:\").ForEach( {
              if ($null -ne $_.Name) {
              New-UDTreeNode -Name $_.Name -Id $_.DistinguishedName 
               }
            })
        }
        else
        {
          @(Get-ChildItem -Path "AD:\$($Obj.NodeId)").ForEach( {
              if ($null -ne $_.Name) {
                      New-UDTreeNode -Name $_.Name -Id $_.DistinguishedName
              }
            })
        }
```

What's happening is that one of the nodes is null and thats causing the entire tree to fail.

**Comment by e1ze** [comment]
@adamdriscoll Thanks! Quite simple and yet the solution. I could have come up with that on my own. :-)
