### ISSUE TITLE
[HELP] New-UDTable using PSSession

### ISSUE THREAD

**Issue by svbuckle** [ironmansoftware/universal-dashboard#956]
Hello All,

I am trying to get the below table to display, but have not been able to:

			New-UDTable -Title "Quarantined Emails" -Headers @("ReceivedTime", "RecipientAddress","Subject","Released","Release") -Endpoint {
                
                $username = "Username"
                $password = Get-Content 'Path' | ConvertTo-SecureString
                $Credentials = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $password
                $proxyOptions = New-PSSessionOption -ProxyAccessType IEConfig
                $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Credentials -Authentication Basic -AllowRedirection -SessionOption $proxyOptions
                Import-PSSession $Session -DisableNameChecking

                Get-QuarantineMessage -SenderAddress *Email* | Select-Object ReceivedTime,RecipientAddress,Subject,Released,MessageId | ForEach-Object {
					[PSCustomObject]@{
						ReceivedTime = $_.ReceivedTime
						RecipientAddress = $_.RecipientAddress
                        Subject = $_.Subject
                        Released = $_.Released
						Release = New-UDButton -Floating -Icon envelope -OnClick {Release-QuarantineMessage -MessageID $_.MessageId; Show-UDToast -Message "Message Released"} 
					} | Out-UDTableData -Property @("ReceivedTime", "RecipientAddress","Subject","Released","Release")
				}
			}

			New-UDButton -Text "Release all" -OnClick {
                Get-QuarantineMessage -SenderAddress *Email* | Release-QuarantineMessage
                #$ReleaseAll
				Show-UDToast -Message "All Quarantined Emails Released"
			}
		}
I have tried to run it with the PSSession outside of the New-UDPage but it comes back with the Get-QuarantineMessage as unknown.  With the PSSession inside, as above it comes back with a very long error message.

Anyhelp on getting this to work would be greatly appreciated.

Kind Regards
Sean Buckle

**Comment by leeberg** [comment]
Hey Sean, sessions are tricky - I'm sure there is likely combo of loading up the exchange session before/during you start the universal dashboard as a whole (NOT JUST the PAGES) but being tricky I and not having an exchange instance handy I can't give you an example.

If there is any chance you could post on the UniversalDashboard Forums over at: https://forums.universaldashboard.io/ - there are some **REALLY** smart PowerShell folks who have probably fought this same battle and could provide some tips or a snippet to get this working for you.

**Comment by svbuckle** [comment]
Hey,

Thanks for the information, I have found a way around it:

I replaced 

Import-PSSession $Session -DisableNameChecking

with

Import-Module (Import-PSSession $Session -CommandName @('Get-QuarantineMessage','Release-QuarantineMessage') -AllowClobber) -Global

and it all seems to be working.  I know there is probably a smarter way of doing it, but for now it is working.

Kind Regards
Sean Buckle
