### ISSUE TITLE
Design mode icon disappear after Update-UDDashboard is triggered

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#958]
![image](https://user-images.githubusercontent.com/1980296/60851901-7e3afb00-a1c3-11e9-8ba3-2e58f34935b2.png)

The design mode icon disappear after your refresh a dashboard through Update-UDDashboard.
Tested on 2.5.2

To reproduce, create a dashboard called **MyDashboard.ps1** and paste the following.
```
$Page = New-UDPage -Name 'Hello' -endpoint {
    New-UDButton -Text 'update' -OnClick {
        Update-UDDashboard -Url 'http://localhost:1001' -UpdateToken '9b39fda6-b943-4ba0-8dba-a8596fcc166b' -FilePath 'PathToYourDashboardFile.ps1'
    }
}
New-UDDashboard -Title 'Hello world' -Pages $Page -Debug
```
**Change PathtoYourDashboardFile.ps1 to the path you sill save that Dashboard file**

From VsCode / Powershell ISe / other, exectue the following statement: 

```
$UDParams = @{
    Port = 1001
    FilePath = 'PathToYourDashboardFile.ps1'
    Design = $true
    UpdateToken = '9b39fda6-b943-4ba0-8dba-a8596fcc166b'
}
Start-UDDashboard @UDParams 
```
**Change PathtoYourDashboardFile.ps1 to the path you did save that Dashboard file**

Navigate to the dashboard, then confirm you can see the design icon.
Click on update. 
Once refreshed, the design icon will have vanished forever (until you restart the dashboard)

**Before Update-UDDashboard**
![image](https://user-images.githubusercontent.com/1980296/60851861-2b614380-a1c3-11e9-9184-e329a03096e7.png)

**After Update-UDDashboard**
![image](https://user-images.githubusercontent.com/1980296/60851927-990d6f80-a1c3-11e9-846c-a9bbf568ff02.png)

**Comment by AlonGvili** [comment]
The strange thing I try The pay version and the community both on 2.5.2, no -Design parameter for Start-UDDashboard.

what version do you have ?

**Comment by itfranck** [comment]
I tested on Windows 10
From IIS and running the code from an IDE (Vscode / ISE)
With 2.5.2 (Enterprise) and 2.4.1 (Community) from 2 different machine. 
Tested on IE / Edge / Chrome / Firefox



@AlonGvili I modified my previous example slightly after reading your comment.

You need to put the dashboard file path in the dashboard file (for the Update-UDDashboard command) too. 

Once the Update-UDDashboard is triggered and the refresh occurs, it is gone. 

https://imgur.com/wU5hX1M

**Comment by AlonGvili** [comment]
> I tested on Windows 10
> From IIS and running the code from an IDE (Vscode / ISE)
> With 2.5.2 (Enterprise) and 2.4.1 (Community) from 2 different machine.
> Tested on IE / Edge / Chrome / Firefox
> 
> @AlonGvili I modified my previous example slightly after reading your comment.
> 
> You need to put the dashboard file path in the dashboard file (for the Update-UDDashboard command) too.
> 
> Once the Update-UDDashboard is triggered and the refresh occurs, it is gone.
> 
> https://imgur.com/wU5hX1M

i do that, but I'm saying that in Start-UDDashboard i don't have the -Design Parameter. so i can't check what is going on

**Comment by AlonGvili** [comment]
> I tested on Windows 10
> From IIS and running the code from an IDE (Vscode / ISE)
> With 2.5.2 (Enterprise) and 2.4.1 (Community) from 2 different machine.
> Tested on IE / Edge / Chrome / Firefox
> 
> @AlonGvili I modified my previous example slightly after reading your comment.
> 
> You need to put the dashboard file path in the dashboard file (for the Update-UDDashboard command) too.
> 
> Once the Update-UDDashboard is triggered and the refresh occurs, it is gone.
> 
> https://imgur.com/wU5hX1M

Try this code
```
$Page = New-UDPage -Name 'Hello' -endpoint {
    New-UDButton -Text 'update' -OnClick {
        Update-UDDashboard -Url 'http://localhost:1001' -UpdateToken '9b39fda6-b943-4ba0-8dba-a8596fcc166b' -FilePath 'D:\MyDashboard.ps1' 
    }
}
$d = New-UDDashboard -Title 'Hello world' -Pages $Page -Debug 
$d.design = $true
$d
```

its working for me , every time i update the dashboard it will start in design mode

**Comment by itfranck** [comment]
> $d = New-UDDashboard -Title 'Hello world' -Pages $Page -Debug 
> $d.design = $true
> $d
> ```
> 
> its working for me , every time i update the dashboard it will start in design mode

Yes indeed ! 
This workaround work perfectly. 

It looks like Start-UDashboard might be passing down that parameter to New-UDDashboard when it start but not when it refresh, leading to the deactivation of the design mode after an update dashboard trigger.
