### ISSUE TITLE
New-UDInput - Get Selected Path

### ISSUE THREAD

**Issue by batessmart** [ironmansoftware/universal-dashboard#961]
Hey,

Just wondering if its possible to get the selected path from New-UDInput.

Example:
File =  \\networkpath\folder\file.csv

`New-UDInputField` -Type 'filepath' -Name 'File' -Placeholder 'Upload file' 
param($file)

$csv = import-csv $file

**Comment by psDevUK** [comment]
I believe that question is answered here:- https://forums.universaldashboard.io/t/file-upload-howto/493/10
