### ISSUE TITLE
Publish-UDFolder - support for Authorization policies / Roles

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/universal-dashboard#973]
It might be nice to have the ability to have the AuthorizationPolicy / AuthorizationRole parameters exposed and working for Publish-UDFolder so one could restrict access to a specific published folder and its files. 

```
Publish-UDFolder -Path 'c:\docs' -RequestPath '/docs'
Publish-UDFolder -Path 'c:\AdminDocs' -RequestPath '/AdminDocs' -AuthorizationPolicy 'Admin'
```

**Comment by adamdriscoll** [comment]
This is supported in PowerShell Universal 1.3
