### ISSUE TITLE
API Route nesting not working

### ISSUE THREAD

**Issue by rdbartram** [ironmansoftware/universal-dashboard#974]
I've tested this a couple of time and have been unable to work out what the root cause of the problem is.

If i create 2 api endpoints one /user/:id and one /user/:id/memberof, both of method get, the memberof block fires for both urls. If i remove the memberof endpoint, the /user/:id works again

I can't find example that I've used it before although i'm almost sure I have. This is suppose to work, am i stupid or is this a bug?

**Comment by rdbartram** [comment]
It just dawned on my it may have happened since you implemented the regex support and you are building a negative lookforward or excluding the / from the :variable syntax. I got it to work like so

user\/(?<id>[^\/]*)$
user\/(?<identity>[^\/]*)\/memberof$

**Comment by adamdriscoll** [comment]
@rdbartram I just added a test for this. It looks like it's working for me. Are you using -EvaluateAsRegex on those routes? It works without it but not with it. 

I added a PR with a test to validate this scenario: https://github.com/ironmansoftware/universal-dashboard/pull/987

If there is something I'm missing, please let me know.
