### ISSUE TITLE
Setting HREF on a New-UDButton

### ISSUE THREAD

**Issue by Jacob-Evans** [ironmansoftware/universal-dashboard#976]
Hey, just updated to 2.5.2 and now this is no longer working:

Set-UDElement -Id "ExportPrompt2" -Content {
	$button = New-UDButton -Text "Download Report"
	$button.Attributes.href = "../files/$filename"
	New-UDCard -Content {
		$button
	}
}

I get the error: 

 The property 'href' cannot be found on this object. Verify that the property exists and can be set. 

Is there a new way to do this? It was working in 2.4.x

Thank you!

**Comment by leeberg** [comment]
Hey @Jacob-Evans looks like you are running into the same issue as: #978 - whereas #816 removed the attirbutes from UD-Button.

I have some workarounds specified over at: https://github.com/ironmansoftware/universal-dashboard/issues/978#issuecomment-514036073

I'm likely going to close this as a duplicate but we'll keep you posted on updates over on that issue. Please feel free to let me know on that issue if this workaround works for you, if you have other issues with this updated method.
