### ISSUE TITLE
New-UDPage without Home / Landing Page / Nav Bar

### ISSUE THREAD

**Issue by coding-totoro** [ironmansoftware/universal-dashboard#981]
There doesnt appear to be a way to create multiple disconnected pages. E.g. I have a ton of crud apps that do simple SQL selects for monitoring. 

I'd like to create 

New-UDDashboard -Content {
    New-UDPage -Name Crud1 
    New-UDPage -Name Crud2
    New-UDPage -Name Crud3
}

I dont need or want to have navigation bar as there will be 30-40 of these.

**Comment by adamdriscoll** [comment]
You can use the `New-UDSideNav -None` to hide the side nav. 

```
$SideNav = New-UDSideNav -None
New-UDDashboard -Navigation $SideNav
```
