### ISSUE TITLE
Negative Page Numbers when multiple pages using New-UDGrid 

### ISSUE THREAD

**Issue by JomackSilvey** [ironmansoftware/universal-dashboard#994]
![image](https://user-images.githubusercontent.com/32070721/62218123-d8ba1800-b379-11e9-9df5-d67070087b4e.png)

In version 2.5.2 I've noticed when using Google Chrome that negative page numbers are displayed when using multipage grid tables. This issue doesn't seem to occur in Firefox. 

New-UdGrid  -Id "jobreport"  -Title "Failed SQL Server Jobs" -Headers @( "Name","LastRunDate", "OwnerLoginName", "SQLInstance","LastRunOutcome") -Properties @("Name","LastRunDate","OwnerLoginName", "SQLInstance","LastRunOutcome") -AutoRefresh -RefreshInterval 60 -Endpoint {
       $JobReport = Import-Clixml C:\MSSQL_Dashboard\data\job_report\failedjobreport.xml
         $JobreportObjectArray = @()
  $JobReport | foreach {     
        
        $JobreportObject = New-Object PSObject -Property @{            
        Name        = $_.name                 
        LastRunDate      = [string] $_.LastRunDate              
        OwnerLoginName      = $_.OwnerLoginName            
       SQLInstance = [string]$_.SQLInstance            
        LastRunOutcome  = [string]$_.LastRunOutcome          
       
                
    }
    $JobreportObjectArray+=$JobreportObject   
    }
               $JobReportObjectArray | Out-UDGridData   }

**Comment by JomackSilvey** [comment]
Looks like it may be a sizing issue...when I increased the column size to 10 the page numbers are listed correctly in Chrome.

**Comment by oitptobbe** [comment]
Nothing to do with your issue but, For faster array creation (You are recreating the $JobReportObjectArray each time you do +=) do this
`
$JobreportObjectArray = $JobReport | foreach {
    $JobreportObject = [PsCustomObject]@{
    Name        = $_.name                 
    LastRunDate      = [string] $_.LastRunDate              
    OwnerLoginName      = $_.OwnerLoginName            
   SQLInstance = [string]$_.SQLInstance            
    LastRunOutcome  = [string]$_.LastRunOutcome          
}
$JobreportObject   
}
$JobReportObjectArray | Out-UDGridData   }
`

or even
`
$JobReport | foreach {
[PsCustomObject]@{
    Name        = $_.name                 
    LastRunDate      = [string] $_.LastRunDate              
    OwnerLoginName      = $_.OwnerLoginName            
   SQLInstance = [string]$_.SQLInstance            
    LastRunOutcome  = [string]$_.LastRunOutcome          
}
} | Out-UDGridData   }
`
